### ISSUE TITLE
NullReferenceException thrown resolving - IsBuiltInDeclarationInScope

### ISSUE THREAD

**Issue by Pitterling** [rubberduck-vba/Rubberduck#1161]
Hi, with the latest commits fixing the "Implicit ActiveSheet"  #1157 issue, i get new Exceptions.
CodeInspector will list findings anyway .. it just takes a while ..

```
Exception thrown resolving 'vbXlPivotAxisPri': System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.Parsing.Symbols.IdentifierReferenceResolver.IsBuiltInDeclarationInScope(Declaration item, Declaration localScope) in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceResolver.cs:line 1174
   at Rubberduck.Parsing.Symbols.IdentifierReferenceResolver.<>c__DisplayClass62_0.<FindProjectScopeDeclaration>b__1(Declaration item) in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceResolver.cs:line 1134
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Rubberduck.Parsing.Symbols.IdentifierReferenceResolver.FindProjectScopeDeclaration(String identifierName, Declaration localScope, ContextAccessorType accessorType, Boolean hasStringQualifier) in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceResolver.cs:line 1134
   at Rubberduck.Parsing.Symbols.IdentifierReferenceResolver.Resolve(String identifierName, Declaration localScope, ContextAccessorType accessorType, Boolean parentContextIsVariableOrProcedureCall, Boolean isAssignmentTarget, Boolean hasStringQualifier) in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceResolver.cs:line 521
   at Rubberduck.Parsing.Symbols.IdentifierReferenceResolver.ResolveInternal(ParserRuleContext callSiteContext, Declaration localScope, ContextAccessorType accessorType, DictionaryCallStmtContext fieldCall, Boolean hasExplicitLetStatement, Boolean isAssignmentTarget) in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceResolver.cs:line 484
   at Rubberduck.Parsing.Symbols.IdentifierReferenceResolver.ResolveInternal(ICS_S_VariableOrProcedureCallContext context, Declaration localScope, ContextAccessorType accessorType, Boolean hasExplicitLetStatement, Boolean isAssignmentTarget) in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceResolver.cs:line 537
   at Rubberduck.Parsing.Symbols.IdentifierReferenceResolver.Resolve(ICS_S_MembersCallContext context) in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceResolver.cs:line 821
   at Rubberduck.Parsing.Symbols.IdentifierReferenceListener.EnterICS_S_MembersCall(ICS_S_MembersCallContext context) in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceListener.cs:line 179
   at Rubberduck.Parsing.Grammar.VBAParser.ICS_S_MembersCallContext.EnterRule(IParseTreeListener listener) in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 14256
   at Antlr4.Runtime.Tree.ParseTreeWalker.EnterRule(IParseTreeListener listener, IRuleNode r)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Rubberduck.Parsing.VBA.RubberduckParser.ResolveReferences(VBComponent component, IParseTree tree, CancellationToken token) in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 313	83.51s
```
[NullReference.ZIP](https://github.com/rubberduck-vba/Rubberduck/files/153440/NullReference.ZIP)

**Comment by retailcoder** [comment]
Ugh. A little oversight on my part.

This statement:

            var isInLocalScope = (localScope != null && item.Accessibility == Accessibility.Global
                && localScope.IdentifierName == item.ParentDeclaration.IdentifierName)
                || (localScope != null && localScope.QualifiedName.QualifiedModuleName.Component.Type == Microsoft.Vbe.Interop.vbext_ComponentType.vbext_ct_Document
                 && item.Accessibility == Accessibility.Public && item.ParentDeclaration.DeclarationType == localScope.DeclarationType);

More specifically, this part:

    localScope.QualifiedName.QualifiedModuleName.Component.Type == Microsoft.Vbe.Interop.vbext_ComponentType.vbext_ct_Document

Is trying to determine if the `localScope` could be something like `Sheet1` - which is a good thing... the only problem is that, well, built-in declarations don't have a `Component`, so accessing its `Type` throws the NRE.

That query is starting to look way too complicated, I need to extract the logic into smaller steps.

**Comment by retailcoder** [comment]
Resolver performance is simply atrocious.

> Resolving 'fnTypePri'...
Resolving 'vbFnPivotTablePri'...
Resolving 'fnEnumPri'...
'fnEnumPri' is Ready. Resolver took 2506ms to complete.
Resolving 'Sheet1'...
Resolving 'vbFnPivotItemPri'...
'Sheet1' is Ready. Resolver took 1787ms to complete.
Resolving 'fnRegEx'...
Resolving 'vbXlPivotItemPri'...
Resolving 'vbXlPivotAxisPri'...
Resolving 'vbXlPivotFieldPri'...
Resolving 'vbVBAAllPri'...
Resolving 'vbXlRangePri'...
Resolving 'fnToolsPri'...
Resolving 'vbFnPivotFieldPri'...
Resolving 'vbXlPivotTablePri'...
Resolving 'vbXlPivotLinePri'...
Resolving 'fnPivotFieldStatFn_ParPri'...
Resolving 'fnInfoErrMsgPri'...
Resolving 'fnConstPri'...
Resolving 'vbFnCollectionPri'...
Resolving 'ThisWorkbook'...
Resolving 'fnErrorPri'...
Resolving 'fnCheckPri'...
'ThisWorkbook' is Ready. Resolver took 6488ms to complete.
'vbVBAAllPri' is Ready. Resolver took 15748ms to complete.
'fnConstPri' is Ready. Resolver took 9360ms to complete.
'fnTypePri' is Ready. Resolver took 41024ms to complete.
'vbXlPivotAxisPri' is Ready. Resolver took 45925ms to complete.
'fnInfoErrMsgPri' is Ready. Resolver took 80103ms to complete.
'fnCheckPri' is Ready. Resolver took 117537ms to complete.
'vbFnCollectionPri' is Ready. Resolver took 122700ms to complete.
'vbXlRangePri' is Ready. Resolver took 131213ms to complete.
Resolving 'vbVarTypeNamePri'...
'vbXlPivotLinePri' is Ready. Resolver took 235589ms to complete.
'vbXlPivotFieldPri' is Ready. Resolver took 280777ms to complete.
'vbFnPivotTablePri' is Ready. Resolver took 301612ms to complete.
'vbXlPivotItemPri' is Ready. Resolver took 301269ms to complete.
'vbXlPivotTablePri' is Ready. Resolver took 307364ms to complete.
'fnRegEx' is Ready. Resolver took 385093ms to complete.
'vbVarTypeNamePri' is Ready. Resolver took 153507ms to complete.
'fnPivotFieldStatFn_ParPri' is Ready. Resolver took 383385ms to complete.
'fnErrorPri' is Ready. Resolver took 860841ms to complete.
'vbFnPivotItemPri' is Ready. Resolver took 987314ms to complete.
'vbFnPivotFieldPri' is Ready. Resolver took 984727ms to complete.
'fnToolsPri' is Ready. Resolver took 1156145ms to complete. (includes about 30 seconds stopped on a breakpoint)

 "it just takes a while" is a complete understatement. 987314ms is **over 16.45 minutes**, it's just completely unacceptable.. including a few seconds spent on a breakpoint to figure out how many `Declaration` instances were involved (2,249!), the parser ended up in a "Ready" state after just under 20 minutes.

That's just ridiculous, we have a big problem here.

**Comment by retailcoder** [comment]
As for the code inspections... indeed, they take a while to show up - and the *busy indicator* isn't displayed during that time, which is a problem. However performance isn't too bad, given...

![image](https://cloud.githubusercontent.com/assets/5751684/13452386/446fb942-e015-11e5-9941-6f3f51707426.png)

**Comment by autoboosh** [comment]
@Pitterling would you allow us to use your code in integration tests in rubberduck?

@retailcoder I was thinking of adding a new "integration test project" that to begin with has a "grammar validity" test that simply parses as much real world code (that is stored in files in a folder somewhere) as possible and reports any errors (and perhaps even compares the parsed text to the original, which should match 100% since we don't want to lose any information).
Same goes for the preprocessor. We could still do small unit tests for weird edge cases. But this way we can be (fairly) certain that once someone reports a parser error it won't happen again.

**Comment by Pitterling** [comment]
@autoboosh OK, please feel free to use the example workbook for any integration tests.
