### ISSUE TITLE
CodeExplorerComponentViewModel.cs - COMException unhandled

### ISSUE THREAD

**Issue by Pitterling** [rubberduck-vba/Rubberduck#1189]
Hi,
with the latest commit I got a COMException in CodeExplorerComponentViewModel.cs Line 60:
`private vbext_ComponentType ComponentType { get { return _declaration.QualifiedName.QualifiedModuleName.Component.Type; } }`

This time I struggle to provide the excel workbook. 
I attach the Exception details in the hope it will provide some insides:

> System.Runtime.InteropServices.COMException was unhandled by user code
  ErrorCode=-2147467259
  HResult=-2147467259
  Message=Error HRESULT E_FAIL has been returned from a call to a COM component.
  Source=Microsoft.Vbe.Interop
  StackTrace:
       at Microsoft.Vbe.Interop._VBComponent.get_Type()
       at Rubberduck.Navigation.CodeExplorer.CodeExplorerComponentViewModel.get_ComponentType() in C:\Code\Tools\Rubberduck\RetailCoder.VBE\Navigation\CodeExplorer\CodeExplorerComponentViewModel.cs:line 60
       at Rubberduck.Navigation.CodeExplorer.CodeExplorerComponentViewModel.get_DeclarationType() in C:\Code\Tools\Rubberduck\RetailCoder.VBE\Navigation\CodeExplorer\CodeExplorerComponentViewModel.cs:line 75
       at Rubberduck.Navigation.CodeExplorer.CodeExplorerComponentViewModel..ctor(Declaration declaration, IEnumerable`1 declarations) in C:\Code\Tools\Rubberduck\RetailCoder.VBE\Navigation\CodeExplorer\CodeExplorerComponentViewModel.cs:line 34
       at Rubberduck.Navigation.CodeExplorer.CodeExplorerCustomFolderViewModel..ctor(String name, IEnumerable`1 declarations) in C:\Code\Tools\Rubberduck\RetailCoder.VBE\Navigation\CodeExplorer\CodeExplorerCustomFolderViewModel.cs:line 39
       at Rubberduck.Navigation.CodeExplorer.CodeExplorerProjectViewModel.FindFolders(IEnumerable`1 declarations, Char delimiter) in C:\Code\Tools\Rubberduck\RetailCoder.VBE\Navigation\CodeExplorer\CodeExplorerProjectViewModel.cs:line 62
       at Rubberduck.Navigation.CodeExplorer.CodeExplorerProjectViewModel..ctor(Declaration declaration, IEnumerable`1 declarations) in C:\Code\Tools\Rubberduck\RetailCoder.VBE\Navigation\CodeExplorer\CodeExplorerProjectViewModel.cs:line 28
       at Rubberduck.Navigation.CodeExplorer.CodeExplorerViewModel.<>c.<ParserState_StateChanged>b__24_1(IGrouping`2 grouping) in C:\Code\Tools\Rubberduck\RetailCoder.VBE\Navigation\CodeExplorer\CodeExplorerViewModel.cs:line 91
       at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
       at System.Collections.ObjectModel.ObservableCollection`1.CopyFrom(IEnumerable`1 collection)
       at Rubberduck.Navigation.CodeExplorer.CodeExplorerViewModel.ParserState_StateChanged(Object sender, ParserStateEventArgs e) in C:\Code\Tools\Rubberduck\RetailCoder.VBE\Navigation\CodeExplorer\CodeExplorerViewModel.cs:line 90
       at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
       at Rubberduck.Parsing.VBA.RubberduckParserState.OnStateChanged(ParserState state) in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParserState.cs:line 66
       at Rubberduck.Parsing.VBA.RubberduckParserState.set_Status(ParserState value) in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParserState.cs:line 141
       at Rubberduck.Parsing.VBA.RubberduckParserState.SetModuleState(VBComponent component, ParserState state, SyntaxErrorException parserError) in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParserState.cs:line 93
       at Rubberduck.Parsing.VBA.RubberduckParser.Parse(VBComponent vbComponent, CancellationToken token, TokenStreamRewriter rewriter) in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 171
       at Rubberduck.Parsing.VBA.RubberduckParser.ParseComponent(VBComponent component, Boolean resolve, TokenStreamRewriter rewriter) in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 81
       at Rubberduck.Parsing.VBA.RubberduckParser.<>c__DisplayClass10_0.<ParseParallel>b__3() in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 124
       at System.Threading.Tasks.Task.Execute()
  InnerException: 

This is within the Immediate output:

> Exception thrown: 'Rubberduck.Parsing.Symbols.SyntaxErrorException' in Rubberduck.Parsing.dll
Rubberduck.Parsing.Symbols.SyntaxErrorException: extraneous input '#' expecting {'!', '.', ACCESS, ADDRESSOF, ALIAS, AND, ATTRIBUTE, APPACTIVATE, APPEND, AS, BEGIN, BEEP, BINARY, BOOLEAN, BYVAL, BYREF, BYTE, CALL, CASE, CHDIR, CHDRIVE, CLASS, CLOSE, COLLECTION, CONST, DATABASE, DATE, DECLARE, DEFBOOL, DEFBYTE, DEFDATE, DEFDBL, DEFDEC, DEFCUR, DEFINT, DEFLNG, DEFOBJ, DEFSNG, DEFSTR, DEFVAR, DELETESETTING, DIM, DO, DOUBLE, EACH, ELSE, ELSEIF, END_SUB, END, ENUM, EQV, ERASE, ERROR, EVENT, EXIT_DO, EXIT_FOR, EXIT_FUNCTION, EXIT_PROPERTY, EXIT_SUB, FALSE, FILECOPY, FRIEND, FOR, FUNCTION, GET, GLOBAL, GOSUB, GOTO, IF, IMP, IMPLEMENTS, IN, INPUT, IS, INTEGER, KILL, LOAD, LOCK, LONG, LOOP, LEN, LET, LIB, LIKE, LINE_INPUT, LSET, ME, MID, MKDIR, MOD, NAME, NEXT, NEW, NOT, NOTHING, NULL, ON, ON_ERROR, ON_LOCAL_ERROR, OPEN, OPTIONAL, OR, OUTPUT, PARAMARRAY, PRESERVE, PRINT, PRIVATE, PUBLIC, PUT, RANDOM, RANDOMIZE, RAISEEVENT, READ, REDIM, REM, RESET, RESUME, RETURN, RMDIR, RSET, SAVEPICTURE, SAVESETTING, SEEK, SELECT, SEN
DKEYS, SET, SETATTR, SHARED, SINGLE, SPC, STATIC, STEP, STOP, STRING, SUB, TAB, TEXT, THEN, TIME, TO, TRUE, TYPE, TYPEOF, UNLOAD, UNLOCK, UNTIL, VARIANT, VERSION, WEND, WHILE, WIDTH, WITH, WITHEVENTS, WRITE, XOR, NEWLINE, REMCOMMENT, COMMENT, ':', WS, IDENTIFIER}
   at Rubberduck.Parsing.Symbols.ExceptionErrorListener.SyntaxError(IRecognizer recognizer, IToken offendingSymbol, Int32 line, Int32 charPositionInLine, String msg, RecognitionException e) in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\Symbols\ExceptionErrorListener.cs:line 10
   at Antlr4.Runtime.ProxyErrorListener`1.SyntaxError(IRecognizer recognizer, Symbol offendingSymbol, Int32 line, Int32 charPositionInLine, String msg, RecognitionException e)
   at Antlr4.Runtime.Parser.NotifyErrorListeners(IToken offendingToken, String msg, RecognitionException e)
   at Antlr4.Runtime.DefaultErrorStrategy.Sync(Parser recognizer)
   at Rubberduck.Parsing.Grammar.VBAParser.endOfStatement() in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 14773
   at Rubberduck.Parsing.Grammar.VBAParser.subStmt() in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 8273
   at Rubberduck.Parsing.Grammar.VBAParser.moduleBodyElement() in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1129
   at Rubberduck.Parsing.Grammar.VBAParser.moduleBody() in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1033
   at Rubberduck.Parsing.Grammar.VBAParser.module() in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 340
   at Rubberduck.Parsing.Grammar.VBAParser.startRule() in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 222
   at Rubberduck.Parsing.VBA.RubberduckParser.ParseInternal(ICharStream stream, IEnumerable`1 listeners, ITokenStream& outStream) in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 292
   at Rubberduck.Parsing.VBA.RubberduckParser.ParseInternal(String code, IEnumerable`1 listeners, ITokenStream& outStream) in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 276
   at Rubberduck.Parsing.VBA.RubberduckParser.ParseInternal(VBComponent vbComponent, String code, CancellationToken token) in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 241
   at Rubberduck.Parsing.VBA.RubberduckParser.Parse(VBComponent vbComponent, CancellationToken token, TokenStreamRewriter rewriter) in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 160
Exception thrown: 'System.Runtime.InteropServices.COMException' in Rubberduck.dll

Let me know If I can provide something more, but without providing the full workbook.

**Comment by Pitterling** [comment]
OK, today i tried on another environment and receive only the 
> Rubberduck.Parsing.Symbols.SyntaxErrorException: extraneous input '#'

I was able to drill it down to an conditional #if statement:

```
`Option Explicit
'setting #CONST ccDEBUGGING within Project properties = 0|1

Public Sub disableScreenOutput()
 #If ccDEBUGGING = 0 Then
 
    With Application
    
        .ScreenUpdating = False
    
    End With

 #End If
End Sub`
```

**Comment by retailcoder** [comment]
Note, project-wide precompiler constants are not accessible to the interpreter for now, which means we can't tell if `ccDEBUGGING` is on or off.

**Comment by Pitterling** [comment]
Understand, but it should not break the parsing completely, right?

**Comment by retailcoder** [comment]
Correct.

**Comment by Pitterling** [comment]
i'm not able to reproduce the "COMException unhandled" error. you might close this issue ?!

**Comment by retailcoder** [comment]
Sure, thanks! Except, I really need to go and finish that darn CodeExplorerViewModel...
