### ISSUE TITLE
Hooking up a remote repository that's not finalized blows everything up

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1205]
So I clicked the [Clone] button, went to GitHub to create a new repository, and then copied the url to the *remote path* box; the *local directory* automatically populated:

![image](https://cloud.githubusercontent.com/assets/5751684/13900407/b33bb442-eddb-11e5-9429-d5423fda250b.png)

Then I clicked [Ok] and after a few seconds the EXCEL.EXE process died on me and I had this stack trace in the debug output:

> A first chance exception of type 'System.InvalidOperationException' occurred in System.Core.dll 
A first chance exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll 
System.Windows.Data Error: 17 : Cannot get 'CurrentBranch' value (type 'String') from '' (type 'ChangesViewViewModel'). BindingExpression:Path=CurrentBranch; DataItem='ChangesViewViewModel' (HashCode=66476022); target element is 'TextBlock' (Name=''); target property is 'Text' (type 'String') TargetInvocationException:'System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Sequence contains no matching element 
at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate) 
at Rubberduck.SourceControl.GitProvider.get_CurrentBranch() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.SourceControl\GitProvider.cs:line 84 
at Rubberduck.UI.SourceControl.ChangesViewViewModel.get_CurrentBranch() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\ChangesViewViewModel.cs:line 76 
--- End of inner exception stack trace --- 
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) 
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) 
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) 
at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index) 
at MS.Internal.Data.PropertyPathWorker.GetValue(Object item, Int32 level) 
at MS.Internal.Data.PropertyPathWorker.RawValue(Int32 k)' 
A first chance exception of type 'System.InvalidOperationException' occurred in System.Core.dll 
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\WINDOWS\assembly\GAC_MSIL\Microsoft.VisualStudio.Debugger.Runtime\12.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.Debugger.Runtime.dll'. 
The program '[7272] EXCEL.EXE' has exited with code -1073741819 (0xc0000005) 'Access violation'.

It would be nice to catch it and display a message box to the user when something goes wrong with hooking up the specified repository...

**Comment by retailcoder** [comment]
Some more clues... the repository exists, but it's empty; I get the same 'Access violation' ka-boom when I try to *open working directory* on the empty repo:

> A first chance exception of type 'System.InvalidOperationException' occurred in System.Core.dll
A first chance exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll
System.Windows.Data Error: 17 : Cannot get 'CurrentBranch' value (type 'String') from '' (type 'ChangesViewViewModel'). BindingExpression:Path=CurrentBranch; DataItem='ChangesViewViewModel' (HashCode=66476022); target element is 'TextBlock' (Name=''); target property is 'Text' (type 'String') TargetInvocationException:'System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Rubberduck.SourceControl.GitProvider.get_CurrentBranch() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.SourceControl\GitProvider.cs:line 84
   at Rubberduck.UI.SourceControl.ChangesViewViewModel.get_CurrentBranch() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\ChangesViewViewModel.cs:line 76
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at MS.Internal.Data.PropertyPathWorker.GetValue(Object item, Int32 level)
   at MS.Internal.Data.PropertyPathWorker.RawValue(Int32 k)'
A first chance exception of type 'System.InvalidOperationException' occurred in System.Core.dll
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\WINDOWS\assembly\GAC_MSIL\Microsoft.VisualStudio.Debugger.Runtime\12.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.Debugger.Runtime.dll'. 
The program '[4284] EXCEL.EXE' has exited with code -1073741819 (0xc0000005) 'Access violation'.

**Comment by retailcoder** [comment]
It's not clear how the initial setup is supposed to be working - there's like some kind of chicken-and-egg problem here, where the SC panel needs an existing remote repo, but then you go and create it and then you can't work in it because - I presume - it's empty.

**Comment by Hosch250** [comment]
Just for the record, this is how you do it:

To clone an existing repo, go clone a repo with content in it.
To start work on a new project you want to be source controlled, initialize a new repo from the project.
To work on a locally-stored source control project, use open existing repo.
To push an existing repo to a remote, go create an empty remote, then use the upload feature (PR'ed at the time of writing this) to specify the branch name and location.

This needs to be thoroughly outlined in the website for new users.
