### ISSUE TITLE
Opening settings dialog throws indenter error

### ISSUE THREAD

**Issue by autoboosh** [rubberduck-vba/Rubberduck#1606]
Here's the error:

```
System.Windows.Data Error: 17 : Cannot get 'PreviewSampleCode' value (type 'String') from '' (type 'IndenterSettingsViewModel'). BindingExpression:Path=PreviewSampleCode; DataItem='IndenterSettingsViewModel' (HashCode=61415348); target element is 'TextBlock' (Name=''); target property is 'Text' (type 'String') TargetInvocationException:'System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentOutOfRangeException: 'count' must be non-negative.
Parameter name: count
   at System.String.CtorCharCount(Char c, Int32 count)
   at Rubberduck.SmartIndenter.Indenter.Indent(String[] codeLines, String moduleName, Boolean reportProgress, Int32 linesAlreadyRebuilt) in D:\Temp\Rubberduck\Rubberduck.SmartIndenter\Indenter.cs:line 471
   at Rubberduck.UI.Settings.IndenterSettingsViewModel.get_PreviewSampleCode() in D:\Temp\Rubberduck\RetailCoder.VBE\UI\Settings\IndenterSettingsViewModel.cs:line 309
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at MS.Internal.Data.PropertyPathWorker.GetValue(Object item, Int32 level)
   at MS.Internal.Data.PropertyPathWorker.RawValue(Int32 k)'
```

Line 471 in Indenter.cs:

`currentLine += new string(' ', gap) + right;`

There's also another error right after the stack trace, not sure if it's the same issue:

`System.Windows.Data Error: 2 : Cannot find governing FrameworkElement or FrameworkContentElement for target element. BindingExpression:Path=LocalizedName; DataItem=null; target element is 'DataGridTemplateColumn' (HashCode=59981247); target property is 'SortMemberPath' (type 'String')`

**Comment by Hosch250** [comment]
Known error.  The indenter crashes for a couple of the line-ending settings.

**Comment by Hosch250** [comment]
Comintern already has this fixed in his branch.
