### ISSUE TITLE
Multiple `Attribute VB_Ext_KEY` entries cause Unhandled Exception

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1683]
A project with this existing code, or a project that tries to import this code encounters the error.

```vb
Attribute VB_Ext_KEY = "MyKey" ,"My Value"
Attribute VB_Ext_KEY = "MyKey1" ,"My Value"
```

```text
************** Exception Text **************
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Rubberduck.Parsing.VBA.AttributeParser.AttributeListener.ExitAttributeStmt(AttributeStmtContext context) in c:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\VBA\AttributeParser.cs:line 169
   at Rubberduck.Parsing.Grammar.VBAParser.AttributeStmtContext.ExitRule(IParseTreeListener listener) in c:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 759
   at Antlr4.Runtime.Tree.ParseTreeWalker.ExitRule(IParseTreeListener listener, IRuleNode r)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Rubberduck.Parsing.VBA.VBAModuleParser.Parse(String moduleName, String moduleCode, IParseTreeListener[] listeners, ITokenStream& outStream) in c:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\VBA\VBAModuleParser.cs:line 39
   at Rubberduck.Parsing.VBA.AttributeParser.Parse(VBComponent component) in c:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\VBA\AttributeParser.cs:line 51
   at Rubberduck.Parsing.VBA.ComponentParseTask.Start(CancellationToken token) in c:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\VBA\ComponentParseTask.cs:line 52
   at Rubberduck.Parsing.VBA.RubberduckParser.ParseAsyncInternal(VBComponent component, CancellationToken token, TokenStreamRewriter rewriter) in c:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 470
   at Rubberduck.Parsing.VBA.RubberduckParser.<>c__DisplayClass26.<ParseAsync>b__24() in c:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 399
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

Unlike all other Attributes, `VB_Ext_KEY` can occur multiple times in a module, as long as it has unique keys for each instance's first argument. If a text file is imported that has conflicting keys, the VBE silently drops the duplicates and only retains the *last* instance's key and value.

Here's a class module with as many Attributes as I could squeeze in. Rubberduck handles them all except the `Attribute VB_Ext_KEY` entries.
```
VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ClassKeys"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Attribute VB_Description = "The Class 2 Description"
Attribute VB_Ext_KEY = "My1ArgKey" ,"Duplicate Key"
Attribute VB_Ext_KEY = "My.Key" ,"Fizz"
Attribute VB_Ext_KEY = "My:Key" ,"Fizz"
Attribute VB_Ext_KEY = "My,Key" ,"Fizz"
Attribute VB_Ext_KEY = "MyKey(1)" ,"Fizz"


Public MyVar As String
Attribute MyVar.VB_VarUserMemId = 256
Attribute MyVar.VB_VarHelpID = 4
Attribute MyVar.VB_VarDescription = "The MyVar description"


Public Function MyFunc() As String
Attribute MyFunc.VB_Description = "The MyFunc Description"
Attribute MyFunc.VB_HelpID = 2
Attribute MyFunc.VB_ProcData.VB_Invoke_Func = "K\n14"
Attribute MyFunc.VB_MemberFlags = "400"

  MsgBox "MyFunc"

End Function

Public Sub MySub()
Attribute MySub.VB_Description = "The MySub Description"
Attribute MySub.VB_HelpID = 3
Attribute MySub.VB_ProcData.VB_Invoke_Func = "J\n14"
Attribute MySub.VB_MemberFlags = "400"

  MsgBox "MySub"

End Sub

Public Property Get MyProp() As String
Attribute MyProp.VB_Description = "The MyProp Description"
Attribute MyProp.VB_HelpID = 1
Attribute MyProp.VB_ProcData.VB_Invoke_Property = "L\n14"

  MsgBox "MyProp"

End Property

Public Property Let MyProp(propVal As String)
Attribute MyProp.VB_ProcData.VB_Invoke_PropertyPut = "M\n14"

  MsgBox "MyProp Let/Put"

End Property

Public Property Set MyProp(propVal As Object)
Attribute MyProp.VB_ProcData.VB_Invoke_PropertyPutRef = "M\n14"

  MsgBox "MyProp Set/Put Ref"

End Property

Public Property Get Value() As String
Attribute Value.VB_Description = "The <Default> Value Description"
Attribute Value.VB_HelpID = 5
Attribute Value.VB_UserMemId = 0


End Property

Property Get NewEnum() As IUnknown
Attribute NewEnum.VB_UserMemId = -4
Attribute NewEnum.VB_MemberFlags = "40"

  Set NewEnum = Nothing
End Property
```

**Comment by autoboosh** [comment]
Thanks, very helpful. Do you have a list of VB attributes and how they are used somewhere?

**Comment by ThunderFrame** [comment]
Have you seen @ckuhn203's [page](https://christopherjmcclellan.wordpress.com/2015/04/21/vb-attributes-what-are-they-and-why-should-we-use-them/)

I think my examples above are *mostly* self evident, but while VBA does persist `VB_MemberFlags`, I don't think VBA honors or does anything with `VB_MemberFlags` 

Some of the attributes are in the raw module test within the VBA binary, but are never exposed in the UI or the exported text files, like `VB_Control` and `VB_Base`

I pulled these from EXCEL.EXE memory strings:

```text
VB_Base
VB_Control
VB_Creatable
VB_Customizable
VB_Description
VB_Exposed
VB_Ext_KEY
VB_GlobalNameSpace
VB_HelpID
VB_Invoke_Func
VB_Invoke_Property
VB_Invoke_PropertyPut
VB_Invoke_PropertyPutRef
VB_MemberFlags
VB_Name
VB_PredeclaredId
VB_ProcData
VB_TemplateDerived
VB_VarDescription
VB_VarHelpID
VB_VarMemberFlags
VB_VarProcData
VB_UserMemId
VB_VarUserMemId
```

**Comment by ckuhn203** [comment]
@Thunderframe, you mean people actually *read* the trash I write?! Lol

Anyway, I wrote up a much better explanation on StackOverflow. http://stackoverflow.com/a/34688164/3198973

**Comment by ThunderFrame** [comment]
See my [SO answer](http://stackoverflow.com/questions/37078992/how-do-i-know-that-thisworkbook-is-a-workbook/37085277#37085277) for examples of the attributes hidden in module inside the VBA Binary.

Also see #1230 for more examples, particularly the VB_Control attribute

**Comment by mburns08109** [comment]
One point to mention in all this is that there seem to be some things like "Excel-isms" involved in these ATTRIBUTE lines, most especially the VB_INVOKE_FUNC area. Without making a more exhaustive search into the other Office (and related) apps, and how their generated/exported VBA modules utilize the ATTRIBUTE "feature" differently, I'm not sure we'll get the whole picture or be able to properly define what these things may really do.
