### ISSUE TITLE
RD had an error

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#1985]
I had an XLSM open with the VBE opened.
I opened an XLSX to look at it for a minute.
I closed the XLSX, then RD told me it had an issue, I should save & close & upload my log file, so here it is.
[rubberduck.log.txt](https://github.com/rubberduck-vba/Rubberduck/files/353023/rubberduck.log.txt)

I do not know what the error was.

**Comment by Vogel612** [comment]
Pasting the last few lines from the log for simplicity

```
2016-07-07 16:44:44.6855;TRACE;DynamicInjector4076424c4453494a9bb95179e9f18b0c;Intercepted invocation of 'ProcedureNotUsedInspection.GetInspectionResults' returned 9 objects.;
2016-07-07 16:44:45.6516;TRACE;DynamicInjector4076424c4453494a9bb95179e9f18b0c;Intercepted invocation of 'ParameterCanBeByValInspection.GetInspectionResults' returned 111 objects.;
2016-07-07 16:44:48.9440;DEBUG;Rubberduck.App;App handles StateChanged (Ready), evaluating menu states...;
2016-07-07 16:44:51.6792;TRACE;DynamicInjector4076424c4453494a9bb95179e9f18b0c;Intercepted invocation of 'UnassignedVariableUsageInspection.GetInspectionResults' returned 56 objects.;
2016-07-07 16:44:58.8230;FATAL;Rubberduck.UI.UnitTesting.TestExplorerViewModel;System.Runtime.InteropServices.COMException (0x800A01A8): Exception from HRESULT: 0x800A01A8
   at Microsoft.Vbe.Interop._VBProject.get_VBComponents()
   at Rubberduck.Parsing.VBA.RubberduckParserState.IsDirty() in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParserState.cs:line 911
   at Rubberduck.UI.Command.CommandBase.CanExecute(Object parameter) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 32;
2016-07-07 16:45:11.5672;FATAL;Rubberduck.Navigation.CodeExplorer.CodeExplorerViewModel;System.Runtime.InteropServices.COMException (0x800A01A8): Exception from HRESULT: 0x800A01A8
   at Microsoft.Vbe.Interop._VBProject.get_VBComponents()
   at Rubberduck.Parsing.VBA.RubberduckParserState.IsDirty() in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParserState.cs:line 911
   at Rubberduck.UI.Command.CommandBase.CanExecute(Object parameter) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 32;
2016-07-07 16:45:12.6723;TRACE;DynamicInjector4076424c4453494a9bb95179e9f18b0c;Intercepted invocation of 'ImplicitByRefParameterInspection.GetInspectionResults' returned 8 objects.;
2016-07-07 16:45:15.5456;FATAL;Rubberduck.UI.ToDoItems.ToDoExplorerViewModel;System.Runtime.InteropServices.COMException (0x800A01A8): Exception from HRESULT: 0x800A01A8
   at Microsoft.Vbe.Interop._VBProject.get_VBComponents()
   at Rubberduck.Parsing.VBA.RubberduckParserState.IsDirty() in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParserState.cs:line 911
   at Rubberduck.UI.Command.CommandBase.CanExecute(Object parameter) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 32;
2016-07-07 16:45:21.2782;TRACE;DynamicInjector4076424c4453494a9bb95179e9f18b0c;Intercepted invocation of 'ImplicitByRefParameterInspection.GetInspectionResults' returned 8 objects.;
```

IIUC this is the same bug that's already reported for closing the Host App
