### ISSUE TITLE
ComponentParseTask crash in RD 2.0.5 + log

### ISSUE THREAD

**Issue by eteichm** [rubberduck-vba/Rubberduck#2050]
Hello 
below is the requested log file after the crash of RD 2.0.5. 

2016-07-13 19:57:05.3433;ERROR;Rubberduck.Parsing.VBA.ComponentParseTask;Exception thrown in thread 8.;System.Runtime.InteropServices.COMException (0x800A01A8): Exception from HRESULT: 0x800A01A8
   at Microsoft.Vbe.Interop._VBProject.get_HelpFile()
   at Rubberduck.Parsing.VBA.RubberduckParserState.SetModuleState(VBComponent component, ParserState state, SyntaxErrorException parserError) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParserState.cs:line 312
   at Rubberduck.Parsing.VBA.RubberduckParser.<>c__DisplayClass22_0.<ParseAsyncInternal>b__1(Object sender, ParseCompletionArgs e) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 500
   at Rubberduck.Parsing.VBA.ComponentParseTask.Start(CancellationToken token) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\VBA\ComponentParseTask.cs:line 68

**Comment by Hosch250** [comment]
Thanks.

**Comment by retailcoder** [comment]
@eteichm was that at startup, random in the middle of a session, or as you were quitting the host application?

**Comment by eteichm** [comment]
It was random in the middle of a session. 
The Excel file contains a total of 36 modules.  I'll provide a longer log file if required.

**Comment by retailcoder** [comment]
@eteichm yeah. seems the few previous log entries would have a clue about what happened. do you have `TRACE` level enabled?

**Comment by eteichm** [comment]
Yes, I've TRACE and DEBUG level enabled as well.  See attached longer log file. 
[Rubberduck_crash.zip](https://github.com/rubberduck-vba/Rubberduck/files/362381/Rubberduck_crash.zip)

**Comment by Vogel612** [comment]
Is this still relevant for 2.0.8?

**Comment by eteichm** [comment]
I can't test before Sept 2nd.

**Comment by retailcoder** [comment]
deemed fixed
