### ISSUE TITLE
Test explorer is freezing when trying to run tests with early bound Assert without Rubberduck reference

### ISSUE THREAD

**Issue by lkavicky** [rubberduck-vba/Rubberduck#2056]
I have some tests with early bound Assert, because of issue #2054 I have removed the Rubberduck reference from the project and tried to run the tests. Obviously I have got an error message, but the test explorer has stayed afterwards frozen in loading mode (circle moving in the center) and is not reacting to any clicks (the buttons are disabled).

Related log entry:

`2016-07-14 21:30:31.4358;DEBUG;Rubberduck.UI.Command.MenuItems.ParentMenus.ParentMenuItemBase;(27824865) Executing click handler for menu item '&Test Explorer', hash code 21830376;
2016-07-14 21:30:34.7048;DEBUG;Rubberduck.App;App handles StateChanged (Ready), evaluating menu states...;
2016-07-14 21:30:35.9408;FATAL;Rubberduck.UI.UnitTesting.TestExplorerViewModel;System.Runtime.InteropServices.COMException (0x800A09D5): Microsoft Access cannot find the procedure 'ImportDB.ModuleInitialize_MeldungXMLReader.'
   at Microsoft.Office.Interop.Access._Application.Run(String Procedure, Object& Arg1, Object& Arg2, Object& Arg3, Object& Arg4, Object& Arg5, Object& Arg6, Object& Arg7, Object& Arg8, Object& Arg9, Object& Arg10, Object& Arg11, Object& Arg12, Object& Arg13, Object& Arg14, Object& Arg15, Object& Arg16, Object& Arg17, Object& Arg18, Object& Arg19, Object& Arg20, Object& Arg21, Object& Arg22, Object& Arg23, Object& Arg24, Object& Arg25, Object& Arg26, Object& Arg27, Object& Arg28, Object& Arg29, Object& Arg30)
   at Rubberduck.VBEditor.VBEHost.AccessApp.Run(QualifiedMemberName qualifiedMemberName) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.VBEEditor\VBEHost\AccessApp.cs:line 12
   at Rubberduck.UnitTesting.TestEngine.Run(IEnumerable`1 members) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\UnitTesting\TestEngine.cs:line 110
   at Rubberduck.UnitTesting.TestEngine.Run(IEnumerable`1 tests) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\UnitTesting\TestEngine.cs:line 73
   at Rubberduck.UI.Command.RunAllTestsCommand.RunTests() in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\UI\Command\RunAllTestsCommand.cs:line 63
   at Rubberduck.UI.Command.RunAllTestsCommand.ExecuteImpl(Object parameter) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\UI\Command\RunAllTestsCommand.cs:line 39
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 51;
2016-07-14 21:30:38.8910;DEBUG;Rubberduck.Common.Hotkeys.Hotkey;Hotkey (Oemtilde) not registered.;
2016-07-14 21:31:21.7485;DEBUG;Rubberduck.Common.Hotkeys.Hotkey;Hotkey (Oemtilde) not registered.;`

I'm running RD 2.0.5-rc on Office 2010(32bit), Win7 (64bit)

**Comment by Hosch250** [comment]
I'm pretty sure that in order to regain control of it, you need to click the red square stop button.  Rubberduck cannot tell that the VBE is hung, and the VBE doesn't return control to Rubberduck until the execution stops.

**Comment by lkavicky** [comment]
I've tried the Reset button (many times), but it's not helping - the explorer is still behaving the same way (circle moving,  buttons disabled)

![untitled](https://cloud.githubusercontent.com/assets/1942695/16853813/5d59b742-4a0e-11e6-877f-f078b01313df.png)

**Comment by Hosch250** [comment]
OK, sounds like a bug.

**Comment by lkavicky** [comment]
Btw. MSACCESS process is running even after closing Access. In order to restart the program I need to kill the process.

**Comment by Hosch250** [comment]
Yes, that is a known issue, and one that is extremely difficult to fix.  We have a memory leak somewhere.

**Comment by retailcoder** [comment]
Perhaps we could check to see if the `AssertClass` is early-bound in any of the test modules? We just need to check the *AsTypeName* of all fields in test modules (we can't assume the identifier name will be `Assert` here); if any of them is a Rubberduck type, we know we need to verify whether the project has a reference to the RD tlb. Although.... again that would be a compile error that the VBE can catch on its own, but that is one we could automatically fix.

**Comment by Hosch250** [comment]
So, basically check whether any non-builtin declarations have the `AsTypeName` of `Rubberduck.PermissiveAssertClass` or `Rubberduck.AssertClass` and automatically reference RD's library if there are any?
