### ISSUE TITLE
Code Explorer and TODO Explorer not refreshed correctly after "Remove.." used on a module.

### ISSUE THREAD

**Issue by PeterMTaylor** [rubberduck-vba/Rubberduck#2085]
Using RD 2.0.6 I did a small test to see if any issues shows up with Code Explorer / TODO Explorer when removing an module called googlesheet, as highlighted in blue. 

I had observed that TODO Explorer Notes do NOT get cleared up after Removal request from Code Explorer.

![capture 2 0 6 failed to delete note after delete in code explorer](https://cloud.githubusercontent.com/assets/2254567/16948311/572877f4-4df7-11e6-9bf1-9f8bde87cf9c.PNG)

Here this test fails after doing a "Remove..." in Code Explorer for googleSheet in while Ready state.

![capture 2 0 6 failed to delete note after delete in code explorer error](https://cloud.githubusercontent.com/assets/2254567/16948309/5726ddae-4df7-11e6-85dd-838d50df48de.PNG)

Still unable to attach .txt file so I can only with ZIP files. Grr!!
[rubberduck.txt.zip](https://github.com/rubberduck-vba/Rubberduck/files/371324/rubberduck.txt.zip)

There are COM issues in the log and has something like this 
`2016-07-1512:52:48.1006;FATAL;Rubberduck.UI.Inspections.InspectionResultsViewModel;System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Microsoft.Vbe.Interop._VBComponent.get_CodeModule()
   at Rubberduck.Inspections.DeclareAsExplicitVariantQuickFix.Fix() in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\Inspections\VariableTypeNotDeclaredInspectionResult.cs:line 46
   at Rubberduck.UI.Inspections.InspectionResultsViewModel.ExecuteQuickFixes(IEnumerable``1 quickFixes) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\UI\Inspections\InspectionResultsViewModel.cs:line 307
   at Rubberduck.UI.Inspections.InspectionResultsViewModel.ExecuteQuickFixInModuleCommand(Object parameter) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\UI\Inspections\InspectionResultsViewModel.cs:line 367
   at Rubberduck.UI.Command.DelegateCommand.ExecuteImpl(Object parameter) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\UI\Command\DelegateCommand.cs:line 26
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 51;
`

![capture 2 0 6 failed to delete note after delete in code explorer error after refresh button](https://cloud.githubusercontent.com/assets/2254567/16948310/57278c5e-4df7-11e6-9cbc-ac5874d9427f.PNG)

Here note that the Project Explorer showed the Removed googleSheet but TODO Explorer hasn't refreshed nor has the Code Explorer updated after the error however given the misleading "Ready" state AFTER the ERROR occured.

**Comment by Hosch250** [comment]
I can't repro the CE not being removed, but I can repro the Todo Explorer not being refresh.

**Comment by retailcoder** [comment]
Confirming as fixed.
