### ISSUE TITLE
Double error windows ( crash) keep popping up, cannot save work.

### ISSUE THREAD

**Issue by TZubiri** [rubberduck-vba/Rubberduck#2113]
[rubberduck.txt](https://github.com/rubberduck-vba/Rubberduck/files/376935/rubberduck.txt)

**Comment by Vogel612** [comment]
For starters: Resolver seems bork:

```
2016-07-20 15:27:29.9423;ERROR;Rubberduck.Parsing.VBA.RubberduckParser;Exception thrown resolving 'Username' (thread 25).;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.Parsing.Symbols.ClassModuleDeclaration.GetSupertypes(Declaration type) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Symbols\ClassModuleDeclaration.cs:line 52
   at Rubberduck.Parsing.Symbols.DeclarationFinder.FindMemberEnclosingModule(Declaration callingModule, Declaration callingParent, String memberName, DeclarationType memberType) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Symbols\DeclarationFinder.cs:line 252
   at Rubberduck.Parsing.Binding.SimpleNameTypeBinding.ResolveEnclosingModule(String name) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Binding\SimpleNameTypeBinding.cs:line 105
   at Rubberduck.Parsing.Binding.SimpleNameTypeBinding.ResolvePreferUdt(String name) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Binding\SimpleNameTypeBinding.cs:line 42
   at Rubberduck.Parsing.Binding.SimpleNameTypeBinding.Resolve() in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Binding\SimpleNameTypeBinding.cs:line 32
   at Rubberduck.Parsing.Binding.TypeBindingContext.Resolve(Declaration module, Declaration parent, ParserRuleContext expression, IBoundExpression withBlockVariable, StatementResolutionContext statementContext) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Binding\TypeBindingContext.cs:line 21
   at Rubberduck.Parsing.Binding.BindingService.ResolveType(Declaration module, Declaration parent, ParserRuleContext expression) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Binding\BindingService.cs:line 49
   at Rubberduck.Parsing.Symbols.IdentifierReferenceResolver.ResolveType(ParserRuleContext expression) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceResolver.cs:line 171
   at Rubberduck.Parsing.Symbols.IdentifierReferenceResolver.Resolve(AsTypeClauseContext context) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceResolver.cs:line 564
   at Rubberduck.Parsing.Symbols.IdentifierReferenceListener.EnterAsTypeClause(AsTypeClauseContext context) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceListener.cs:line 274
   at Rubberduck.Parsing.Grammar.VBAParser.AsTypeClauseContext.EnterRule(IParseTreeListener listener) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 14136
   at Antlr4.Runtime.Tree.ParseTreeWalker.EnterRule(IParseTreeListener listener, IRuleNode r)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Rubberduck.Parsing.VBA.RubberduckParser.ResolveReferences(DeclarationFinder finder, VBComponent component, IParseTree tree) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 584
2016-07-20 15:27:29.9423;ERROR;Rubberduck.Parsing.VBA.RubberduckParser;Exception thrown resolving 'StringLib' (thread 27).;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.Parsing.Binding.SimpleNameDefaultBinding.ResolveProcedureNamespace() in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Binding\SimpleNameDefaultBinding.cs:line 79
   at Rubberduck.Parsing.Binding.SimpleNameDefaultBinding.Resolve() in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Binding\SimpleNameDefaultBinding.cs:line 40
   at Rubberduck.Parsing.Binding.DefaultBindingContext.Resolve(Declaration module, Declaration parent, ParserRuleContext expression, IBoundExpression withBlockVariable, StatementResolutionContext statementContext) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Binding\DefaultBindingContext.cs:line 29
   at Rubberduck.Parsing.Symbols.IdentifierReferenceResolver.ResolveDefault(ParserRuleContext expression, StatementResolutionContext statementContext, Boolean isAssignmentTarget, Boolean hasExplicitLetStatement) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceResolver.cs:line 153
   at Rubberduck.Parsing.Symbols.IdentifierReferenceResolver.Resolve(LetStmtContext context) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceResolver.cs:line 333
   at Rubberduck.Parsing.Symbols.IdentifierReferenceListener.EnterLetStmt(LetStmtContext context) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceListener.cs:line 264
   at Rubberduck.Parsing.Grammar.VBAParser.LetStmtContext.EnterRule(IParseTreeListener listener) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 8511
   at Antlr4.Runtime.Tree.ParseTreeWalker.EnterRule(IParseTreeListener listener, IRuleNode r)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Rubberduck.Parsing.VBA.RubberduckParser.ResolveReferences(DeclarationFinder finder, VBComponent component, IParseTree tree) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 584
2016-07-20 15:27:29.9423;ERROR;Rubberduck.Parsing.VBA.RubberduckParser;Exception thrown resolving 'FileLib' (thread 21).;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.Parsing.Symbols.ClassModuleDeclaration.GetSupertypes(Declaration type) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Symbols\ClassModuleDeclaration.cs:line 52
   at Rubberduck.Parsing.Symbols.DeclarationFinder.FindMemberEnclosingModule(Declaration callingModule, Declaration callingParent, String memberName, DeclarationType memberType) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Symbols\DeclarationFinder.cs:line 252
   at Rubberduck.Parsing.Binding.SimpleNameTypeBinding.ResolveEnclosingModule(String name) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Binding\SimpleNameTypeBinding.cs:line 105
   at Rubberduck.Parsing.Binding.SimpleNameTypeBinding.ResolvePreferUdt(String name) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Binding\SimpleNameTypeBinding.cs:line 42
   at Rubberduck.Parsing.Binding.SimpleNameTypeBinding.Resolve() in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Binding\SimpleNameTypeBinding.cs:line 32
   at Rubberduck.Parsing.Binding.TypeBindingContext.Resolve(Declaration module, Declaration parent, ParserRuleContext expression, IBoundExpression withBlockVariable, StatementResolutionContext statementContext) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Binding\TypeBindingContext.cs:line 21
   at Rubberduck.Parsing.Binding.BindingService.ResolveType(Declaration module, Declaration parent, ParserRuleContext expression) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Binding\BindingService.cs:line 49
   at Rubberduck.Parsing.Symbols.IdentifierReferenceResolver.ResolveType(ParserRuleContext expression) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceResolver.cs:line 171
   at Rubberduck.Parsing.Symbols.IdentifierReferenceResolver.Resolve(AsTypeClauseContext context) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceResolver.cs:line 564
   at Rubberduck.Parsing.Symbols.IdentifierReferenceListener.EnterAsTypeClause(AsTypeClauseContext context) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceListener.cs:line 274
   at Rubberduck.Parsing.Grammar.VBAParser.AsTypeClauseContext.EnterRule(IParseTreeListener listener) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 14136
   at Antlr4.Runtime.Tree.ParseTreeWalker.EnterRule(IParseTreeListener listener, IRuleNode r)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Rubberduck.Parsing.VBA.RubberduckParser.ResolveReferences(DeclarationFinder finder, VBComponent component, IParseTree tree) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 584
2016-07-20 15:27:29.9423;ERROR;Rubberduck.Parsing.VBA.RubberduckParser;Exception thrown resolving 'RangeLib' (thread 33).;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.Parsing.Symbols.ClassModuleDeclaration.GetSupertypes(Declaration type) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Symbols\ClassModuleDeclaration.cs:line 52
   at Rubberduck.Parsing.Symbols.DeclarationFinder.FindMemberEnclosingModule(Declaration callingModule, Declaration callingParent, String memberName, DeclarationType memberType) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Symbols\DeclarationFinder.cs:line 252
   at Rubberduck.Parsing.Binding.SimpleNameTypeBinding.ResolveEnclosingModule(String name) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Binding\SimpleNameTypeBinding.cs:line 105
   at Rubberduck.Parsing.Binding.SimpleNameTypeBinding.ResolvePreferUdt(String name) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Binding\SimpleNameTypeBinding.cs:line 42
   at Rubberduck.Parsing.Binding.SimpleNameTypeBinding.Resolve() in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Binding\SimpleNameTypeBinding.cs:line 32
   at Rubberduck.Parsing.Binding.TypeBindingContext.Resolve(Declaration module, Declaration parent, ParserRuleContext expression, IBoundExpression withBlockVariable, StatementResolutionContext statementContext) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Binding\TypeBindingContext.cs:line 21
   at Rubberduck.Parsing.Binding.BindingService.ResolveType(Declaration module, Declaration parent, ParserRuleContext expression) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Binding\BindingService.cs:line 49
   at Rubberduck.Parsing.Symbols.IdentifierReferenceResolver.ResolveType(ParserRuleContext expression) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceResolver.cs:line 171
   at Rubberduck.Parsing.Symbols.IdentifierReferenceResolver.Resolve(AsTypeClauseContext context) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceResolver.cs:line 564
   at Rubberduck.Parsing.Symbols.IdentifierReferenceListener.EnterAsTypeClause(AsTypeClauseContext context) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceListener.cs:line 274
   at Rubberduck.Parsing.Grammar.VBAParser.AsTypeClauseContext.EnterRule(IParseTreeListener listener) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 14136
   at Antlr4.Runtime.Tree.ParseTreeWalker.EnterRule(IParseTreeListener listener, IRuleNode r)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Rubberduck.Parsing.VBA.RubberduckParser.ResolveReferences(DeclarationFinder finder, VBComponent component, IParseTree tree) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 584
2016-07-20 15:27:29.9763;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Sheet3' state is changing to 'Ready' (thread 29);
```

Additionally the Rename Refactoring seems to be out of sync:

```
2016-07-21 11:54:01.2458;FATAL;DynamicInjector470344871c584b65aa2e9eae022b7868;System.ArgumentOutOfRangeException: Index and count must refer to a location within the string.
Parameter name: count
   at System.String.Remove(Int32 startIndex, Int32 count)
   at Rubberduck.Refactorings.Rename.RenameRefactoring.GetReplacementLine(String content, String newName, Selection selection) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\Refactorings\Rename\RenameRefactoring.cs:line 433
   at Rubberduck.Refactorings.Rename.RenameRefactoring.RenameUsages(Declaration target, String interfaceName) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\Refactorings\Rename\RenameRefactoring.cs:line 393
   at Rubberduck.Refactorings.Rename.RenameRefactoring.Rename() in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\Refactorings\Rename\RenameRefactoring.cs:line 188
   at Rubberduck.Refactorings.Rename.RenameRefactoring.Refactor(Declaration target) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\Refactorings\Rename\RenameRefactoring.cs:line 60
   at Rubberduck.UI.Command.Refactorings.CodePaneRefactorRenameCommand.ExecuteImpl(Object parameter) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\UI\Command\Refactorings\CodePaneRefactorRenameCommand.cs:line 65
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 51;
```

Next up is a Grammar :boom: :

```
2016-07-21 14:44:58.4274;DEBUG;Rubberduck.Parsing.Symbols.SyntaxErrorException;Antlr4.Runtime.NoViableAltException: Exception of type 'Antlr4.Runtime.NoViableAltException' was thrown.
   at Antlr4.Runtime.Atn.ParserATNSimulator.HandleNoViableAlt(ITokenStream input, Int32 startIndex, SimulatorState previous)
   at Antlr4.Runtime.Atn.ParserATNSimulator.ExecATN(DFA dfa, ITokenStream input, Int32 startIndex, SimulatorState initialState)
   at Antlr4.Runtime.Atn.ParserATNSimulator.ExecDFA(DFA dfa, ITokenStream input, Int32 startIndex, SimulatorState state)
   at Antlr4.Runtime.Atn.ParserATNSimulator.AdaptivePredict(ITokenStream input, Int32 decision, ParserRuleContext outerContext, Boolean useContext)
   at Antlr4.Runtime.Atn.ParserATNSimulator.AdaptivePredict(ITokenStream input, Int32 decision, ParserRuleContext outerContext)
   at Rubberduck.Parsing.Grammar.VBAParser.expression(Int32 _p) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 15986;
2016-07-21 14:44:58.4434;DEBUG;Rubberduck.Parsing.Symbols.SyntaxErrorException;Token: Select (L1C1);
2016-07-21 14:44:58.4434;WARN;Rubberduck.Parsing.VBA.VBAExpressionParser;SLL mode failed for Select. Retrying using LL.;Rubberduck.Parsing.Symbols.SyntaxErrorException: no viable alternative at input 'Select' ---> Antlr4.Runtime.NoViableAltException: Exception of type 'Antlr4.Runtime.NoViableAltException' was thrown.
   at Antlr4.Runtime.Atn.ParserATNSimulator.HandleNoViableAlt(ITokenStream input, Int32 startIndex, SimulatorState previous)
   at Antlr4.Runtime.Atn.ParserATNSimulator.ExecATN(DFA dfa, ITokenStream input, Int32 startIndex, SimulatorState initialState)
   at Antlr4.Runtime.Atn.ParserATNSimulator.ExecDFA(DFA dfa, ITokenStream input, Int32 startIndex, SimulatorState state)
   at Antlr4.Runtime.Atn.ParserATNSimulator.AdaptivePredict(ITokenStream input, Int32 decision, ParserRuleContext outerContext, Boolean useContext)
   at Antlr4.Runtime.Atn.ParserATNSimulator.AdaptivePredict(ITokenStream input, Int32 decision, ParserRuleContext outerContext)
   at Rubberduck.Parsing.Grammar.VBAParser.expression(Int32 _p) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 15986
   --- End of inner exception stack trace ---
   at Rubberduck.Parsing.Symbols.ExceptionErrorListener.SyntaxError(IRecognizer recognizer, IToken offendingSymbol, Int32 line, Int32 charPositionInLine, String msg, RecognitionException e) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Symbols\ExceptionErrorListener.cs:line 10
   at Antlr4.Runtime.ProxyErrorListener`1.SyntaxError(IRecognizer recognizer, Symbol offendingSymbol, Int32 line, Int32 charPositionInLine, String msg, RecognitionException e)
   at Antlr4.Runtime.Parser.NotifyErrorListeners(IToken offendingToken, String msg, RecognitionException e)
   at Antlr4.Runtime.DefaultErrorStrategy.NotifyErrorListeners(Parser recognizer, String message, RecognitionException e)
   at Antlr4.Runtime.DefaultErrorStrategy.ReportNoViableAlternative(Parser recognizer, NoViableAltException e)
   at Antlr4.Runtime.DefaultErrorStrategy.ReportError(Parser recognizer, RecognitionException e)
   at Rubberduck.Parsing.Grammar.VBAParser.expression(Int32 _p) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 16470
   at Rubberduck.Parsing.VBA.VBAExpressionParser.Parse(String expression) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\VBA\VBAExpressionParser.cs:line 29
2016-07-21 14:44:58.4644;DEBUG;Rubberduck.Parsing.Symbols.SyntaxErrorException;Antlr4.Runtime.NoViableAltException: Exception of type 'Antlr4.Runtime.NoViableAltException' was thrown.
   at Antlr4.Runtime.Atn.ParserATNSimulator.HandleNoViableAlt(ITokenStream input, Int32 startIndex, SimulatorState previous)
   at Antlr4.Runtime.Atn.ParserATNSimulator.ExecDFA(DFA dfa, ITokenStream input, Int32 startIndex, SimulatorState state)
   at Antlr4.Runtime.Atn.ParserATNSimulator.AdaptivePredict(ITokenStream input, Int32 decision, ParserRuleContext outerContext, Boolean useContext)
   at Antlr4.Runtime.Atn.ParserATNSimulator.AdaptivePredict(ITokenStream input, Int32 decision, ParserRuleContext outerContext)
   at Rubberduck.Parsing.Grammar.VBAParser.expression(Int32 _p) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 15986;
2016-07-21 14:44:58.4644;DEBUG;Rubberduck.Parsing.Symbols.SyntaxErrorException;Token: Select (L1C1);
``´

This happens twice before a wall of COM-Exceptions (the following three repeated over and over):

```
2016-07-21 17:42:22.9211;FATAL;Rubberduck.UI.CodeExplorer.Commands.CodeExplorer_ExportCommand;System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Microsoft.Vbe.Interop._VBComponent.get_Type()
   at Rubberduck.UI.CodeExplorer.Commands.CodeExplorer_ExportCommand.CanExecuteImpl(Object parameter) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\UI\CodeExplorer\Commands\CodeExplorer_ExportCommand.cs:line 36
   at Rubberduck.UI.Command.CommandBase.CanExecute(Object parameter) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 32;
2016-07-21 17:42:22.9311;FATAL;Rubberduck.UI.CodeExplorer.Commands.CodeExplorer_RemoveCommand;System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Microsoft.Vbe.Interop._VBComponent.get_Type()
   at Rubberduck.UI.CodeExplorer.Commands.CodeExplorer_RemoveCommand.CanExecuteImpl(Object parameter) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\UI\CodeExplorer\Commands\CodeExplorer_RemoveCommand.cs:line 40
   at Rubberduck.UI.Command.CommandBase.CanExecute(Object parameter) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 32;
2016-07-21 17:42:22.9541;FATAL;DynamicInjector540ae2874e47488f927942274f68a8bd;System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Microsoft.Vbe.Interop._VBComponent.get_CodeModule()
   at Rubberduck.UI.CodeExplorer.Commands.CodeExplorer_PrintCommand.CanExecuteImpl(Object parameter) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\UI\CodeExplorer\Commands\CodeExplorer_PrintCommand.cs:line 25
   at Rubberduck.UI.Command.CommandBase.CanExecute(Object parameter) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 32;
```

The log is huge... @TZubiri could I ask you to clear your log and try to reproduce the error while keeping the log as small as possible?

Additionally I have a question: Do you use preprocessor directives in the module where you renamed something from the Code Explorer?

**Comment by TZubiri** [comment]
From now on I'll clear the log.
By preprocessor directives you mean comments marked like this?
'@
I don't use them but the autogenerated tests do.

**Comment by Hosch250** [comment]
Nope, those are "annotations".  Preprocessor directives are things like `#If`, `#EndIf`.

**Comment by TZubiri** [comment]
I do not use preprocessor directives.

**Comment by retailcoder** [comment]
Deemed fixed.
