### ISSUE TITLE
Excel hard crash

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2147]
Excel has hard crashed at least 5 times this afternoon, and RD has had several times where it's hung on `Resolving Declarations...`.

Here are the event logs for the 6 most recent events pointing at Excel.

[Crash log 1.evtx.txt](https://github.com/rubberduck-vba/Rubberduck/files/384707/Crash.log.1.evtx.txt)
[Crash log 2.evtx.txt](https://github.com/rubberduck-vba/Rubberduck/files/384703/Crash.log.2.evtx.txt)
[Crash log 3.evtx.txt](https://github.com/rubberduck-vba/Rubberduck/files/384705/Crash.log.3.evtx.txt)
[Crash log 4.evtx.txt](https://github.com/rubberduck-vba/Rubberduck/files/384708/Crash.log.4.evtx.txt)
[Crash log 5.evtx.txt](https://github.com/rubberduck-vba/Rubberduck/files/384706/Crash.log.5.evtx.txt)
[Crash log 6.evtx.txt](https://github.com/rubberduck-vba/Rubberduck/files/384704/Crash.log.6.evtx.txt)

Obviously, remove the `.txt` from the file name to get back to the "event log" format. (thanks, Git!)

**Comment by comintern** [comment]
Sample stack trace from above:

```
Exception Info: System.AccessViolationException
   at Rubberduck.Common.DeclarationExtensions+<>c.<FindBuiltInEventHandlers>b__20_0(Rubberduck.Parsing.Symbols.Declaration)
   at System.Linq.Enumerable+WhereListIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Linq.Enumerable+<SelectManyIterator>d__16`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Linq.Enumerable.Contains[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.__Canon, System.Collections.Generic.IEqualityComparer`1<System.__Canon>)
   at System.Linq.Enumerable+WhereListIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at System.Linq.Enumerable.ToList[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at Rubberduck.Common.DeclarationExtensions.FindBuiltInEventHandlers(System.Collections.Generic.IEnumerable`1<Rubberduck.Parsing.Symbols.Declaration>)
   at Rubberduck.Inspections.ProcedureCanBeWrittenAsFunctionInspection.<GetInspectionResults>b__12_5(SubStmtContext)
   at System.Linq.Enumerable+WhereListIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Linq.Enumerable.Contains[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.__Canon, System.Collections.Generic.IEqualityComparer`1<System.__Canon>)
   at System.Linq.Enumerable+WhereSelectEnumerableIterator`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Linq.Enumerable.Count[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at Rubberduck.Root.EnumerableCounterInterceptor`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].AfterInvoke(Ninject.Extensions.Interception.IInvocation)
   at Rubberduck.Root.InterceptorBase.Intercept(Ninject.Extensions.Interception.IInvocation)
   at Ninject.Extensions.Interception.Wrapper.DynamicProxyWrapper.Intercept(Castle.DynamicProxy.IInvocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IParseTreeInspectionProxy.GetInspectionResults()
   at Rubberduck.Inspections.Rubberduck.Inspections.Inspector+<>c__DisplayClass5_1.<FindIssuesAsync>b__3()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by ThunderFrame** [comment]
I've just rebuilt my PC. installed Office 2013 32-bit, then VS 2013, then pulled from next and built (including registry and regasm).

When opening Excel's VBE, I get a hard crash every time. When I look in the Rubberduck directory I see there are logs, but **there isn't a config file**.

I can open Word's VBE with only a soft-crash (the VBE is still usable even though Windows said it crashed), and I can open the settings Window, which I reset, navigate around without changing anything and press OK, and **I now have a config file.**, but I get the dictionary error on closing the instance of Word.

Now when I open Excel's VBE it doesn't crash. and exits without any errors. Word is behaving too.

So, it seems the absence of a config file, or perhaps the default settings in the absence of a config file are causing a hard crash and the dictionary error on quitting a host that didn't hard-crash?

**Comment by ThunderFrame** [comment]
Application: EXCEL.EXE
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Rubberduck.Inspections.UseMeaningfulNameInspection.GetInspectionResults()
   at DynamicClass.(System.Object, System.Object[])
   at Ninject.Extensions.Interception.Injection.Dynamic.DynamicMethodInjector.Invoke(System.Object, System.Object[])
   at Ninject.Extensions.Interception.Invocation.Invocation.CallTargetMethod()
   at Ninject.Extensions.Interception.Invocation.InvocationBase.Proceed()
   at Rubberduck.Root.InterceptorBase.Intercept(Ninject.Extensions.Interception.IInvocation)

Exception Info: Rubberduck.Root.InterceptedException
   at Rubberduck.Root.InterceptorBase.OnError(Ninject.Extensions.Interception.IInvocation, System.Exception)
   at Rubberduck.Root.InterceptorBase.Intercept(Ninject.Extensions.Interception.IInvocation)
   at Ninject.Extensions.Interception.Invocation.InvocationBase.Proceed()
   at Rubberduck.Root.InterceptorBase.Intercept(Ninject.Extensions.Interception.IInvocation)

Exception Info: Rubberduck.Root.InterceptedException
   at Rubberduck.Root.InterceptorBase.OnError(Ninject.Extensions.Interception.IInvocation, System.Exception)
   at Rubberduck.Root.InterceptorBase.Intercept(Ninject.Extensions.Interception.IInvocation)
   at Ninject.Extensions.Interception.Invocation.InvocationBase.Proceed()
   at Ninject.Extensions.Interception.Wrapper.DynamicProxyWrapper.Intercept(Castle.DynamicProxy.IInvocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IInspectionProxy.GetInspectionResults()
   at Rubberduck.Inspections.Rubberduck.Inspections.Inspector+<>c__DisplayClass6+<>c__DisplayClass8.<FindIssuesAsync>b__3()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Rubberduck.Inspections.Rubberduck.Inspections.Inspector+<FindIssuesAsync>d__a.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetResult()
   at Rubberduck.UI.Inspections.InspectionResultsViewModel+<RefreshInspections>d__38.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by ThunderFrame** [comment]
FWIW, I wonder if the different behavior in Word is because there is always a template plus the host document, so there are 2 projects for RD to parse. Or maybe Word is just more resilient?

**Comment by daFreeMan** [comment]
My machine was freshly imaged yesterday (Win7 x64), and I'm still getting the crash. 

Here are the details from the 2 events that were recorded
~~~
Application: EXCEL.EXE
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: Rubberduck.Root.InterceptedException
Stack:
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__5(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
~~~
~~~
Faulting application name: EXCEL.EXE, version: 14.0.7170.5000, time stamp: 0x573ba033
Faulting module name: KERNELBASE.dll, version: 6.1.7601.23418, time stamp: 0x5708a7e4
Exception code: 0xe0434352
Fault offset: 0x0000c54f
Faulting process id: 0xf10
Faulting application start time: 0x01d1e8de37287d35
Faulting application path: C:\Program Files (x86)\Office 2010\Office14\EXCEL.EXE
Faulting module path: C:\windows\syswow64\KERNELBASE.dll
Report Id: 33640bfd-54d2-11e6-bd43-782bcbb0d7e4
~~~

I don't think they're any different than before, but I figured I'd post an update

**Comment by Hosch250** [comment]
I don't suppose you could share the workbook at this point.

**Comment by daFreeMan** [comment]
Sadly, I'm no further along than I was on Tuesday evening - I spent _all day_ yesterday waiting on the machine to be repaired...

**Comment by Vogel612** [comment]
@daFreeMan What's the status on this?
