### ISSUE TITLE
Microsoft .NET Framwork Error

### ISSUE THREAD

**Issue by nchelladurai** [rubberduck-vba/Rubberduck#2197]
Hi Team,

With Excel 2010 and Rubberduck.Setup.1.4.3.0, I am getting the following error when trying to create a Test.

**Here are the steps i followed:**
Open Excel 2010 -> Alt+F11 -> Open Rubberduck -> Add Test Method.

**Error Details:**

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.UnitTesting.NewTestMethodCommand.NewTestMethod(VBE vbe) in c:\Users\Mathieu\Source\Repos\Rubberduck\RetailCoder.VBE\UnitTesting\NewTestMethodCommand.cs:line 52
   at Rubberduck.UI.UnitTesting.TestExplorerDockablePresenter.OnExplorerAddTestMethodButtonClick(Object sender, EventArgs e) in c:\Users\Mathieu\Source\Repos\Rubberduck\RetailCoder.VBE\UI\UnitTesting\TestExplorerDockablePresenter.cs:line 221
   at Rubberduck.UI.UnitTesting.TestExplorerWindow.OnButtonClick(EventHandler clickEvent) in c:\Users\Mathieu\Source\Repos\Rubberduck\RetailCoder.VBE\UI\UnitTesting\TestExplorerWindow.cs:line 117
   at Rubberduck.UI.UnitTesting.TestExplorerWindow.AddTestMethodButtonClicked(Object sender, EventArgs e) in c:\Users\Mathieu\Source\Repos\Rubberduck\RetailCoder.VBE\UI\UnitTesting\TestExplorerWindow.cs:line 178
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

**Comment by retailcoder** [comment]
Hmm.. is there a test module in the project?

IIRC v2.x disables "add test method"  when there is no test module in the active project.
