### ISSUE TITLE
RD 2.0.8 crash log file

### ISSUE THREAD

**Issue by eteichm** [rubberduck-vba/Rubberduck#2204]
RD 2.0.8 requested the attached log file while I wasn't using RD. 
[RubberduckLogExtract.txt](https://github.com/rubberduck-vba/Rubberduck/files/451640/RubberduckLogExtract.txt)

**Comment by retailcoder** [comment]
Thanks for the logs, though I'm not sure what this is referring to - was this meant to go on another issue#?

I can see these two exceptions after `StateChanged(Ready)` occurs here:

    2016-09-02 11:12:11.2415;DEBUG;Rubberduck.App;App handles StateChanged (Ready), evaluating menu states...;

    2016-09-02 11:12:11.2955;ERROR;DynamicInjectorec925bae357445f6b41137355c526cc5;System.NullReferenceException: Object reference not set to an instance of an object.
	   at Rubberduck.UI.Command.AddTestMethodCommand.<CanExecuteImpl>b__6_2(Declaration a) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\UI\Command\AddTestMethodCommand.cs:line 58
	   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
	   at Rubberduck.UI.Command.AddTestMethodCommand.CanExecuteImpl(Object parameter) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\UI\Command\AddTestMethodCommand.cs:line 57
	   at Rubberduck.UI.Command.CommandBase.CanExecute(Object parameter) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 36;

    2016-09-02 11:12:11.3485;ERROR;DynamicInjectord003a2d892314a2497e911cf3ff3a36a;System.NullReferenceException: Object reference not set to an instance of an object.
	   at Rubberduck.UI.Command.AddTestMethodExpectedErrorCommand.<CanExecuteImpl>b__6_2(Declaration a) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\UI\Command\AddTestMethodExpectedErrorCommand.cs:line 63
	   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
	   at Rubberduck.UI.Command.AddTestMethodExpectedErrorCommand.CanExecuteImpl(Object parameter) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\UI\Command\AddTestMethodExpectedErrorCommand.cs:line 62
	   at Rubberduck.UI.Command.CommandBase.CanExecute(Object parameter) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 36;

The commands' `CanExecute` implementations are throwing a `NullReferenceException` - this needs to be fixed.

**Comment by eteichm** [comment]
No, it wasn't meant to go on another issue#. 
As said, I wasn't using RD when it occured. So, I can't be more specific.

**Comment by retailcoder** [comment]
Hmm.. what does "RD 2.0.8 *requested* the attached log file" mean then? I don't understand, was there an error message? How does RD request anything if it's not running?

**Comment by eteichm** [comment]
Yes, there was an error message asking to save my work and submit the log file. 
RD was running but I wasn't coding in VBE when RD issued the error message.

**Comment by retailcoder** [comment]
The log indicates parser state changing to `Ready` after processing some "Names" module; inspections started running, and then RD started handling the `Ready` state and evaluating menu states - the bug is in `AddTestMethodCommand.CanExecuteImpl`, specifically:

            try
            {
                // the code modules consistently match correctly, but the components don't
                return testModules.Any(a =>
                            a.QualifiedName.QualifiedModuleName.Component.CodeModule ==
                            _vbe.SelectedVBComponent.CodeModule);
            }
            catch (COMException)
            {
                return false;
            }

My first guess is that `_vbe.SelectedVBComponent` was `null`. This code assumes there's a selected VBComponent when it accesses its `CodeModule` - and then catches a `COMException` but lets a `NullReferenceException` bubble up the call stack unhandled, and that's how it crashed.

Should be an easy fix.

**Comment by retailcoder** [comment]
SafeComWrappers in 2.0.9 definitely fixed this:

````csharp
public IVBComponent SelectedVBComponent
{
    get { return new VBComponent(IsWrappingNullReference ? null : Target.SelectedVBComponent); }
}
````
