### ISSUE TITLE
Reloading a modified source file => Unhandled exception

### ISSUE THREAD

**Issue by eteichm** [rubberduck-vba/Rubberduck#2229]
When I export all the vba code outside of Rubberduck (with my own code) in the directory serving as git repo instead of with RD's source control menu, RD detects a change in the source code and sends a warning saying: "A source file was modified out of the editor; should Rubberduck reload it?"  This is good!
(I exported it with my own code because I erroneously thought RD's source control was not fully functional.)  
Could the warning tell which source file has changed? I'll open another issue for this change request. #2230 

When I cancel, there is no bug. 
When I click OK, I get the below error message !

Unhandled exception has occurred in a component in your application. If you click Continue, the application will ignore this error and attempt to continue.

Exception from HRESULT: 0x800A01A8.
&Details
&Continue
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.Runtime.InteropServices.COMException (0x800A01A8): Exception from HRESULT: 0x800A01A8
   at Microsoft.Vbe.Interop.VBProjectClass.get_VBComponents()
   at Rubberduck.VBEditor.Extensions.ProjectExtensions.ExportSourceFiles(VBProject project, String directoryPath) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.VBEEditor\Extensions\VbProjectExtensions.cs:line 60
   at Rubberduck.SourceControl.SourceControlProviderBase.Status() in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.SourceControl\SourceControlProviderBase.cs:line 142
   at Rubberduck.SourceControl.GitProvider.Status() in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.SourceControl\GitProvider.cs:line 498
   at Rubberduck.UI.SourceControl.ChangesViewViewModel.RefreshView() in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\UI\SourceControl\ChangesViewViewModel.cs:line 55
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.Refresh() in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 902
   at Rubberduck.UI.Command.MenuItems.UiDispatcher.<>c__DisplayClass5_0.<InvokeAsync>b__0(Object x) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\UI\Command\MenuItems\UiDispatcher.cs:line 29

**Comment by retailcoder** [comment]
Was the VBE executing cose at that time?

**Comment by eteichm** [comment]
No, the VBE was not executing code at that time.

**Comment by rubberduck203** [comment]
Please see #3758.
