### ISSUE TITLE
Init Repo doesn't carry User Form Object Blob

### ISSUE THREAD

**Issue by mrbub** [rubberduck-vba/Rubberduck#2315]
Initializing a new repo on a work book containing User Forms is struggling to export the .frx portion to the git destination folder. The .frm transfers perfectly fine, but in my case I find the .frx file being exported to C:/TEMP. This is the TRACE I receive when trying to initialize a new repo:

I tried moving the .frx back into the git folder, and then tracked those new files. I then committed and fetched, but the objectBlobs don't import. I'm just left with blank user forms. I tried modifying the User Forms by including a label, and then committing the changes, which produces the error below.

```
2016-10-14 16:27:57.0024;TRACE;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Initializing repo;
2016-10-14 16:27:57.3025;TRACE;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Provider changed;
2016-10-14 16:27:57.3195;TRACE;Rubberduck.UI.SourceControl.ChangesViewViewModel;Refreshing view;
2016-10-14 16:27:57.4365;TRACE;Rubberduck.UI.SourceControl.BranchesViewViewModel;Provider changed;
2016-10-14 16:27:57.4365;TRACE;Rubberduck.UI.SourceControl.BranchesViewViewModel;Refreshing view;
2016-10-14 16:27:57.6465;TRACE;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Displaying Error with title 'Unknown exception.' and message 'Could not find the specified object.'
Could not find the specified object.
Could not find the specified object.
Could not find the specified object.':
2016-10-14 16:27:57.6465;TRACE;Rubberduck.UI.SourceControl.UnsyncedCommitsViewViewModel;Provider changed;
2016-10-14 16:27:57.6545;TRACE;Rubberduck.UI.SourceControl.UnsyncedCommitsViewViewModel;Refreshing view;

2016-10-14 16:32:15.0237;TRACE;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Refreshing display;
2016-10-14 16:32:15.0237;TRACE;Rubberduck.UI.SourceControl.ChangesViewViewModel;Refreshing view;
2016-10-14 16:32:15.1497;ERROR;Rubberduck.UI.SourceControl.SourceControlViewViewModel;System.Runtime.InteropServices.COMException (0x800AC372): Member not found.

   at Microsoft.Vbe.Interop._VBComponent.Export(String FileName)
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBComponent.ExportAsSourceFile(String folder) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBComponent.cs:line 120
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBProject.ExportSourceFiles(String folder) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBProject.cs:line 167
   at Rubberduck.SourceControl.SourceControlProviderBase.Status() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.SourceControl\SourceControlProviderBase.cs:line 140
   at Rubberduck.SourceControl.GitProvider.Status() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.SourceControl\GitProvider.cs:line 499
   at Rubberduck.UI.SourceControl.ChangesViewViewModel.RefreshView() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\ChangesViewViewModel.cs:line 57
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.Refresh() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 897
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.<.ctor>b__8(Object _) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 72
   at Rubberduck.UI.Command.DelegateCommand.ExecuteImpl(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\DelegateCommand.cs:line 26
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 60.
```

Appreciate any help on this matter.

**Comment by retailcoder** [comment]
See possibly related discussion in #453:

> In a perfect world, maybe, but since the *.frx file changes each time it's imported into a project it's important that this be on by default. Otherwise, after you commit, it shows right back up in the "pending changes". This causes the user to be unable to switch between branches. I would also note that when you use Visual a Studio to init a new Git repo, it also creates a default .gitignore file. [ckuhn203 on October 11 2015](https://github.com/rubberduck-vba/Rubberduck/issues/453#issuecomment-147177213)

Seems the .frx files have been a problem from the start.

I have a repro with [VBTools/ProgressView.frm](https://github.com/retailcoder/VBTools); if I import the form into a new project by loading it from disk, the VBE loads the .frx and my form retains its controls. If I load the project into the VBE from the git repository, I lose the controls and get a *could not find the specified object* COM exception from HRESULT: 0x800A004B (CTL_E_PATHFILEACCESSERROR).

**Comment by ThunderFrame** [comment]
As per #1230, I don't think the order that controls are persisted is deterministic.

> So, the order of the VB_Control attributes seems to be unreliable/unpredictable, but the order does not seem to matter to VBE

That means the FRX file can change from one export to the next.

**Comment by rubberduck203** [comment]
Is this an issue with the import functionality as well?
Otherwise we should close this as part of #3758.
