### ISSUE TITLE
"RubberDuck has encountered an issue" v2.0.9

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2324]
Here's the log.
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/547789/RubberduckLog.txt)

I had the workbook open, got distracted. Came back to it & hit F11 to open the VBE. I had not yet hit the parse button.

Closed the file, closed Excel, reopened & everything appears to be OK.

**Comment by Vogel612** [comment]
The only thing in the log that seems like it could be responsible is the following stacktrace:

```

2016-07-28 13:39:52.3045;FATAL;Rubberduck._Extension;System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Microsoft.Office.Core.CommandBarControls.Add(Object Type, Object Id, Object Parameter, Object Before, Object Temporary)
   at Rubberduck.UI.Command.MenuItems.ParentMenus.ParentMenuItemBase.Initialize() in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\UI\Command\MenuItems\ParentMenus\ParentMenuItemBase.cs:line 71
   at Rubberduck.AppMenu.Initialize() in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\AppMenu.cs:line 23
   at Rubberduck.App.Startup() in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\App.cs:line 140
   at Rubberduck._Extension.OnConnection(Object Application, ext_ConnectMode ConnectMode, Object AddInInst, Array& custom) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\Extension.cs:line 73;
```

this shows up multiple times in the log, so apparently it's not blowing up the host on the first try. it does show up last though, so there's that ...

**Comment by retailcoder** [comment]
Not sure how the 2.0.10 wrappers would change anything about this one, but I don't see how it could be reproduced. Closing for now.
