### ISSUE TITLE
Resolver fails if a form contains an image control

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#2328]
We should be doing a soft-cast instead of just assuming all controls are, well, `Control` objects:

> cast object of type 'Microsoft.Vbe.Interop.Forms.ImageClass' to type 'Microsoft.Vbe.Interop.Forms.Control'.
   at Rubberduck.VBEditor.SafeComWrappers.VBA.Controls.<System.Collections.Generic.IEnumerable<Rubberduck.VBEditor.SafeComWrappers.Office.Core.Abstract.IControl>.GetEnumerator>b__0(Object o) in c:\Dev\Rubberduck\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\Controls.cs:line 28
   at Rubberduck.VBEditor.SafeComWrappers.ComWrapperEnumerator\`1.get_Current() in c:\Dev\Rubberduck\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\ComWrapperEnumerator.cs:line 38
   at Rubberduck.Parsing.Symbols.DeclarationSymbolsListener.DeclareControlsAsMembers(IVBComponent form) in c:\Dev\Rubberduck\Rubberduck\Rubberduck.Parsing\Symbols\DeclarationSymbolsListener.cs:line 168
   at Rubberduck.Parsing.Symbols.DeclarationSymbolsListener..ctor(RubberduckParserState state, QualifiedModuleName qualifiedName, ComponentType type, IEnumerable\`1 annotations, IDictionary`2 attributes, Declaration projectDeclaration) in c:\Dev\Rubberduck\Rubberduck\Rubberduck.Parsing\Symbols\DeclarationSymbolsListener.cs:line 119
   at Rubberduck.Parsing.VBA.RubberduckParser.ResolveDeclarations(IVBComponent component, IParseTree tree) in c:\Dev\Rubberduck\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 564

**Comment by retailcoder** [comment]
Referencing commit fixes the resolver error, but wraps `ImageClass` controls with a null reference; seems `ImageClass` doesn't implement the `IControl` interface, it's not clear how to get the name of an image control. So yeah, commit fixes the issue, but then we have a problem with renaming image controls being referenced in code.
