### ISSUE TITLE
crash on start in excel 2016

### ISSUE THREAD

**Issue by Talorthain** [rubberduck-vba/Rubberduck#2385]
runtime error when starting
Rubberduck 2.0.9 (Latest RC)
excel 2016 desktop
Installed both normally and as administrator
Click ok on error message, takes me in to VBE, but no menu bar for rubberduck. Rubberduck is listed in addin window.
![capture](https://cloud.githubusercontent.com/assets/6796503/20705290/4b91a650-b61a-11e6-9012-588f83cd95e1.PNG)
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/618632/RubberduckLog.txt)

**Comment by retailcoder** [comment]
That log is rather troubling. First, this:

````
2016-11-29 09:54:08.8994;ERROR;Rubberduck._Extension;System.Runtime.InteropServices.COMException (0x800AC471): Can't perform operation since the project is protected.
   at Microsoft.Vbe.Interop.VBProjectClass.get_VBComponents()
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBProject.get_VBComponents() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBProject.cs:line 64
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBProject.Release() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBProject.cs:line 109
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBProjects.Release() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBProjects.cs:line 67
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBE.Release() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBE.cs:line 76
   at Rubberduck._Extension.ShutdownAddIn() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\Extension.cs:line 195;
````

Seems the shutdown code is iterating `VBComponents` in protected projects when iterating all COM wrappers to call `.Release()` on them, which is throwing an exception. This is clearly a bug, and will definitely be fixed, shortly.

---

The other error (the one bringing up the "Rubberduck Add-In could not be loaded" error dialog on initialization) is more of a worrying question mark:

````
2016-11-29 09:52:54.8519;FATAL;Rubberduck._Extension;System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Vbe.Interop.Forms, Version=11.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Vbe.Interop.Forms, Version=11.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c'
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Ninject.Extensions.Conventions.BindingBuilder.TypeSelector.<GetExportedTypes>b__0(Assembly asm)
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<UnionIterator>d__66`1.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Ninject.Extensions.Conventions.BindingBuilder.ConventionBindingBuilder.CreateTypeList()
   at Ninject.Extensions.Conventions.BindingBuilder.ConventionBindingBuilder.BindWith(IBindingGenerator generator)
   at Ninject.Extensions.Conventions.BindingBuilder.ConventionSyntax.BindDefaultInterface()
   at Rubberduck.Root.RubberduckModule.<>c__DisplayClass7.<ApplyDefaultInterfacesConvention>b__4(IFromSyntax t) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\Root\RubberduckModule.cs:line 155
   at Ninject.Extensions.Conventions.ExtensionsForIKernel.Bind(IBindingRoot kernel, Action`1 configure)
   at Rubberduck.Root.RubberduckModule.ApplyDefaultInterfacesConvention(IEnumerable`1 assemblies) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\Root\RubberduckModule.cs:line 155
   at Rubberduck.Root.RubberduckModule.Load() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\Root\RubberduckModule.cs:line 79
   at Ninject.Modules.NinjectModule.OnLoad(IKernel kernel)
   at Ninject.KernelBase.Load(IEnumerable`1 m)
   at Rubberduck._Extension.InitializeAddIn() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\Extension.cs:line 166
````

This suggests that `Microsoft.Vbe.Interop.Forms.dll` couldn't be *found*... which is rather puzzling given the install seems to be working for *some* users.

I've reviewed the project references, and **Copy Local** was set to `False` for that assembly (`Microsoft.Vbe.Interop.dll` has it set to `True`) - I've set it to `True`, PR incoming.

!["Copy Local" was set to FALSE](https://cloud.githubusercontent.com/assets/5751684/20716877/b31b6ed0-b621-11e6-81fd-59126bc84741.png)

I can't reproduce the issue though, but I'm pretty confident that these changes will fix the problem.

**Comment by andyrichardson** [comment]
I can confirm I'm experiencing this issue also. I don't have the time to install all the build dependencies so really looking forward to this next release.
