### ISSUE TITLE
Error Initializing Git Repository

### ISSUE THREAD

**Issue by jstans** [rubberduck-vba/Rubberduck#2386]
Version: 2.0 RC6

I'm getting an error initialising a repository on a large Access project with it telling me to upload a log file from a directory which is empty, so I guess I have two issues :)

Keen to do what I can to track down the problem.

**Comment by retailcoder** [comment]
Hi @jstans and thanks for reporting the issue. Logging is disabled by default in that build, you need to enable it manually in the settings dialog.

We'll need to know what steps were performed to reproduce the issue; have you seen the [Source Control: Getting Started](https://github.com/rubberduck-vba/Rubberduck/wiki/Source-Control:-Getting-Started) wiki?

**Comment by jstans** [comment]
Hi @retailcoder,

I've had a look over the wiki but I'm only currently loading a pre-existing access project and selecting Initialise git repostiory and selecting a folder, after a few seconds the window changes to the forms open in design mode and the error shown.

I've enabled logging and the below exception is being thrown:

```2016-11-30 10:49:31.7911;TRACE;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Initializing repo;
2016-11-30 10:49:35.0975;TRACE;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Provider changed;
2016-11-30 10:49:35.1171;TRACE;Rubberduck.UI.SourceControl.ChangesViewViewModel;Refreshing view;
2016-11-30 10:49:42.5083;TRACE;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Displaying Error with title 'An unknown error occurred.' and message 'Please set your log level to Fatal or lower and create an issue on our GitHub page with the contents of your log file in C:\Users\{username}\AppData\Roaming\Rubberduck\Logs.';
2016-11-30 10:49:42.5180;ERROR;Rubberduck.UI.SourceControl.SourceControlViewViewModel;System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Microsoft.Vbe.Interop.CodeModuleClass.DeleteLines(Int32 StartLine, Int32 Count)
   at Rubberduck.VBEditor.SafeComWrappers.VBA.CodeModule.Clear() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\CodeModule.cs:line 91
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBComponents.ImportSourceFile(String path) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBComponents.cs:line 116
   at Rubberduck.VBEditor.Extensions.VBProjectExtensions.ImportDocumentTypeSourceFiles(IVBProject project, String filePath) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.VBEEditor\Extensions\IDEExtensions.cs:line 198
   at Rubberduck.SourceControl.SourceControlProviderBase.Status() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.SourceControl\SourceControlProviderBase.cs:line 141
   at Rubberduck.SourceControl.GitProvider.Status() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.SourceControl\GitProvider.cs:line 499
   at Rubberduck.UI.SourceControl.ChangesViewViewModel.RefreshView() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\ChangesViewViewModel.cs:line 55
   at Rubberduck.UI.SourceControl.ChangesViewViewModel.set_Provider(ISourceControlProvider value) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\ChangesViewViewModel.cs:line 47
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.SetChildPresenterSourceControlProviders(ISourceControlProvider provider) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 665
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.set_Provider(ISourceControlProvider value) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 227
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.InitRepo() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 641
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.<.ctor>b__0(Object _) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 68
   at Rubberduck.UI.Command.DelegateCommand.ExecuteImpl(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\DelegateCommand.cs:line 26
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 60;```

Most (if not all) of the files appear in the directory and it appears to be a correctly configured git repository, so it is at least doing most of the work.

**Comment by retailcoder** [comment]
Looking at the stack trace it seems to be throwing an `SEHException` in `CodeModule.Clear`. This needs some serious investigation, I've never seen that one before. CC: @comintern, @Hosch250

**Comment by retailcoder** [comment]
@jstans I suspect the `CodeModule.Clear()` implementation might be the cause:

```csharp
public void Clear()
{
    Target.DeleteLines(1, CountOfLines);
}
```

Would you happen to have any empty modules? I'm about to push a commit that changes it to this:

```csharp
public void Clear()
{
    if (Target.CountOfLines > 0)
    {
        Target.DeleteLines(1, CountOfLines);
    }
}
```

If the exception was thrown by trying to call `DeleteLines(1, 0)` then that would fix it.

**Comment by jstans** [comment]
@retailcoder Just had a look, no empty modules. 2 forms with empty code which I put a comment line in and ran again, same error.

**Comment by retailcoder** [comment]
ok, so I moved up the call stack to [VBComponents line 116](https://github.com/rubberduck-vba/Rubberduck/blob/b0e206ff555dcd510888e487dafb53994bf0cd35/Rubberduck.VBEEditor/SafeComWrappers/VBA/VBComponents.cs#L116), and found another possible problem.

```csharp
if (ext == ComponentTypeExtensions.DocClassExtension)
{
    var component = this[name];
    component.CodeModule.Clear();
    component.CodeModule.AddFromString(codeString);
}
```

It's possible `this[name]` returns a non-null `VBComponent` wrapper that actually wraps a null reference:

```csharp
public IVBComponent this[object index]
{
    get { return new VBComponent(IsWrappingNullReference ? null : Target.Item(index)); }
}
```

The `component.CodeModule` call will not return a null reference either:

```csharp
public ICodeModule CodeModule
{
    get { return new CodeModule(IsWrappingNullReference ? null : Target.CodeModule); }
}
```

Thing is, if `component` is wrapping a null reference, I would expect `component.CodeModule.Clear()` to throw a `NullReferenceException`; the fact that we're seeing a native exception indicates that the `component` was correctly fetched.

I've made a few adjustments to the code to account for wrapped null references, but I still don't know how it gets to that.

I also made the `GitProvider` throw a `SourceControlException` to wrap this `SEHException` and report the SEH error code so we can get a better idea of exactly what's going on.

@jstans do you have any `.doccls` files in your repository folder that have no corresponding document module in your VBA project?

**Comment by jstans** [comment]
@retailcoder I'm trying to build from source so I can test the latest changes, is there a building guide?.

I've just counted the amount of documents and they match up, 222.

**Comment by mansellan** [comment]
@jstans the latest pre-release build has fixed a number of outstanding issues with source control, and it sounds like the last issue you were seeing may have been related. Can you please download the latest build and advise whether the issue persists?

**Comment by Vogel612** [comment]
Since the source control integration has been removed (see #3758), this issue is now obsolete
