### ISSUE TITLE
Refresh Resolving Declarations  stalls

### ISSUE THREAD

**Issue by halcwb** [rubberduck-vba/Rubberduck#2459]
Hitting refresh stalls with 'Resolving Declarations'. See log file: 
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/671738/RubberduckLog.txt)

However, the logfile is set to Error, and isn't modified at the time of the problem.

**Comment by Vogel612** [comment]
Problem seems to be in parsing. Expected behaviour: Parser Error with an error marker upon clicking the status bar.

Stacktrace from the attached log:
```
2016-12-22 17:14:06.8770;ERROR;Rubberduck.Parsing.VBA.ComponentParseTask;Exception thrown in thread 111.;Rubberduck.Parsing.Symbols.SyntaxErrorException: extraneous input ' ' expecting {ABS, ANY, ARRAY, B_CHAR, CBOOL, CBYTE, CCUR, CDATE, CDBL, CDEC, CINT, CIRCLE, CLNG, CLNGLNG, CLNGPTR, CSNG, CSTR, CURRENCY, CVAR, CVERR, DEBUG, DOEVENTS, EXIT, FIX, INPUTB, INT, LBOUND, LEN, LENB, LONGLONG, LONGPTR, MIDB, MIDBTYPESUFFIX, MIDTYPESUFFIX, OPTION, PSET, SCALE, SGN, UBOUND, '!', '.', '#', ACCESS, ADDRESSOF, ALIAS, AND, ATTRIBUTE, APPEND, AS, BEGIN, BINARY, BOOLEAN, BYVAL, BYREF, BYTE, CALL, CASE, CLASS, CLOSE, CONST, DATABASE, DATE, DECLARE, DEFBOOL, DEFBYTE, DEFDATE, DEFDBL, DEFCUR, DEFINT, DEFLNG, DEFLNGLNG, DEFLNGPTR, DEFOBJ, DEFSNG, DEFSTR, DEFVAR, DIM, DO, DOUBLE, ELSE, ELSEIF, EMPTY, END_IF, END_SELECT, END_WITH, END, ENUM, EQV, ERASE, ERROR, EVENT, EXIT_DO, EXIT_FOR, EXIT_FUNCTION, EXIT_PROPERTY, EXIT_SUB, FALSE, FRIEND, FOR, FUNCTION, GET, GLOBAL, GOSUB, GOTO, IF, IMP, IMPLEMENTS, IN, INPUT, IS, INTEGER, LOCK, LONG, LOOP, LET, LIB, LIKE, LINE_INPUT, LOCK_READ, LOCK_WRITE, LOCK_READ_WRITE, LSET, ME, MID, MOD, NAME, NEXT, NEW, NOT, NOTHING, NULL, OBJECT, ON, ON_ERROR, ON_LOCAL_ERROR, OPEN, OPTIONAL, OR, OUTPUT, PARAMARRAY, PRESERVE, PRINT, PRIVATE, PTRSAFE, PUBLIC, PUT, RANDOM, RAISEEVENT, READ, READ_WRITE, REDIM, REM, RESET, RESUME, RETURN, RSET, SEEK, SELECT, SET, SHARED, SINGLE, SPC, STATIC, STEP, STOP, STRING, SUB, TAB, TEXT, THEN, TO, TRUE, TYPE, TYPEOF, UNLOCK, UNTIL, VARIANT, VERSION, WEND, WHILE, WIDTH, WITH, WITHEVENTS, WRITE, XOR, '(', '-', '[', STRINGLITERAL, OCTLITERAL, HEXLITERAL, FLOATLITERAL, INTEGERLITERAL, DATELITERAL, IDENTIFIER, LOAD, RESUME_NEXT}
   at Rubberduck.Parsing.Symbols.ExceptionErrorListener.SyntaxError(IRecognizer recognizer, IToken offendingSymbol, Int32 line, Int32 charPositionInLine, String msg, RecognitionException e) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Symbols\ExceptionErrorListener.cs:line 10
   at Antlr4.Runtime.ProxyErrorListener`1.SyntaxError(IRecognizer recognizer, Symbol offendingSymbol, Int32 line, Int32 charPositionInLine, String msg, RecognitionException e)
   at Antlr4.Runtime.Parser.NotifyErrorListeners(IToken offendingToken, String msg, RecognitionException e)
   at Antlr4.Runtime.DefaultErrorStrategy.Sync(Parser recognizer)
   at Rubberduck.Parsing.Grammar.VBAParser.block() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1543
   at Rubberduck.Parsing.Grammar.VBAParser.ifStmt() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 7693
   at Rubberduck.Parsing.Grammar.VBAParser.blockStmt() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1791
   at Rubberduck.Parsing.Grammar.VBAParser.block() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1537
   at Rubberduck.Parsing.Grammar.VBAParser.withStmt() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 12436
   at Rubberduck.Parsing.Grammar.VBAParser.blockStmt() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1917
   at Rubberduck.Parsing.Grammar.VBAParser.block() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1537
   at Rubberduck.Parsing.Grammar.VBAParser.ifStmt() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 7693
   at Rubberduck.Parsing.Grammar.VBAParser.blockStmt() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1791
   at Rubberduck.Parsing.Grammar.VBAParser.block() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1537
   at Rubberduck.Parsing.Grammar.VBAParser.elseBlock() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 7856
   at Rubberduck.Parsing.Grammar.VBAParser.ifStmt() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 7714
   at Rubberduck.Parsing.Grammar.VBAParser.blockStmt() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1791
   at Rubberduck.Parsing.Grammar.VBAParser.block() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1537
   at Rubberduck.Parsing.Grammar.VBAParser.subStmt() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 11094
   at Rubberduck.Parsing.Grammar.VBAParser.moduleBodyElement() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1472
   at Rubberduck.Parsing.Grammar.VBAParser.moduleBody() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1377
   at Rubberduck.Parsing.Grammar.VBAParser.module() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 357
   at Rubberduck.Parsing.Grammar.VBAParser.startRule() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 267
   at Rubberduck.Parsing.VBA.VBAModuleParser.Parse(String moduleName, String moduleCode, IParseTreeListener[] listeners, ITokenStream& outStream) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\VBA\VBAModuleParser.cs:line 34
   at Rubberduck.Parsing.VBA.AttributeParser.Parse(IVBComponent component) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\VBA\AttributeParser.cs:line 51
   at Rubberduck.Parsing.VBA.ComponentParseTask.Start(CancellationToken token) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\VBA\ComponentParseTask.cs:line 51
```

**Comment by comintern** [comment]
Unrelated to this issue, but I'm also a bit concerned about the `Rubberduck.Common.WinAPI.RawInput;Error sizing the rawinput buffer: The handle is invalid;` spam in the log file.

What build is this from?

**Comment by halcwb** [comment]
I am using: https://github.com/rubberduck-vba/Rubberduck/tree/v2.0.9RC

**Comment by retailcoder** [comment]
@Vogel612 the commandbar error marker/icon wasn't in 2.0.9 I think
