### ISSUE TITLE
Source control (?) crashing 

### ISSUE THREAD

**Issue by bogdimon** [rubberduck-vba/Rubberduck#2477]
Source control doesn't really work for me. This happened when I tried to 'open a local repository'. However, when I initiated the local repo, there were also some errors.

P.S. as you can see, I'm a noob, so beg your pardon for not-quite-great description. Happy to provide more info.

These are the relevant contents of the log file:

```
2017-01-04 09:46:15.0042;TRACE;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Refreshing display;
2017-01-04 09:57:35.7675;DEBUG;Rubberduck.UI.Command.MenuItems.ParentMenus.ParentMenuItemBase;(60227273) Executing click handler for menu item '&Source Control', hash code 49496992;
2017-01-04 09:57:41.1714;TRACE;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Refreshing display;
2017-01-04 09:58:09.4486;TRACE;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Initializing repo;
2017-01-04 09:58:09.7380;TRACE;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Displaying Error with title 'Unable to perform initial commit.' and message 'Configuration value 'user.name' is missing or invalid.';
2017-01-04 09:58:17.4548;TRACE;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Displaying Info with title 'Settings updated' and message 'Your user name, email address, and default repository location have been saved.';
2017-01-04 09:58:38.4587;TRACE;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Initializing repo;
2017-01-04 09:58:38.5212;TRACE;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Displaying Error with title 'Unable to perform initial commit.' and message 'Configuration value 'user.name' is missing or invalid.';
```
```
2017-01-03 18:48:15.8535;ERROR;Rubberduck.UI.SourceControl.SourceControlViewViewModel;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.UI.SourceControl.BranchesViewViewModel.RefreshView() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\BranchesViewViewModel.cs:line 54
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.Refresh() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 897
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.<.ctor>b__8(Object _) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 72
   at Rubberduck.UI.Command.DelegateCommand.ExecuteImpl(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\DelegateCommand.cs:line 26
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 60;
2017-01-03 18:48:38.2065;ERROR;Rubberduck.UI.SourceControl.SourceControlViewViewModel;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.UI.SourceControl.BranchesViewViewModel.RefreshView() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\BranchesViewViewModel.cs:line 54
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.Refresh() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 897
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.<.ctor>b__8(Object _) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 72
   at Rubberduck.UI.Command.DelegateCommand.ExecuteImpl(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\DelegateCommand.cs:line 26
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 60;
2017-01-03 18:48:42.0775;ERROR;Rubberduck.UI.SourceControl.SourceControlViewViewModel;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.UI.SourceControl.BranchesViewViewModel.RefreshView() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\BranchesViewViewModel.cs:line 54
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.Refresh() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 897
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.<.ctor>b__8(Object _) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 72
   at Rubberduck.UI.Command.DelegateCommand.ExecuteImpl(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\DelegateCommand.cs:line 26
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 60;
2017-01-03 18:48:42.4515;ERROR;Rubberduck.UI.SourceControl.SourceControlViewViewModel;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.UI.SourceControl.BranchesViewViewModel.RefreshView() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\BranchesViewViewModel.cs:line 54
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.Refresh() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 897
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.<.ctor>b__8(Object _) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 72
   at Rubberduck.UI.Command.DelegateCommand.ExecuteImpl(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\DelegateCommand.cs:line 26
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 60;
2017-01-03 18:48:42.6171;ERROR;Rubberduck.UI.SourceControl.SourceControlViewViewModel;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.UI.SourceControl.BranchesViewViewModel.RefreshView() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\BranchesViewViewModel.cs:line 54
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.Refresh() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 897
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.<.ctor>b__8(Object _) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 72
   at Rubberduck.UI.Command.DelegateCommand.ExecuteImpl(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\DelegateCommand.cs:line 26
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 60;
2017-01-03 18:48:51.4847;ERROR;Rubberduck._Extension;System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Microsoft.Vbe.Interop.VBComponentClass.get_Properties()
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBComponent.get_Properties() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBComponent.cs:line 40
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBComponent.Release() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBComponent.cs:line 174
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBComponents.Release() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBComponents.cs:line 81
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBProject.Release() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBProject.cs:line 109
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBProjects.Release() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBProjects.cs:line 67
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBE.Release() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBE.cs:line 76
   at Rubberduck._Extension.ShutdownAddIn() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\Extension.cs:line 195;
2017-01-03 19:00:28.1945;ERROR;Rubberduck.UI.SourceControl.SourceControlViewViewModel;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.UI.SourceControl.BranchesViewViewModel.RefreshView() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\BranchesViewViewModel.cs:line 54
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.Refresh() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 897
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.<.ctor>b__8(Object _) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 72
   at Rubberduck.UI.Command.DelegateCommand.ExecuteImpl(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\DelegateCommand.cs:line 26
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 60;
2017-01-03 19:00:37.2504;ERROR;Rubberduck.UI.SourceControl.SourceControlViewViewModel;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.UI.SourceControl.BranchesViewViewModel.RefreshView() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\BranchesViewViewModel.cs:line 54
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.Refresh() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 897
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.<.ctor>b__8(Object _) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 72
   at Rubberduck.UI.Command.DelegateCommand.ExecuteImpl(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\DelegateCommand.cs:line 26
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 60;
2017-01-03 19:00:38.0770;ERROR;Rubberduck.UI.SourceControl.SourceControlViewViewModel;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.UI.SourceControl.BranchesViewViewModel.RefreshView() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\BranchesViewViewModel.cs:line 54
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.Refresh() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 897
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.<.ctor>b__8(Object _) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 72
   at Rubberduck.UI.Command.DelegateCommand.ExecuteImpl(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\DelegateCommand.cs:line 26
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 60;
2017-01-03 19:00:38.2246;ERROR;Rubberduck.UI.SourceControl.SourceControlViewViewModel;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.UI.SourceControl.BranchesViewViewModel.RefreshView() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\BranchesViewViewModel.cs:line 54
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.Refresh() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 897
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.<.ctor>b__8(Object _) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 72
   at Rubberduck.UI.Command.DelegateCommand.ExecuteImpl(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\DelegateCommand.cs:line 26
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 60;
2017-01-03 19:00:38.4902;ERROR;Rubberduck.UI.SourceControl.SourceControlViewViewModel;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.UI.SourceControl.BranchesViewViewModel.RefreshView() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\BranchesViewViewModel.cs:line 54
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.Refresh() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 897
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.<.ctor>b__8(Object _) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 72
   at Rubberduck.UI.Command.DelegateCommand.ExecuteImpl(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\DelegateCommand.cs:line 26
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 60;
2017-01-04 09:33:19.1886;ERROR;Rubberduck.UI.SourceControl.SourceControlViewViewModel;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.set_Provider(ISourceControlProvider value) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 229
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.OpenRepo() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 721
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.<.ctor>b__2(Object _) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 69
   at Rubberduck.UI.Command.DelegateCommand.ExecuteImpl(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\DelegateCommand.cs:line 26
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 60;
```

**Comment by mansellan** [comment]
This should be fixed as of #3401

**Comment by seppu** [comment]
@Vogel612 
I am having the same issues using Rubberduck.Setup.2.1.2.2851-pre version. I am getting the error 
![image](https://user-images.githubusercontent.com/7526379/36452827-1225ab46-16ea-11e8-88a8-c18ceacb87a3.png)
When checking the logs the error is
 ```
2018-02-21 09:29:07.9629;ERROR-2.1.2.2851;Rubberduck.UI.SourceControl.SourceControlViewViewModel;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.set_Provider(ISourceControlProvider value) in C:\projects\rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 265
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.OpenRepo() in C:\projects\rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 739
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.<.ctor>b__11_2(Object _) in C:\projects\rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 69
   at Rubberduck.UI.Command.DelegateCommand.OnExecute(Object parameter) in C:\projects\rubberduck\RetailCoder.VBE\UI\Command\DelegateCommand.cs:line 26
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in C:\projects\rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 47;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.set_Provider(ISourceControlProvider value) in C:\projects\rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 265
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.OpenRepo() in C:\projects\rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 739
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.<.ctor>b__11_2(Object _) in C:\projects\rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 69
   at Rubberduck.UI.Command.DelegateCommand.OnExecute(Object parameter) in C:\projects\rubberduck\RetailCoder.VBE\UI\Command\DelegateCommand.cs:line 26
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in C:\projects\rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 47
```
Any idea what to do? 
You seemed to have marked this as Done

**Comment by Vogel612** [comment]
FWIW @seppu, Source control is scheduled for removal from Rubberduck because of the significant cost associated with maintaining it. The comparably small use it sees, as well as the lack of integration for SourceControl Providers other than git just doesn't stack up against the cost of maintaining.

As such, Source control will be removed, see also #3758. You should be able to effectively practice source control by using Rubberduck's "Export All" command
