### ISSUE TITLE
Windows message: "Microsoft Excel is trying to recover your information"

### ISSUE THREAD

**Issue by bogdimon** [rubberduck-vba/Rubberduck#2479]
The subj. message has started to show up since I installed Rubberduck. The logfile seems to show some relevant info too.

> 2017-01-04 12:41:15.7288;ERROR;Rubberduck._Extension;System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Microsoft.Vbe.Interop.VBComponentClass.get_Properties()
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBComponent.get_Properties() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBComponent.cs:line 40
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBComponent.Release() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBComponent.cs:line 174
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBComponents.Release() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBComponents.cs:line 81
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBProject.Release() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBProject.cs:line 109
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBProjects.Release() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBProjects.cs:line 67
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBE.Release() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBE.cs:line 76
   at Rubberduck._Extension.ShutdownAddIn() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\Extension.cs:line 195;

**Comment by retailcoder** [comment]
That would be the crash-on-exit that's sometimes seen upon teardown. Is that off 2.0.10?

**Comment by bogdimon** [comment]
its 2.0.9.18871

**Comment by retailcoder** [comment]
We've made a number of changes to the teardown process between 2.0.9 and 2.0.10; seems the property getters on all wrapper types might all going to end up needing to swallow any `COMException` that can be thrown out of the blue at teardown, but something tells me that won't be the end of the story and then the add-in crashing won't blow up the host process, but then the host won't shut down either and linger in Task Manager, which isn't any better (I prefer a hard crash, personally!)... anyway, please let us know if 2.0.10 has the same problem - on my end I've been having "clean exits" for a while with that build now.

**Comment by retailcoder** [comment]
ref. #2436
