### ISSUE TITLE
Unknown error trying to setup test project with Remote path

### ISSUE THREAD

**Issue by yorkshire-pudding** [rubberduck-vba/Rubberduck#2560]
I have been developing in VBA for years but only recently come across Rubberduck.  I am trying to get to grips with Source Control, but am also new to github.

I setup settings with username, a local repository directory.  I created a new spreadsheet, saved as RubberduckTest.xlsm, set the project name in VBA to be RubberduckTest and initialised a repository with a folder of the same name.  When I try to enter a remote path (https://github.com/yorkshire-pudding/RubberduckTest.git) I get the following error
![image](https://cloud.githubusercontent.com/assets/20357797/22147025/bfc921a8-defe-11e6-846a-70a4d822ce1f.png)
And this is what the log says
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/719130/RubberduckLog.txt)

Please could you advise what if anything I am doing wrong here

**Comment by Vogel612** [comment]
Apparently there's an issue in the SourceControl component:

```

2017-01-20 10:48:00.6653;ERROR-2.0.11.2453;Rubberduck.UI.SourceControl.SourceControlViewViewModel;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.SourceControl.GitProvider.get_Branches() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.SourceControl\GitProvider.cs:line 88
   at Rubberduck.SourceControl.GitProvider.get_CurrentBranch() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.SourceControl\GitProvider.cs:line 79
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.PublishRepo() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 803
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.<.ctor>b__11(Object _) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 81
   at Rubberduck.UI.Command.DelegateCommand.ExecuteImpl(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\DelegateCommand.cs:line 26
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 54;
```

This stacktrace is repeated over and over in the log.

I assume the error is that `_repo` isn't correctly initialized yet :confused: The exception is thrown on [this line](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.SourceControl/GitProvider.cs#L88)

**Comment by yorkshire-pudding** [comment]
Any ideas how this can be fixed? Am I the only one experiencing this?

**Comment by DiegoTheWolf** [comment]
Same problem here
```
2017-06-20 10:21:36.3383;ERROR-2.0.13.32288;Rubberduck.UI.SourceControl.SourceControlViewViewModel;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.set_Provider(ISourceControlProvider value) in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 249
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.OpenRepo() in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 740
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.<.ctor>b__11_2(Object _) in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 71
   at Rubberduck.UI.Command.DelegateCommand.ExecuteImpl(Object parameter) in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\RetailCoder.VBE\UI\Command\DelegateCommand.cs:line 26
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 54;
```

I'm kinda unable to work with a git.

**Comment by Vogel612** [comment]
Since the source control integration has been removed (see #3758), this issue is now obsolete
