### ISSUE TITLE
Rubberduck , VisualStudioCode Local Git repositories only

### ISSUE THREAD

**Issue by cleidigh** [rubberduck-vba/Rubberduck#2567]
just got rubberduck installed with Excel 2010. Also installed Windows git. I can successfully create a local repository. and do a local commit. Visual Studio code can also see the commit. I am trying to use the repository just locally for now. I want to use Visual Studio code as my main editor as it has accessibility I need as I am disabled. can I pull the VCS commits into Excel this way? I can't seem to figure out how to do a  sync to pull in my edits from Visual Studio code. Note I am brand-new to Git.

thanks Christopher

**Comment by ckuhn203** [comment]
Just to be sure I've got this right, you're wanting to edit your VBA code in the Visual Studio Code editor instead of the built in VBA editor?

**Comment by retailcoder** [comment]
The commits are in the git repository, and we detect changes made outside the VBE on refresh.. it should 'just work", no?

**Comment by cleidigh** [comment]
thanks for the quick responses, I've been trying to do more experiments and understand git better.
Answer to the first question: yes I'm trying to use Visual Studio as the main editor. 
in general it still means I will have commitments from both VBE as well as the VCS

I re-created a simple project with just one module to experiment on. I used the following basic sequence:

- initialize new repository using rubber duck
- create single comment in module file
- commit this module with rubber duck
- open the file in VCS and verify git history (so far this works)
- make a single-line change in VCS and commit
- go back to Excel and view the un synced committs
- (under outgoing commits both Excel and VCS commits are visible
- I get a Pull error when I do a sync "there is no tracking information for this branch"

from some research I think this has to do with creating only the local repository but I can't find the right way to configure it. RD not seem to see my edits from VCS

here's the log file from the back and forth:

2017-01-22 22:35:30.3228;INFO-2.0.11.2453;Rubberduck.App;Rubberduck version 2.0.11.2453 loading:
	Operating System: Microsoft Windows NT 6.1.7601 Service Pack 1 x64
	Host Product: Microsoft Office 2010 x86
	Host Version: 14.0.7177.5000
	Host Executable: EXCEL.EXE;
2017-01-22 22:35:36.3128;DEBUG-2.0.11.2453;Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase;(51699968) Executing click handler for commandbar item 'Pending', hash code 770424;
2017-01-22 22:35:36.3248;ERROR-2.0.11.2453;DynamicInjectorba79ce74d7d149a4a9dbef4936c7c9f2;System.Runtime.InteropServices.COMException (0x800AC471): Can't perform operation since the project is protected.
   at Microsoft.Vbe.Interop._VBProject.get_VBComponents()
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBProject.get_VBComponents() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBProject.cs:line 62
   at Rubberduck.VBEditor.Events.Sinks.Start() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.VBEEditor\Events\Sinks.cs:line 39
   at Rubberduck.Parsing.VBA.RubberduckParserState.StartEventSinks() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParserState.cs:line 88
   at Rubberduck.UI.Command.ReparseCommand.ExecuteImpl(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\ReparseCommand.cs:line 36
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 54;
2017-01-22 22:35:36.4318;DEBUG-2.0.11.2453;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisWorkbook' state is changing to 'Pending' (thread 9);
2017-01-22 22:35:36.4428;DEBUG-2.0.11.2453;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Sheet1' state is changing to 'Pending' (thread 9);
2017-01-22 22:35:36.4428;DEBUG-2.0.11.2453;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Sheet2' state is changing to 'Pending' (thread 9);
2017-01-22 22:35:36.4428;DEBUG-2.0.11.2453;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Sheet3' state is changing to 'Pending' (thread 9);
2017-01-22 22:35:36.4428;DEBUG-2.0.11.2453;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Module1' state is changing to 'Pending' (thread 9);
2017-01-22 22:35:36.4988;TRACE-2.0.11.2453;Rubberduck.Parsing.VBA.ParseCoordinator;Loading referenced type 'VBA'.;
2017-01-22 22:35:36.4988;TRACE-2.0.11.2453;Rubberduck.Parsing.VBA.ParseCoordinator;COM reflecting reference 'VBA'.;
2017-01-22 22:35:36.5088;TRACE-2.0.11.2453;Rubberduck.Parsing.VBA.ParseCoordinator;Loading referenced type 'Excel'.;
2017-01-22 22:35:36.5088;TRACE-2.0.11.2453;Rubberduck.Parsing.VBA.ParseCoordinator;COM reflecting reference 'Excel'.;
2017-01-22 22:35:36.5258;TRACE-2.0.11.2453;Rubberduck.Parsing.VBA.ParseCoordinator;Loading referenced type 'stdole'.;
2017-01-22 22:35:36.5258;TRACE-2.0.11.2453;Rubberduck.Parsing.VBA.ParseCoordinator;COM reflecting reference 'stdole'.;
2017-01-22 22:35:36.5568;TRACE-2.0.11.2453;Rubberduck.Parsing.VBA.ParseCoordinator;Loading referenced type 'Office'.;
2017-01-22 22:35:36.5568;TRACE-2.0.11.2453;Rubberduck.Parsing.VBA.ParseCoordinator;COM reflecting reference 'Office'.;
2017-01-22 22:35:38.9668;DEBUG-2.0.11.2453;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Sheet2' state is changing to 'Parsing' (thread 10);
2017-01-22 22:35:38.9708;DEBUG-2.0.11.2453;Rubberduck.App;App handles StateChanged (Parsing), evaluating menu states...;
2017-01-22 22:35:39.3618;DEBUG-2.0.11.2453;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Sheet2' state is changing to 'Parsed' (thread 10);
2017-01-22 22:35:39.3618;DEBUG-2.0.11.2453;Rubberduck.App;App handles StateChanged (Pending), evaluating menu states...;
2017-01-22 22:35:39.3618;TRACE-2.0.11.2453;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Refreshing display;
2017-01-22 22:35:39.3618;TRACE-2.0.11.2453;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Opening repo assigned to project;
2017-01-22 22:35:39.4018;TRACE-2.0.11.2453;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Provider changed;
2017-01-22 22:35:39.4548;TRACE-2.0.11.2453;Rubberduck.UI.SourceControl.ChangesViewViewModel;Refreshing view;
2017-01-22 22:35:39.5618;TRACE-2.0.11.2453;Rubberduck.UI.SourceControl.BranchesViewViewModel;Provider changed;
2017-01-22 22:35:39.5628;TRACE-2.0.11.2453;Rubberduck.UI.SourceControl.BranchesViewViewModel;Refreshing view;
2017-01-22 22:35:39.9048;TRACE-2.0.11.2453;Rubberduck.UI.SourceControl.UnsyncedCommitsViewViewModel;Provider changed;
2017-01-22 22:35:39.9058;TRACE-2.0.11.2453;Rubberduck.UI.SourceControl.UnsyncedCommitsViewViewModel;Refreshing view;
2017-01-22 22:35:39.9788;DEBUG-2.0.11.2453;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Sheet1' state is changing to 'Parsing' (thread 11);
2017-01-22 22:35:39.9788;DEBUG-2.0.11.2453;Rubberduck.App;App handles StateChanged (Parsing), evaluating menu states...;
2017-01-22 22:35:40.0358;DEBUG-2.0.11.2453;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisWorkbook' state is changing to 'Parsing' (thread 13);
2017-01-22 22:35:40.2078;DEBUG-2.0.11.2453;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Sheet2' state is changing to 'ResolvingDeclarations' (thread 8);
2017-01-22 22:35:40.2078;DEBUG-2.0.11.2453;Rubberduck.App;App handles StateChanged (ResolvingDeclarations), evaluating menu states...;
2017-01-22 22:35:40.2378;DEBUG-2.0.11.2453;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisWorkbook' state is changing to 'Parsed' (thread 13);
2017-01-22 22:35:40.2638;DEBUG-2.0.11.2453;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisWorkbook' state is changing to 'ResolvingDeclarations' (thread 7);
2017-01-22 22:35:40.2748;DEBUG-2.0.11.2453;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Sheet3' state is changing to 'Parsing' (thread 13);
2017-01-22 22:35:40.2748;DEBUG-2.0.11.2453;Rubberduck.Parsing.VBA.ParseCoordinator;Creating declarations for module RubberTest.ThisWorkbook.;
2017-01-22 22:35:40.2868;DEBUG-2.0.11.2453;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Sheet1' state is changing to 'Parsed' (thread 11);
2017-01-22 22:35:40.3118;DEBUG-2.0.11.2453;Rubberduck.Parsing.VBA.ParseCoordinator;36ms to resolve declarations for component ThisWorkbook;
2017-01-22 22:35:40.3118;DEBUG-2.0.11.2453;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Sheet1' state is changing to 'ResolvingDeclarations' (thread 6);
2017-01-22 22:35:40.3118;DEBUG-2.0.11.2453;Rubberduck.Parsing.VBA.ParseCoordinator;Creating declarations for module RubberTest.Sheet1.;
2017-01-22 22:35:40.3308;DEBUG-2.0.11.2453;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Sheet3' state is changing to 'Parsed' (thread 13);
2017-01-22 22:35:40.3308;DEBUG-2.0.11.2453;Rubberduck.Parsing.VBA.ParseCoordinator;18ms to resolve declarations for component Sheet1;
2017-01-22 22:35:40.3558;DEBUG-2.0.11.2453;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Sheet3' state is changing to 'ResolvingDeclarations' (thread 10);
2017-01-22 22:35:40.3598;DEBUG-2.0.11.2453;Rubberduck.Parsing.VBA.ParseCoordinator;Creating declarations for module RubberTest.Sheet3.;
2017-01-22 22:35:40.3778;DEBUG-2.0.11.2453;Rubberduck.Parsing.VBA.ParseCoordinator;18ms to resolve declarations for component Sheet3;
2017-01-22 22:35:40.4248;DEBUG-2.0.11.2453;Rubberduck.Parsing.VBA.ParseCoordinator;Creating declarations for module RubberTest.Sheet2.;
2017-01-22 22:35:40.4398;DEBUG-2.0.11.2453;Rubberduck.Parsing.VBA.ParseCoordinator;15ms to resolve declarations for component Sheet2;
2017-01-22 22:38:09.5195;TRACE-2.0.11.2453;Rubberduck.UI.SourceControl.UnsyncedCommitsViewViewModel;Fetching;
2017-01-22 22:38:09.5505;TRACE-2.0.11.2453;Rubberduck.UI.SourceControl.UnsyncedCommitsViewViewModel;Refreshing view;
2017-01-22 22:38:15.3580;TRACE-2.0.11.2453;Rubberduck.UI.SourceControl.UnsyncedCommitsViewViewModel;Syncing (pull + push);
2017-01-22 22:38:15.3910;TRACE-2.0.11.2453;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Displaying Error with title 'Pull failed.' and message 'There is no tracking information for the current branch.';
2017-01-22 22:38:51.1008;TRACE-2.0.11.2453;Rubberduck.UI.SourceControl.UnsyncedCommitsViewViewModel;Fetching;
2017-01-22 22:38:51.1278;TRACE-2.0.11.2453;Rubberduck.UI.SourceControl.UnsyncedCommitsViewViewModel;Refreshing view;
2017-01-22 22:41:54.9798;TRACE-2.0.11.2453;Rubberduck.UI.SourceControl.UnsyncedCommitsViewViewModel;Pulling;
2017-01-22 22:41:54.9868;TRACE-2.0.11.2453;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Displaying Error with title 'Pull failed.' and message 'There is no tracking information for the current branch.';

thanks Christopher

**Comment by retailcoder** [comment]
AFAIK you can't *sync* if you're working without a remote.

**Comment by cleidigh** [comment]
I'm a total git newbie this seems to be the issue. but can't I work with the local repository between the two clients? RD does not seem to see the changes from VCS on refresh so it always reverts to the Excel version.
and that actually gets recommitted. I do think I saw a detect once. but I don't know what the sequence was.
is there a way to pull in the committed file from VCS as it is? I could just merging in VCS?

I still think there's something I don't understand about the right sequence in RD

**Comment by comintern** [comment]
What version of Visual Studio are you using?  If you're using a local repository it needs to be flagged as 'bare'.

**Comment by cleidigh** [comment]
latest: 1.8.1
I'm reading up on the bare flag. I'm also going to look at the config

**Comment by Vogel612** [comment]
The way I understand the issue described the problem is actually within Rubberduck.

Rubberduck (incorrectly) expects there to be a remote repository when refreshing the repository status. This shouldn't actually be that way and initializing the repository with the `--bare`-Flag will only result in not being able to work with Visual Studio. 

The correct fix here is to allow refreshing repositories that do not have any remotes set.

For the record: I highly recommend you do actually set up a remote repository on a separate machine, so as to prevent data loss in case of fatal failure. This allows git to act similarly to SVN and allows collaboration with your colleagues.

**Comment by ckuhn203** [comment]
So, I see two new issues being created from this one. 

1. Create a bug detailing that RD should not blow up if a refresh occurs when there isn't a remote, as Vogel pointed out. 
2. Ensure that all the RD controls are accessible. 

Thoughts on that?

**Comment by cleidigh** [comment]
thanks for your guy 's patience , my dictation is rough as it's too hard to correct everything and again I'm new to git

I've been bearing myself in the docs. As Vogel said you can't just use a bare repository I've learned that much. So what I'm trying to do now I think there's a couple more things:

1 as ckuhn mentions in his one, RD could work better without requiring the remote. Additionally I have found that it doesn't like local file references, not necessarily something common but an easy way to get private repositories locally on something like dropbox. Visual Studio code seems to be okay with either although the kit commands are inconsistent as to what they accept for UNC style repository specs. Some of this is of course my lack of knowledge but I've been experimenting all day trying to see what both VCS and RD would accept.

I agree for most work at Gig Harbor big bucket absolutely makes sense. Right now I'm just trying to deal with some local use.

As for accessibility this was one of my goals using RD just the act of importing and exporting modules is a huge amount l work when you can't use your hands and your voice is minimal (thanks ALS) the seamless source control of RD and the use of an external editor can really help. I would be more than happy to enumerate a few areas where there are accessibility points lacking in RD but overall I really like it. Let me do that in a separate thread.

Below are a couple examples of repository references RD doesn't like:


[remote "master"]
	url = file://E:/GitCentral/RubberTest
	fetch = +refs/heads/*:refs/remotes/master/*
[branch "master"]
	remote = E:\\GitCentral\\RubberTest
	merge = refs/heads/master

3 - detecting external changes

RD does not seem to be consistent detecting external file changes unless I'm completely misunderstanding when it should happen. Sometimes I can change a file externally and I get a pop-up sometimes I don't. Since it appears to be an all or nothing one obviously has to do with merging externally but I've never really gotten that far.

If I should send along any more logs please let me know. I'll see if I can set up a legit git hub repository so I can test more of the other features.

Great project guys I just wish VBE itself was more accessible try just closing a sub window! Takes me half a day with voice commands ;-)

Christopher

**Comment by ckuhn203** [comment]
@cleidigh thank you for reminding me that not everyone uses our software in the same way. I'm promise you that I am personally going to be more aware of accessibility in the future.

**Comment by ThunderFrame** [comment]
I think @rossknudsen had some code that edited VBA in Visual Studio.

**Comment by rossknudsen** [comment]
@ThunderFrame I do have some, but it's not really functional.  I was trying to get it to compile the code into an Office file format but was having trouble debugging.  I was hoping that [this question](http://stackoverflow.com/questions/37000572/bug-in-implementation-of-microsoft-vba-compression-algorithm) might get solved, because if I can reproduce the binary compression algorithm used in the Office applications, then it will make it easier to debug.

So you can get syntax highlighting and brace completion but that's not helpful if you can't create an Office document.

**Comment by rubberduck203** [comment]
Per #3758 we’ve removed the source control feature. The “correct” workflow now would be to “Export All” to the file system, edit with VS Code, then “Import All” back into the workbook. 

@contributors also a reminder to be mindful of Rubberduck’s accessibility. Please take the time to fill in UI element attributes properly.
