### ISSUE TITLE
ParserState cache is acting up

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#2773]
From a new VBA project:

 - Wait for initial parse to complete
 - Add a new standard/procedural module
 - Add dummy procedure
 - Parse again, wait for completion
 - Remove the module
 - Parse again -> Parse Error, no details in the *Parser Errors* result toolwindow.

Logs a `COMException` trying to get the `VBComponent.Name` of a module that no longer exists:

````
2017-03-02 12:34:15.0740;DEBUG-2.0.12.19847;Rubberduck.Parsing.VBA.RubberduckParserState;Component 'Module1' was removed.;
2017-03-02 12:34:15.0930;DEBUG-2.0.12.19847;Rubberduck.Parsing.VBA.ParseCoordinator;Parsing run started. (thread 28).;
2017-03-02 12:34:15.2430;ERROR-2.0.12.19847;Rubberduck.Parsing.VBA.ParseCoordinator;Unexpected exception thrown in parsing run. (thread 28).;System.Runtime.InteropServices.COMException (0x80070006): System Error &H80070006 (-2147024890).  
   at Microsoft.Vbe.Interop.VBComponentClass.get_Name()
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBComponent.get_Name() in c:\Dev\Rubberduck\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBComponent.cs:line 55
   at Rubberduck.Parsing.VBA.ParseCoordinator.<RemovedModuleDeclarations>b__4a(IVBComponent component) in c:\Dev\Rubberduck\Rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:line 766
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection)
   at Rubberduck.Parsing.VBA.EnumerableExtensions.ToHashSet[T](IEnumerable`1 source) in c:\Dev\Rubberduck\Rubberduck\Rubberduck.Parsing\VBA\EnumerableExtensions.cs:line 26
   at Rubberduck.Parsing.VBA.ParseCoordinator.RemovedModuleDeclarations(ICollection`1 components) in c:\Dev\Rubberduck\Rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:line 766
   at Rubberduck.Parsing.VBA.ParseCoordinator.CleanUpRemovedComponents(ICollection`1 components, CancellationToken token) in c:\Dev\Rubberduck\Rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:line 748
   at Rubberduck.Parsing.VBA.ParseCoordinator.ParseAllInternal(Object requestor, CancellationToken token) in c:\Dev\Rubberduck\Rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:line 713
   at Rubberduck.Parsing.VBA.ParseCoordinator.ParseAll(Object requestor, CancellationToken token) in c:\Dev\Rubberduck\Rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:line 680
2017-03-02 12:34:15.3180;DEBUG-2.0.12.19847;Rubberduck.Parsing.VBA.RubberduckParserState;RubberduckParserState raised StateChanged (Error);
2017-03-02 12:34:15.4500;DEBUG-2.0.12.19847;Rubberduck.Parsing.VBA.ParseCoordinator;Parsing run finished after 0s. (thread 28).;
````

**Comment by retailcoder** [comment]
While trying to repro #2641 I also managed to get the parser state stuck on "Resolving declarations..." with a `COMException` thrown when trying to run a non-compilable test module.

**Comment by MDoerner** [comment]
I cannot repro the COMException.

At the point of the exception, the `components` collection contains the components found on the projects saved on the `RubberduckParserState`. These gets refreshed right before querying them. 

The only thing I can imagine causing an error there would be the component not getting removed fast enough from the `IVBE` object. In that case the handler of the component removed event would be the problem.

**Comment by comintern** [comment]
@MDoerner - The IVBE events aren't tracking individual `VBComponents` anymore, so this one is a bit puzzling.  The 0x80070006 error is an invalid handle, which points toward the `VBComponent` having been released.  The `ComponentEventArgs` do include a reference to the `VBComponent` that was removed, so I could envision a scenario where the underlying component is destroyed before the wrapped one gets to the sink.  I _suspect_ that the Logger is to blame:

`Logger.Debug("Component '{0}' was removed.", e.Component.Name);`

I don't think it get used for anything else on that code path.

**Comment by MDoerner** [comment]
@comintern It is not the logger. `RemovedModuleDeclarations` in the call stack above explicitly queries the names and helpfiles of the parent (projectID) of the components to get something to match them to the module declarations.

However, if a component got removed, it should not be in the `components` collection at that point.

**Comment by comintern** [comment]
@MDoerner - You're right - I wasn't reading the call stack, I was focusing on the execution path backward from `RubberduckParserState.Sinks_ComponentRemoved`.  The `VBComponents` sink _should_ be blocking on the main thread, so unless something screwy is going on in the RCW the source object that gets passed to `VBComponents.OnDispatch` shouldn't be destroyed by the VBE until after the event handler exits. Is it possible that removing the component is generating multiple reparse requests?

**Comment by MDoerner** [comment]
Do we really have to reparse whenever a module gets removed or can we defer that? Which functionallity requires the reparse?

The problem here seems to be that the timing is wrong: when we trigger the reparse from the event handler we are in a race with the VBE. Since the handler is executed prior to the actual release of the component by the VBE, the VBE only gets the oportunity to release the component when the parsing run starts (on a background thread). The first thing done in the parsing run is the refresh the projects on the parser state. If the component has not been released at that point, the entire parsing run will assume that the component still exists. Hence, the data supposed to get cleaned up by the parsing run probably never gets cleaned up. Moreover, if the VBE releases the component at an inappropriate time, we run into the exception above.

**Comment by retailcoder** [comment]
@MDoerner if we don't sync right away, then the code explorer will contain modules (and associated navigation commands) that no longer exist.

**Comment by MDoerner** [comment]
@retailcoder The problem is: we are too fast. When the reparse queries the components from the VBE, the VBE has not gotten around to actually release the component. 

With a sufficiently large test project, I can repro the exception now.

**Comment by comintern** [comment]
@MDoerner - I can see what I can do to delay raising the managed event until the VBE is actually finished removing it from the components collection. There may be a windows event associated with it, but I'd need to check.  I'd prefer not to do anything that would block if I can avoid it (i.e. looping until the module count decreases) - this will all be running on the VBE's main thread.

**Comment by MDoerner** [comment]
With the hack in place, I cannot reproduce the issue anymore. Shall we close it for now?

**Comment by retailcoder** [comment]
Yup. I'm putting it in the release notes :)
