### ISSUE TITLE
The CodeExplorer throws when a new standard  module gets added

### ISSUE THREAD

**Issue by MDoerner** [rubberduck-vba/Rubberduck#2813]
I tried to repro #2773 and ran into another bug. 

When a standard module gets added, the CodeExplorer throws an exception on every later parsing attempt.
This happens after resolving the declarations upon firing the corresponding state changed event.

```
2017-03-08 15:54:54.9476;ERROR-2.0.13.28116;Rubberduck.Parsing.VBA.ParseCoordinator;Unexpected exception thrown in parsing run. (thread 75).;System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Microsoft.Vbe.Interop.VBComponentClass.get_Type()
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBComponent.get_Type() in h:\Repositories\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBComponent.cs:line 20
   at Rubberduck.Navigation.CodeExplorer.CodeExplorerComponentViewModel..ctor(CodeExplorerItemViewModel parent, Declaration declaration, IEnumerable`1 declarations) in h:\Repositories\Rubberduck\RetailCoder.VBE\Navigation\CodeExplorer\CodeExplorerComponentViewModel.cs:line 54
   at Rubberduck.Navigation.CodeExplorer.CodeExplorerCustomFolderViewModel.AddNodes(List`1 declarations) in h:\Repositories\Rubberduck\RetailCoder.VBE\Navigation\CodeExplorer\CodeExplorerCustomFolderViewModel.cs:line 48
   at Rubberduck.Navigation.CodeExplorer.CodeExplorerProjectViewModel.AddNodesToTree(CodeExplorerCustomFolderViewModel tree, List`1 items, IGrouping`2 grouping) in h:\Repositories\Rubberduck\RetailCoder.VBE\Navigation\CodeExplorer\CodeExplorerProjectViewModel.cs:line 84
   at Rubberduck.Navigation.CodeExplorer.CodeExplorerProjectViewModel.FillFolders(IEnumerable`1 declarations) in h:\Repositories\Rubberduck\RetailCoder.VBE\Navigation\CodeExplorer\CodeExplorerProjectViewModel.cs:line 66
   at Rubberduck.Navigation.CodeExplorer.CodeExplorerProjectViewModel..ctor(FolderHelper folderHelper, Declaration declaration, IEnumerable`1 declarations) in h:\Repositories\Rubberduck\RetailCoder.VBE\Navigation\CodeExplorer\CodeExplorerProjectViewModel.cs:line 36
   at Rubberduck.Navigation.CodeExplorer.CodeExplorerViewModel.<ParserState_StateChanged>b__f(IGrouping`2 grouping) in h:\Repositories\Rubberduck\RetailCoder.VBE\Navigation\CodeExplorer\CodeExplorerViewModel.cs:line 272
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Rubberduck.Navigation.CodeExplorer.CodeExplorerViewModel.ParserState_StateChanged(Object sender, ParserStateEventArgs e) in h:\Repositories\Rubberduck\RetailCoder.VBE\Navigation\CodeExplorer\CodeExplorerViewModel.cs:line 271
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Rubberduck.Parsing.VBA.RubberduckParserState.OnStateChanged(Object requestor, ParserState state) in h:\Repositories\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParserState.cs:line 309
   at Rubberduck.Parsing.VBA.RubberduckParserState.set_Status(ParserState value) in h:\Repositories\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParserState.cs:line 539
   at Rubberduck.Parsing.VBA.RubberduckParserState.SetStatusAndFireStateChanged(Object requestor, ParserState status) in h:\Repositories\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParserState.cs:line 552
   at Rubberduck.Parsing.VBA.ParseCoordinator.ExecuteCommonParseActivities(ICollection`1 toParse, CancellationToken token) in h:\Repositories\Rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:line 237
   at Rubberduck.Parsing.VBA.ParseCoordinator.ParseAllInternal(Object requestor, CancellationToken token) in h:\Repositories\Rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:line 743
   at Rubberduck.Parsing.VBA.ParseCoordinator.ParseAll(Object requestor, CancellationToken token) in h:\Repositories\Rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:line 680
```

**Comment by MDoerner** [comment]
I cannot repro this anymore. Probably, RD was in a bad state after encountering issue #2773.
