### ISSUE TITLE
The CodePane throws (hard crash) when the module in the active code pane gets removed. 

### ISSUE THREAD

**Issue by MDoerner** [rubberduck-vba/Rubberduck#2814]
Way to repro:

1. Open a project.
2. Open a module.
3. Remove that module via the ProjectExplorer.

**Comment by retailcoder** [comment]
Does the initial parse run? I can't reproduce this issue.

**Comment by comintern** [comment]
This seems to be a timing issue.  The failing code is in `CodePane`:
```
        public IWindow Window
        {
            get { return new Window(IsWrappingNullReference ? null : Target.Window); }
        }
```
Exception info:
```
System.Runtime.InteropServices.COMException was unhandled
  _HResult=-2147352560
  _message=Invalid callee. (Exception from HRESULT: 0x80020010 (DISP_E_BADCALLEE))
  HResult=-2147352560
  IsTransient=false
  Message=Invalid callee. (Exception from HRESULT: 0x80020010 (DISP_E_BADCALLEE))
  Source=Microsoft.Vbe.Interop
  ErrorCode=-2147352560
  StackTrace:
       at Microsoft.Vbe.Interop._CodePane.get_Window()
       at Rubberduck.VBEditor.SafeComWrappers.VBA.CodePane.get_Window() in c:\Work\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\CodePane.cs:line 27
       at Rubberduck.VBEditor.Events.VBENativeServices.<>c__DisplayClass5.<GetCodePaneFromHwnd>b__4(ICodePane x) in c:\Work\Rubberduck\Rubberduck.VBEEditor\Events\VBENativeServices.cs:line 174
       at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
       at Rubberduck.VBEditor.Events.VBENativeServices.GetCodePaneFromHwnd(IntPtr hwnd) in c:\Work\Rubberduck\Rubberduck.VBEEditor\Events\VBENativeServices.cs:line 174
       at Rubberduck.VBEditor.Events.VBENativeServices.OnSelectionChanged(IntPtr hwnd) in c:\Work\Rubberduck\Rubberduck.VBEEditor\Events\VBENativeServices.cs:line 157
       at Rubberduck.VBEditor.Events.VBENativeServices.VbeEventCallback(IntPtr hWinEventHook, UInt32 eventType, IntPtr hwnd, Int32 idObject, Int32 idChild, UInt32 dwEventThread, UInt32 dwmsEventTime) in c:\Work\Rubberduck\Rubberduck.VBEEditor\Events\VBENativeServices.cs:line 76
  InnerException: 
```
