### ISSUE TITLE
Exceptions following initial parse in GetInspectionResults()

### ISSUE THREAD

**Issue by BZngr** [rubberduck-vba/Rubberduck#2924]
A few days ago I indicated (in the war room) a fairly persistent exception immediately following the initial parse.  That was still the case for me this morning (I believe I have all the latest updates as of 3/22/2017).
So, based on the debug trace output, I ended up stubbing out the return values for GetInspectionResults() for two classes: MissingAnnotationArguementInspection and ObsoleteCallStatementInspection.  

MissingAnnotationArgumentInspection exception was: `Unable to cast object of type Rubberduck.Parsing.QualifiedContext1[Rubberduck.Parsing.Grammar.VBAParser+ArgListContext] to type Rubberduck.Parsing.QualifiedContext1[Rubberduck.Parsing.Grammar.VBAParser+AnnotationContext]`

The ObsoleteCallStatementInspection exception was: `Unable to cast object of type ArgListContext' to type 'CallStmtContext`

I imagine these casts (and their exceptions) may be specific to the content of the workbook that I am using.  That said, the workbook has two modules and five very small Subroutines for testing.  Very simple content.

With these two Inspection return values stubbed out, launching RD within Debug or standalone Excel is free of any exceptions following the initial parse.

**Comment by retailcoder** [comment]
Where are these casts occurring? Do you have a stack trace for them?

**Comment by retailcoder** [comment]
Can you share the code content? It looks like these two inspections could be passing the wrong `ParserRuleContext` somewhere, e.g. the called code expects an `ArgListContext` but we give it the `CallStmtContext`; this could be because there's an extra `.Parent` call somewhere... stack traces would be very helpful here.

**Comment by BZngr** [comment]
Please pardon the formatting:

Call stack: best reference is Inspector.cs line 79:
```
                var inspections = _inspections.Where(inspection => inspection.Severity != CodeInspectionSeverity.DoNotShow)
                    .Select(inspection =>
                        Task.Run(() =>
                        {
                            token.ThrowIfCancellationRequested();
                            var inspectionResults = inspection.GetInspectionResults();
                            
                            foreach (var inspectionResult in inspectionResults)
                            {
                                allIssues.Add(inspectionResult);
                            }
                        }, token)).ToList();


```
Debug output (partial - hopefully has the relevant content)

2017-03-22 08:07:26.5448;DEBUG;Rubberduck.Parsing.VBA.ParseCoordinator;Binding resolution done for component 'VBAProject.modOne' in 86ms (thread 9);
2017-03-22 08:07:26.5619;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'modOne' state is changing to 'Ready' (thread 9);
2017-03-22 08:07:28.4566;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;RubberduckParserState raised StateChanged (Ready);
Exception thrown: 'System.MissingMethodException' in mscorlib.dll
Exception thrown: 'System.MissingMethodException' in mscorlib.dll
Exception thrown: 'System.MissingMethodException' in mscorlib.dll
Exception thrown: 'System.MissingMethodException' in mscorlib.dll
Exception thrown: 'System.MissingMethodException' in mscorlib.dll
Exception thrown: 'System.MissingMethodException' in mscorlib.dll
Exception thrown: 'System.MissingMethodException' in mscorlib.dll
Exception thrown: 'System.MissingMethodException' in mscorlib.dll
Exception thrown: 'System.InvalidCastException' in System.Core.dll
System.InvalidCastException: Unable to cast object of type 'Rubberduck.Parsing.QualifiedContext`1[Rubberduck.Parsing.Grammar.VBAParser+ArgListContext]' to type 'Rubberduck.Parsing.QualifiedContext`1[Rubberduck.Parsing.Grammar.VBAParser+AnnotationContext]'.
   at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Rubberduck.Inspections.MissingAnnotationArgumentInspection.GetInspectionResults() in C:\Users\Brian\Documents\GitHub\VisualStudioProjects\Rubberduck\RetailCoder.VBE\Inspections\MissingAnnotationArgumentInspection.cs:line 38
   at (Object , Object[] )
   at Ninject.Extensions.Interception.Injection.Dynamic.DynamicMethodInjector.Invoke(Object target, Object[] arguments)
   at Ninject.Extensions.Interception.Invocation.Invocation.CallTargetMethod()
   at Ninject.Extensions.Interception.Invocation.InvocationBase.Proceed()
   at Rubberduck.Root.InterceptorBase.Intercept(IInvocation invocation) in C:\Users\Brian\Documents\GitHub\VisualStudioProjects\Rubberduck\RetailCoder.VBE\Root\InterceptorBase.cs:line 14Exception thrown: 'Rubberduck.Root.InterceptedException' in Rubberduck.dll
Rubberduck.Root.InterceptedException: Unable to cast object of type 'Rubberduck.Parsing.QualifiedContext`1[Rubberduck.Parsing.Grammar.VBAParser+ArgListContext]' to type 'Rubberduck.Parsing.QualifiedContext`1[Rubberduck.Parsing.Grammar.VBAParser+AnnotationContext]'. ---> System.InvalidCastException: Unable to cast object of type 'Rubberduck.Parsing.QualifiedContext`1[Rubberduck.Parsing.Grammar.VBAParser+ArgListContext]' to type 'Rubberduck.Parsing.QualifiedContext`1[Rubberduck.Parsing.Grammar.VBAParser+AnnotationContext]'.
   at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Rubberduck.Inspections.MissingAnnotationArgumentInspection.GetInspectionResults() in C:\Users\Brian\Documents\GitHub\VisualStudioProjects\Rubberduck\RetailCoder.VBE\Inspections\MissingAnnotationArgumentInspection.cs:line 38
   at (Object , Object[] )

```
```

**Comment by BZngr** [comment]
The example is for MissingAnnotationArguementInspection.  The RD code (including my commented-out work-around:

```
        public override IEnumerable<IInspectionResult> GetInspectionResults()
        {
            //return new InspectionResultBase[] { };
            if (_parseTreeResults == null)
            {
                return new InspectionResultBase[] { };
            }

            return (from result in _parseTreeResults.Cast<QualifiedContext<VBAParser.AnnotationContext>>()
                    let context = result.Context 
                    where context.annotationName().GetText() == AnnotationType.Ignore.ToString() 
                       || context.annotationName().GetText() == AnnotationType.Folder.ToString() 
                    where context.annotationArgList() == null 
                    select new MissingAnnotationArgumentInspectionResult(this, result)).ToList();
        }

```

**Comment by retailcoder** [comment]
Seems all `IParseTreeInspection` implementations have somehow come to work off the same inspection results:

![image](https://cloud.githubusercontent.com/assets/5751684/24205426/c3eec40e-0ef1-11e7-8e12-b0b0e1594c67.png)

@Hosch250 did you have a fix for this already?

The fix would be simply to replace `_parseTreeResults.Cast<QualifiedContext<VBAParser.AnnotationContext>>()` with `_parseTreeResults.OfType<QualifiedContext<VBAParser.AnnotationContext>>()`.

**Comment by BZngr** [comment]
Similar Debug trace content for ObsoleteCallStatementInspection:

2017-03-22 08:25:59.3211;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'modOne' state is changing to 'Ready' (thread 18);
2017-03-22 08:26:01.2683;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;RubberduckParserState raised StateChanged (Ready);
Exception thrown: 'System.MissingMethodException' in mscorlib.dll
Exception thrown: 'System.MissingMethodException' in mscorlib.dll
Exception thrown: 'System.MissingMethodException' in mscorlib.dll
Exception thrown: 'System.MissingMethodException' in mscorlib.dll
Exception thrown: 'System.MissingMethodException' in mscorlib.dll
Exception thrown: 'System.MissingMethodException' in mscorlib.dll
Exception thrown: 'System.MissingMethodException' in mscorlib.dll
Exception thrown: 'System.MissingMethodException' in mscorlib.dll
Exception thrown: 'System.InvalidCastException' in Rubberduck.dll
System.InvalidCastException: Unable to cast object of type 'ArgListContext' to type 'CallStmtContext'.
   at Rubberduck.Inspections.ObsoleteCallStatementInspection.GetInspectionResults() in C:\Users\Brian\Documents\GitHub\VisualStudioProjects\Rubberduck\RetailCoder.VBE\Inspections\ObsoleteCallStatementInspection.cs:line 55
   at (Object , Object[] )
   at Ninject.Extensions.Interception.Injection.Dynamic.DynamicMethodInjector.Invoke(Object target, Object[] arguments)
   at Ninject.Extensions.Interception.Invocation.Invocation.CallTargetMethod()
   at Ninject.Extensions.Interception.Invocation.InvocationBase.Proceed()
   at Rubberduck.Root.InterceptorBase.Intercept(IInvocation invocation) in C:\Users\Brian\Documents\GitHub\VisualStudioProjects\Rubberduck\RetailCoder.VBE\Root\InterceptorBase.cs:line 14Exception thrown: 'Rubberduck.Root.InterceptedException' in Rubberduck.dll
Rubberduck.Root.InterceptedException: Unable to cast object of type 'ArgListContext' to type 'CallStmtContext'. ---> System.InvalidCastException: Unable to cast object of type 'ArgListContext' to type 'CallStmtContext'.
   at Rubberduck.Inspections.ObsoleteCallStatementInspection.GetInspectionResults() in C:\Users\Brian\Documents\GitHub\VisualStudioProjects\Rubberduck\RetailCoder.VBE\Inspections\ObsoleteCallStatementInspection.cs:line 55
   at (Object , Object[] )
   at Ninject.Extensions.Interception.Injection.Dynamic.DynamicMethodInjector.Invoke(Object target, Object[] arguments)
   at Ninject.Extensions.Interception.Invocation.Invocation.CallTargetMethod()
   at Ninject.Extensions.Interception.Invocation.InvocationBase.Proceed()
   at Rubberduck.Root.InterceptorBase.Intercept(IInvocation invocation) in C:\Users\Brian\Documents\GitHub\VisualStudioProjects\Rubberduck\RetailCoder.VBE\Root\InterceptorBase.cs:line 14
   --- End of inner exception stack trace ---
   at Rubberduck.Root.InterceptorBase.OnError(IInvocation invocation, Exception exception) in C:\Users\Brian\Documents\GitHub\VisualStudioProjects\Rubberduck\RetailCoder.VBE\Root\InterceptorBase.cs:line 33
   at Rubberduck.Root.InterceptorBase.Intercept(IInvocation invocation) in C:\Users\Brian\Documents\GitHub\VisualStudioProjects\Rubberduck\RetailCoder.VBE\Root\InterceptorBase.cs:line 18
   at Ninject.Extensions.Interception.Invocation.InvocationBase.Proceed()
   at Rubberduck.Root.InterceptorBase.Intercept(IInvocation invocation) in C:\Users\Brian\Documents\GitHub\VisualStudioProjects\Rubberduck\RetailCoder.VBE\Root\InterceptorBase.cs:line 14Exception thrown: 'Rubberduck.Root.InterceptedException' in Rubberduck.dll
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\WINDOWS\assembly\GAC_MSIL\Microsoft.VisualStudio.Debugger.Runtime\14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.Debugger.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The program '[13596] EXCEL.EXE' has exited with code -1 (0xffffffff).

**Comment by retailcoder** [comment]
Same problem. Line 55 in `ObsoleteCallStatementInspection` is casting parse tree inspection results to a specific type that isn't valid for everything in that list.

The fix would be on [line 38](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/Inspections/ObsoleteCallStatementInspection.cs#L38):

    foreach (var context in _parseTreeResults.Where(context => !IsIgnoringInspectionResultFor(context.ModuleName.Component, context.Context.Start.Line)))

Adding a `.OfType(QualifiedContext<CallStmtContext>)` before that `.Where` call would fix the problem.

All `IParseTreeInspection` implementations need to be looked at.

**Comment by Hosch250** [comment]
@retailcoder Well, what the working ones seem to be doing is defining a `ParseResults` that returns the limited set and using that everywhere. However, I'm still not sure why any inspection has access to other inspections' results.

**Comment by retailcoder** [comment]
@Hosch250 only `IParseTreeInspection` implementations do, and only because of how parse tree results are being assigned to the inspections with the `CombinedParseTreeListener`, but I can't seem to find a specific commit that broke it. :confused:

**Comment by Hosch250** [comment]
Well, just fix it when you rearrange the inspections, will you?

**Comment by rubberduck203** [comment]
@retailcoder have you tried a `git bisect`?
