### ISSUE TITLE
Does not seem to work properly when un-registered .xlam addins are loaded

### ISSUE THREAD

**Issue by AndreMuraro** [rubberduck-vba/Rubberduck#2940]
I have an .xlam addin installed through excel´s normal addin interface, which loads a list of other addins which are un-registered. Whenever any of these un-registered .xlams are loaded, Rubberduck does not seem to parse any projects at all, and the code explorer remains blank. 
 - It seems to be able to parse the registered .xlam. Loading an un-registered version of it causes the bug to happen.
 - All other files work fine, as long as no un-registered .xlams are loaded. When on is loaded, the project explorer still shows the previously opened files, but does not detect new changes to them.
 - The .xlams are password protected, but removing protection does not solve it. As long as all un-registered .xlams are protected, Rubberduck works fine.
 - There are no parse error messages in the IDE. 

I annexed the only error log that was displayed during testing, while closing the excel instance.

[Error Log.txt](https://github.com/rubberduck-vba/Rubberduck/files/883283/Error.Log.txt)

**Comment by retailcoder** [comment]
````
System.Runtime.InteropServices.COMException (0x800A01A8): Exception from HRESULT: 0x800A01A8
   at Microsoft.Vbe.Interop.VBProjectClass.get_HelpFile()
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBProject.get_HelpFile() in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBProject.cs:line 30
   at Rubberduck.UI.Command.ShowParserErrorsCommand.FindModuleDeclaration(IVBComponent component) in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\RetailCoder.VBE\UI\Command\ShowParserErrorsCommand.cs:line 113
   at Rubberduck.UI.Command.ShowParserErrorsCommand.<CreateViewModel>b__8_0(Tuple`2 error) in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\RetailCoder.VBE\UI\Command\ShowParserErrorsCommand.cs:line 99
````

That exception was thrown after clicking the `ShowParserErrors` command button. It's helpful in the sense that it tells us that `VBProjectClass.get_HelpFile()` is throwing a COM exception, but it's not necessarily what happened during the parse.

Bring up Rubberduck's settings dialog, and make sure logging is enabled - `ERROR` level should be good enough. Then reproduce the parser error, and inspect Rubberduck's log, which is saved under `%appdata%\Rubberduck\logs` (if you put minimum log level to `TRACE` the file should be pretty verbose) - if we're lucky we'll be looking at a different exception.

Rubberduck needs a way to reliably identify projects. And since VBA projects can be unsaved, the file name can't be used (the VBIDE API actually throws an exception if you try to get the file name of an unsaved project... thanks Microsoft). And since the VBE can very well have 12 different projects named `VBAProject1`, the project's name is pretty much useless. And since COM interop gives us a different hash code for the same object reference depending on the alignment of the stars in the Milky Way (seriously!), we're down to getting quite creative in order to correctly identify a specific `VBAProject` object (which is... well, kinda fundamental for everything we need to do!).

The solution we've found was to store the first hash code we get for a `VBProject` object, into its `HelpFile` property (nobody uses that, right?). You can *see* that value in the *project properties* - *changing* that value will *definitely* break something in Rubberduck though.

The exception above seems to indicate that the `HelpFile` property couldn't be *read* - I suspect there's something else going on, but only the actual RD log would contain the information about it.

**Comment by AndreMuraro** [comment]
Here´s the Log after loading an unregistered addin and unprotecting it, at ERROR level

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/883716/RubberduckLog.txt)

**Comment by Vogel612** [comment]
duplicates #2931

**Comment by retailcoder** [comment]
Interesting. It has apparently nothing to do with the add-in being registered or not (wait a minute, was it *protected*? RD isn't *supposed* to even *look* at protected VBA projects...)

````
2017-03-30 17:22:54.8239;ERROR-2.0.13.32288;Rubberduck.Parsing.VBA.ComponentParseTask;Exception thrown in thread 15, ParseTaskID ea44512c-515f-4504-b0ec-2f55d90e975b.;System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Rubberduck.Parsing.Preprocessing.LivelinessExpression.MarkAsDead(String code) in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.Parsing\Preprocessing\LivelinessExpression.cs:line 26
   at Rubberduck.Parsing.Preprocessing.LivelinessExpression.Evaluate() in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.Parsing\Preprocessing\LivelinessExpression.cs:line 21
   at Rubberduck.Parsing.Preprocessing.ConditionalCompilationIfExpression.Evaluate() in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.Parsing\Preprocessing\ConditionalCompilationIfExpression.cs:line 48
   at Rubberduck.Parsing.Preprocessing.ConditionalCompilationBlockExpression.<>c.<Evaluate>b__2_0(IExpression child) in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.Parsing\Preprocessing\ConditionalCompilationBlockExpression.cs:line 17
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at Rubberduck.Parsing.Preprocessing.ConditionalCompilationBlockExpression.Evaluate() in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.Parsing\Preprocessing\ConditionalCompilationBlockExpression.cs:line 17
   at Rubberduck.Parsing.Preprocessing.VBAPreprocessor.Execute(String moduleName, String unprocessedCode, CancellationToken token) in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.Parsing\Preprocessing\VBAPreprocessor.cs:line 24
   at Rubberduck.Parsing.VBA.ComponentParseTask.RewriteAndPreprocess(CancellationToken token) in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.Parsing\VBA\ComponentParseTask.cs:line 184
   at Rubberduck.Parsing.VBA.ComponentParseTask.Start(CancellationToken token) in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.Parsing\VBA\ComponentParseTask.cs:line 51
````

It's the preprocessing step that's blowing up with an `ArgumentOutOfRangeException` while marking a block of conditionally-compiled code as "dead".

Here's the faulting method:

````csharp
        private string MarkAsDead(string code)
        {
            var hasNewLine = code.EndsWith(Environment.NewLine);
            // Remove parsed new line.
            code = code.Substring(0, code.Length - Environment.NewLine.Length);
            var lines = code.Split(new[] { Environment.NewLine }, StringSplitOptions.None);
            var result = string.Join(Environment.NewLine, lines.Select(_ => string.Empty));
            if (hasNewLine)
            {
                result += Environment.NewLine;
            }
            return result;
        }
````

More specifically, this instruction:

    code = code.Substring(0, code.Length - Environment.NewLine.Length);

Looks like a pretty easy thing to fix - we assume `code.Length` is greater than or equal to `Environment.NewLine.Length` (...which *should* be a safe assumption to make)... but sure how `code.Length` could be less than `Environment.NewLine.Length`, but it seems to be the case anyway - so we need to make that instruction conditional to `hasNewLine`.

I'd love to have a unit test for that case though. No idea how it could happen.

**Comment by retailcoder** [comment]
This indeeds duplicates an already-reported issue. Thanks!
