### ISSUE TITLE
SyntaxErrorException with multiple spaces between array decalration's bounds and As keyword

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2950]
The exception is confined to the log file, and the module ends up parsing, but a module level and procedure level array declaration both encounter the exception - although **the exact error detail differs according to the scope of the declaration**:

The exceptions don't occur if there is only a single space between the `)` and `As`:

```vb
Dim Foo1(0 To 3) As Long
```

But do occur with 2 or more spaces
```vb
Dim Foo1(0 To 3)    As Long
```

**Module 1 - Procedure level array declaration**
```vb
Option Explicit

'Dim Foo1(0 To 3)       As Long


Sub Test()
    Dim Foo2(0 To 3)       As Long
End Sub
```

**Trace Log**
```text
2017-04-08 22:17:12.8109;DEBUG-2.0.14.39296;Rubberduck.Parsing.Symbols.SyntaxErrorException;;
2017-04-08 22:17:12.8109;DEBUG-2.0.14.39296;Rubberduck.Parsing.Symbols.SyntaxErrorException;Token: Long (L8C31);
2017-04-08 22:17:12.8190;WARN-2.0.14.39296;Rubberduck.Parsing.VBA.VBAModuleParser;SLL mode failed in module Module2. Retrying using LL.;Rubberduck.Parsing.Symbols.SyntaxErrorException: extraneous input 'Long' expecting {':', WS, LINE_CONTINUATION}
   at Rubberduck.Parsing.Symbols.ExceptionErrorListener.SyntaxError(IRecognizer recognizer, IToken offendingSymbol, Int32 line, Int32 charPositionInLine, String msg, RecognitionException e) in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Symbols\ExceptionErrorListener.cs:line 10
   at Antlr4.Runtime.ProxyErrorListener`1.SyntaxError(IRecognizer recognizer, Symbol offendingSymbol, Int32 line, Int32 charPositionInLine, String msg, RecognitionException e)
   at Antlr4.Runtime.Parser.NotifyErrorListeners(IToken offendingToken, String msg, RecognitionException e)
   at Antlr4.Runtime.DefaultErrorStrategy.ReportUnwantedToken(Parser recognizer)
   at Antlr4.Runtime.DefaultErrorStrategy.Sync(Parser recognizer)
   at Rubberduck.Parsing.Grammar.VBAParser.whiteSpace() in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 19433
   at Rubberduck.Parsing.Grammar.VBAParser.identifierStatementLabel() in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 15270
   at Rubberduck.Parsing.Grammar.VBAParser.statementLabelDefinition() in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 15202
   at Rubberduck.Parsing.Grammar.VBAParser.blockStmt() in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1701
   at Rubberduck.Parsing.Grammar.VBAParser.block() in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1537
   at Rubberduck.Parsing.Grammar.VBAParser.subStmt() in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 11309
   at Rubberduck.Parsing.Grammar.VBAParser.moduleBodyElement() in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1473
   at Rubberduck.Parsing.Grammar.VBAParser.moduleBody() in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1377
   at Rubberduck.Parsing.Grammar.VBAParser.module() in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 354
   at Rubberduck.Parsing.Grammar.VBAParser.startRule() in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 264
   at Rubberduck.Parsing.VBA.VBAModuleParser.Parse(String moduleName, String moduleCode, IParseTreeListener[] listeners, BaseErrorListener errorListener, ITokenStream& outStream) in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\VBA\VBAModuleParser.cs:line 25
2017-04-08 22:17:12.8470;DEBUG-2.0.14.39296;Rubberduck.Parsing.Symbols.SyntaxErrorException;;
2017-04-08 22:17:12.8470;DEBUG-2.0.14.39296;Rubberduck.Parsing.Symbols.SyntaxErrorException;Token: Long (L7C31);
2017-04-08 22:17:12.8470;WARN-2.0.14.39296;Rubberduck.Parsing.VBA.VBAModuleParser;SLL mode failed in module Module2. Retrying using LL.;Rubberduck.Parsing.Symbols.SyntaxErrorException: extraneous input 'Long' expecting {':', WS, LINE_CONTINUATION}
   at Rubberduck.Parsing.Symbols.ExceptionErrorListener.SyntaxError(IRecognizer recognizer, IToken offendingSymbol, Int32 line, Int32 charPositionInLine, String msg, RecognitionException e) in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Symbols\ExceptionErrorListener.cs:line 10
   at Antlr4.Runtime.ProxyErrorListener`1.SyntaxError(IRecognizer recognizer, Symbol offendingSymbol, Int32 line, Int32 charPositionInLine, String msg, RecognitionException e)
   at Antlr4.Runtime.Parser.NotifyErrorListeners(IToken offendingToken, String msg, RecognitionException e)
   at Antlr4.Runtime.DefaultErrorStrategy.ReportUnwantedToken(Parser recognizer)
   at Antlr4.Runtime.DefaultErrorStrategy.Sync(Parser recognizer)
   at Rubberduck.Parsing.Grammar.VBAParser.whiteSpace() in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 19433
   at Rubberduck.Parsing.Grammar.VBAParser.identifierStatementLabel() in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 15270
   at Rubberduck.Parsing.Grammar.VBAParser.statementLabelDefinition() in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 15202
   at Rubberduck.Parsing.Grammar.VBAParser.blockStmt() in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1701
   at Rubberduck.Parsing.Grammar.VBAParser.block() in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1537
   at Rubberduck.Parsing.Grammar.VBAParser.subStmt() in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 11309
   at Rubberduck.Parsing.Grammar.VBAParser.moduleBodyElement() in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1473
   at Rubberduck.Parsing.Grammar.VBAParser.moduleBody() in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1377
   at Rubberduck.Parsing.Grammar.VBAParser.module() in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 354
   at Rubberduck.Parsing.Grammar.VBAParser.startRule() in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 264
   at Rubberduck.Parsing.VBA.VBAModuleParser.Parse(String moduleName, String moduleCode, IParseTreeListener[] listeners, BaseErrorListener errorListener, ITokenStream& outStream) in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\VBA\VBAModuleParser.cs:line 25
2017-04-08 22:17:12.8821;DEBUG-2.0.14.39296;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Module2' state is changing to 'Parsed' (thread 20);
```

**Module 1 - Module level array declaration**
```vb
Option Explicit

Dim Foo1(0 To 3)       As Long


Sub Test()
'    Dim Foo2(0 To 3)       As Long
End Sub
```

**Trace Log**
```text
2017-04-08 22:24:54.4068;DEBUG-2.0.14.39296;Rubberduck.Parsing.Symbols.SyntaxErrorException;;
2017-04-08 22:24:54.4108;DEBUG-2.0.14.39296;Rubberduck.Parsing.Symbols.SyntaxErrorException;Token: As (L4C24);
2017-04-08 22:24:54.4108;WARN-2.0.14.39296;Rubberduck.Parsing.VBA.VBAModuleParser;SLL mode failed in module Module2. Retrying using LL.;Rubberduck.Parsing.Symbols.SyntaxErrorException: extraneous input 'As' expecting {<EOF>, ':', ATTRIBUTE, BEGIN, CONST, DECLARE, DEFBOOL, DEFBYTE, DEFDATE, DEFDBL, DEFCUR, DEFINT, DEFLNG, DEFLNGLNG, DEFLNGPTR, DEFOBJ, DEFSNG, DEFSTR, DEFVAR, DIM, ENUM, EVENT, FRIEND, FUNCTION, GLOBAL, IMPLEMENTS, OPTION_BASE, OPTION_EXPLICIT, OPTION_COMPARE, OPTION_PRIVATE_MODULE, PRIVATE, PROPERTY_GET, PROPERTY_LET, PROPERTY_SET, PUBLIC, REM, STATIC, SUB, TYPE, VERSION, NEWLINE, ''', WS, LINE_CONTINUATION}
   at Rubberduck.Parsing.Symbols.ExceptionErrorListener.SyntaxError(IRecognizer recognizer, IToken offendingSymbol, Int32 line, Int32 charPositionInLine, String msg, RecognitionException e) in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Symbols\ExceptionErrorListener.cs:line 10
   at Antlr4.Runtime.ProxyErrorListener`1.SyntaxError(IRecognizer recognizer, Symbol offendingSymbol, Int32 line, Int32 charPositionInLine, String msg, RecognitionException e)
   at Antlr4.Runtime.Parser.NotifyErrorListeners(IToken offendingToken, String msg, RecognitionException e)
   at Antlr4.Runtime.DefaultErrorStrategy.ReportUnwantedToken(Parser recognizer)
   at Antlr4.Runtime.DefaultErrorStrategy.SingleTokenDeletion(Parser recognizer)
   at Antlr4.Runtime.DefaultErrorStrategy.Sync(Parser recognizer)
   at Rubberduck.Parsing.Grammar.VBAParser.endOfStatement() in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 18521
   at Rubberduck.Parsing.Grammar.VBAParser.moduleDeclarations() in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 990
   at Rubberduck.Parsing.Grammar.VBAParser.module() in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 352
   at Rubberduck.Parsing.Grammar.VBAParser.startRule() in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 264
   at Rubberduck.Parsing.VBA.VBAModuleParser.Parse(String moduleName, String moduleCode, IParseTreeListener[] listeners, BaseErrorListener errorListener, ITokenStream& outStream) in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\VBA\VBAModuleParser.cs:line 25
2017-04-08 22:24:54.4509;DEBUG-2.0.14.39296;Rubberduck.Parsing.Symbols.SyntaxErrorException;;
2017-04-08 22:24:54.4560;DEBUG-2.0.14.39296;Rubberduck.Parsing.Symbols.SyntaxErrorException;Token: As (L3C24);
2017-04-08 22:24:54.4560;WARN-2.0.14.39296;Rubberduck.Parsing.VBA.VBAModuleParser;SLL mode failed in module Module2. Retrying using LL.;Rubberduck.Parsing.Symbols.SyntaxErrorException: extraneous input 'As' expecting {<EOF>, ':', ATTRIBUTE, BEGIN, CONST, DECLARE, DEFBOOL, DEFBYTE, DEFDATE, DEFDBL, DEFCUR, DEFINT, DEFLNG, DEFLNGLNG, DEFLNGPTR, DEFOBJ, DEFSNG, DEFSTR, DEFVAR, DIM, ENUM, EVENT, FRIEND, FUNCTION, GLOBAL, IMPLEMENTS, OPTION_BASE, OPTION_EXPLICIT, OPTION_COMPARE, OPTION_PRIVATE_MODULE, PRIVATE, PROPERTY_GET, PROPERTY_LET, PROPERTY_SET, PUBLIC, REM, STATIC, SUB, TYPE, VERSION, NEWLINE, ''', WS, LINE_CONTINUATION}
   at Rubberduck.Parsing.Symbols.ExceptionErrorListener.SyntaxError(IRecognizer recognizer, IToken offendingSymbol, Int32 line, Int32 charPositionInLine, String msg, RecognitionException e) in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Symbols\ExceptionErrorListener.cs:line 10
   at Antlr4.Runtime.ProxyErrorListener`1.SyntaxError(IRecognizer recognizer, Symbol offendingSymbol, Int32 line, Int32 charPositionInLine, String msg, RecognitionException e)
   at Antlr4.Runtime.Parser.NotifyErrorListeners(IToken offendingToken, String msg, RecognitionException e)
   at Antlr4.Runtime.DefaultErrorStrategy.ReportUnwantedToken(Parser recognizer)
   at Antlr4.Runtime.DefaultErrorStrategy.SingleTokenDeletion(Parser recognizer)
   at Antlr4.Runtime.DefaultErrorStrategy.Sync(Parser recognizer)
   at Rubberduck.Parsing.Grammar.VBAParser.endOfStatement() in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 18521
   at Rubberduck.Parsing.Grammar.VBAParser.moduleDeclarations() in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 990
   at Rubberduck.Parsing.Grammar.VBAParser.module() in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 352
   at Rubberduck.Parsing.Grammar.VBAParser.startRule() in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 264
   at Rubberduck.Parsing.VBA.VBAModuleParser.Parse(String moduleName, String moduleCode, IParseTreeListener[] listeners, BaseErrorListener errorListener, ITokenStream& outStream) in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.Parsing\VBA\VBAModuleParser.cs:line 25
2017-04-08 22:24:54.4911;DEBUG-2.0.14.39296;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Module2' state is changing to 'Parsed' (thread 36);
```

**Comment by ThunderFrame** [comment]
TIL - VBE will remove extra spaces in a `Redim` statement, but not in a `Dim` statement.

**Comment by retailcoder** [comment]
Should be an easy fix: https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Parsing/Grammar/VBAParser.g4#L509

    variableSubStmt : identifier (whiteSpace? LPAREN whiteSpace? (subscripts whiteSpace?)? RPAREN whiteSpace?)? (whiteSpace asTypeClause)?;

The last part `(whiteSpace asTypeClause)?` should be `(whiteSpace+ asTypeClause)?`

**Comment by MDoerner** [comment]
Is this bug still there?

The proposed solution does not change the matching at all. A `whiteSpace` already represents a stretch of consecutive `WS` and `LINE_CONTIUATION` tokens.

**Comment by MDoerner** [comment]
I think the SLL errors here stem fromthe fact that the `whiteSpace?` after the `RPAREN` already consumes all whitespace. Then, the parser has to back out of consuming all in `whiteSpace` because it cannot match the one preceding `asTypeClause` anymore. However, the SLL mode parser cannot back out of a decision already made.
