### ISSUE TITLE
Inspection error in the logs

### ISSUE THREAD

**Issue by MDoerner** [rubberduck-vba/Rubberduck#2974]
Since a few PRs back, I consistently see the following error in the log file.

```
2017-04-16 00:58:25.8893;ERROR-2.0.14.1489;Rubberduck.Inspections.Rubberduck.Inspections.Inspector+<FindIssuesAsync>d__6;Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at CallSite.Target(Closure , CallSite , Object )
   at Rubberduck.Inspections.Concrete.VariableNotUsedInspection.<GetInspectionResults>b__3_2(Declaration issue)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Rubberduck.Inspections.Rubberduck.Inspections.Inspector.<>c__DisplayClass6_1.<FindIssuesAsync>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Rubberduck.Inspections.Rubberduck.Inspections.Inspector.<FindIssuesAsync>d__6.MoveNext();
```

**Comment by retailcoder** [comment]
Fixed?

**Comment by MDoerner** [comment]
Fixed
