### ISSUE TITLE
Parsing issue: Library not registered

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#3058]
Added a reference to Microsoft_Hpc_Excel and the parser comes up with the following error.
```
2017-06-09 13:17:23.2184;ERROR-2.0.13.32288;Rubberduck.Parsing.VBA.ParseCoordinator;Unexpected exception thrown in parsing run. (thread 30).;System.Runtime.InteropServices.COMException (0x8002801D): Library not registered. (Exception from HRESULT: 0x8002801D (TYPE_E_LIBNOTREGISTERED))
   at Microsoft.Vbe.Interop.Reference.get_FullPath()
   at Rubberduck.VBEditor.SafeComWrappers.VBA.Reference.get_FullPath() in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\Reference.cs:line 45
   at Rubberduck.VBEditor.QualifiedModuleName.GetProjectId(IReference reference) in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.VBEEditor\QualifiedModuleName.cs:line 31
   at Rubberduck.Parsing.VBA.ParseCoordinator.GetReferenceProjectId(IReference reference, IReadOnlyList`1 projects) in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:line 804
   at Rubberduck.Parsing.VBA.ParseCoordinator.GetReferencesToLoadAndSaveReferencePriority(IReadOnlyList`1 projects) in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:line 912
   at Rubberduck.Parsing.VBA.ParseCoordinator.SyncComReferences(IReadOnlyList`1 projects, CancellationToken token) in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:line 841
   at Rubberduck.Parsing.VBA.ParseCoordinator.ExecuteCommonParseActivities(ICollection`1 toParse, CancellationToken token) in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:line 201
   at Rubberduck.Parsing.VBA.ParseCoordinator.ParseAllInternal(Object requestor, CancellationToken token) in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:line 749
   at Rubberduck.Parsing.VBA.ParseCoordinator.ParseAll(Object requestor, CancellationToken token) in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:line 682
```

**Comment by retailcoder** [comment]
Nice catch. Looks like `Rubberduck.Parsing.VBA.ParseCoordinator.GetReferenceProjectId` needs a `try/catch` block to cleanly handle `HRESULT: 0x8002801D`.

**Comment by MDoerner** [comment]
It is no longer in the `ParseCoordinator`. It is now in the `COMReferenceSynchronizerBase`.

**Comment by MDoerner** [comment]
I think the problem is rather with `Rubberduck.VBEditor.SafeComWrappers.VBA.Reference`, which is the wrapper that cannot handle unregistered references. This is also the natural place where to decide what to return as `FullName` in case of the exception. (Probably the same as when `IsBroken` is true on the reference, i.e. ` string.Empty`.)

**Comment by FrankHentzschel** [comment]
I just tried with a simple new project. Only with dummy function to test.

I fI use late binding for unit tests, I have no error. But if I use early binding I get the parse error.

That means at the moment early bindng does not work? And I cannot use intellisense for Assert-Object in my testmodules.

Does anyone knows a solution?

**Comment by retailcoder** [comment]
@FrankHentzschel ok I know what that is - there's a known issue involving a possible COM exception resulting in a parse error when the Rubberduck type library is referenced; the error can't be reliably reproduced, but it does prevent a successful parse on systems where it happens.

We need to exclude the RD type library from the reference loader, *and* somehow still have a `Declaration` for every exposed type, member and parameter. A [rather annoying] work-around would be to reference the Rubberduck type library only when writing the tests, and switch to late-binding to parse and/or run the tests. One way to make that switching easier would be to have a commented-out late-bound declaration for the `AssertClass`:

    Private Assert As Rubberduck.AssertClass
    'Private Assert As Object

And then commented-out initialization code:

    Set Assert = New Rubberduck.AssertClass
    'Set Assert = CreateObject("Rubberduck.AssertClass")

We'll definitely have that fixed for next release.

**Comment by retailcoder** [comment]
@MDoerner I wonder if that might also fix the COM exception that's sometimes thrown when the RD typelib is loaded... but then why wouldn't it be registered properly? Hmmm...

**Comment by IvenBach** [comment]
What's the difficulty on this to fix? This is quickly rising to the top of my fix list.

**Comment by Vogel612** [comment]
@rubberduck-vba/dev is this still open?

**Comment by retailcoder** [comment]
@Vogel612 yup.

**Comment by IvenBach** [comment]
Tested and COMException is taken care of.

**Comment by simonk83** [comment]
I'm still getting this error with the lastest master and the latest dev release.

``2018-10-10 15:15:57.5979;ERROR-2.2.0.3939;Rubberduck.Parsing.VBA.ParseCoordinator;Unexpected exception thrown in parsing run. (thread 31).;System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Office.Core.CommandBarControl'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{000C0308-0000-0000-C000-000000000046}' failed due to the following error: Library not registered. (Exception from HRESULT: 0x8002801D (TYPE_E_LIBNOTREGISTERED)).``

Anything I can do to get this going?
