### ISSUE TITLE
Status bar assignment with long procedure name causes unhandled exception

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#3083]
I created a procedure name with 180 characters in a module named with 31 characters, got this exception when placing the cursor within the procedure body:

```text
System.ArgumentException: Value does not fall within the expected range.
   at Microsoft.Office.Core.CommandBarControl.set_Caption(String pbstrCaption)
   at Rubberduck.VBEditor.SafeComWrappers.Office.Core.CommandBarControl.set_Caption(String value) in C:\Users\Andrew\Documents\GitHub\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\Office.Core\CommandBarControl.cs:line 28
   at Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase.<>c__DisplayClass6_0.<Localize>b__0() in C:\Users\Andrew\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\MenuItems\CommandBars\AppCommandBarBase.cs:line 46
   at Rubberduck.UI.Command.MenuItems.UiDispatcher.<>c__DisplayClass5_0.<InvokeAsync>b__0(Object x) in C:\Users\Andrew\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\MenuItems\UiDispatcher.cs:line 29
```

Seems like there's an upper limit on the length of a `CommandBarButton.Caption`

**Comment by ThunderFrame** [comment]
Duplicate of #3082 - should have read the history :-(
