### ISSUE TITLE
Empty Conditional Compilation block throws System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#3093]
Here is the code that can generate the error and how to avoid it:

```vba
Option Explicit

' an empty #IF clause causes RD to throw an error System.ArgumentOutOfRangeException: Length cannot be less than zero.
#If Mac Then
#else
   ' this construct is to avoid problems from #If Not failing because it's a number 1 not a boolean
   'Source:
   'https://answers.microsoft.com/en-us/msoffice/wiki/msoffice_word-mso_other/that-whacky-conditional-compiler-constant/3da810b8-9b89-4372-8104-a10c2ad25d4d
#End If

'Rubberduck is OK with a non empty block
#If Mac Then
   ' Do Mac stuff
#Else
   ' Do Windows stuff
#End If

#If Mac = 0 Then
   ' this construct is to avoid problems from #If Not failing because it's a number 1 not a boolean
#End If
``` 

Now about the error trace itself: It would be helpful if Starting Parse reported the module it was working on, in this case `frmQueryDB`
And if it reported the module line number where the exception was thrown.

```
2017-06-30 09:36:34.8718;TRACE-2.0.13.32288;Rubberduck.Parsing.VBA.ComponentParseTask;Starting ParseTaskID 76d9ae46-287b-4c38-88f2-2ef649032244 on thread 15.;
2017-06-30 09:36:34.9128;ERROR-2.0.13.32288;Rubberduck.Parsing.VBA.ComponentParseTask;Exception thrown in thread 15, ParseTaskID 76d9ae46-287b-4c38-88f2-2ef649032244.;System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Rubberduck.Parsing.Preprocessing.LivelinessExpression.MarkAsDead(String code) in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.Parsing\Preprocessing\LivelinessExpression.cs:line 26
   at Rubberduck.Parsing.Preprocessing.LivelinessExpression.Evaluate() in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.Parsing\Preprocessing\LivelinessExpression.cs:line 21
   at Rubberduck.Parsing.Preprocessing.ConditionalCompilationIfExpression.Evaluate() in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.Parsing\Preprocessing\ConditionalCompilationIfExpression.cs:line 48
   at Rubberduck.Parsing.Preprocessing.ConditionalCompilationBlockExpression.<>c.<Evaluate>b__2_0(IExpression child) in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.Parsing\Preprocessing\ConditionalCompilationBlockExpression.cs:line 17
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at Rubberduck.Parsing.Preprocessing.ConditionalCompilationBlockExpression.Evaluate() in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.Parsing\Preprocessing\ConditionalCompilationBlockExpression.cs:line 17
   at Rubberduck.Parsing.Preprocessing.VBAPreprocessor.Execute(String moduleName, String unprocessedCode, CancellationToken token) in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.Parsing\Preprocessing\VBAPreprocessor.cs:line 24
   at Rubberduck.Parsing.VBA.ComponentParseTask.RewriteAndPreprocess(CancellationToken token) in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.Parsing\VBA\ComponentParseTask.cs:line 184
   at Rubberduck.Parsing.VBA.ComponentParseTask.Start(CancellationToken token) in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.Parsing\VBA\ComponentParseTask.cs:line 51

2017-06-30 09:36:34.9938;DEBUG-2.0.13.32288;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'frmQueryDB' state is changing to 'Error' (thread 15);
```

**Comment by MDoerner** [comment]
I will have a look at this tonight. 
Judging from the log entry, this is on the release build 2.0.13. So, it might be that this has been resolved already as part of the changes to the preprocessor since then. 

Regarding the suggestions for the log entries, I agree that adding the component name to the log message would make sense. However, adding the line of code is basically impossible because any exception but the syntax exceptions from antlr have no idea about the code of the module.

**Comment by MDoerner** [comment]
I just tested it on the current development build: with the new preprocessor, this problem does not exist anymore.
