### ISSUE TITLE
Parse Error & Crash on close (HRESULT: 0x800A01A8) in next branch v2.1.1981

### ISSUE THREAD

**Issue by A9G-Data-Droid** [rubberduck-vba/Rubberduck#3145]
I am testing the next branch Rubberduck v2.1.1981 and the code inspector toolbar began to show "Parse Error" during normal usage. I finished what I was working on and got this crash when I went to close Excel:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.InteropServices.COMException (0x800A01A8): Exception from HRESULT: 0x800A01A8
   at Microsoft.Vbe.Interop._VBProject.get_HelpFile()
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBProject.get_HelpFile() in C:\projects\rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBProject.cs:line 30
   at Rubberduck.UI.Command.ShowParserErrorsCommand.FindModuleDeclaration(IVBComponent component) in C:\projects\rubberduck\RetailCoder.VBE\UI\Command\ShowParserErrorsCommand.cs:line 113
   at Rubberduck.UI.Command.ShowParserErrorsCommand.<CreateViewModel>b__8_0(Tuple`2 error) in C:\projects\rubberduck\RetailCoder.VBE\UI\Command\ShowParserErrorsCommand.cs:line 99
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Rubberduck.UI.Command.ShowParserErrorsCommand.CreateViewModel() in C:\projects\rubberduck\RetailCoder.VBE\UI\Command\ShowParserErrorsCommand.cs:line 103
   at Rubberduck.UI.Command.ShowParserErrorsCommand.UpdateTab() in C:\projects\rubberduck\RetailCoder.VBE\UI\Command\ShowParserErrorsCommand.cs:line 56
   at Rubberduck.UI.Command.MenuItems.UiDispatcher.<>c__DisplayClass5_0.<InvokeAsync>b__0(Object x) in C:\projects\rubberduck\RetailCoder.VBE\UI\Command\MenuItems\UiDispatcher.cs:line 29

**Comment by retailcoder** [comment]
Interesting... the stack trace seems to be pointing to the `ShowParserErrorsCommand` trying to build a view model out of... hold on here, *on close?* do you have logging enabled? I think the logs would have more information about the actual parse exception. Yet this one is troubling.. not sure how `ShowParserErrorsCommand.CreateViewModel` could be invoked *on close*...

**Comment by retailcoder** [comment]
That said, it's nice to see that the earlier installer/AppVeyor updates worked =)

**Comment by A9G-Data-Droid** [comment]
I didn't have logging on but I can do that. What level would you want to see? Debug? Trace? 

There was nothing wrong with the program I was working on. I'm still working on it and I haven't seen that Parse Error since. I'm not sure what caused it but I can try to reproduce it.

I found my RubberduckLog.txt in %appdata% here is the header:

`2017-07-19 08:04:27.5341;ERROR-2.0.14.29721;Rubberduck.Common.LogLevelHelper;
	Rubberduck version 2.0.14.29721 loading:
	Operating System: Microsoft Windows NT 6.1.7601 Service Pack 1 x64
	Host Product: Microsoft Office 2013 x86
	Host Version: 15.0.4937.1000
	Host Executable: EXCEL.EXE;
`

**Comment by A9G-Data-Droid** [comment]
Ok, I updated to the latest version v2.1.1994 and then loaded up my project. It immediately got "Resolver Error". When I closed I got the Excel is restarting error that I am used to seeing now. It did not create an unhandled exception like before but I did get a log of the Resolver Error. Does this help? Or is this something completely different?

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/1159555/RubberduckLog.txt)

**Comment by retailcoder** [comment]
Yup, that's useful. Thanks!

**Comment by Vogel612** [comment]
Can this still be reproduced?

**Comment by A9G-Data-Droid** [comment]
I believe this was resolved. I'm on 2.1.0 right now and I haven't seen a parse error yet with my code.
