### ISSUE TITLE
VariableRequiresSetAssignmentEvaluator is missing a check for null

### ISSUE THREAD

**Issue by MDoerner** [rubberduck-vba/Rubberduck#3181]
When pasing the projec from #3178, I got the following warning in the log.

```
2017-07-29 20:37:42.1658;WARN-2.0.14.24961;Rubberduck.Inspections.Rubberduck.Inspections.Inspector+<>c__DisplayClass6_2;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.Inspections.VariableRequiresSetAssignmentEvaluator.RHSUsesNew(LetStmtContext letStmtContext)
   at Rubberduck.Inspections.VariableRequiresSetAssignmentEvaluator.ObjectOrVariantRequiresSetAssignment(IdentifierReference objectOrVariantRef, IEnumerable`1 variantAndObjectDeclarations)
   at Rubberduck.Inspections.VariableRequiresSetAssignmentEvaluator.RequiresSetAssignment(IdentifierReference reference, RubberduckParserState state)
   at Rubberduck.Inspections.Concrete.ObjectVariableNotSetInspection.<GetInspectionResults>b__3_3(IdentifierReference reference)
   at System.Linq.Enumerable.<>c__DisplayClass6_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.<>c__DisplayClass6_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Rubberduck.Inspections.Rubberduck.Inspections.Inspector.<>c__DisplayClass6_2.<FindIssuesAsync>b__5();
```

Apparently, a check for `null` is missing somewhere in the `VariableRequiresSetAssignmentEvaluator`. Maybe something else is wrong, too.

**Comment by retailcoder** [comment]
Line 99 is assuming the parent LetStmt context won't be null, so `RHSUsesNew` is getting a null parameter, which throws the exception when we try to make a member call on it. The method could use a guard clause (and return false given a null parameter), and/or caller (line 99) needs to check if `letStmt` is null. That said, *how* that context can be null is an interesting thing to look into (i.e. there would be no LetStmtContext in the parent nodes, ...which makes me wonder how that node even got there).

**Comment by MDoerner** [comment]
I am currently looking at the inspection. One thing I can see already is that it seems to assume that assignments are always a `letStmt` or a `setStmt`, which is not true.
