### ISSUE TITLE
Add-in Unload Issues: Incomplete Unload, Crash on Exit Possible Cause, Unhandled Exceptions on Reload & Lack of Debug Logging

### ISSUE THREAD

**Issue by PowerAccess** [rubberduck-vba/Rubberduck#3213]
Rubberduck isn't getting fully unloaded, even when unloaded manually by the user, with toolbars, menubar entry, and dialogs still remaining.  

Not only does this cause a series of unhandled exceptions dialogs to be shown for the exact same exception when attempting to reload Rubberduck, but it may also be a root cause of the issue with Access, Excel, etc. crashing on exit, and sometimes automatically restarting, after VBE with Rubberduck was opened.

I attempted to debug this, I also noticed that Debug/Trace logging isn't functioning, that exceptions were going unhandled and without any global handler, and that crash-on-exit seems more common than first though (or to occur for all Office apps) but is just hidden due to no error dialog or restart-on-crash occurring outside of Access and certain cases.

All of these related issues I have detailed below, along with steps to reproduce.

## Related Issue 1:  Failure to Unload Toolbar and Menubar Entry

1. It seems that Rubberduck isn't fully unloading itself, even after unloading manually via Add-in Manager > Uncheck "Loaded/Unloaded"
2. The Rubberduck toolbar and entry in menubar both remain visible, despite manual unloading (Issue 1)
3. Clicking on the About menu item still continues to work, showing an About dialog, though an empty one (which should probably look into to ensure no pre-created dialog or handler code, etc. is still around when exiting Access to cause an issue).

You can see this is not expected behavior in how unloading other add-ins such as MZ-Tools results in toolbars after hid and menubar entry being removed.

## Related Issue 2:  Toolbar Doesn't Persist Position/Visibility and Always Takes Up Another Row

Also, a somewhat unrelated issue is that Rubberduck toolbar does not persist its location like other toolbars, or remember whether was last hidden, but instead always gets moved to its own toolbar row (which is annoying for it to always us another row just for a couple buttons, when I have half a dozen toolbars effectively all sitting on one and only toolbar row to avoid just that).
More importantly, because its impossible to hide the Rubberduck toolbar and have it stay hidden after restart, that may also be preventing a workaround with unhandled exceptions related to ElementHost and the toolbar (as seen in attached unhandled exception stack trace) and possibly even related to the crash-on-exit.

## Related Issue 3: Repeated Unhandled Exceptions on Addin Reload

4. Attempting to load Rubberduck add-in again (by re-checking Loaded/Loaded in Addin Manager) results in 4 identical Unhandled Exception dialogs popping up immediately (not when trying to exit) one after the other 
5. The attached log file is in Debug mode, but I tried tested this with Log Level set to None, Debug, and Trace, and the results were identical in all cases.
6. Exit Access (or even Excel, etc.) and you will see it crash, with error message, and automatically restarting the app (which is very annoying). As mentioned, this actually occurs with all Office apps for me, but is only noticeable with Access, as in other cases it's only seen in Windows Event Viewer or if you watch the processes and WerFault

## Related Issue 4: Logging Mode Seems Ignored and No Trace/Debug Info Ever Logged Except Exceptions

Even in Trace/Debug logging mode, the OS description on startup, shown below, is the *only* log entry.  It therefore seems that either there is a complete lack of any much needed debug logging, the logging modes are never applied/used, and/or the log isn't getting flushed.

As with other apps/add-ins, there should be a difference between Debug/Trace and Normal/Disabled logging, with a large number of log entries needed for debugging in Debug mode, instead of nothing but the same exceptions shown with Normal or No Logging.

## Related Issue 5:  Crash and Restart on Exit for Access + Possible Cause

As discussed before, RubberDuck causes Access (MSACCESS.exe) to crash every time I exit Access after having opened VBE with RubberDuck loaded, resulting in a Access restarting itself.
However, based on what I am seeing here, it seems clear that Rubberduck is not getting properly unloaded, even when unloaded manually by the user. Leaving a toolbar and menubar entry after unloading is *not* an expected behavior, as you can see when unloading other add-ins like MZ-Tools which fully remove on manual unload, and as seen in how attempting to reload again results in unhandled exceptions.

Therefore, it seems like this failure to completely unload might be the root cause of that crash on exit, or one of multiple causes at least. instead of it just being a "timing-related issue occurring only when exiting Access due to use of ElementHost for hosting your WPF controls within WinForms tool windows" as it was described in a previous response to my report on that issue.

It may be that you don't have to completely rewrite all your tool windows with WinForms to avoid crash and auto-restart issue with Access, Excel, etc. It may be that just fixing this incomplete unload issue + replacing WPF with WinForms use in just the *main VBE toolbar/menubar area* may be sufficient.

Also, do you create any UI elements/windows ahead of time, even if never shown?
If so, I wonder if that could be avoided with JIT creation of them when needed, so that if there is an issue related to tool window cleanup at all, it doesn't result in crashing Access, etc. even when no tool windows or dialogs were ever shown or used, as well as to reduce overhead.

## Related Issue 5: Unhandled Exceptions

As suggested previously, I believe you should be handling AppDomain.UnhandledException, as it's clear that unhandled exceptions (not just now-level native errors as was previously described as being the cause of crash on exit) are occurring without being handled, as seen in the 4 Unhandled Exception error dialogs in just this one case alone.  You may be able to avoid showing that repeating showing of the exact same not-user-friendly error messages to users (and at most, if at all, show one user friendly Addin Load/Unload error message, though ideally not even that), and ideally log all the details instead of just part of them even in Debug or Trace mode, as well as potentially prevent those unhandled exceptions causing a crash and restart, by handling AppDomain.UnhandledException, as well as other similar events described previously.

Also, if the exceptions are occurring in places like WinProc, like seen in attached unhandled exception stack trace, then maybe you can place try-catch in various places like there around your own code and any calls to the base implementation, and other  

## Related Issue 6:  Crash on Exit Occurs Always with All Office Apps or More Often Than Seen

It was mentioned in response to my previous report the "crash on exit" only occurs on some systems, and not with all office applications, more often with Access, etc.? Is that the case?
I ask because I noticed that though it seemed like it only occurred for Access for me, it was in fact occurring with all Office applications, (Excel, etc.) where VBE was shown with Rubberduck.
It seems that, for me, it is only Access which actually *shows* an error message when it crashes on exit and performs an auto-restart. However, if you check Windows Event Viewer, you may see like I do that the same error / crash event log entry occurs for Excel and other office apps too (when VBE with Rubberduck was opened at some point).

Therefore, this critical crash-on-exit issue may be occurring for more people ,and more cases, and with more Office apps than previously realized, just without it being as noticeable due to the error message and auto app restart not occurring in all cases.

## Log File & Stack Trace

See log file and text copied from 1st of 4 identical Unhandled Exception dialogs below:

[Log File - RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/1195025/RubberduckLog.txt)

[Copied from Handled Exception Dialog - RubberDuck-UnhandledException-1of4.txt](https://github.com/rubberduck-vba/Rubberduck/files/1195028/RubberDuck-UnhandledException-1of4.txt)

**Comment by daFreeMan** [comment]
Issue 1: To be fair, unloading/reloading RD is a [known issue](https://github.com/rubberduck-vba/Rubberduck/releases?after=Rubberduck-v2.1.1973) and it's recommended that you do not do that.

I agree that issue 2 is a major annoyance and have asked about it several times. I've been told that it's up to the VBE to place the tool bar and that RD has no control over it. If you know otherwise, I'm _sure_ the devs would be thrilled to hear about the method for doing so.

Issue 3: See Issue 1

Issue 4: I'm unable to reproduce that on the latest release build (2.0.13) or any of the [next] builds I've used. I get copious amounts of logging when set on Trace or Debug.

Issue 5: this is a known issue has been an ongoing struggle for some time. Progress is being made, slowly, see the [SlimDucky](https://github.com/rubberduck-vba/SlimDucky) project for what's happening there.

Issue 6: I'd never thought to look there. I'll check it out. Access has a hung process on exit, but I'm not seeing any actual signs of an Office App crash on exit anymore. (Currently running [next] build 2.1.2020, but haven't seen them in any builds since around .1970-ish)

**Comment by retailcoder** [comment]
@daFreeMan to be fair, the incomplete unloading (never mind the crashing) *is* quite likely the reason why unload+reload is a problem.

I want to say something about the RD commandbar though. It's *much* more than a button and a status label; on a parsed project you get context-sensitive information right there, including the kind & type of identifier you're on, and if there's a docstring or a `@Description` annotation (or `VB_Description` attribute), you get that, as well as the number of references to that identifier, serving as a one-click shortcut to the "find all references" command - the RD commandbar is really a *status bar* (VBE lacks one), that can get pretty wide:

![docstrings-in-rdbar](https://user-images.githubusercontent.com/5751684/28894141-e783f060-77a1-11e7-8c18-12156e0cfd75.PNG)

Hiding that commandbar seems counter-productive, to me at least.

I think the SlimDucky bare-bones add-in proves that WPF has nothing to do with the teardown problems we're having, despite prior leads pointing to it; the bare-bones add-in unloads and reloads perfectly fine, and an interesting point is that it doesn't actively do anything to clean up after itself, either - meaning a VBE add-in creates objects that it doesn't actually own (which is counter-intuitive at best), but that own objects that we *do* own, and that we *do* need to clean up (some have disposable dependencies). I need to get SlimDucky to create some menu items and see if these need to be explicitly destroyed or not (that code is currently commeted-out in Rubberduck).

I'm no Carlos Quintero (MZ-Tools' author), the man has all my admiration for what he did (heck, we're using some of the code he provided to us!). MZ-Tools runs in its own `AppDomain`, using a shim (a piece of C++ code that loads the .net runtime and the add-in), so that a crash in MZ-Tools doesn't crash other IDE add-ins (all add-ins run in the same `AppDomain` otherwise) - Rubberduck doesn't have a shim, and debugging with a shim sounds like a nightmare and a half.

The `OnDisconnection` handler (or the `ShutdownAddIn` method) is indeed missing a `try...catch` block, which, now that I'm looking, completely baffles me. How the F did that escape me all this time??!! Anyway logging in RD has historically been pretty much dedicated to debugging parser and resolver issues; if you run a parse you'll see a TON of entries. There *are* several entries written at teardown, but they're not written to the logs - they're still `Debug.WriteLine` calls.

Anyway I think the reason for the partial unloading is because an exception is thrown before everything gets to unload.

**Comment by retailcoder** [comment]
That said, not experiencing the crashes on my machine makes it pretty damn hard to debug them.

**Comment by PowerAccess** [comment]
Thanks for getting back so quickly on this.

@retailcoder 
Btw, what is the known issue number for reload issue?  You linked to a release version.

## Issue 1:

I'm not that concerned about about reloading.
I'm concerned that Rubberduck is failing to even hide, let alone properly dispose of, WPF elements, toolbars, menu, etc. even when manually unloading the add-in.
If it can't do so then, even with no tool windows/dialogs shown, then I doubt crash-on-exit could be resolved.
The failure to unload those elements may even be the root cause of crash-on-exit.

I noticed that your hosting a WPF Toolbar hosted of a WinForms ElementHost, and that is what is causing the unhandled exceptions, as seen in the following excerpt from attached call stack  (with intermediate calls excluded):

> System.NullReferenceException:
>    at System.Windows.Data.BindingExpressionBase.OnDetach(DependencyObject d, DependencyProperty dp)
>    at System.Windows.Data.BindingExpression.Deactivate()
> at System.Windows.StyleHelper.DoThemeStyleInvalidations(FrameworkElement fe, FrameworkContentElement fce, Style oldThemeStyle, Style newThemeStyle, Style style)
>    at System.Windows.Controls.Primitives.ToolBarPanel.GenerateChildren()
>    at System.Windows.Controls.**ToolBar**.MeasureOverride(Size constraint)
>    at System.Windows.Controls.**ToolBarTray**.MeasureOverride(Size constraint)
>    at System.Windows.UIElement.Measure(Size availableSize)
>    at System.Windows.Forms.Integration.**ElementHost**.OnHandleCreated(EventArgs e)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

______
### Questions / Concerns

Are you actually hosting  a WPF toolbar inside of the VBA toolbar? 
Any WPF (or WPF handlers for it) in Menubar items too?
Was WPF in VBE's main toolbar and creation of menubar entry tested in SlimDuck? If aren't already seeing crash in SlimDuck, it may be worth testing that there.

Also was that unhandled exception due to main VBE toolbar area, or toolbar within a Rubberduck tool window?
Do you have Rubberduck tool windows and/or dialogs created ahead of time even when never showing any of them, and, if so, can that be delayed to JIT?

### Suggestion

It may be worth first trying to fix this incomplete manual unload (of toolbar, menu, etc.) issue (which I assume is easier to reproduce) to see if it may be enough to fix the crash-on-exit issue.

Especially since the unhandled exceptions on reload seem related to incomplete unload, and those exceptions relate to WinForms hosted WPF - the suspected cause of crash-on-exit. 
And especially since this crash-on-exit occurs even when not using any Rubberduck toolbars/features/dialogs, when the only things actually showing (and ideally the only things yet created) are the toolbar and menu prior to exiting and experiencing this crash.

________

### My Configuration
(for reference)

Rubberduck 2.0.14.32297
Office 365 32-bit (v1707 - Slow Release Insiders Channel)
Windows 10 Pro x64

**Comment by PowerAccess** [comment]
Issue 5: Unhandled Exceptions

@retailcoder 
You mentioned this is something being looked into with SlimDuck. 

Do you mean just fixing exceptions, or specifically the addition of AppDomain.UnhandledException, etc. handlers as a fallback in worst case?
Such global handlers (ideally in addition to adding more try-catch's, in WndProc, etc) may possibly help avoid crash-on-exit if you fully handle there. But, at very least, you could use them to avoid showing repeated not-very-user-friendly Unhandled Exception dialogs, and replace with additional logging (or in worst case a single Addin Load/Unload failed message box).

Here are the global exception handling methods I was suggesting looking into in my previous comment on #3018:

> -     AppDomain.CurrentDomain.UnhandledException
> -     Application.Current.DispatcherUnhandledException for main UI thread
> -     Dispatcher.UnhandledException for each thread
> -     TaskScheduler.UnobservedTaskException
>

**Comment by retailcoder** [comment]
All dockable toolwindows are essentially a WinForms `UserControl` with a fill-docked WPF `ElementHost` - what you're seeing in that stack trace is probably one of these dockable toolwindows unloading, as most toolwindows have WPF toolbars (inside that ElementHost). We're considering skipping the `UserControl` part and using the `ElementHost` directly, but I doubt that will make a difference other than reducing the depth of the Window layouts (which can't hurt, TBH).

Menu items are 100% COM, no WPF involved whatsoever.

We're constructing the entire object/dependency graph at startup through dependency injection, so yes, everything is readily usable as soon as the VBE comes up (after a startup delay, ...Ninject isn't exactly the fastest IoC framework out there).

"*even when manually unloading*" is the exact same code path as completely exiting the host application, so to me the teardown and unload+reload issues are one and the same.

Can you PR the exception handlers? I'll promptly merge a PR that adds them - let me know if it helps in any way, as I said I'm not getting any exceptions so it's very hard for me to even know that what I do has any effect whatsoever.

Thanks!

**Comment by PowerAccess** [comment]
@retailcoder 
Yea, I can sympathize with difficulty of debugging and fixing without being able to reproduce.

When it came to Excel and other apps, crashes were still occurring, but I only noticed them recently when checking Event Viewer, since there was no error box shown, and no auto-restarting the app, unlike Access.
  (On that note, anyone know why  WERFault handling of Access crashes is so different vs Excel and other Office apps...?)
Do you happen to see any such error entries in Event Viewer for Access and/or Excel, such as was the case for me even when otherwise not noticing a crash?
What version (and 32 vs 64-bit?) of Office do you have that you don't end up seeing even with Access?

**Comment by PowerAccess** [comment]
Right, same case for manual vs on-exit unloading, but I was thinking may be easier to debug with manual unload, and followup reload possibly too.
Though I thought someone had mentioned in #3018 comments something about crash-on-exit possibly involving some timing-related issues.

Is there any possibility of JIT creation of tool windows, either whether with or without continued NInject usage? That would avoid the crash-on-exit in many cases, and possibly help pinpoint,
Also, can you entirely dispose of tool windows (in addition to VBE toolbar and menubar) on Unload, or are you still resorting to hide/resize in that case, or is there some remnant with NInject'ing, etc.? Even if can't dispose of them entirely, you could potentially remove all controls/content from them.


Sure, will look into further as well and PR if find anything that may help.

**Comment by retailcoder** [comment]
We're not the ones hiding and resizing toolwindows - that's the VBE's own doing!

I'm running Office 2010, 32-bit at work and 64-bit at home, same exit code 0 on both (I don't have MS-Access), and also in Sage 300 ERP.

Creating the toolwindows the first time they're needed would definitely speed up the startup, but then there would be a lag the first time it's opened... not sure it's a win. Getting the UI out of Ninject's hands sounds like a plan though - but then manually injecting the dependencies is going to be a royal pain in the neck. I'm hoping we can take control of the UI while leaving the hard work to Ninject, using factories.

**Comment by PowerAccess** [comment]
Many times I will open and use VBE without showing, let alone using, any Rubberduck tool windows.
More importantly, I can't even click on a tool window from Rubberduck menu in order to show it until I click on Pending in toolbar and wait for all the parsing.
So I think the delay wouldn't be very noticeable or even occur at all unless someone has all windows always shown at startup (in which case, it doesn't matter, as first thing one does probably won't be to use addin tool windows).

On that note, is it possible to at least allow using the Rubberduck menu, clicking on menu items to show tool windows, without first having to manually parse everything?
Also, can you have parsing done automatically on startup, so I don't have to manually click Pending in toolbar every time I open Access?

**Comment by PowerAccess** [comment]
@daFreeMan, @retailcoder 

> Issue 2 is a major annoyance and have asked about it several times. I've been told that it's up to the VBE to place the tool bar and that RD has no control over it. If you know otherwise, I'm sure the devs would be thrilled to hear about the method for doing so and will make the requisite changes.

See Issue #3215 I just created. Toolbar's failing to persist position and visibility only happens with Rubberduck, not other addins.


Also, I just reported issue #3214 relating to tool window docking, startup state, and context menu.

**Comment by retailcoder** [comment]
In all likelihood we're crashing before the VBE gets to persist commandbar position/visibility, because that is also something I can't repro.

**Comment by daFreeMan** [comment]
@PowerAccess - OK, I came off as (quite) a bit of a jerk there. My apologies. 

I've spent quite a bit of time hanging out in [chat](https://chat.stackexchange.com/rooms/14929/vba-rubberducking) with the devs and I know these issues have been a real thorn in their side for quite a while and they're working hard on it. I was feeling rather defensive.

The link to the 2.0.13 release page has the list of known issues right there at the top, so that's why I linked there. The crashing has been reported in several places, but I don't know the issue log well enough to have pointed you to "the" correct one. With the details you're including, _this_ may become the defacto "crash-on-exit" thread.

**Comment by PowerAccess** [comment]
@daFreeMan 
I'm not sure what you mean.
I was just saying before I appreciated how quickly you responded to the length report of various issues/suggestions/concerns. So thanks again for that 😃
