### ISSUE TITLE
Rubberduck library not referenced / User-defined type not defined

### ISSUE THREAD

**Issue by pvitkovsky** [rubberduck-vba/Rubberduck#3380]
Dear all, 
I can't compile module with 
```
Private Assert As Object
Set Assert = New Rubberduck.AssertClass
```
Returns
 `"User defined type not defined".`

Rubberduck library is not seen in the Object browser. 
Rubberduck library is not seen in the Reference window. 
If I knew where the installation files are, I could google up the references, but the project wiki shows only registry keys. 
What am I doing wrong? 

Content of
\AppData\Roaming\Rubberduck\Logs
```
2017-09-12 12:53:57.4481;ERROR-;DynamicInjector1f10c9a1fceb45b2992be6d98f21be69;System.Runtime.InteropServices.COMException (0x800AC471): Can't perform operation since the project is protected.
   at Microsoft.Vbe.Interop.VBProjectClass.get_VBComponents()
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBProject.get_VBComponents() in C:\projects\rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBProject.cs:line 63
   at Rubberduck.UI.Command.ExportAllCommand.Evaluate(IVBProject project) in C:\projects\rubberduck\RetailCoder.VBE\UI\Command\ExportAllCommand.cs:line 45
   at Rubberduck.UI.Command.CommandBase.CanExecute(Object parameter) in C:\projects\rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 29;
```

![image](https://user-images.githubusercontent.com/19492701/30537507-9ad2435c-9c72-11e7-8cd5-c75199f8f547.png)

**Comment by Vogel612** [comment]
hi @pvitkovsky,

it looks like you're trying to use early-bound unit-testing with Rubberduck, which had some  [known problems](https://github.com/rubberduck-vba/Rubberduck/issues/2056). I'm not quite sure how it works in the end but I see two options:

1. You add the refernce to `Rubberduck.tlb` in your project's references. Note that this may result in problems when later running your code.

2. You use late-bound testing like so:

        Private Assert As Object
        Set Assert = Application.CreateObject("Rubberduck.AssertClass")

Let me know if this helps or if I could explain better ;)

**Comment by retailcoder** [comment]
The *default* install folder is `%appdata%\Rubberduck`. It's possible you installed it elsewhere though, but that's where the TLB would be. Note that Rubberduck (should) automatically add the reference when running unit tests, if your test settings are set to early-bound.

**Comment by pvitkovsky** [comment]
Dear all,
Thank you for your prompt responses. Knowing the program location helped a lot. 
Issue can be closed
With thanks,
Philip

**Comment by retailcoder** [comment]
:+1:
