### ISSUE TITLE
Log-Levels in parsing process seem used weirdly

### ISSUE THREAD

**Issue by Vogel612** [rubberduck-vba/Rubberduck#3520]
When parsing fails, we get something along these lines in the Log:

```
2017-10-27 19:39:03.2139;WARN-2.1.1.2433;Rubberduck.Parsing.VBA.VBAModuleParser;SLL mode failed in module frmDocumentProperties. Retrying using LL.;Rubberduck.Parsing.Symbols.SyntaxErrorException: extraneous input ')' expecting {',', '!', '.', '&', AND, EQV, IMP, IS, LIKE, MOD, OR, XOR, '/', '\', '=', GEQ, '>', LEQ, '(', '<', '-', '*', NEQ, '+', '^', WS, LINE_CONTINUATION}
   at Rubberduck.Parsing.Symbols.ExceptionErrorListener.SyntaxError(IRecognizer recognizer, IToken offendingSymbol, Int32 line, Int32 charPositionInLine, String msg, RecognitionException e) in C:\projects\rubberduck\Rubberduck.Parsing\Symbols\ExceptionErrorListener.cs:line 10
   at Antlr4.Runtime.ProxyErrorListener`1.SyntaxError(IRecognizer recognizer, Symbol offendingSymbol, Int32 line, Int32 charPositionInLine, String msg, RecognitionException e)
   at Antlr4.Runtime.Parser.NotifyErrorListeners(IToken offendingToken, String msg, RecognitionException e)
   at Antlr4.Runtime.DefaultErrorStrategy.Sync(Parser recognizer)
   at Rubberduck.Parsing.Grammar.VBAParser.lExpression(Int32 _p) in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 17938
   at Rubberduck.Parsing.Grammar.VBAParser.expression(Int32 _p) in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 16810
   at Rubberduck.Parsing.Grammar.VBAParser.expression(Int32 _p) in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 16889
   at Rubberduck.Parsing.Grammar.VBAParser.tuple() in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 13694
   at Rubberduck.Parsing.Grammar.VBAParser.lineSpecialForm() in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 13308
   at Rubberduck.Parsing.Grammar.VBAParser.mainBlockStmt() in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 2005
   at Rubberduck.Parsing.Grammar.VBAParser.blockStmt() in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1633
   at Rubberduck.Parsing.Grammar.VBAParser.block() in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1549
   at Rubberduck.Parsing.Grammar.VBAParser.withStmt() in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 13200
   at Rubberduck.Parsing.Grammar.VBAParser.mainBlockStmt() in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1998
   at Rubberduck.Parsing.Grammar.VBAParser.blockStmt() in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1633
   at Rubberduck.Parsing.Grammar.VBAParser.block() in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1549
   at Rubberduck.Parsing.Grammar.VBAParser.subStmt() in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 11797
   at Rubberduck.Parsing.Grammar.VBAParser.moduleBodyElement() in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1484
   at Rubberduck.Parsing.Grammar.VBAParser.moduleBody() in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1389
   at Rubberduck.Parsing.Grammar.VBAParser.module() in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 365
   at Rubberduck.Parsing.Grammar.VBAParser.startRule() in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 268
   at Rubberduck.Parsing.VBA.VBAModuleParser.Parse(String moduleName, CommonTokenStream moduleTokens, IParseTreeListener[] listeners, BaseErrorListener errorListener, ITokenStream& outStream) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\VBAModuleParser.cs:line 23
2017-10-27 19:39:03.2349;TRACE-2.1.1.2433;Rubberduck.Parsing.VBA.ComponentParseTask;Starting ParseTaskID f5ee8f9e-f2f2-4337-95f3-ece1d9b70841 on thread 5.;
2017-10-27 19:39:03.2349;DEBUG-2.1.1.2433;Rubberduck.Parsing.Symbols.SyntaxErrorException;;
2017-10-27 19:39:03.2529;DEBUG-2.1.1.2433;Rubberduck.Parsing.Symbols.SyntaxErrorException;Token: ) (L56C56);
2017-10-27 19:39:03.2529;WARN-2.1.1.2433;Rubberduck.Parsing.VBA.ComponentParseTask;Syntax error; offending token ')' at line 56, column 56 in module Project.frmHeadingNumbering.;
2017-10-27 19:39:03.2639;ERROR-2.1.1.2433;Rubberduck.Parsing.VBA.ComponentParseTask;Exception thrown in thread 9, ParseTaskID b957e16d-7135-44c8-be45-e9f902e2ea14.;Rubberduck.Parsing.Symbols.SyntaxErrorException: extraneous input ')' expecting {',', '!', '.', '&', AND, EQV, IMP, IS, LIKE, MOD, OR, XOR, '/', '\', '=', GEQ, '>', LEQ, '(', '<', '-', '*', NEQ, '+', '^', WS, LINE_CONTINUATION}
   at Rubberduck.Parsing.Symbols.ExceptionErrorListener.SyntaxError(IRecognizer recognizer, IToken offendingSymbol, Int32 line, Int32 charPositionInLine, String msg, RecognitionException e) in C:\projects\rubberduck\Rubberduck.Parsing\Symbols\ExceptionErrorListener.cs:line 10
   at Antlr4.Runtime.ProxyErrorListener`1.SyntaxError(IRecognizer recognizer, Symbol offendingSymbol, Int32 line, Int32 charPositionInLine, String msg, RecognitionException e)
   at Antlr4.Runtime.Parser.NotifyErrorListeners(IToken offendingToken, String msg, RecognitionException e)
   at Antlr4.Runtime.DefaultErrorStrategy.Sync(Parser recognizer)
   at Rubberduck.Parsing.Grammar.VBAParser.lExpression(Int32 _p) in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 17938
   at Rubberduck.Parsing.Grammar.VBAParser.expression(Int32 _p) in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 16810
   at Rubberduck.Parsing.Grammar.VBAParser.expression(Int32 _p) in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 16889
   at Rubberduck.Parsing.Grammar.VBAParser.tuple() in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 13694
   at Rubberduck.Parsing.Grammar.VBAParser.lineSpecialForm() in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 13308
   at Rubberduck.Parsing.Grammar.VBAParser.mainBlockStmt() in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 2005
   at Rubberduck.Parsing.Grammar.VBAParser.blockStmt() in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1633
   at Rubberduck.Parsing.Grammar.VBAParser.block() in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1549
   at Rubberduck.Parsing.Grammar.VBAParser.subStmt() in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 11797
   at Rubberduck.Parsing.Grammar.VBAParser.moduleBodyElement() in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1484
   at Rubberduck.Parsing.Grammar.VBAParser.moduleBody() in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1389
   at Rubberduck.Parsing.Grammar.VBAParser.module() in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 365
   at Rubberduck.Parsing.Grammar.VBAParser.startRule() in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 268
   at Rubberduck.Parsing.VBA.VBAModuleParser.Parse(String moduleName, CommonTokenStream moduleTokens, IParseTreeListener[] listeners, BaseErrorListener errorListener, ITokenStream& outStream) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\VBAModuleParser.cs:line 31
   at Rubberduck.Parsing.VBA.AttributeParser.Parse(IVBComponent component, CancellationToken token, ITokenStream& stream, IParseTree& tree) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\AttributeParser.cs:line 66
   at Rubberduck.Parsing.VBA.ComponentParseTask.RunAttributesPass(CancellationToken token, IParseTree& attributesTree, IDictionary`2& attributes) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\ComponentParseTask.cs:line 136
   at Rubberduck.Parsing.VBA.ComponentParseTask.Start(CancellationToken token) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\ComponentParseTask.cs:line 54
```
(taken from #3518)

I find the verbosity weird: Why does an "ERROR" log a full stacktrace? And why is critical information regarding the ERROR in a "WARNING" logged right before that?

Why does the "SLL Mode Failed" log a full Stacktrace, even though we retry using LL?

- [ ] Stacktraces should be moved to the `DEBUG` level.
- [ ] The Retry entry should be split into an INFO and a DEBUG entry (It's no cause for warning that the parse failed with SLL).
- [ ] There is a duplicated DEBUG log-entry for `Rubberduck.Parsing.Symbols.SyntaxException`
- [ ] The `SyntaxErrorException` stacktrace for the actual parser failure (in LL mode) should log the message at "WARNING" in combination with the `"offending token"` message, but the Stacktrace at DEBUG

**Comment by MDoerner** [comment]
I kind of agree. However, I would like to note that we cannot easily split the the reporting of the exception and the stack trace. Whenever we pass an exception to NLog, it logs the entire exception, including the stack trace. 

Moreover, I would put the parser error, i.e. the message about the offending token, on level ERROR instead of WARNING and then put the actual exception on either WARN or DEBUG. We log a lot of things in the resolver on level WARNING that do not stop the parsing process. By the same reasonging, I would leave the SSL error on WARNING, but push  the logging of the actual exception to DEBUG.
