### ISSUE TITLE
Test Explorer XAML causes callstack errors

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#3545]
Came across these while working on #3544.

https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/UI/UnitTesting/TestExplorerControl.xaml#L592-L629 produces the error:
```
ArgumentException: value must be a TestOutcome
   at Rubberduck.UI.UnitTesting.TestOutcomeImageSourceConverter.Convert(Object value, Type targetType, Object parameter, CultureInfo culture)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at MS.Internal.Data.DataBindEngine.OnLayoutUpdated(Object sender, EventArgs e)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.UIElement.UpdateLayout()
   at Microsoft.VisualStudio.DesignTools.WpfDesigner.Views.WpfSceneView.UpdateLayoutInternal()
   at Microsoft.VisualStudio.DesignTools.Designer.Views.SceneView.UpdateLayout()
```

I could only get to the ^ above error after commenting out the below lines
https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/UI/UnitTesting/TestExplorerControl.xaml#L21 and https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/UI/UnitTesting/TestExplorerControl.xaml#L273 which together produced:
```
ArgumentException: value is not a TestResult object.
   at Rubberduck.UI.UnitTesting.TestResultToOutcomeTextConverter.Convert(Object value, Type targetType, Object parameter, CultureInfo culture)
   at System.Windows.Data.PropertyGroupDescription.GroupNameFromItem(Object item, Int32 level, CultureInfo culture)
   at MS.Internal.Data.CollectionViewGroupRoot.AddToSubgroups(Object item, LiveShapingItem lsi, CollectionViewGroupInternal group, Int32 level, Boolean loading)
   at System.Windows.Data.ListCollectionView.PrepareGroups()
   at System.Windows.Data.ListCollectionView.PrepareLocalArray()
   at System.Windows.Data.ListCollectionView.RefreshOverride()
   at System.Windows.Data.CollectionView.RefreshInternal()
   at System.Windows.Data.CollectionView.Refresh()
   at System.Windows.Data.CollectionView.EndDefer()
   at System.Windows.Data.CollectionView.DeferHelper.Dispose()
   at System.Windows.Data.CollectionViewSource.ApplyPropertiesToView(ICollectionView view)
   at System.Windows.Data.CollectionViewSource.EnsureView(Object source, Type collectionViewType)
   at System.Windows.Data.CollectionViewSource.EnsureView()
   at System.Windows.Data.CollectionViewSource.OnSourceChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at MS.Internal.Data.DataBindEngine.OnLayoutUpdated(Object sender, EventArgs e)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.UIElement.UpdateLayout()
```

**Comment by comintern** [comment]
This should be resolved in the current build.
