### ISSUE TITLE
Resolver Error

### ISSUE THREAD

**Issue by BindiW** [rubberduck-vba/Rubberduck#3547]
I'm getting a Resolver Error for three of my modules -- one basic module and 2 class modules. The error for all 3 is "System.NullReferenceException: Object reference not set to an instance of an object." How can I fix this?

Details:

- Using Rubberduck v2.1.1.2461, but the problem appears also when using v2.1.0 and v2.1.1.2457.
- Log file attached.
- MS Excel v16.0.7668.7101 on an Office 365 subscription.
- The code compiles.
- Screenshot of references used.
![image](https://user-images.githubusercontent.com/33530849/32633297-931b7d86-c56c-11e7-9fb1-896119c26a67.png)
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/1459449/RubberduckLog.txt)

**Comment by Vogel612** [comment]
Stacktrace:

```
2017-11-09 16:46:44.1436;ERROR-2.1.1.2461;Rubberduck.Parsing.VBA.ReferenceResolveRunnerBase;Exception thrown resolving 'BulkPathRevTool.modControlEpadd' (thread 33).;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.Parsing.Binding.IndexDefaultBinding.ResolveLExpressionIsVariablePropertyFunctionNoParameters(IBoundExpression lExpression) in C:\projects\rubberduck\Rubberduck.Parsing\Binding\IndexDefaultBinding.cs:line 133
   at Rubberduck.Parsing.Binding.IndexDefaultBinding.Resolve(IBoundExpression lExpression) in C:\projects\rubberduck\Rubberduck.Parsing\Binding\IndexDefaultBinding.cs:line 91
   at Rubberduck.Parsing.Binding.IndexDefaultBinding.Resolve() in C:\projects\rubberduck\Rubberduck.Parsing\Binding\IndexDefaultBinding.cs:line 79
   at Rubberduck.Parsing.Binding.DefaultBindingContext.Resolve(Declaration module, Declaration parent, ParserRuleContext expression, IBoundExpression withBlockVariable, StatementResolutionContext statementContext) in C:\projects\rubberduck\Rubberduck.Parsing\Binding\DefaultBindingContext.cs:line 29
   at Rubberduck.Parsing.Symbols.IdentifierReferenceResolver.ResolveDefault(ParserRuleContext expression, StatementResolutionContext statementContext, Boolean isAssignmentTarget, Boolean hasExplicitLetStatement, Boolean isSetAssignment) in C:\projects\rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceResolver.cs:line 167
   at Rubberduck.Parsing.Symbols.IdentifierReferenceResolver.Resolve(LetStmtContext context) in C:\projects\rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceResolver.cs:line 365
   at Rubberduck.Parsing.Symbols.IdentifierReferenceListener.EnterLetStmt(LetStmtContext context) in C:\projects\rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceListener.cs:line 274
   at Rubberduck.Parsing.Grammar.VBAParser.LetStmtContext.EnterRule(IParseTreeListener listener) in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 8794
   at Antlr4.Runtime.Tree.ParseTreeWalker.EnterRule(IParseTreeListener listener, IRuleNode r)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Rubberduck.Parsing.VBA.ReferenceResolveRunnerBase.ResolveReferences(DeclarationFinder finder, QualifiedModuleName module, IParseTree tree, CancellationToken token) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\ReferenceResolveRunnerBase.cs:line 210
```

The stacktrace suggests that the Resolver implementation makes an incorrect assumption about the nullability of the left-hand side of an expression IIUC... A symptomatic fix should be simple, but this could have far-reaching implications ...

**Comment by retailcoder** [comment]
Note that a `Let` statement is usually implicit - it's basically just a value assignment.

**Comment by bclothier** [comment]
I just want to rule out a possibility. I noticed you were referencing `Microsoft Shell Controls and Automation` library. Are you actually using any objects from the library? 

if so, are you actually using any methods that contains or returns an unsupported automation type? This library is known to contain some objects with methods that will NOT work at all under early binding, but it does work fine under late binding, so I'm just wondering if the resolver is tripping over that same bug.

**Comment by BindiW** [comment]
I did searches on resolver error before submitting this, but I finally stumbled on the answer very late last night. #3098 mentions that the resolver can't handle an array of arrays. After removing/replacing these in the 3 modules the resolver issue disappeared, and I was able to proceed with other Rubberduck operations.

@bclothier : I am using objects from that library. I need them to control IE windows when switching from one security zone to another within the company intranet. I will, however, make a note of your remarks for future reference.

It would really be nice if it could handle an array of arrays. In the 3 modules, I was able to change to a concatenated string in the 1st module and revert to an earlier version for a 2nd module. The 3rd module involves a new feature which I don't have an immediate solution for, so I removed it to work on later. 

I'm evaluating the tool for use in the company I work for, and I'm finding it very useful so far. Not many users in the company would run into this particular bug, but I find an array of arrays very useful in some cases.

Thanks everyone for jumping in so quick.

**Comment by Vogel612** [comment]
This should be symptomatically fixed with #3554 Can you confirm @BindiW ?
You'd find out by installing the latest Prerelease :)

**Comment by BindiW** [comment]
@Vogel612  This is awesome! It works. I'm not getting any resolver errors. And so far, everything else looks good too.

Since I'm new here, would it be appropriate for me to close this issue, or is that handled more formally by someone on the team?

**Comment by retailcoder** [comment]
@BindiW I think @MDoerner wants to take a deeper look. @Vogel612's fix simply skips the expression; might be possible to actually resolve it instead; I think that's why we haven't closed the issue yet :smiley:

**Comment by Vogel612** [comment]
Closing as dup of #3089 as these should be the same issue
