### ISSUE TITLE
Double round brackets breaks the resolver

### ISSUE THREAD

**Issue by peterfhenry** [rubberduck-vba/Rubberduck#3552]
Hi, 

I am getting the follow error with the resolver.

2017-11-15 10:13:37.7256;ERROR-2.1.1.2461;Rubberduck.Parsing.VBA.ReferenceResolveRunnerBase;Exception thrown resolving 'AMMPrototype.CSVFunctions' (thread 79).;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.Parsing.Binding.IndexDefaultBinding.ResolveLExpressionIsVariablePropertyFunctionNoParameters(IBoundExpression lExpression) in C:\projects\rubberduck\Rubberduck.Parsing\Binding\IndexDefaultBinding.cs:line 133
   at Rubberduck.Parsing.Binding.IndexDefaultBinding.Resolve(IBoundExpression lExpression) in C:\projects\rubberduck\Rubberduck.Parsing\Binding\IndexDefaultBinding.cs:line 91
   at Rubberduck.Parsing.Binding.IndexDefaultBinding.Resolve() in C:\projects\rubberduck\Rubberduck.Parsing\Binding\IndexDefaultBinding.cs:line 79
   at Rubberduck.Parsing.Binding.DefaultBindingContext.Resolve(Declaration module, Declaration parent, ParserRuleContext expression, IBoundExpression withBlockVariable, StatementResolutionContext statementContext) in C:\projects\rubberduck\Rubberduck.Parsing\Binding\DefaultBindingContext.cs:line 29
   at Rubberduck.Parsing.Symbols.IdentifierReferenceResolver.ResolveDefault(ParserRuleContext expression, StatementResolutionContext statementContext, Boolean isAssignmentTarget, Boolean hasExplicitLetStatement, Boolean isSetAssignment) in C:\projects\rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceResolver.cs:line 167
   at Rubberduck.Parsing.Symbols.IdentifierReferenceResolver.Resolve(LetStmtContext context) in C:\projects\rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceResolver.cs:line 365
   at Rubberduck.Parsing.Symbols.IdentifierReferenceListener.EnterLetStmt(LetStmtContext context) in C:\projects\rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceListener.cs:line 274
   at Rubberduck.Parsing.Grammar.VBAParser.LetStmtContext.EnterRule(IParseTreeListener listener) in C:\projects\rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 8794

I traced it back to this line of code;

`locData(i, j + 1) = locLinesList(i)(j)`

Specifically the locLinesList(i)(j)

Was not limited to just this line. When I removed anything that had ()(), the resolver passed.

Using Version 2.1.1.2461

**Comment by bclothier** [comment]
I'm assuming the `locLinesList` is an array. This is already reported here: #3098

**Comment by peterfhenry** [comment]
Correct, that is the same issue. I'll close this one and follow the other.
