### ISSUE TITLE
Source control crashes

### ISSUE THREAD

**Issue by robleedotinfo** [rubberduck-vba/Rubberduck#3594]
```
2017-12-07 09:50:39.3355;TRACE-2.1.1.2526;Rubberduck.UI.SourceControl.SourceControlViewViewModel;FileSystemWatcher.EnableRaisingEvents is disabled.;
2017-12-07 09:50:46.2941;TRACE-2.1.1.2526;Rubberduck.UI.SourceControl.SourceControlViewViewModel;FileSystemWatcher.EnableRaisingEvents is disabled.;
2017-12-07 09:50:58.6804;TRACE-2.1.1.2526;Rubberduck.UI.SourceControl.SourceControlViewViewModel;FileSystemWatcher.EnableRaisingEvents is disabled.;
2017-12-07 09:52:02.0757;TRACE-2.1.1.2526;Rubberduck.UI.SourceControl.SourceControlViewViewModel;FileSystemWatcher.EnableRaisingEvents is disabled.;
2017-12-07 09:52:09.1204;DEBUG-2.1.1.2526;Rubberduck.UI.Command.MenuItems.ParentMenus.ParentMenuItemBase;(39129256) Executing click handler for menu item '&Source Control', hash code 25096836;
2017-12-07 09:52:10.6436;TRACE-2.1.1.2526;Rubberduck.UI.SourceControl.SourceControlViewViewModel;FileSystemWatcher.EnableRaisingEvents is disabled.;
2017-12-07 09:52:18.2923;TRACE-2.1.1.2526;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Initializing repo;
2017-12-07 09:52:19.1574;WARN-2.1.1.2526;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Handling SourceControlException: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'git2-15e1193': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods.LibraryLifetimeObject..ctor() in C:\projects\libgit2sharp\LibGit2Sharp\Core\NativeMethods.cs:line 35
   at LibGit2Sharp.Core.NativeMethods..cctor() in C:\projects\libgit2sharp\LibGit2Sharp\Core\NativeMethods.cs:line 81
   --- End of inner exception stack trace ---
   at LibGit2Sharp.Core.NativeMethods.git_repository_init_ext(git_repository*& repository, FilePath path, GitRepositoryInitOptions options)
   at LibGit2Sharp.Core.Proxy.git_repository_init_ext(FilePath workdirPath, FilePath gitdirPath, Boolean isBare) in C:\projects\libgit2sharp\LibGit2Sharp\Core\Proxy.cs:line 2477
   at LibGit2Sharp.Repository.Init(String path, Boolean isBare) in C:\projects\libgit2sharp\LibGit2Sharp\Repository.cs:line 454
   at Rubberduck.SourceControl.GitProvider.Init(String directory, Boolean bare) in C:\projects\rubberduck\Rubberduck.SourceControl\GitProvider.cs:line 138
   at Rubberduck.SourceControl.GitProvider.InitVBAProject(String directory) in C:\projects\rubberduck\Rubberduck.SourceControl\GitProvider.cs:line 180
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.InitRepo() in C:\projects\rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 640;
2017-12-07 09:52:19.1574;TRACE-2.1.1.2526;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Displaying Error notification with title 'An unknown error occurred.' and message 'If logging is enabled, you may create an issue on our GitHub page with the contents of your log file in '%AppData%\Roaming\Rubberduck\Logs' for support.';
2017-12-07 09:52:19.1574;ERROR-2.1.1.2526;Rubberduck.UI.SourceControl.SourceControlViewViewModel;System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'git2-15e1193': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods.LibraryLifetimeObject..ctor() in C:\projects\libgit2sharp\LibGit2Sharp\Core\NativeMethods.cs:line 35
   at LibGit2Sharp.Core.NativeMethods..cctor() in C:\projects\libgit2sharp\LibGit2Sharp\Core\NativeMethods.cs:line 81
   --- End of inner exception stack trace ---
   at LibGit2Sharp.Core.NativeMethods.git_repository_init_ext(git_repository*& repository, FilePath path, GitRepositoryInitOptions options)
   at LibGit2Sharp.Core.Proxy.git_repository_init_ext(FilePath workdirPath, FilePath gitdirPath, Boolean isBare) in C:\projects\libgit2sharp\LibGit2Sharp\Core\Proxy.cs:line 2477
   at LibGit2Sharp.Repository.Init(String path, Boolean isBare) in C:\projects\libgit2sharp\LibGit2Sharp\Repository.cs:line 454
   at Rubberduck.SourceControl.GitProvider.Init(String directory, Boolean bare) in C:\projects\rubberduck\Rubberduck.SourceControl\GitProvider.cs:line 138
   at Rubberduck.SourceControl.GitProvider.InitVBAProject(String directory) in C:\projects\rubberduck\Rubberduck.SourceControl\GitProvider.cs:line 180
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.InitRepo() in C:\projects\rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 660
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.<.ctor>b__11_0(Object _) in C:\projects\rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 68
   at Rubberduck.UI.Command.DelegateCommand.OnExecute(Object parameter) in C:\projects\rubberduck\RetailCoder.VBE\UI\Command\DelegateCommand.cs:line 26
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in C:\projects\rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 48;
2017-12-07 09:52:23.2958;FATAL-2.1.1.2526;Rubberduck._Extension;System.UnhandledExceptionEventArgs;
```

**Comment by robleedotinfo** [comment]
Hi, I've just uninstalled and reinstalled Rubberduck, and still get the same error, seems I'm missing git2-15e1193.DLL.  Is there anything I can do about this to fix it?

**Comment by NelsonVides** [comment]
Please give more information. That OS and host app are you using. Which version have you installed. When exactly did it throw that error (which steps did you follow to reproduce it).

**Comment by robleedotinfo** [comment]
I'm on Windows 7 Enterprise SP1 64 bit, I've just reinstalled Rubberduck 2.1.1.2532.  If I open the source control window, it doesn't spot changes in the modules, so I have tried to open an existing repository and create a new repository.  The error occurs on invoking either of those.

**Comment by rubberduck203** [comment]
It seems like there might be something wrong with our automated build. That’s the *native* libgit2 binary that’s missing. 

IIRC I saw a PR recently that upgraded the version of libgit2sharp we’re using.

**Comment by Vogel612** [comment]
@rubberduck203 you're thinking about https://github.com/rubberduck-vba/Rubberduck/pull/3559

**Comment by rubberduck203** [comment]
Thanks @Vogel. 

@NelsonVides you might want to check the installer script to see if it needs updated. I didn’t see any mods in your PR. It might also be worthwhile to see what SHA v1.85 of libgit2 relates to.

**Comment by vogel** [comment]
@rubberduck203 No problem. But it was not me.

**Comment by rubberduck203** [comment]
Oops. Sorry @Vogel. Cheers.

**Comment by robleedotinfo** [comment]
Hi, is there any progress on this?  Failing that, is there an older version I could install in the meantime that will avoid it?

**Comment by Vogel612** [comment]
@robleedotinfo  Unfortunately I removed the prereleases between 2.1.0 and 2.2.0. You can try installing [v2.1.0](https://github.com/rubberduck-vba/Rubberduck/releases/tag/v2.1.0). That should work "just fine" at least for source control.

**Comment by NelsonVides** [comment]
If you trust me in any way, I just built this installer with the correct .dll. You can try it and tell us if this problem persists. If it doesn't, then I found the issue :) After that, you may want to fall back to v2.1.0 as @Vogel612 just advised.
[Rubberduck.Setup.zip](https://github.com/rubberduck-vba/Rubberduck/files/1559226/Rubberduck.Setup.zip)

**Comment by winnieXY** [comment]
@NelsonVides I also hit this problem on Win7 64bit. I can confirm after using the attached zip file,  the crash didn't occur anymore. Can you estimate when you'll release a fixed version of rubberduck?
