### ISSUE TITLE
Trying to clone repo crashes excel: Unable to load DLL 'git2-15e1193'

### ISSUE THREAD

**Issue by marcucciboy2** [rubberduck-vba/Rubberduck#3624]
```
2017-12-19 10:00:55.2626;FATAL-2.1.1.2532;Rubberduck.Common.LogLevelHelper;
	Rubberduck version 2.1.1.2532 loading:
	Operating System: Microsoft Windows NT 6.1.7601 Service Pack 1 x64
	Host Product: Microsoft Office 2013 x86
	Host Version: 15.0.4911.1000
	Host Executable: EXCEL.EXE;
2017-12-19 10:09:56.4411;TRACE-2.1.1.2532;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Cloning repo;
2017-12-19 10:09:56.4461;TRACE-2.1.1.2532;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Displaying Error notification with title 'An unknown error occurred.' and message 'If logging is enabled, you may create an issue on our GitHub page with the contents of your log file in '%AppData%\Roaming\Rubberduck\Logs' for support.';
2017-12-19 10:09:56.4461;ERROR-2.1.1.2532;Rubberduck.UI.SourceControl.SourceControlViewViewModel;System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'git2-15e1193': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods.LibraryLifetimeObject..ctor() in C:\projects\libgit2sharp\LibGit2Sharp\Core\NativeMethods.cs:line 35
   at LibGit2Sharp.Core.NativeMethods..cctor() in C:\projects\libgit2sharp\LibGit2Sharp\Core\NativeMethods.cs:line 81
   --- End of inner exception stack trace ---
   at LibGit2Sharp.Core.NativeMethods.git_clone(git_repository*& repo, String origin_url, FilePath workdir_path, GitCloneOptions& opts)
   at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts) in C:\projects\libgit2sharp\LibGit2Sharp\Core\Proxy.cs:line 354
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options) in C:\projects\libgit2sharp\LibGit2Sharp\Repository.cs:line 732
   at Rubberduck.SourceControl.GitProvider.Clone(String remotePathOrUrl, String workingDirectory, SecureCredentials credentials) in C:\projects\rubberduck\Rubberduck.SourceControl\GitProvider.cs:line 0
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.CloneRepo(SecureCredentials credentials) in C:\projects\rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 791
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.<.ctor>b__11_14(Object _) in C:\projects\rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 78
   at Rubberduck.UI.Command.DelegateCommand.OnExecute(Object parameter) in C:\projects\rubberduck\RetailCoder.VBE\UI\Command\DelegateCommand.cs:line 26
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in C:\projects\rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 48;

```

**Comment by marcucciboy2** [comment]
Actually, this might be the same as [3594](https://github.com/rubberduck-vba/Rubberduck/issues/3594), apologies if it is.

**Comment by Vogel612** [comment]
yes, it is. @NelsonVides when will you push the fixed library configuration?

**Comment by NelsonVides** [comment]
@Vogel612 in a little while, excuse me the delay, Christmas is disrupting the routine a bit.
