### ISSUE TITLE
Warning in debug output on startup

### ISSUE THREAD

**Issue by MDoerner** [rubberduck-vba/Rubberduck#3651]
When debugging in native mode, I get the following warning in the output on startup:

`System.Windows.Data Error: 2 : Cannot find governing FrameworkElement or FrameworkContentElement for target element. BindingExpression:(no path); DataItem=null; target element is 'DataGridTemplateColumn' (HashCode=37228582); target property is 'SortDirection' (type 'Nullable1')`

This does not seems to be right.

**Comment by MDoerner** [comment]
More warnings:

```
System.Windows.Data Error: 40 : BindingExpression path error: 'EmptyUIRefreshMessageVisibility' property not found on 'object' ''CodeMetricsViewModel' (HashCode=59271898)'. BindingExpression:Path=EmptyUIRefreshMessageVisibility; DataItem='CodeMetricsViewModel' (HashCode=59271898); target element is 'TextBlock' (Name=''); target property is 'Visibility' (type 'Visibility')
System.Windows.Data Error: 40 : BindingExpression path error: 'RefreshCommand' property not found on 'object' ''CodeMetricsViewModel' (HashCode=59271898)'. BindingExpression:Path=RefreshCommand; DataItem='CodeMetricsViewModel' (HashCode=59271898); target element is 'Button' (Name=''); target property is 'Command' (type 'ICommand')
System.Windows.Data Error: 40 : BindingExpression path error: 'RefreshCommand' property not found on 'object' ''CodeMetricsViewModel' (HashCode=59271898)'. BindingExpression:Path=RefreshCommand; DataItem='CodeMetricsViewModel' (HashCode=59271898); target element is 'Hyperlink' (HashCode=42719917); target property is 'Command' (type 'ICommand')
```

**Comment by bclothier** [comment]
Just to follow up on this issue. This still exists and seems to contain more output now from more sources. I suspect each section are from different toolwindows but have not looked closely.

In my simple load & parse & unload test using the current pre-release:

Section 1
```
System.Windows.Data Error: 40 : BindingExpression path error: 'SelectedTest' property not found on 'object' ''TestExplorerViewModel' (HashCode=38048949)'. BindingExpression:Path=SelectedTest; DataItem='TestExplorerViewModel' (HashCode=38048949); target element is 'GroupingGrid' (Name=''); target property is 'SelectedItem' (type 'Object')
System.Windows.Data Error: 40 : BindingExpression path error: 'SelectedTest' property not found on 'object' ''TestExplorerViewModel' (HashCode=38048949)'. BindingExpression:Path=SelectedTest; DataItem='TestExplorerViewModel' (HashCode=38048949); target element is 'GroupingGrid' (Name=''); target property is 'SelectedItem' (type 'Object')
System.Windows.Data Error: 40 : BindingExpression path error: 'SelectedTest' property not found on 'object' ''TestExplorerViewModel' (HashCode=38048949)'. BindingExpression:Path=SelectedTest; DataItem='TestExplorerViewModel' (HashCode=38048949); target element is 'GroupingGrid' (Name=''); target property is 'SelectedItem' (type 'Object')
System.Windows.Data Error: 2 : Cannot find governing FrameworkElement or FrameworkContentElement for target element. BindingExpression:Path=Model.ProgressBarColor; DataItem='TestExplorerViewModel' (HashCode=38048949); target element is 'SolidColorBrush' (HashCode=51141415); target property is 'Color' (type 'Color')
```

Section 2
```
System.Windows.Data Error: 1 : Cannot create default converter to perform 'one-way' conversions between types 'System.Boolean' and 'System.Windows.Visibility'. Consider using Converter property of Binding. BindingExpression:Path=EmptyUIRefreshMessageVisibility; DataItem='CodeMetricsViewModel' (HashCode=32832084); target element is 'TextBlock' (Name=''); target property is 'Visibility' (type 'Visibility')
System.Windows.Data Error: 5 : Value produced by BindingExpression is not valid for target property.; Value='True' BindingExpression:Path=EmptyUIRefreshMessageVisibility; DataItem='CodeMetricsViewModel' (HashCode=32832084); target element is 'TextBlock' (Name=''); target property is 'Visibility' (type 'Visibility')
System.Windows.Data Error: 40 : BindingExpression path error: 'RefreshCommand' property not found on 'object' ''CodeMetricsViewModel' (HashCode=32832084)'. BindingExpression:Path=RefreshCommand; DataItem='CodeMetricsViewModel' (HashCode=32832084); target element is 'Button' (Name=''); target property is 'Command' (type 'ICommand')
System.Windows.Data Error: 40 : BindingExpression path error: 'RefreshCommand' property not found on 'object' ''CodeMetricsViewModel' (HashCode=32832084)'. BindingExpression:Path=RefreshCommand; DataItem='CodeMetricsViewModel' (HashCode=32832084); target element is 'Hyperlink' (HashCode=6147620); target property is 'Command' (type 'ICommand')
System.Windows.Data Error: 23 : Cannot convert '<null>' from type '<null>' to type 'System.Double' for 'en-US' culture with default conversions; consider using Converter property of Binding. NotSupportedException:'System.NotSupportedException: DoubleConverter cannot convert from (null).
   at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
   at System.ComponentModel.TypeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)'
System.Windows.Data Error: 6 : 'ObjectSourceConverter' converter failed to convert value '<null>' (type '<null>'); fallback value will be used, if available. BindingExpression:Path=SelectedItem; DataItem='ComboBox' (Name='ChosenFontSize'); target element is 'TextBox' (Name='SearchBox'); target property is 'FontSize' (type 'Double') NotSupportedException:'System.NotSupportedException: DoubleConverter cannot convert from (null).
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)
   at MS.Internal.Data.ObjectSourceConverter.Convert(Object o, Type type, Object parameter, CultureInfo culture)
   at System.Windows.Data.BindingExpression.ConvertHelper(IValueConverter converter, Object value, Type targetType, Object parameter, CultureInfo culture)'
```

Section 3
```   
System.Windows.Data Error: 23 : Cannot convert '<null>' from type '<null>' to type 'System.Double' for 'en-US' culture with default conversions; consider using Converter property of Binding. NotSupportedException:'System.NotSupportedException: DoubleConverter cannot convert from (null).
   at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
   at System.ComponentModel.TypeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)'
System.Windows.Data Error: 6 : 'ObjectSourceConverter' converter failed to convert value '<null>' (type '<null>'); fallback value will be used, if available. BindingExpression:Path=SelectedItem; DataItem='ComboBox' (Name='ChosenFontSize'); target element is 'TextBox' (Name=''); target property is 'FontSize' (type 'Double') NotSupportedException:'System.NotSupportedException: DoubleConverter cannot convert from (null).
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)
   at MS.Internal.Data.ObjectSourceConverter.Convert(Object o, Type type, Object parameter, CultureInfo culture)
   at System.Windows.Data.BindingExpression.ConvertHelper(IValueConverter converter, Object value, Type targetType, Object parameter, CultureInfo culture)'
System.Windows.Data Error: 23 : Cannot convert '<null>' from type '<null>' to type 'System.Double' for 'en-US' culture with default conversions; consider using Converter property of Binding. NotSupportedException:'System.NotSupportedException: DoubleConverter cannot convert from (null).
   at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
   at System.ComponentModel.TypeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)'
System.Windows.Data Error: 6 : 'ObjectSourceConverter' converter failed to convert value '<null>' (type '<null>'); fallback value will be used, if available. BindingExpression:Path=SelectedItem; DataItem='ComboBox' (Name='ChosenFontSize'); target element is 'TextBox' (Name=''); target property is 'FontSize' (type 'Double') NotSupportedException:'System.NotSupportedException: DoubleConverter cannot convert from (null).
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)
   at MS.Internal.Data.ObjectSourceConverter.Convert(Object o, Type type, Object parameter, CultureInfo culture)
   at System.Windows.Data.BindingExpression.ConvertHelper(IValueConverter converter, Object value, Type targetType, Object parameter, CultureInfo culture)'
System.Windows.Data Error: 23 : Cannot convert '<null>' from type '<null>' to type 'System.Double' for 'en-US' culture with default conversions; consider using Converter property of Binding. NotSupportedException:'System.NotSupportedException: DoubleConverter cannot convert from (null).
   at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
   at System.ComponentModel.TypeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)'
System.Windows.Data Error: 6 : 'ObjectSourceConverter' converter failed to convert value '<null>' (type '<null>'); fallback value will be used, if available. BindingExpression:Path=SelectedItem; DataItem='ComboBox' (Name='ChosenFontSize'); target element is 'LinkButton' (Name=''); target property is 'FontSize' (type 'Double') NotSupportedException:'System.NotSupportedException: DoubleConverter cannot convert from (null).
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)
   at MS.Internal.Data.ObjectSourceConverter.Convert(Object o, Type type, Object parameter, CultureInfo culture)
   at System.Windows.Data.BindingExpression.ConvertHelper(IValueConverter converter, Object value, Type targetType, Object parameter, CultureInfo culture)'
System.Windows.Data Error: 23 : Cannot convert '<null>' from type '<null>' to type 'System.Double' for 'en-US' culture with default conversions; consider using Converter property of Binding. NotSupportedException:'System.NotSupportedException: DoubleConverter cannot convert from (null).
   at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
   at System.ComponentModel.TypeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)'
System.Windows.Data Error: 6 : 'ObjectSourceConverter' converter failed to convert value '<null>' (type '<null>'); fallback value will be used, if available. BindingExpression:Path=SelectedItem; DataItem='ComboBox' (Name='ChosenFontSize'); target element is 'LinkButton' (Name=''); target property is 'FontSize' (type 'Double') NotSupportedException:'System.NotSupportedException: DoubleConverter cannot convert from (null).
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)
   at MS.Internal.Data.ObjectSourceConverter.Convert(Object o, Type type, Object parameter, CultureInfo culture)
   at System.Windows.Data.BindingExpression.ConvertHelper(IValueConverter converter, Object value, Type targetType, Object parameter, CultureInfo culture)'
System.Windows.Data Error: 23 : Cannot convert '<null>' from type '<null>' to type 'System.Double' for 'en-US' culture with default conversions; consider using Converter property of Binding. NotSupportedException:'System.NotSupportedException: DoubleConverter cannot convert from (null).
   at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
   at System.ComponentModel.TypeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)'
System.Windows.Data Error: 6 : 'ObjectSourceConverter' converter failed to convert value '<null>' (type '<null>'); fallback value will be used, if available. BindingExpression:Path=SelectedItem; DataItem='ComboBox' (Name='ChosenFontSize'); target element is 'LinkButton' (Name=''); target property is 'FontSize' (type 'Double') NotSupportedException:'System.NotSupportedException: DoubleConverter cannot convert from (null).
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)
   at MS.Internal.Data.ObjectSourceConverter.Convert(Object o, Type type, Object parameter, CultureInfo culture)
   at System.Windows.Data.BindingExpression.ConvertHelper(IValueConverter converter, Object value, Type targetType, Object parameter, CultureInfo culture)'
```   

Section 4   
```
System.Windows.Data Error: 23 : Cannot convert '<null>' from type '<null>' to type 'System.Double' for 'en-US' culture with default conversions; consider using Converter property of Binding. NotSupportedException:'System.NotSupportedException: DoubleConverter cannot convert from (null).
   at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
   at System.ComponentModel.TypeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)'
System.Windows.Data Error: 6 : 'ObjectSourceConverter' converter failed to convert value '<null>' (type '<null>'); fallback value will be used, if available. BindingExpression:Path=SelectedItem; DataItem='ComboBox' (Name='ChosenFontSize'); target element is 'Menu' (Name=''); target property is 'FontSize' (type 'Double') NotSupportedException:'System.NotSupportedException: DoubleConverter cannot convert from (null).
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)
   at MS.Internal.Data.ObjectSourceConverter.Convert(Object o, Type type, Object parameter, CultureInfo culture)
   at System.Windows.Data.BindingExpression.ConvertHelper(IValueConverter converter, Object value, Type targetType, Object parameter, CultureInfo culture)'
System.Windows.Data Error: 23 : Cannot convert '<null>' from type '<null>' to type 'System.Double' for 'en-US' culture with default conversions; consider using Converter property of Binding. NotSupportedException:'System.NotSupportedException: DoubleConverter cannot convert from (null).
   at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
   at System.ComponentModel.TypeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)'
System.Windows.Data Error: 6 : 'ObjectSourceConverter' converter failed to convert value '<null>' (type '<null>'); fallback value will be used, if available. BindingExpression:Path=SelectedItem; DataItem='ComboBox' (Name='ChosenFontSize'); target element is 'MenuItem' (Name=''); target property is 'FontSize' (type 'Double') NotSupportedException:'System.NotSupportedException: DoubleConverter cannot convert from (null).
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)
   at MS.Internal.Data.ObjectSourceConverter.Convert(Object o, Type type, Object parameter, CultureInfo culture)
   at System.Windows.Data.BindingExpression.ConvertHelper(IValueConverter converter, Object value, Type targetType, Object parameter, CultureInfo culture)'
System.Windows.Data Error: 23 : Cannot convert '<null>' from type '<null>' to type 'System.Double' for 'en-US' culture with default conversions; consider using Converter property of Binding. NotSupportedException:'System.NotSupportedException: DoubleConverter cannot convert from (null).
   at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
   at System.ComponentModel.TypeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)'
System.Windows.Data Error: 6 : 'ObjectSourceConverter' converter failed to convert value '<null>' (type '<null>'); fallback value will be used, if available. BindingExpression:Path=SelectedItem; DataItem='ComboBox' (Name='ChosenFontSize'); target element is 'Label' (Name=''); target property is 'FontSize' (type 'Double') NotSupportedException:'System.NotSupportedException: DoubleConverter cannot convert from (null).
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)
   at MS.Internal.Data.ObjectSourceConverter.Convert(Object o, Type type, Object parameter, CultureInfo culture)
   at System.Windows.Data.BindingExpression.ConvertHelper(IValueConverter converter, Object value, Type targetType, Object parameter, CultureInfo culture)'
```

Section 5
```
System.Windows.Data Error: 2 : Cannot find governing FrameworkElement or FrameworkContentElement for target element. BindingExpression:(no path); DataItem=null; target element is 'DataGridTemplateColumn' (HashCode=59140623); target property is 'SortDirection' (type 'Nullable`1')
```

Section 6
```
System.Windows.Data Error: 5 : Value produced by BindingExpression is not valid for target property.; Value='False' BindingExpression:Path=EmptyUIRefreshMessageVisibility; DataItem='CodeMetricsViewModel' (HashCode=32832084); target element is 'TextBlock' (Name=''); target property is 'Visibility' (type 'Visibility')
```

Section 7
```
System.Windows.Data Error: 40 : BindingExpression path error: 'IsObsolete' property not found on 'object' ''CodeExplorerProjectViewModel' (HashCode=67057771)'. BindingExpression:Path=IsObsolete; DataItem='CodeExplorerProjectViewModel' (HashCode=67057771); target element is 'TextBlock' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 40 : BindingExpression path error: 'IsObsolete' property not found on 'object' ''CodeExplorerProjectViewModel' (HashCode=67057771)'. BindingExpression:Path=IsObsolete; DataItem='CodeExplorerProjectViewModel' (HashCode=67057771); target element is 'TextBlock' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 40 : BindingExpression path error: 'IsObsolete' property not found on 'object' ''CodeExplorerCustomFolderViewModel' (HashCode=5705260)'. BindingExpression:Path=IsObsolete; DataItem='CodeExplorerCustomFolderViewModel' (HashCode=5705260); target element is 'TextBlock' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 40 : BindingExpression path error: 'IsObsolete' property not found on 'object' ''CodeExplorerCustomFolderViewModel' (HashCode=5705260)'. BindingExpression:Path=IsObsolete; DataItem='CodeExplorerCustomFolderViewModel' (HashCode=5705260); target element is 'TextBlock' (Name=''); target property is 'NoTarget' (type 'Object')
```

Section 8
```
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=DisplaySignatures'. BindingExpression:Path=IsChecked; DataItem=null; target element is 'TextBlock' (Name=''); target property is 'Visibility' (type 'Visibility')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=DisplaySignatures'. BindingExpression:Path=IsChecked; DataItem=null; target element is 'TextBlock' (Name=''); target property is 'Visibility' (type 'Visibility')
```

**Comment by bclothier** [comment]
This may have been fixed in recent commits, so closing this as stale.
