### ISSUE TITLE
Installs, but doesn't appear in the VBE, if installed to a directory the current user can't write

### ISSUE THREAD

**Issue by cxw42** [rubberduck-vba/Rubberduck#3693]
@retailcoder Hey, Mat's Mug!  I finally got around to installing :) .  I have checked the issues, but can't find this one.  I have also read the contributing guidelines.

Environment: Win 8.1 Enterprise x64; Office 2013 x86.

Steps:
 - Install [v2.1.1](https://github.com/rubberduck-vba/Rubberduck/releases/download/v2.1.1/Rubberduck.Setup.2.1.1.exe) as local admin per [the instructions](https://github.com/rubberduck-vba/Rubberduck/wiki/Installing).  **However**, instead of `C:\ProgramData`, install into `C:\Program Files (x86)`.
    - Why?  Because I have a personal preference for not putting programs in a directory that calls itself "Data". :)
 - As a non-admin user, run the PowerShell commands to populate HKCU, also per the instructions.
 - Run winword
 - Alt+F11 into the VBE

Expected:
 - Rubberduck splash screen
 - `Rubberduck` item on the menu bar

Observed:
 - The splash screen, for just a moment
 - **No menu bar item**

Log:

    2018-01-11 12:03:12.7833;FATAL-;Rubberduck._Extension;Startup sequence threw an unexpected exception.;System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\Rubberduck\Plug-ins' is denied.
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
       at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
       at System.IO.Directory.CreateDirectory(String path)
       at Rubberduck.Root.RubberduckIoCInstaller.FindPlugins() in C:\projects\rubberduck\RetailCoder.VBE\Root\RubberduckIoCInstaller.cs:line 820
       at Rubberduck.Root.RubberduckIoCInstaller.AssembliesToRegister() in C:\projects\rubberduck\RetailCoder.VBE\Root\RubberduckIoCInstaller.cs:line 795
       at Rubberduck.Root.RubberduckIoCInstaller.Install(IWindsorContainer container, IConfigurationStore store) in C:\projects\rubberduck\RetailCoder.VBE\Root\RubberduckIoCInstaller.cs:line 137
       at Castle.Windsor.WindsorContainer.Install(IWindsorInstaller[] installers, DefaultComponentInstaller scope)
       at Castle.Windsor.WindsorContainer.Install(IWindsorInstaller[] installers)
       at Rubberduck._Extension.Startup() in C:\projects\rubberduck\RetailCoder.VBE\Extension.cs:line 213

The extension does show in the Add-Ins manager.  Also, after exiting Word, I get the log entries:

    2018-01-11 12:07:36.6899;INFO-;Rubberduck._Extension;Rubberduck is shutting down.;
    2018-01-11 12:07:36.6899;INFO-;Rubberduck._Extension;No exceptions were thrown.;

Workaround:

 - Exit Word
 - As a local admin, manually create `C:\Program Files (x86)\Rubberduck\Plug-ins`
 - Launch Word and the VBE - the menu-bar item **does** appear.

I conclude that 
 - the installer should create the `Plug-ins` directory, or 
 - the instructions should tell the user to install only in a directory writeable by the non-privileged user who will be running Rubberduck.

Make sense?

**Edit** I should mention that the above steps and workaround were my second or third try at installing, with uninstalls between each.  After an earlier failure in `Program Files (x86)` with the same symptoms, I tried the x64 regasm, even though I never got the `E_FAIL` dialog box.  I can try undoing that, but don't know offhand what changes it makes that don't go away with the uninstall.

**Comment by cxw42** [comment]
@Vogel612 thanks for the quick triage and feedback!

**Comment by retailcoder** [comment]
Indeed, the installer should be creating that folder - currently it's created by Rubberduck at run-time. This would be the correct fix.

**Comment by bclothier** [comment]
@retailcoder  are we actually supporting plugins? I think that if we are not ready to use plug-ins, we shouldn't ask for a directory just yet...

**Comment by retailcoder** [comment]
@bclothier good point. we need to remove that code before the next release.
