### ISSUE TITLE
Crash when trying to create or open repository in Source Control

### ISSUE THREAD

**Issue by navferty** [rubberduck-vba/Rubberduck#3726]
When try to create new or open existing repository, fails after selecting folder.

![image](https://user-images.githubusercontent.com/20906347/35388003-16893eda-01e3-11e8-86a0-3ac373932770.png)

Logs say:
`LibGit2Sharp throws System.DllNotFoundException: Unable to load DLL 'git2-15e1193'`

[RubberduckLog_OpenExistingRepo.txt](https://github.com/rubberduck-vba/Rubberduck/files/1663906/RubberduckLog_OpenExistingRepo.txt)
[RubberduckLog_CreateNewRepo.txt](https://github.com/rubberduck-vba/Rubberduck/files/1663907/RubberduckLog_CreateNewRepo.txt)

	Rubberduck version 2.1.1.2532 loading:
	Operating System: Microsoft Windows NT 10.0.15063.0 x64
	Host Product: Microsoft Office 2013 x64
	Host Version: 15.0.4997.1000
	Host Executable: EXCEL.EXE;

**Comment by Vogel612** [comment]
Stacktrace from both logs looks pretty similar

```
2018-01-25 15:12:56.8492;WARN-2.1.1.2532;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Handling SourceControlException: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'git2-15e1193': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods.LibraryLifetimeObject..ctor() in C:\projects\libgit2sharp\LibGit2Sharp\Core\NativeMethods.cs:line 35
   at LibGit2Sharp.Core.NativeMethods..cctor() in C:\projects\libgit2sharp\LibGit2Sharp\Core\NativeMethods.cs:line 81
   --- End of inner exception stack trace ---
   at LibGit2Sharp.Core.NativeMethods.git_repository_init_ext(git_repository*& repository, FilePath path, GitRepositoryInitOptions options)
   at LibGit2Sharp.Core.Proxy.git_repository_init_ext(FilePath workdirPath, FilePath gitdirPath, Boolean isBare) in C:\projects\libgit2sharp\LibGit2Sharp\Core\Proxy.cs:line 2477
   at LibGit2Sharp.Repository.Init(String path, Boolean isBare) in C:\projects\libgit2sharp\LibGit2Sharp\Repository.cs:line 454
   at Rubberduck.SourceControl.GitProvider.Init(String directory, Boolean bare) in C:\projects\rubberduck\Rubberduck.SourceControl\GitProvider.cs:line 140
   at Rubberduck.SourceControl.GitProvider.InitVBAProject(String directory) in C:\projects\rubberduck\Rubberduck.SourceControl\GitProvider.cs:line 183
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.InitRepo() in C:\projects\rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 640;
2018-01-25 15:12:56.8492;TRACE-2.1.1.2532;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Displaying Error notification with title 'An unknown error occurred.' and message 'If logging is enabled, you may create an issue on our GitHub page with the contents of your log file in '%AppData%\Roaming\Rubberduck\Logs' for support.';
2018-01-25 15:12:56.8648;ERROR-2.1.1.2532;Rubberduck.UI.SourceControl.SourceControlViewViewModel;System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'git2-15e1193': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods.LibraryLifetimeObject..ctor() in C:\projects\libgit2sharp\LibGit2Sharp\Core\NativeMethods.cs:line 35
   at LibGit2Sharp.Core.NativeMethods..cctor() in C:\projects\libgit2sharp\LibGit2Sharp\Core\NativeMethods.cs:line 81
   --- End of inner exception stack trace ---
   at LibGit2Sharp.Core.NativeMethods.git_repository_init_ext(git_repository*& repository, FilePath path, GitRepositoryInitOptions options)
   at LibGit2Sharp.Core.Proxy.git_repository_init_ext(FilePath workdirPath, FilePath gitdirPath, Boolean isBare) in C:\projects\libgit2sharp\LibGit2Sharp\Core\Proxy.cs:line 2477
   at LibGit2Sharp.Repository.Init(String path, Boolean isBare) in C:\projects\libgit2sharp\LibGit2Sharp\Repository.cs:line 454
   at Rubberduck.SourceControl.GitProvider.Init(String directory, Boolean bare) in C:\projects\rubberduck\Rubberduck.SourceControl\GitProvider.cs:line 140
   at Rubberduck.SourceControl.GitProvider.InitVBAProject(String directory) in C:\projects\rubberduck\Rubberduck.SourceControl\GitProvider.cs:line 183
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.InitRepo() in C:\projects\rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 660
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in C:\projects\rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 48;
``` 

It seems like the native binaries for libgit2sharp are not at the correct version (again?)

**Comment by navferty** [comment]
Win 10 Enterprise 64 bit
Version	10.0.15063 Build 15063
Excel 2013 (15.0.4997.1000) 64 bit

**Comment by rubberduck203** [comment]
Please see #3758.
