### ISSUE TITLE
GitHub creating new local repository crashes Excel/VBA

### ISSUE THREAD

**Issue by Excelautomation** [rubberduck-vba/Rubberduck#3826]
GitHub creating new local repository crashes Excel/VBA

From Source Control Window:
"Manage" -> "Create New Local Repository" -> Select Folder -> Crash

**Errorlog:**
2018-03-07 20:15:33.4266;WARN-2.1.1.2532;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Handling SourceControlException: System.TypeInitializationException: 
The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'git2-15e1193': Det angivne modul blev ikke fundet. (Exception from HRESULT: 0x8007007E)
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods.LibraryLifetimeObject..ctor() in C:\projects\libgit2sharp\LibGit2Sharp\Core\NativeMethods.cs:line 35
   at LibGit2Sharp.Core.NativeMethods..cctor() in C:\projects\libgit2sharp\LibGit2Sharp\Core\NativeMethods.cs:line 81
   --- End of inner exception stack trace ---
   at LibGit2Sharp.Core.NativeMethods.git_repository_init_ext(git_repository*& repository, FilePath path, GitRepositoryInitOptions options)
   at LibGit2Sharp.Core.Proxy.git_repository_init_ext(FilePath workdirPath, FilePath gitdirPath, Boolean isBare) in C:\projects\libgit2sharp\LibGit2Sharp\Core\Proxy.cs:line 2477
   at LibGit2Sharp.Repository.Init(String path, Boolean isBare) in C:\projects\libgit2sharp\LibGit2Sharp\Repository.cs:line 454
   at Rubberduck.SourceControl.GitProvider.Init(String directory, Boolean bare) in C:\projects\rubberduck\Rubberduck.SourceControl\GitProvider.cs:line 140
   at Rubberduck.SourceControl.GitProvider.InitVBAProject(String directory) in C:\projects\rubberduck\Rubberduck.SourceControl\GitProvider.cs:line 183
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.InitRepo() in C:\projects\rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 640;
2018-03-07 20:15:33.4266;ERROR-2.1.1.2532;Rubberduck.UI.SourceControl.SourceControlViewViewModel;System.TypeInitializationException: 
The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'git2-15e1193': Det angivne modul blev ikke fundet. (Exception from HRESULT: 0x8007007E)
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods.LibraryLifetimeObject..ctor() in C:\projects\libgit2sharp\LibGit2Sharp\Core\NativeMethods.cs:line 35
   at LibGit2Sharp.Core.NativeMethods..cctor() in C:\projects\libgit2sharp\LibGit2Sharp\Core\NativeMethods.cs:line 81
   --- End of inner exception stack trace ---
   at LibGit2Sharp.Core.NativeMethods.git_repository_init_ext(git_repository*& repository, FilePath path, GitRepositoryInitOptions options)
   at LibGit2Sharp.Core.Proxy.git_repository_init_ext(FilePath workdirPath, FilePath gitdirPath, Boolean isBare) in C:\projects\libgit2sharp\LibGit2Sharp\Core\Proxy.cs:line 2477
   at LibGit2Sharp.Repository.Init(String path, Boolean isBare) in C:\projects\libgit2sharp\LibGit2Sharp\Repository.cs:line 454
   at Rubberduck.SourceControl.GitProvider.Init(String directory, Boolean bare) in C:\projects\rubberduck\Rubberduck.SourceControl\GitProvider.cs:line 140
   at Rubberduck.SourceControl.GitProvider.InitVBAProject(String directory) in C:\projects\rubberduck\Rubberduck.SourceControl\GitProvider.cs:line 183
   at Rubberduck.UI.SourceControl.SourceControlViewViewModel.InitRepo() in C:\projects\rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:line 660
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in C:\projects\rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 48;
2018-03-07 20:15:37.4423;FATAL-2.1.1.2532;Rubberduck._Extension;System.UnhandledExceptionEventArgs;

**Comment by MDoerner** [comment]
Thank you for reporting this issue.

Please note that integrated SC has been removed from Rubberduck in accordance with #3758. The ability to export and import all components of a project still remains and can be employed to use external SC tools.

Closing this issue as no longer applicable.
