### ISSUE TITLE
ParameterCanBeByVal throws ArgumentOutOfRange

### ISSUE THREAD

**Issue by Vogel612** [rubberduck-vba/Rubberduck#3906]
Found in the logs for #3905:

```
2018-04-09 08:25:58.0942;WARN-2.2.6672.28001;Rubberduck.Inspections.Rubberduck.Inspections.Inspector;System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Rubberduck.Inspections.Concrete.ParameterCanBeByValInspection.<GetResults>d__3.MoveNext() in C:\projects\rubberduck\Rubberduck.Inspections\Concrete\ParameterCanBeByValInspection.cs:line 94
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Rubberduck.Inspections.Concrete.ParameterCanBeByValInspection.DoGetInspectionResults() in C:\projects\rubberduck\Rubberduck.Inspections\Concrete\ParameterCanBeByValInspection.cs:line 29
   at Rubberduck.Inspections.Abstract.InspectionBase.GetInspectionResults(CancellationToken token) in C:\projects\rubberduck\Rubberduck.Inspections\Abstract\InspectionBase.cs:line 166
   at Rubberduck.Inspections.Rubberduck.Inspections.Inspector.RunInspection(IInspection inspection, ConcurrentBag`1 allIssues, CancellationToken token) in C:\projects\rubberduck\Rubberduck.Inspections\Inspector.cs:line 157;System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Rubberduck.Inspections.Concrete.ParameterCanBeByValInspection.<GetResults>d__3.MoveNext() in C:\projects\rubberduck\Rubberduck.Inspections\Concrete\ParameterCanBeByValInspection.cs:line 94
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Rubberduck.Inspections.Concrete.ParameterCanBeByValInspection.DoGetInspectionResults() in C:\projects\rubberduck\Rubberduck.Inspections\Concrete\ParameterCanBeByValInspection.cs:line 29
   at Rubberduck.Inspections.Abstract.InspectionBase.GetInspectionResults(CancellationToken token) in C:\projects\rubberduck\Rubberduck.Inspections\Abstract\InspectionBase.cs:line 166
   at Rubberduck.Inspections.Rubberduck.Inspections.Inspector.RunInspection(IInspection inspection, ConcurrentBag`1 allIssues, CancellationToken token) in C:\projects\rubberduck\Rubberduck.Inspections\Inspector.cs:line 157
``` 

We should not be throwing that exception when analyzing any code. Let's find out where this comes from and fix it. No bandaids, please :)

**Comment by comintern** [comment]
The problem is here:

```
                    for (var i = 0; i < parameters.Count; i++)
                    {
                        parametersAreByRef[i] = parametersAreByRef[i] &&
                                                !IsUsedAsByRefParam(declarations, parameters[i]) &&
                                                ((VBAParser.ArgContext) parameters[i].Context).BYVAL() == null &&
                                                !parameters[i].References.Any(reference => reference.IsAssignment);
                    }
```

Note that the indexing of the `parameters` `List` is bounded by the condition of the `for` loop. The indexing of the `parametersAreByRef` `List` is unchecked. I can't spot the error with casual static analysis, but this will throw the exeception above if `parametersAreByRef` has less members than `parameters`
