### ISSUE TITLE
Excel 2016: unexpected error

### ISSUE THREAD

**Issue by tdalon** [rubberduck-vba/Rubberduck#4009]
When I press refresh I get "Unexpected Error".
I have Excel 2016/ Win 7.
I have retried with latest pre-release.
![image](https://user-images.githubusercontent.com/6458444/40045965-0006b38c-582c-11e8-937b-ec4edf1aaef8.png)
Attached the log file.
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/2006034/RubberduckLog.txt)

Many thanks.

**Comment by MDoerner** [comment]
Thank you for reporting this.

To determine what went wrong we will need some more information. It would be great if you could go into the Rubberduck setting to enable logging, hit the refresh button again and post the log here. _Trace_ level would be ideal, but if you fear to leak too much information about your project on that level, _Warning_ or _Error_ might be sufficient.

**Comment by retailcoder** [comment]
Log:

```
2018-05-15 19:28:44.4260;ERROR-2.2.6708.13023;Rubberduck.UI.Command.AddTestModuleCommand;System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Vbe.Interop.VBE'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{0002E166-0000-0000-C000-000000000046}' failed due to the following error: Error loading type library/DLL. (Exception from HRESULT: 0x80029C4A (TYPE_E_CANTLOADLIBRARY)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Vbe.Interop.VBE.get_ActiveVBProject()
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBE.get_ActiveVBProject() in C:\projects\rubberduck\Rubberduck.VBEditor.VBA\SafeComWrappers\VB\VBE.cs:line 40
   at Rubberduck.UI.Command.AddTestModuleCommand.GetProject() in C:\projects\rubberduck\Rubberduck.Core\UI\Command\AddTestModuleCommand.cs:line 124
   at Rubberduck.UI.Command.AddTestModuleCommand.EvaluateCanExecute(Object parameter) in C:\projects\rubberduck\Rubberduck.Core\UI\Command\AddTestModuleCommand.cs:line 140
   at Rubberduck.UI.Command.CommandBase.CanExecute(Object parameter) in C:\projects\rubberduck\Rubberduck.Core\UI\Command\CommandBase.cs:line 28;System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Vbe.Interop.VBE'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{0002E166-0000-0000-C000-000000000046}' failed due to the following error: Error loading type library/DLL. (Exception from HRESULT: 0x80029C4A (TYPE_E_CANTLOADLIBRARY)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Vbe.Interop.VBE.get_ActiveVBProject()
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBE.get_ActiveVBProject() in C:\projects\rubberduck\Rubberduck.VBEditor.VBA\SafeComWrappers\VB\VBE.cs:line 40
   at Rubberduck.UI.Command.AddTestModuleCommand.GetProject() in C:\projects\rubberduck\Rubberduck.Core\UI\Command\AddTestModuleCommand.cs:line 124
   at Rubberduck.UI.Command.AddTestModuleCommand.EvaluateCanExecute(Object parameter) in C:\projects\rubberduck\Rubberduck.Core\UI\Command\AddTestModuleCommand.cs:line 140
   at Rubberduck.UI.Command.CommandBase.CanExecute(Object parameter) in C:\projects\rubberduck\Rubberduck.Core\UI\Command\CommandBase.cs:line 28
```

**Comment by tdalon** [comment]
If you need anytime to have a debugging Skype session with me just contact me (Matthieu got my email).

**Comment by comintern** [comment]
@tdalon -  I was taking a look at this and was trying to come up with reasons why LoadLibrary would be failing. Do you remember if you had any other add-ins loaded when you got this error?

This may be related to #3837 (need COM shims).

**Comment by bclothier** [comment]
Pinging @tdalon  to see if this is still an issue.

**Comment by bclothier** [comment]
This is an old issue and no followups. Assuming stale and closing. If this still is an issue, feel free to reopen.

**Comment by tdalon** [comment]
I don't get an error anymore :-) Still the menu Indent stays greyed out. :-(

**Comment by bclothier** [comment]
Thanks for the followup! To confirm, indent is disabled even after you've run the parse and selected a procedure or a module?

**Comment by retailcoder** [comment]
@tdalon whether the *Code Explorer* context menu's Indent command is enabled is dependent on parser state (because if it's not `Ready` then the Code Explorer nodes necessarily aren't up to date) **and** on what kind of node is selected - and it's disabled otherwise:

https://github.com/rubberduck-vba/Rubberduck/blob/2ccff5a227204f550455a20763c34969780ab68b/Rubberduck.Core/UI/CodeExplorer/Commands/IndentCommand.cs#L44-L69

If parser state is `Ready` and the Code Explorer context menu is brought up with a right-click on a project, folder, module, or member node, and the command is still disabled, then something's off.

The ActiveX menu commands (main menu bar /"Rubberduck" menu, code pane context menu) however, don't even override `CanExecute`, so they should be enabled regardless of parser state (they do trigger a reparse once executed though). These are always enabled, correct?
