### ISSUE TITLE
Parsing Exception

### ISSUE THREAD

**Issue by joshuader6** [rubberduck-vba/Rubberduck#4078]
Hello everyone, 

I just installed Build 2.2.0.3368-pre. 

When I hit Parse nothing happens. According to the Log, the Parser crashes immediately after clicking the Button. 
Log: [https://pastebin.com/kXtEHq8r](https://pastebin.com/kXtEHq8r)

It says something about: "Bibliothek nicht registriert." which means "Libary not registered". 
Did the installer not Register everything? I installed it just for my user. 

I'm running Rubberduck in Excel 14.0.7208.5000 (32-Bit)

**Comment by Vogel612** [comment]
Stacktrace: 

```
2018-06-13 07:58:18.3993;ERROR-2.2.6737.8365;Rubberduck.Parsing.VBA.ParseCoordinator;Unexpected exception thrown in parsing run. (thread 6).;System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Office.Core.CommandBarControl'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{000C0308-0000-0000-C000-000000000046}' failed due to the following error: Bibliothek nicht registriert. (Exception from HRESULT: 0x8002801D (TYPE_E_LIBNOTREGISTERED)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Office.Core.CommandBarControl.set_Enabled(Boolean pvarfEnabled)
   at Rubberduck.VBEditor.SafeComWrappers.Office12.CommandBarButton.set_IsEnabled(Boolean value) in C:\projects\rubberduck\Rubberduck.VBEditor.VBA\SafeComWrappers\Office\CommandBarButton.cs:line 193
   at Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase.EvaluateCanExecute(RubberduckParserState state) in C:\projects\rubberduck\Rubberduck.Core\UI\Command\MenuItems\CommandBars\AppCommandBarBase.cs:line 156
   at Rubberduck.UI.Command.MenuItems.CommandBars.RubberduckCommandBar.OnParserStateChanged(Object sender, EventArgs e) in C:\projects\rubberduck\Rubberduck.Core\UI\Command\MenuItems\CommandBars\RubberduckCommandBar.cs:line 92
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Rubberduck.Parsing.VBA.RubberduckParserState.OnStateChanged(Object requestor, CancellationToken token, ParserState state) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\RubberduckParserState.cs:line 347
   at Rubberduck.Parsing.VBA.RubberduckParserState.SetStatusAndFireStateChanged(Object requestor, ParserState status, CancellationToken token) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\RubberduckParserState.cs:line 561
   at Rubberduck.Parsing.VBA.ParserStateManagerBase.SetStatusAndFireStateChanged(Object requestor, ParserState status, CancellationToken token) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\ParserStateManagerBase.cs:line 51
   at Rubberduck.Parsing.VBA.ParseCoordinator.ParseAllInternal(Object requestor, CancellationToken token) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:line 340
   at Rubberduck.Parsing.VBA.ParseCoordinator.ParseAll(Object requestor, CancellationToken token) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:line 313
```

**Comment by bclothier** [comment]
ref #4192 -- this sounds too similar and bears investigating.

**Comment by bclothier** [comment]
Following up on this old issue - is this still an issue?

**Comment by bclothier** [comment]
Closing this due to age. Feel free to reopen if this still occurs.
