### ISSUE TITLE
Test execution fails when multiple VBA projects loaded at Excel start up

### ISSUE THREAD

**Issue by donile** [rubberduck-vba/Rubberduck#4253]
**Rubberduck Version**

Version 2.2.6672.28001
OS: Microsoft Windows NT 10.0.16299.0, x64
Host Product: Microsoft Office 2013 x64
Host Version: 15.0.5045.1000
Host Executable: EXCEL.EXE

**Reproduce Instructions**

1. Start Excel with an Excel Add-In installed
2. Create blank workbook
3. Add Test Module to Book1
4. Add TestMethod1 to TestModule1
5. Run All Tests

**Stack Trace**

```
System.ArgumentException: TypeInfosCollection::Get failed. 'TestModule1' component not found.
   at Rubberduck.VBEditor.ComManagement.TypeLibs.TypeLibWrapper.TypeInfosCollection.Get(String searchTypeName) in C:\projects\rubberduck\Rubberduck.VBEEditor\ComManagement\TypeLibs\TypeLibs.cs:line 67
   at Rubberduck.VBEditor.ComManagement.TypeLibsAPI.VBETypeLibsAPI.ExecuteCode(TypeLibWrapper projectTypeLib, String standardModuleName, String procName, Object[] args) in C:\projects\rubberduck\Rubberduck.VBEEditor\ComManagement\TypeLibs\TypeLibsAPI.cs:line 211
   at Rubberduck.UnitTesting.TestEngine.Run(IEnumerable`1 members) in C:\projects\rubberduck\Rubberduck.Core\UnitTesting\TestEngine.cs:line 166
   at Rubberduck.UnitTesting.TestEngine.RunInternal(IEnumerable`1 tests) in C:\projects\rubberduck\Rubberduck.Core\UnitTesting\TestEngine.cs:line 113
```

**Screenshot**
![image](https://user-images.githubusercontent.com/6015052/43723680-da2ec6ea-995d-11e8-8e21-1a41bec3a94d.png)

...

**Comment by bclothier** [comment]
I believe this particular PR has yet to make to the green release. The [last green release](https://github.com/rubberduck-vba/Rubberduck/releases/tag/Rubberduck-v2.2.0.3086) was a quite while ago, and this particular PR was merged in sometime after that, as [this pre-release](https://github.com/rubberduck-vba/Rubberduck/releases/tag/Rubberduck-v2.2.0.3260).

Of course, the OP can also download the [latest pre-release here](https://github.com/rubberduck-vba/Rubberduck/releases/tag/Rubberduck-v2.2.0.3576).

**Comment by bclothier** [comment]
This should have been closed with the green release but I think this got missed, so closing.
