### ISSUE TITLE
NRE in UnreachableCaseInspection

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#4258]
This was noted before in #4150, and I hit it a couple times with my stress test workbook (AfsprakenProgramma.xlsm - [download link is here](https://github.com/halcwb/AfsprakenProgramma)).

Relevant log bit:
```
2018-08-07 20:05:32.6020;WARN-2.2.6793.35158;Rubberduck.Inspections.Rubberduck.Inspections.Inspector;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.GetConstantDeclarationValueToken(Declaration constantDeclaration) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 294
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.GetContextValue(ParserRuleContext context, String& declaredTypeName, String& expressionValue) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 274
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.TryGetLExprValue(LExprContext lExprContext, String& expressionValue, String& declaredTypeName) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 247
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(LExprContext context) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 126
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(ParserRuleContext parserRuleContext) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 96
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.VisitImpl(ParserRuleContext context) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 225
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(ParserRuleContext parserRuleContext) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 105
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.VisitImpl(ParserRuleContext context) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 225
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(ParserRuleContext parserRuleContext) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 105
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(IParseTree tree) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 41
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.VisitChildren(IRuleNode node) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 52
   at Rubberduck.Parsing.Grammar.VBAParser.SelectCaseStmtContext.Accept[TResult](IParseTreeVisitor`1 visitor) in C:\Rubberduck\Rubberduck.Parsing\obj\Debug\VBAParser.cs:line 12328
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.UnreachableCaseInspection.DoGetInspectionResults() in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\UnreachableCaseInspection.cs:line 58
   at Rubberduck.Inspections.Abstract.InspectionBase.GetInspectionResults(CancellationToken token) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Abstract\InspectionBase.cs:line 166
   at Rubberduck.Inspections.Rubberduck.Inspections.Inspector.RunInspection(IInspection inspection, ConcurrentBag`1 allIssues, CancellationToken token) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Inspector.cs:line 188;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.GetConstantDeclarationValueToken(Declaration constantDeclaration) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 294
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.GetContextValue(ParserRuleContext context, String& declaredTypeName, String& expressionValue) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 274
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.TryGetLExprValue(LExprContext lExprContext, String& expressionValue, String& declaredTypeName) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 247
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(LExprContext context) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 126
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(ParserRuleContext parserRuleContext) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 96
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.VisitImpl(ParserRuleContext context) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 225
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(ParserRuleContext parserRuleContext) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 105
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.VisitImpl(ParserRuleContext context) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 225
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(ParserRuleContext parserRuleContext) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 105
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(IParseTree tree) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 41
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.VisitChildren(IRuleNode node) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 52
   at Rubberduck.Parsing.Grammar.VBAParser.SelectCaseStmtContext.Accept[TResult](IParseTreeVisitor`1 visitor) in C:\Rubberduck\Rubberduck.Parsing\obj\Debug\VBAParser.cs:line 12328
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.UnreachableCaseInspection.DoGetInspectionResults() in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\UnreachableCaseInspection.cs:line 58
   at Rubberduck.Inspections.Abstract.InspectionBase.GetInspectionResults(CancellationToken token) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Abstract\InspectionBase.cs:line 166
   at Rubberduck.Inspections.Rubberduck.Inspections.Inspector.RunInspection(IInspection inspection, ConcurrentBag`1 allIssues, CancellationToken token) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Inspector.cs:line 188
```
This appears to be failing due to a null context in the `constantDeclaration` (in my case it was `vbNull`). I'm guessing this just needs to be made aware of referenced declarations, but I haven't investigated it much further than that.

The full log file [is here](https://github.com/rubberduck-vba/Rubberduck/files/2268691/log.txt) if anyone is interested.

**Comment by comintern** [comment]
This seems to have disappeared with the recent PR for the UnreachableCaseInspection.
