### ISSUE TITLE
Massive parser slowdown

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#4307]
On the `next` from last night, I'm observing that the parser seems to be much much slower to parse VBA projects of moderate complexity in both Access and Excel. Depending on which I open, it can take from 20 seconds to > 2 minutes to parse projects that used to parse in 2-5 seconds. Is anyone else observing the same?

**Comment by mansellan** [comment]
I noticed the big VB6 project I ran took ~300s to parse, but had nothing to baseline against.

**Comment by comintern** [comment]
I'm not sure that I'd classify my benchmark workbook's slowdown as being "massive", but I first noticed this [on August 8th](https://chat.stackexchange.com/transcript/message/46089200#46089200):

> 2018-08-07 20:03:17.9850;INFO-
> .2.6793.35158;Rubberduck.Parsing.VBA.RubberduckParserState;RubberduckParserState (1) is invoking StateChanged (Started);
> 2018-08-07 20:05:30.7678;INFO-2.2.6793.35158;Rubberduck.Parsing.VBA.RubberduckParserState;RubberduckParserState (8) is invoking StateChanged (Ready);

That comes out to 02:12.8

I just ran it again and got this:

> 2018-08-25 14:00:23.7587;INFO-2.2.6811.22155;Rubberduck.Parsing.VBA.RubberduckParserState;RubberduckParserState (1) is invoking StateChanged (Started);
> 2018-08-25 14:02:13.1428;INFO-2.2.6811.22155;Rubberduck.Parsing.VBA.RubberduckParserState;RubberduckParserState (8) is invoking StateChanged (Ready);

...for a total of 01:49.4

So..., in the last couple of weeks this improved by about 23 seconds. However, the same workbook from [the start  of 2017](https://chat.stackexchange.com/transcript/message/34871812#34871812) was 46 seconds *including* running inspections.

Is it possible that we're hitting more thread locks now?

**Comment by PeterMTaylor** [comment]
Suggesting we use a tag for either performance or benchmark so we can reference again here later?

**Comment by MDoerner** [comment]
There are two possible reasons I can think of:

1. If you do not look at the pure parsing time but the the total time for a parsing run, you will see an increase because the COM collector started to use the actual type names for enums in referenced libraries even if the enums are in another library that is not referenced. That causes a ton of errors in the type annotation pass that all get logged on warning level.

2. There is now more logging in the parser, which was probably a bad idea. I think we should actually only log errors in concurrently paralellized code. The logger probably forces a synchronization. However, how bad this is really depends on the implementation of Nlog.

**Comment by PeterMTaylor** [comment]
Food for thought from me here about Nlog. 
Found an SO answer about Nlog.
Not sure if this is the problem, but pretty sure it is:
Reading the NLog.config from an unit test environment could be difficult, therefor is more robust to read the config from string in the unit tests. We use the helper:
    protected XmlLoggingConfiguration CreateConfigurationFromString(string configXml)
    {
        XmlDocument doc = new XmlDocument();
        doc.LoadXml(configXml);

        return new XmlLoggingConfiguration(doc.DocumentElement, Environment.CurrentDirectory);
    }
and then:
 LogManager.Configuration = CreateConfigurationFromString(@"
            <nlog throwExceptions='true'>
                <targets><target name='debug' type='debug' layout='${message}' /></targets>
                <rules>
                    <logger name='*' minlevel='info' appendto='debug'>
                        <filters>
                            <whencontains layout='${message}' substring='msg' action='ignore' />
                        </filters>
                    </logger>
                </rules>
            </nlog>");
don't forget to reset the LogManager.Configuration before or after each test.
Update : enabled throwExceptions in config.
Also about the error. You need probably an absolute path in the unit test.
https://stackoverflow.com/questions/39476927/nlog-and-unit-testing

**Comment by bclothier** [comment]
I'm referring to the status being stuck on `Parsing` for extraordinary long time. Mansallen mentioned a need for baseline so I went and grabbed the original 2.2 release. In both cases, I loaded exact same VBA project, and did a parsing. You can see how original 2.2 compares to the current `next` release:

```
2018-08-25 23:02:56.0802;DEBUG-2.2.6811.41439;Rubberduck.Parsing.VBA.ParseCoordinator;Parsing run finished after 21.1327857s. (thread 7).;
2018-08-26 09:42:43.1686;DEBUG-2.2.6812.17334;Rubberduck.Parsing.VBA.ParseCoordinator;Parsing run finished after 81.7404188s. (thread 11).;
```

Thus it's a full minute slower on the same VBA project. To be clear, we are comparing the debug versions, not release version as I used the git's tag to grab the 2.2 version and built the debug version, so it's closest to apple-apple comparison. The 2.2 generated 3955 lines of log output while the `next` generated 4195 lines, so there is not significantly much more log noise that might contribute to the slowdown. Neither had any errors.

Ironically, the version 2.2 had 3 instances of this, causing it to switch to LL mode to recover. That did not happen in the `next`.

```
2018-08-25 23:02:38.1712;DEBUG-2.2.6811.41439;Rubberduck.Parsing.VBA.VBAModuleParser;SLL mode exception;Rubberduck.Parsing.Symbols.ParsingExceptions.MainParseSyntaxErrorException: mismatched input 'CriteriaLabelName' expecting {<EOF>, ':', REM, NEWLINE, ''', WS, LINE_CONTINUATION} ---> Antlr4.Runtime.InputMismatchException: Exception of type 'Antlr4.Runtime.InputMismatchException' was thrown.
   at Antlr4.Runtime.DefaultErrorStrategy.Sync(Parser recognizer)
   at Rubberduck.Parsing.Grammar.VBAParser.endOfStatement() in C:\GitHub\Rubberduck\Rubberduck\Rubberduck.Parsing\obj\Debug\VBAParser.cs:line 19566
   --- End of inner exception stack trace ---
   at Rubberduck.Parsing.Symbols.ParsingExceptions.MainParseExceptionErrorListener.SyntaxError(IRecognizer recognizer, IToken offendingSymbol, Int32 line, Int32 charPositionInLine, String msg, RecognitionException e) in C:\GitHub\Rubberduck\Rubberduck\Rubberduck.Parsing\Symbols\ParsingExceptions\MainParseExceptionErrorListener.cs:line 15
   at Antlr4.Runtime.ProxyErrorListener`1.SyntaxError(IRecognizer recognizer, Symbol offendingSymbol, Int32 line, Int32 charPositionInLine, String msg, RecognitionException e)
   at Antlr4.Runtime.Parser.NotifyErrorListeners(IToken offendingToken, String msg, RecognitionException e)
   at Antlr4.Runtime.DefaultErrorStrategy.NotifyErrorListeners(Parser recognizer, String message, RecognitionException e)
   at Antlr4.Runtime.DefaultErrorStrategy.ReportInputMismatch(Parser recognizer, InputMismatchException e)
   at Antlr4.Runtime.DefaultErrorStrategy.ReportError(Parser recognizer, RecognitionException e)
   at Rubberduck.Parsing.Grammar.VBAParser.endOfStatement() in C:\GitHub\Rubberduck\Rubberduck\Rubberduck.Parsing\obj\Debug\VBAParser.cs:line 19653
   at Rubberduck.Parsing.Grammar.VBAParser.block() in C:\GitHub\Rubberduck\Rubberduck\Rubberduck.Parsing\obj\Debug\VBAParser.cs:line 1634
   at Rubberduck.Parsing.Grammar.VBAParser.elseBlock() in C:\GitHub\Rubberduck\Rubberduck\Rubberduck.Parsing\obj\Debug\VBAParser.cs:line 8251
   at Rubberduck.Parsing.Grammar.VBAParser.ifStmt() in C:\GitHub\Rubberduck\Rubberduck\Rubberduck.Parsing\obj\Debug\VBAParser.cs:line 8085
   at Rubberduck.Parsing.Grammar.VBAParser.mainBlockStmt() in C:\GitHub\Rubberduck\Rubberduck\Rubberduck.Parsing\obj\Debug\VBAParser.cs:line 1961
   at Rubberduck.Parsing.Grammar.VBAParser.blockStmt() in C:\GitHub\Rubberduck\Rubberduck\Rubberduck.Parsing\obj\Debug\VBAParser.cs:line 1721
   at Rubberduck.Parsing.Grammar.VBAParser.block() in C:\GitHub\Rubberduck\Rubberduck\Rubberduck.Parsing\obj\Debug\VBAParser.cs:line 1633
   at Rubberduck.Parsing.Grammar.VBAParser.doLoopStmt() in C:\GitHub\Rubberduck\Rubberduck\Rubberduck.Parsing\obj\Debug\VBAParser.cs:line 6738
   at Rubberduck.Parsing.Grammar.VBAParser.mainBlockStmt() in C:\GitHub\Rubberduck\Rubberduck\Rubberduck.Parsing\obj\Debug\VBAParser.cs:line 1898
   at Rubberduck.Parsing.Grammar.VBAParser.blockStmt() in C:\GitHub\Rubberduck\Rubberduck\Rubberduck.Parsing\obj\Debug\VBAParser.cs:line 1721
   at Rubberduck.Parsing.Grammar.VBAParser.block() in C:\GitHub\Rubberduck\Rubberduck\Rubberduck.Parsing\obj\Debug\VBAParser.cs:line 1633
   at Rubberduck.Parsing.Grammar.VBAParser.subStmt() in C:\GitHub\Rubberduck\Rubberduck\Rubberduck.Parsing\obj\Debug\VBAParser.cs:line 12023
   at Rubberduck.Parsing.Grammar.VBAParser.moduleBodyElement() in C:\GitHub\Rubberduck\Rubberduck\Rubberduck.Parsing\obj\Debug\VBAParser.cs:line 1569
   at Rubberduck.Parsing.Grammar.VBAParser.moduleBody() in C:\GitHub\Rubberduck\Rubberduck\Rubberduck.Parsing\obj\Debug\VBAParser.cs:line 1472
   at Rubberduck.Parsing.Grammar.VBAParser.module() in C:\GitHub\Rubberduck\Rubberduck\Rubberduck.Parsing\obj\Debug\VBAParser.cs:line 428
   at Rubberduck.Parsing.Grammar.VBAParser.startRule() in C:\GitHub\Rubberduck\Rubberduck\Rubberduck.Parsing\obj\Debug\VBAParser.cs:line 328
   at Rubberduck.Parsing.VBA.VBAModuleParser.Parse(String moduleName, CommonTokenStream moduleTokens, IParseTreeListener[] listeners, BaseErrorListener errorListener) in C:\GitHub\Rubberduck\Rubberduck\Rubberduck.Parsing\VBA\VBAModuleParser.cs:line 25
Token: CriteriaLabelName at L259C30
Component: ReportGeneratorClass (code pane version)
ParseType: Main parse
```

Logically since there weren't any parser error causing LL switch, the `next` should have been even faster but it's not happening.

**Comment by bclothier** [comment]
Some followup -

As there was question to whether the logging can be a factor, I verified that the time to parse did not change whether:

1) I used a debug or release build
2) I set the logging level to `None` or `Trace

I also tried to configure the NLog, using either [`AsyncWrapper` or `async` attribute](https://github.com/NLog/NLog/wiki/AsyncWrapper-target) or [`BufferingWriter`](https://github.com/NLog/NLog/wiki/BufferingWrapper-target). In all cases, there were no significant change in the time to parse.

**Comment by MDoerner** [comment]
I investigated a bit and the commit responsible for the first doubling of the parse time is https://github.com/rubberduck-vba/Rubberduck/pull/4242/commits/f2b5f185329e69eda9739893a79ccdcc8448c852

**Comment by MDoerner** [comment]
Further investigation show that the line registering the `SourceFileHandler` caused the parsing time to double, for a good reason: 

Prior to this PR, there was no explicit registration of the `SourceFileHandler`. Accordingly, the default interface registration kicked in and used the first registration implementation it encountered, the one for VB6. That implementation does not export the modules for the attributes pass and simply tries to read them from disk. (For VB6, the source files are persisted as separate text files.) Since there was no file, the handler returns an empty string, basically canceling the attributes pass. 

With the addition of the correct registration, the attributes pass retuned and, thus, we parse each module another time.

I will keep investigating where the remainder of the slow down originates from.

**Comment by MDoerner** [comment]
The remaining slowdown happened after commit https://github.com/rubberduck-vba/Rubberduck/pull/4242/commits/d40c6fa5cd4413d23516754403f9cdc541e7a937.
