### ISSUE TITLE
Scale keyword in UDT as a member name is a parser error

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#4328]
Stumbled upon this while I was playing with a `tagDEC` struct:

```
Option Explicit

' https://docs.microsoft.com/en-us/windows/desktop/api/wtypes/ns-wtypes-tagdec
Private Type tagDec
    wReserved As Integer
    scale As Byte
    sign As Byte
    Hi32 As Long
    Lo64Lo As Long
    Lo64Hi As Long
End Type
```
The parser is choking on the `scale` member because it's a keyword.

Relevant log bit:

```
2018-08-30 11:16:07.1279;ERROR-2.2.0.3624;Rubberduck.Parsing.VBA.Parsing.ModuleParser;Syntax error; offending token 'scale' at line 6, column 5 in the CodePaneCode version of module Module1.;
2018-08-30 11:16:07.1279;DEBUG-2.2.0.3624;Rubberduck.Parsing.VBA.Parsing.ModuleParser;SyntaxErrorException thrown in thread 31, ParseTaskID a1d3ada6-85ce-4f61-98a9-30829356b3bf.;Rubberduck.Parsing.Symbols.ParsingExceptions.MainParseSyntaxErrorException: mismatched input 'scale' expecting END_TYPE ---> Antlr4.Runtime.InputMismatchException: Exception of type 'Antlr4.Runtime.InputMismatchException' was thrown.
   at Antlr4.Runtime.DefaultErrorStrategy.RecoverInline(Parser recognizer)
   at Antlr4.Runtime.Parser.Match(Int32 ttype)
   at Rubberduck.Parsing.Grammar.VBAParser.udtDeclaration() in C:\projects\rubberduck\Rubberduck.Parsing\obj\Release\VBAParser.cs:line 13232
   --- End of inner exception stack trace ---
   at Rubberduck.Parsing.Symbols.ParsingExceptions.MainParseExceptionErrorListener.SyntaxError(IRecognizer recognizer, IToken offendingSymbol, Int32 line, Int32 charPositionInLine, String msg, RecognitionException e) in C:\projects\rubberduck\Rubberduck.Parsing\Symbols\ParsingExceptions\MainParseExceptionErrorListener.cs:line 17
   at Antlr4.Runtime.ProxyErrorListener`1.SyntaxError(IRecognizer recognizer, Symbol offendingSymbol, Int32 line, Int32 charPositionInLine, String msg, RecognitionException e)
   at Antlr4.Runtime.Parser.NotifyErrorListeners(IToken offendingToken, String msg, RecognitionException e)
   at Antlr4.Runtime.DefaultErrorStrategy.NotifyErrorListeners(Parser recognizer, String message, RecognitionException e)
   at Antlr4.Runtime.DefaultErrorStrategy.ReportInputMismatch(Parser recognizer, InputMismatchException e)
   at Antlr4.Runtime.DefaultErrorStrategy.ReportError(Parser recognizer, RecognitionException e)
   at Rubberduck.Parsing.Grammar.VBAParser.udtDeclaration() in C:\projects\rubberduck\Rubberduck.Parsing\obj\Release\VBAParser.cs:line 13237
   at Rubberduck.Parsing.Grammar.VBAParser.moduleDeclarationsElement() in C:\projects\rubberduck\Rubberduck.Parsing\obj\Release\VBAParser.cs:line 2257
   at Rubberduck.Parsing.Grammar.VBAParser.moduleDeclarations() in C:\projects\rubberduck\Rubberduck.Parsing\obj\Release\VBAParser.cs:line 1945
   at Rubberduck.Parsing.Grammar.VBAParser.module() in C:\projects\rubberduck\Rubberduck.Parsing\obj\Release\VBAParser.cs:line 442
   at Rubberduck.Parsing.Grammar.VBAParser.startRule() in C:\projects\rubberduck\Rubberduck.Parsing\obj\Release\VBAParser.cs:line 332
   at Rubberduck.Parsing.VBA.Parsing.VBATokenStreamParser.Parse(ITokenStream tokenStream, PredictionMode predictionMode, IParserErrorListener errorListener) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\Parsing\VBATokenStreamParser.cs:line 21
   at Rubberduck.Parsing.VBA.Parsing.TokenStreamParserBase.ParseSll(String moduleName, ITokenStream tokenStream, CodeKind codeKind) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\Parsing\TokenStreamParserBase.cs:line 84
   at Rubberduck.Parsing.VBA.Parsing.TokenStreamParserBase.ParseWithFallBack(String moduleName, CommonTokenStream tokenStream, CodeKind codeKind) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\Parsing\TokenStreamParserBase.cs:line 52
   at Rubberduck.Parsing.VBA.Parsing.TokenStreamParserBase.Parse(String moduleName, CommonTokenStream tokenStream, CodeKind codeKind, ParserMode parserMode) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\Parsing\TokenStreamParserBase.cs:line 32
   at Rubberduck.Parsing.VBA.Parsing.TokenStreamParserStringParserAdapterWithPreprocessing.Parse(String moduleName, String projectId, String code, CancellationToken token, CodeKind codeKind, ParserMode parserMode) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\Parsing\TokenStreamParserStringParserAdapterWithPreprocessing.cs:line 29
   at Rubberduck.Parsing.VBA.Parsing.ModuleParser.CodePanePassResults(QualifiedModuleName module, CancellationToken token, TokenStreamRewriter rewriter) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\Parsing\ModuleParser.cs:line 167
   at Rubberduck.Parsing.VBA.Parsing.ModuleParser.ParseInternal(QualifiedModuleName module, CancellationToken cancellationToken, TokenStreamRewriter rewriter, Guid taskId) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\Parsing\ModuleParser.cs:line 87
   at Rubberduck.Parsing.VBA.Parsing.ModuleParser.Parse(QualifiedModuleName module, CancellationToken cancellationToken, TokenStreamRewriter rewriter) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\Parsing\ModuleParser.cs:line 43
Token: scale at L6C5
Kind of parsed code: CodePaneCode
Component: Module1 (code pane version)
ParseType: Main parse
```

**Comment by comintern** [comment]
It also doesn't like `Circle`.
```
Public Type RoundThing
    Circle As Boolean
End Type
```

**Comment by MDoerner** [comment]
The problem is that tokens for these keywords have been added to the lexer but not the `keyword` rule for the parser. This is why they are not picked up by the `unrestrictedIdentifier` parser rule.
