### ISSUE TITLE
"Refactor: Extract Interface" is broken

### ISSUE THREAD

**Issue by Inarion** [rubberduck-vba/Rubberduck#4361]
A picture tells more than a thousand words:

![extractinterface](https://user-images.githubusercontent.com/28350405/45416064-5f410a80-b67f-11e8-8fb0-0a8cd1c6b038.PNG)

From my testing the number of empty fields in the Members list seems to correspond to the number of public procedures in my class (as expected). Just the lack of any sort of description/name is curious.  
A test with a different class with significantly less members yields the same result, with just 3 empty fields.  
Clicking `Select All` and confirming with `Ok` doesn't seem to do anything.

Not sure if this should go into a separate issue: The Members list is not scrollable. I can move the focus down the list (out of sight basically) with the arrow keys, but I found no way to scroll. 

```
Version 2.2.0.3762
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2010 x86
Host Version: 14.0.7210.5000
Host Executable: EXCEL.EXE
```

**Comment by comintern** [comment]
This is a binding issue. Debug output:

```
Exception thrown: 'System.NullReferenceException' in Rubberduck.Core.dll
**_wrapped** was null.

The thread 0x2d5c has exited with code 0 (0x0).
System.Windows.Data Error: 17 : Cannot get 'FullMemberSignature' value (type 'String') from '' (type 'InterfaceMemberViewModel'). BindingExpression:Path=FullMemberSignature; DataItem='InterfaceMemberViewModel' (HashCode=42701800); target element is 'TextBlock' (Name=''); target property is 'Text' (type 'String') TargetInvocationException:'System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.UI.Refactorings.ExtractInterface.InterfaceMemberViewModel.get_FullMemberSignature() in C:\Rubberduck\Rubberduck.Core\UI\Refactorings\ExtractInterface\InterfaceMemberViewModel.cs:line 29
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at MS.Internal.Data.PropertyPathWorker.GetValue(Object item, Int32 level)
   at MS.Internal.Data.PropertyPathWorker.RawValue(Int32 k)'
```

**Comment by comintern** [comment]
Linking [chat](https://chat.stackexchange.com/transcript/message/46827783#46827783). This is likely a much wider issue than just this dialog.

**Comment by retailcoder** [comment]
I'm not sure how that UI ever worked at all... the `<StackPanel>` is what's preventing the scrollbars from being shown (the control just expands beyond the bottom of the parent WinForms dialog); the NRE is specific to that ViewModel, fix on the way.
