### ISSUE TITLE
V 2.3.0.4221 Extract Interface does not do anything

### ISSUE THREAD

**Issue by devtycoon** [rubberduck-vba/Rubberduck#4552]
Hopefully this picture will help.  When I try to extract interface nothing happens.  Thanks for the help / tips to get this to work!

![picture1](https://user-images.githubusercontent.com/16538715/48991865-3367e980-f0f2-11e8-9e3a-1ab0cddc08b7.png)

**Comment by retailcoder** [comment]
The class in the screenshot looks suspicious - `Message1`, `Message2` and `Message3` functions don't return a value, and `Message` doesn't look like it's declared... despite `Option Explicit` being specified.

That said, I did reproduce the issue. Logs:

```
2018-11-25 22:10:21.2227;DEBUG-2.2.6903.39760;Rubberduck.UI.Command.MenuItems.ParentMenus.ParentMenuItemBase;(35342723) Executing click handler for menu item 'E&xtract Interface', hash code 50697487;
2018-11-25 22:10:21.7597;ERROR-2.2.6903.39760;Rubberduck.UI.Command.Refactorings.RefactorCommandBase;System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Rubberduck.UI.Refactorings.ExtractInterfaceDialog.resources" was correctly embedded or linked into assembly "Rubberduck.Core" at compile time, or that all the satellite assemblies required are loadable and fully signed.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at System.Resources.ResourceManager.GetObject(String name)
   at Rubberduck.UI.Refactorings.ExtractInterfaceDialog.InitializeComponent() in C:\Dev\GitHub\Rubberduck\Rubberduck.Core\UI\Refactorings\ExtractInterface\ExtractInterfaceDialog.Designer.cs:line 53
   at Rubberduck.UI.Refactorings.ExtractInterfaceDialog..ctor() in C:\Dev\GitHub\Rubberduck\Rubberduck.Core\UI\Refactorings\ExtractInterface\ExtractInterfaceDialog.cs:line 12
   at Rubberduck.UI.Refactorings.ExtractInterfaceDialog..ctor(ExtractInterfaceViewModel vm) in C:\Dev\GitHub\Rubberduck\Rubberduck.Core\UI\Refactorings\ExtractInterface\ExtractInterfaceDialog.cs:line 16
   at Rubberduck.UI.Command.Refactorings.RefactorExtractInterfaceCommand.OnExecute(Object parameter) in C:\Dev\GitHub\Rubberduck\Rubberduck.Core\UI\Command\Refactorings\RefactorExtractInterfaceCommand.cs:line 88
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in C:\Dev\GitHub\Rubberduck\Rubberduck.Core\UI\Command\CommandBase.cs:line 47;System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Rubberduck.UI.Refactorings.ExtractInterfaceDialog.resources" was correctly embedded or linked into assembly "Rubberduck.Core" at compile time, or that all the satellite assemblies required are loadable and fully signed.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at System.Resources.ResourceManager.GetObject(String name)
   at Rubberduck.UI.Refactorings.ExtractInterfaceDialog.InitializeComponent() in C:\Dev\GitHub\Rubberduck\Rubberduck.Core\UI\Refactorings\ExtractInterface\ExtractInterfaceDialog.Designer.cs:line 53
   at Rubberduck.UI.Refactorings.ExtractInterfaceDialog..ctor() in C:\Dev\GitHub\Rubberduck\Rubberduck.Core\UI\Refactorings\ExtractInterface\ExtractInterfaceDialog.cs:line 12
   at Rubberduck.UI.Refactorings.ExtractInterfaceDialog..ctor(ExtractInterfaceViewModel vm) in C:\Dev\GitHub\Rubberduck\Rubberduck.Core\UI\Refactorings\ExtractInterface\ExtractInterfaceDialog.cs:line 16
   at Rubberduck.UI.Command.Refactorings.RefactorExtractInterfaceCommand.OnExecute(Object parameter) in C:\Dev\GitHub\Rubberduck\Rubberduck.Core\UI\Command\Refactorings\RefactorExtractInterfaceCommand.cs:line 88
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in C:\Dev\GitHub\Rubberduck\Rubberduck.Core\UI\Command\CommandBase.cs:line 47
```

Looks like I messed up something in #4527 - thanks for reporting this!

**Comment by retailcoder** [comment]
no-repro off current [next]
