### ISSUE TITLE
Create Unit Test Module Does not work

### ISSUE THREAD

**Issue by devtycoon** [rubberduck-vba/Rubberduck#4553]
I tried changing the macro settings and then restarting the program.  Am I doing this right?  Thanks for the help!
![capture](https://user-images.githubusercontent.com/16538715/48993408-b5f4a700-f0fa-11e8-9b3a-3c01cdb9b26e.PNG)

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/2614080/RubberduckLog.txt)

**Comment by retailcoder** [comment]
Macro security shouldn't need to be lowered (as long as macros are enabled and VBA code is allowed to run) - looks like we're going to have to ship a hotfix release this week...

**Comment by Vogel612** [comment]
The stacktrace in the log implies we're incorrectly handling a COM object in that part of the codebase. Thanks for the report :)

```
2018-11-25 21:37:01.8147;WARN-2.3.0.4221;Rubberduck.UI.UnitTesting.Commands.AddTestModuleCommand;Unable to add test module. An exception was thrown.;
2018-11-25 21:37:01.8277;WARN-2.3.0.4221;Rubberduck.UI.UnitTesting.Commands.AddTestModuleCommand;System.Runtime.InteropServices.InvalidComObjectException: COM object that has been separated from its underlying RCW cannot be used.
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Vbe.Interop._VBProject.get_Protection()
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBProject.get_Protection() in C:\projects\rubberduck\Rubberduck.VBEditor.VBA\SafeComWrappers\VB\VBProject.cs:line 49
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBProject.get_VBComponents() in C:\projects\rubberduck\Rubberduck.VBEditor.VBA\SafeComWrappers\VB\VBProject.cs:line 47
   at Rubberduck.UI.UnitTesting.Commands.AddTestModuleCommand.ExecuteInternal(IVBProject project, Declaration projectDeclaration) in C:\projects\rubberduck\Rubberduck.Core\UI\UnitTesting\Commands\AddTestModuleCommand.cs:line 195;System.Runtime.InteropServices.InvalidComObjectException: COM object that has been separated from its underlying RCW cannot be used.
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Vbe.Interop._VBProject.get_Protection()
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBProject.get_Protection() in C:\projects\rubberduck\Rubberduck.VBEditor.VBA\SafeComWrappers\VB\VBProject.cs:line 49
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBProject.get_VBComponents() in C:\projects\rubberduck\Rubberduck.VBEditor.VBA\SafeComWrappers\VB\VBProject.cs:line 47
   at Rubberduck.UI.UnitTesting.Commands.AddTestModuleCommand.ExecuteInternal(IVBProject project, Declaration projectDeclaration) in C:\projects\rubberduck\Rubberduck.Core\UI\UnitTesting\Commands\AddTestModuleCommand.cs:line 195
```

**Comment by Vogel612** [comment]
As a workaround you could add the module without involving Rubberduck. The module will still be discovered after parsing then.

**Comment by retailcoder** [comment]
![unable to create test module](https://user-images.githubusercontent.com/5751684/49020874-71e7bd80-f15f-11e8-914e-f055709b557e.png)

Adding test module manually does work though, and tests run fine.

**Comment by devtycoon** [comment]
Thanks, you folks are great.  I hope to get on your level one day.
