### ISSUE TITLE
Excel crash on exit

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4584]
Over the last several weeks, I've had an increasing frequency of Excel crashing on exit. I'm running Win10, Excel 2016 (desktop) and have had several incremental builds installed. Currently, I'm on .4235, and was shutting down to install .4244 to test another fix.

Here's the complete log after one such event.
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/2633368/RubberduckLog.txt)

This was with one XLSM opened. 

I clicked the "red X" to close Excel, then told it to save when prompted. It appears that my code changes _are_ being saved (whew!). As it crashes, I'm cancelling the "trying to figure out what went wrong" dialog and the "Excel is restarting" dialog. I then reopen by hand because I'm weird that way.

**Comment by comintern** [comment]
Can you dig the WER report out of the Event Log for one of these crashes and post the details here? The proximate cause is this:

```

2018-11-30 08:29:34.4297;TRACE-2.3.0.4235;Rubberduck.VBEditor.WindowsApi.SubclassManager;Releasing subclass for hWnd 0x00581520.;
2018-11-30 08:29:34.4609;ERROR-2.3.0.4235;Rubberduck._Extension;System.Exception: RemoveWindowSubclass Failed
   at Rubberduck.VBEditor.WindowsApi.SubclassingWindow.ReleaseHandle() in C:\projects\rubberduck\Rubberduck.VBEEditor\WindowsApi\SubclassingWindow.cs:line 73
   at Rubberduck.VBEditor.WindowsApi.SubclassingWindow.Dispose(Boolean disposing) in C:\projects\rubberduck\Rubberduck.VBEEditor\WindowsApi\SubclassingWindow.cs:line 125
   at Rubberduck.VBEditor.WindowsApi.FocusSource.Dispose(Boolean disposing) in C:\projects\rubberduck\Rubberduck.VBEEditor\WindowsApi\FocusSource.cs:line 45
   at Rubberduck.VBEditor.WindowsApi.VbeAttachableSubclass`1.Dispose(Boolean disposing) in C:\projects\rubberduck\Rubberduck.VBEEditor\WindowsApi\VbeAttachableSubclass.cs:line 86
   at Rubberduck.VBEditor.WindowsApi.CodePaneSubclass.Dispose(Boolean disposing) in C:\projects\rubberduck\Rubberduck.VBEEditor\WindowsApi\CodePaneSubclass.cs:line 66
   at Rubberduck.VBEditor.WindowsApi.SubclassManager.Dispose(Boolean disposing) in C:\projects\rubberduck\Rubberduck.VBEEditor\WindowsApi\SubclassManager.cs:line 138
   at Rubberduck.VBEditor.Events.VbeNativeServices.UnhookEvents() in C:\projects\rubberduck\Rubberduck.VBEEditor\Events\VBENativeServices.cs:line 50
   at Rubberduck._Extension.ShutdownAddIn() in C:\projects\rubberduck\Rubberduck.Main\Extension.cs:line 246;System.Exception: RemoveWindowSubclass Failed
   at Rubberduck.VBEditor.WindowsApi.SubclassingWindow.ReleaseHandle() in C:\projects\rubberduck\Rubberduck.VBEEditor\WindowsApi\SubclassingWindow.cs:line 73
   at Rubberduck.VBEditor.WindowsApi.SubclassingWindow.Dispose(Boolean disposing) in C:\projects\rubberduck\Rubberduck.VBEEditor\WindowsApi\SubclassingWindow.cs:line 125
   at Rubberduck.VBEditor.WindowsApi.FocusSource.Dispose(Boolean disposing) in C:\projects\rubberduck\Rubberduck.VBEEditor\WindowsApi\FocusSource.cs:line 45
   at Rubberduck.VBEditor.WindowsApi.VbeAttachableSubclass`1.Dispose(Boolean disposing) in C:\projects\rubberduck\Rubberduck.VBEEditor\WindowsApi\VbeAttachableSubclass.cs:line 86
   at Rubberduck.VBEditor.WindowsApi.CodePaneSubclass.Dispose(Boolean disposing) in C:\projects\rubberduck\Rubberduck.VBEEditor\WindowsApi\CodePaneSubclass.cs:line 66
   at Rubberduck.VBEditor.WindowsApi.SubclassManager.Dispose(Boolean disposing) in C:\projects\rubberduck\Rubberduck.VBEEditor\WindowsApi\SubclassManager.cs:line 138
   at Rubberduck.VBEditor.Events.VbeNativeServices.UnhookEvents() in C:\projects\rubberduck\Rubberduck.VBEEditor\Events\VBENativeServices.cs:line 50
   at Rubberduck._Extension.ShutdownAddIn() in C:\projects\rubberduck\Rubberduck.Main\Extension.cs:line 246
```

That' an error that we're throwing (mainly because it will take the host down when that call fails). I scanned the rest of the log, and the failing call is the only `RemoveWindowSubclass` call for that hWnd, so that should really never be failing unless the window gets destroyed without RD getting notified in the message pump.

**Comment by daFreeMan** [comment]
Just had a crash this morning. I believe this is what you're after. I think that 08:14:42am error is the Excel crash, but I grabbed all 4 that have occurred this morning. If this isn't what you're after, you'll have to give me a better roadmap.


[2018.12.04 Excel crash event logs.evtx.txt](https://github.com/rubberduck-vba/Rubberduck/files/2644087/2018.12.04.Excel.crash.event.logs.evtx.txt)

Simply remove the ".txt" extension to "convert" it back to a ".evtx" file due to GH's file type requirements.

**Comment by retailcoder** [comment]
> Faulting application name: EXCEL.EXE, version: 16.0.4771.1000, time stamp: 0x5bc5f806
Faulting module name: KERNELBASE.dll, version: 10.0.15063.1446, time stamp: 0xdf98f224
Exception code: 0xe0434352
Fault offset: 0x00000000000656b8
Faulting process id: 0x250c
Faulting application start time: 0x01d48b3853b72ec2
Faulting application path: C:\Program Files\Office 2016\Office16\EXCEL.EXE
Faulting module path: C:\windows\System32\KERNELBASE.dll
Report Id: 01b1f065-650c-4bf1-a0cf-238d8110ba8a
Faulting package full name: 
Faulting package-relative application ID:

**Comment by daFreeMan** [comment]
I am. I'll be sure to grab a couple of crash logs when I'm back in the office.
I'm getting crashes from Excel when I've got several workbooks open, not just on exit now. I'm not convinced it's an RD issue, but I feel that I'll get a better and more responsive investigation from you guys than I ever would from MS. ;)

**Comment by bclothier** [comment]
@daFreeMan Still observing this?

**Comment by daFreeMan** [comment]
Nope. Weird, random crashes, but nothing consistent like I had been having.

Closing as "works on my machine".
