### ISSUE TITLE
Crashes Excel - Auto-complete on continuation line

### ISSUE THREAD

**Issue by pmtutko** [rubberduck-vba/Rubberduck#4621]
I'm getting a consistent crash in the following simple scenario:

In a New, empty workbook, create a code module. In the module, create a single Sub:

    Sub Test()
        Err.Raise 5, _
                  "          <---- crashes when you type the first double-quote
    End Sub

*Version 2.3.0.4221
OS: Microsoft Windows NT 10.0.16299.0, x64
Host Product: Microsoft Office 2013 x86
Host Version: 15.0.5085.1000
Host Executable: EXCEL.EXE*

**Comment by retailcoder** [comment]
Thanks for reporting this!! *Just* in time to stop the 2.3.1 hotfix release! :+1:

**Comment by comintern** [comment]
Did you happen to get a log file for this?  Also, if you can dig of the WER app crash record, that might also be useful.

**Comment by retailcoder** [comment]
Confirmed repro with .4269

Version 2.3.0.4269
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2010 x86
Host Version: 14.0.7212.5000
Host Executable: EXCEL.EXE

Note that this doesn't crash:

    MsgBox _
    "

**Comment by pmtutko** [comment]
Didn't get a crash dump, but here's the log:

2018-12-07 15:11:32.2825;ERROR-2.3.0.4221;Rubberduck.Common.LogLevelHelper;
	Rubberduck version 2.3.0.4221 loading:
	Operating System: Microsoft Windows NT 10.0.16299.0 x64
	Host Product: Microsoft Office 2013 x86
	Host Version: 15.0.5085.1000
	Host Executable: EXCEL.EXE;
2018-12-07 15:11:32.8156;ERROR-2.3.0.4221;Rubberduck.UI.UnitTesting.Commands.AddTestModuleCommand;System.Runtime.InteropServices.InvalidComObjectException: COM object that has been separated from its underlying RCW cannot be used.
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Vbe.Interop._VBProject.get_Protection()
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBProject.get_Protection() in C:\projects\rubberduck\Rubberduck.VBEditor.VBA\SafeComWrappers\VB\VBProject.cs:line 49
   at Rubberduck.UI.UnitTesting.Commands.AddTestModuleCommand.EvaluateCanExecute(Object parameter) in C:\projects\rubberduck\Rubberduck.Core\UI\UnitTesting\Commands\AddTestModuleCommand.cs:line 148
   at Rubberduck.UI.Command.CommandBase.CanExecute(Object parameter) in C:\projects\rubberduck\Rubberduck.Core\UI\Command\CommandBase.cs:line 28;System.Runtime.InteropServices.InvalidComObjectException: COM object that has been separated from its underlying RCW cannot be used.
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Vbe.Interop._VBProject.get_Protection()
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBProject.get_Protection() in C:\projects\rubberduck\Rubberduck.VBEditor.VBA\SafeComWrappers\VB\VBProject.cs:line 49
   at Rubberduck.UI.UnitTesting.Commands.AddTestModuleCommand.EvaluateCanExecute(Object parameter) in C:\projects\rubberduck\Rubberduck.Core\UI\UnitTesting\Commands\AddTestModuleCommand.cs:line 148
   at Rubberduck.UI.Command.CommandBase.CanExecute(Object parameter) in C:\projects\rubberduck\Rubberduck.Core\UI\Command\CommandBase.cs:line 28

**Comment by retailcoder** [comment]
FWIW, here's the stack trace for the actual exception - an `IndexOutOfBoundsException`, as I suspected:

```
   at System.String.get_Chars(Int32 index)
   at Rubberduck.AutoComplete.Service.SelfClosingPairCompletionService.Execute(SelfClosingPair pair, CodeString original, Char input, CodeString& result) in C:\Dev\GitHub\Rubberduck\Rubberduck.Core\AutoComplete\Service\SelfClosingPairCompletionService.cs:line 30
   at Rubberduck.AutoComplete.Service.SelfClosingPairHandler.HandleInternal(AutoCompleteEventArgs e, CodeString original, SelfClosingPair pair, CodeString& result) in C:\Dev\GitHub\Rubberduck\Rubberduck.Core\AutoComplete\Service\SelfClosingPairHandler.cs:line 107
   at Rubberduck.AutoComplete.Service.SelfClosingPairHandler.Handle(AutoCompleteEventArgs e, AutoCompleteSettings settings, CodeString& result) in C:\Dev\GitHub\Rubberduck\Rubberduck.Core\AutoComplete\Service\SelfClosingPairHandler.cs:line 55
   at Rubberduck.AutoComplete.Service.AutoCompleteService.TryHandle(AutoCompleteEventArgs e, AutoCompleteHandlerBase handler) in C:\Dev\GitHub\Rubberduck\Rubberduck.Core\AutoComplete\Service\AutoCompleteService.cs:line 149
```

This exception is now successfully caught & handled (logged), gracefully failing any autocompletion handler that throws.

Working on the root cause now, but still unable to reproduce the issue with a unit test.
