### ISSUE TITLE
Results missing from Code Inspections window

### ISSUE THREAD

**Issue by chrisdaniels** [rubberduck-vba/Rubberduck#4644]
Version 2.3.1.4308

I have noticed that the code inspection window will sometimes not display expected results.

Noticed this against **Procedure Not Used** & **Statically accessible sheet accessed using string**.

I cannot replicate for the Procedure Not Used at the moment, but have replicated for Statically accessible sheet.

Logs attached - log for Showing has 4 instances, I then ignored one and reparsed and they all disapeared. This is exact same behaviour to what I have seen for Procedure Not Used, but I cannot seem to replicate.

[RubberduckLog - missing Statically Accessible.txt](https://github.com/rubberduck-vba/Rubberduck/files/2686590/RubberduckLog.-.missing.Statically.Accessible.txt)

[RubberduckLog - Showing Statically Accessible sheet.txt](https://github.com/rubberduck-vba/Rubberduck/files/2686578/RubberduckLog.-.Showing.Statically.Accessible.sheet.txt)

**Comment by Vogel612** [comment]
The issue seems to be a COM-Exception that's blowing up when we're inspecting for that.

```
2018-12-17 15:02:01.0154;WARN-2.3.1.4308;Rubberduck.Inspections.Rubberduck.Inspections.Inspector;System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Microsoft.Vbe.Interop._VBComponent.get_Properties()
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBComponent.get_Properties() in C:\projects\rubberduck\Rubberduck.VBEditor.VBA\SafeComWrappers\VB\VBComponent.cs:line 26
   at Rubberduck.Inspections.Concrete.SheetAccessedUsingStringInspection.GetVBComponentMatchingSheetName(IdentifierReferenceInspectionResult reference) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\SheetAccessedUsingStringInspection.cs:line 105
   at Rubberduck.Inspections.Concrete.SheetAccessedUsingStringInspection.DoGetInspectionResults() in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\SheetAccessedUsingStringInspection.cs:line 55
   at Rubberduck.Inspections.Abstract.InspectionBase.GetInspectionResults(CancellationToken token) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Abstract\InspectionBase.cs:line 166
   at Rubberduck.Inspections.Rubberduck.Inspections.Inspector.RunInspection(IInspection inspection, ConcurrentBag`1 allIssues, CancellationToken token) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Inspector.cs:line 188;System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Microsoft.Vbe.Interop._VBComponent.get_Properties()
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBComponent.get_Properties() in C:\projects\rubberduck\Rubberduck.VBEditor.VBA\SafeComWrappers\VB\VBComponent.cs:line 26
   at Rubberduck.Inspections.Concrete.SheetAccessedUsingStringInspection.GetVBComponentMatchingSheetName(IdentifierReferenceInspectionResult reference) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\SheetAccessedUsingStringInspection.cs:line 105
   at Rubberduck.Inspections.Concrete.SheetAccessedUsingStringInspection.DoGetInspectionResults() in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\SheetAccessedUsingStringInspection.cs:line 55
   at Rubberduck.Inspections.Abstract.InspectionBase.GetInspectionResults(CancellationToken token) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Abstract\InspectionBase.cs:line 166
   at Rubberduck.Inspections.Rubberduck.Inspections.Inspector.RunInspection(IInspection inspection, ConcurrentBag`1 allIssues, CancellationToken token) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Inspector.cs:line 188
```

I also couldn't help but notice that the inspection *consistently* runs for about 70 seconds, taking up basically **all** of the time for inspecting for itself. This is especially visible in the Log titled "Showing Statically Accessible" when searching for `SheetAccessedUsingStringInspection`

**Comment by bclothier** [comment]
I had a look at this. I have issues with this inspection doing COM accesses. Because it takes 70 seconds, it is conceivable that the focus may have had moved to Excel formula bar while the inspections were running. When the focus is on the formula bar, the VBE is unavailable, and the access to the `VBComponent.Properties` has been shown to be sketchy. 

This needs to be using declarations for inspection. However, I think this is best fixed once the PR #4535 goes in so that we have access to the declarations and not require any COM accesses.
