### ISSUE TITLE
NRE in UnreachableCaseInspection

### ISSUE THREAD

**Issue by Vogel612** [rubberduck-vba/Rubberduck#4656]
Spotted in the logs presented in #4644. This was originally reported under #4258, but seems to have resurfaced:

```
2018-12-17 14:27:43.7524;WARN-2.3.1.4308;Rubberduck.Inspections.Rubberduck.Inspections.Inspector;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.GetConstantContextValueToken(ParserRuleContext context) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 324
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.GetContextValue(ParserRuleContext context, String& declaredTypeName, String& expressionValue) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 296
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.TryGetLExprValue(LExprContext lExprContext, String& expressionValue, String& declaredTypeName) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 271
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(LExprContext context) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 134
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(ParserRuleContext parserRuleContext) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 96
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.VisitChildren(ParserRuleContext context) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 247
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(ParserRuleContext parserRuleContext) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 106
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.VisitChildren(ParserRuleContext context) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 247
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(ParserRuleContext parserRuleContext) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 102
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(IParseTree tree) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 56
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.VisitChildren(IRuleNode node) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 67
   at Rubberduck.Parsing.Grammar.VBAParser.SelectCaseStmtContext.Accept[TResult](IParseTreeVisitor`1 visitor) in C:\projects\rubberduck\Rubberduck.Parsing\obj\Release\net46\VBAParser.cs:line 12464
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.UnreachableCaseInspection.DoGetInspectionResults() in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\UnreachableCaseInspection.cs:line 58
   at Rubberduck.Inspections.Abstract.InspectionBase.GetInspectionResults(CancellationToken token) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Abstract\InspectionBase.cs:line 166
   at Rubberduck.Inspections.Rubberduck.Inspections.Inspector.RunInspection(IInspection inspection, ConcurrentBag`1 allIssues, CancellationToken token) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Inspector.cs:line 188;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.GetConstantContextValueToken(ParserRuleContext context) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 324
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.GetContextValue(ParserRuleContext context, String& declaredTypeName, String& expressionValue) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 296
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.TryGetLExprValue(LExprContext lExprContext, String& expressionValue, String& declaredTypeName) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 271
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(LExprContext context) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 134
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(ParserRuleContext parserRuleContext) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 96
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.VisitChildren(ParserRuleContext context) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 247
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(ParserRuleContext parserRuleContext) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 106
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.VisitChildren(ParserRuleContext context) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 247
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(ParserRuleContext parserRuleContext) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 102
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(IParseTree tree) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 56
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.VisitChildren(IRuleNode node) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 67
   at Rubberduck.Parsing.Grammar.VBAParser.SelectCaseStmtContext.Accept[TResult](IParseTreeVisitor`1 visitor) in C:\projects\rubberduck\Rubberduck.Parsing\obj\Release\net46\VBAParser.cs:line 12464
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.UnreachableCaseInspection.DoGetInspectionResults() in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\UnreachableCaseInspection.cs:line 58
   at Rubberduck.Inspections.Abstract.InspectionBase.GetInspectionResults(CancellationToken token) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Abstract\InspectionBase.cs:line 166
   at Rubberduck.Inspections.Rubberduck.Inspections.Inspector.RunInspection(IInspection inspection, ConcurrentBag`1 allIssues, CancellationToken token) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Inspector.cs:line 188
```

**Comment by Vogel612** [comment]
closing this as duplicate of https://github.com/rubberduck-vba/Rubberduck/issues/4659
