### ISSUE TITLE
NRE in UnreachableCaseInspection

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#4659]
I noticed this while I was meatbagging the Code Explorer. The expression parser in the `UnreachableCaseInspection` apparently has problems with enumerations that use built-in constants. This MCVE...

```
Enum Fubar
    Foo = vbObjectError + 1
    Bar = vbObjectError + 2
End Enum

Sub Example()
    Select Case 42
        Case Fubar.Foo
            Debug.Print "Foo"
        Case Fubar.Bar
            Debug.Print "Bar"
    End Select
End Sub
```
...results in this error:

```
2018-12-18 17:19:14.9769;WARN-2.3.6926.13270;Rubberduck.Inspections.Rubberduck.Inspections.Inspector;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.GetConstantContextValueToken(ParserRuleContext context) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 324
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.GetContextValue(ParserRuleContext context, String& declaredTypeName, String& expressionValue) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 291
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.TryGetLExprValue(LExprContext lExprContext, String& expressionValue, String& declaredTypeName) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 271
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(LExprContext context) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 135
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(ParserRuleContext parserRuleContext) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 96
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.VisitChildren(ParserRuleContext context) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 247
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.VisitBinaryOpEvaluationContext(ParserRuleContext context) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 167
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(ParserRuleContext parserRuleContext) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 116
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.GetConstantContextValueToken(ParserRuleContext context) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 339
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.LoadEnumMemberValues() in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 393
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor..ctor(IParseTreeValueFactory valueFactory, List`1 allEnums, Func`2 idRefRetriever) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 45
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.UnreachableCaseInspection.CreateParseTreeValueVisitor(IParseTreeValueFactory valueFactory, List`1 allEnums, Func`2 func) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\UnreachableCaseInspection.cs:line 84
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.UnreachableCaseInspection.DoGetInspectionResults() in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\UnreachableCaseInspection.cs:line 55
   at Rubberduck.Inspections.Abstract.InspectionBase.GetInspectionResults(CancellationToken token) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Abstract\InspectionBase.cs:line 166
   at Rubberduck.Inspections.Rubberduck.Inspections.Inspector.RunInspection(IInspection inspection, ConcurrentBag`1 allIssues, CancellationToken token) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Inspector.cs:line 188;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.GetConstantContextValueToken(ParserRuleContext context) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 324
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.GetContextValue(ParserRuleContext context, String& declaredTypeName, String& expressionValue) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 291
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.TryGetLExprValue(LExprContext lExprContext, String& expressionValue, String& declaredTypeName) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 271
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(LExprContext context) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 135
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(ParserRuleContext parserRuleContext) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 96
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.VisitChildren(ParserRuleContext context) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 247
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.VisitBinaryOpEvaluationContext(ParserRuleContext context) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 167
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(ParserRuleContext parserRuleContext) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 116
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.GetConstantContextValueToken(ParserRuleContext context) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 339
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.LoadEnumMemberValues() in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 393
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor..ctor(IParseTreeValueFactory valueFactory, List`1 allEnums, Func`2 idRefRetriever) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 45
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.UnreachableCaseInspection.CreateParseTreeValueVisitor(IParseTreeValueFactory valueFactory, List`1 allEnums, Func`2 func) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\UnreachableCaseInspection.cs:line 84
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.UnreachableCaseInspection.DoGetInspectionResults() in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\UnreachableCaseInspection.cs:line 55
   at Rubberduck.Inspections.Abstract.InspectionBase.GetInspectionResults(CancellationToken token) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Abstract\InspectionBase.cs:line 166
   at Rubberduck.Inspections.Rubberduck.Inspections.Inspector.RunInspection(IInspection inspection, ConcurrentBag`1 allIssues, CancellationToken token) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Inspector.cs:line 188
```

**Comment by Vogel612** [comment]
was previously reported under https://github.com/rubberduck-vba/Rubberduck/issues/4258

**Comment by BZngr** [comment]
The root cause of the NREs is that the `UnreachableCaseInspection` `ParseTreeValueVisitor` does not (currently) evaluate VBA's predefined enum constants (like vbObjectError).  I have a solution for the enums, but I am currently stumped with regard to a workable approach to deal with the 10 VBA predefined 'string' constants like` vbNewLine`, `vbCr`, etc.  I'm thinking that we may not want to delay fixing the NRE issue because of the string constants.  So, I'd like to proceed with a PR for this issue and, for now, the inspection would not find unreachable cases for expressions containing elements like `vbNewLine`.  Thoughts?
