### ISSUE TITLE
COM Exception in Reference Synchronizer during parsing

### ISSUE THREAD

**Issue by Vogel612** [rubberduck-vba/Rubberduck#4663]
tried your program today and got the unexpected error, here's the bottom part of the log.

Excel 2010 vba
```
2018-12-19 13:14:48.0371;ERROR-2.3.1.4308;Rubberduck.Parsing.VBA.ParseCoordinator;Unexpected exception thrown in parsing run. (thread 5).;System.Runtime.InteropServices.COMException (0x80029C4A): Error loading type library/DLL. (Exception from HRESULT: 0x80029C4A (TYPE_E_CANTLOADLIBRARY))
   at Microsoft.Vbe.Interop.Reference.get_IsBroken()
   at Rubberduck.VBEditor.SafeComWrappers.VBA.Reference.get_IsBroken() in C:\projects\rubberduck\Rubberduck.VBEditor.VBA\SafeComWrappers\VB\Reference.cs:line 67
   at Rubberduck.Parsing.VBA.ComReferenceLoading.COMReferenceSynchronizerBase.ProjectReferenceInfos(IVBProject project) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\ComReferenceLoading\COMReferenceSynchronizerBase.cs:line 227
   at Rubberduck.Parsing.VBA.ComReferenceLoading.COMReferenceSynchronizerBase.ReferencedByProjectId() in C:\projects\rubberduck\Rubberduck.Parsing\VBA\ComReferenceLoading\COMReferenceSynchronizerBase.cs:line 212
   at Rubberduck.Parsing.VBA.ComReferenceLoading.COMReferenceSynchronizerBase.SyncComReferences(CancellationToken token) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\ComReferenceLoading\COMReferenceSynchronizerBase.cs:line 84
   at Rubberduck.Parsing.VBA.ParsingStageService.SyncComReferences(CancellationToken token) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\ParsingStageService.cs:line 92
   at Rubberduck.Parsing.VBA.ParseCoordinator.ExecuteCommonParseActivities(IReadOnlyCollection`1 toParse, IReadOnlyCollection`1 toReresolveReferencesInput, IReadOnlyCollection`1 newProjectIds, CancellationToken token) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:line 230
   at Rubberduck.Parsing.VBA.ParseCoordinator.ParseAllInternal(Object requestor, CancellationToken token) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:line 497
   at Rubberduck.Parsing.VBA.ParseCoordinator.ParseAll(Object requestor) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:line 406
2018-12-19 13:14:48.0501;INFO-2.3.1.4308;Rubberduck.Parsing.VBA.RubberduckParserState;RubberduckParserState (3) is invoking StateChanged (UnexpectedError);
2018-12-19 13:14:48.1321;DEBUG-2.3.1.4308;Rubberduck.Parsing.VBA.ParseCoordinator;Parsing run finished after 0.5485871s. (thread 5).;
```

_Originally posted by @iamorangehat in https://github.com/rubberduck-vba/Rubberduck/issues/3837#issuecomment-448694182_

**Comment by iamorangehat** [comment]
I did update to v2.3.1.4340-pre and still the same error.

**Comment by retailcoder** [comment]
@iamorangehat thanks for the update, the issue is still open, we'll get that exception under control :smiley:  - however per the stack trace in the logs that exception is thrown when querying for broken references, with an error code `HRESULT: 0x80029C4A (TYPE_E_CANTLOADLIBRARY)` - can you confirm whether your project has any broken references? Thanks!

**Comment by retailcoder** [comment]
@iamorangehat no problem! Looks like the VBIDE API is throwing an exception from the `Reference.IsBroken` getter when the reference is missing; we can pretty easily fix that, and the Code Explorer toolwindow will then be able to show broken references. Thanks again for the bug report!
