### ISSUE TITLE
Refactor renaming via VBA IDE project explorer does not remame in the code

### ISSUE THREAD

**Issue by SteveLaycock** [rubberduck-vba/Rubberduck#4773]
**Rubberduck version information**
Version 2.4.0.4511
OS: Microsoft Windows NT 10.0.17763.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.11231.20130
Host Executable: WINWORD.EXE

**Description**
If I click on a class name in the VBA IDE and use RubberDuck.Refactor.Rename then the class name is changed in the project explorer but this change is not propagated into the code base.

**Logfile**

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/2836360/RubberduckLog.txt)

**Comment by comintern** [comment]
This appears to be the relevant item from the log file:

```
2019-02-06 12:17:59.5602;ERROR-2.4.0.4511;Rubberduck.UI.Command.Refactorings.ProjectExplorerRefactorRenameCommand;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.Refactorings.Rename.RenameRefactoring.RestoreInitialSelection() in C:\projects\rubberduck\Rubberduck.Refactorings\Rename\RenameRefactoring.cs:line 609
   at Rubberduck.Refactorings.Rename.RenameRefactoring.Refactor(Declaration target) in C:\projects\rubberduck\Rubberduck.Refactorings\Rename\RenameRefactoring.cs:line 112
   at Rubberduck.UI.Command.Refactorings.ProjectExplorerRefactorRenameCommand.OnExecute(Object parameter) in C:\projects\rubberduck\Rubberduck.Core\UI\Command\Refactorings\ProjectExplorerRefactorRenameCommand.cs:line 42
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in C:\projects\rubberduck\Rubberduck.Core\UI\Command\CommandBase.cs:line 47;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.Refactorings.Rename.RenameRefactoring.RestoreInitialSelection() in C:\projects\rubberduck\Rubberduck.Refactorings\Rename\RenameRefactoring.cs:line 609
   at Rubberduck.Refactorings.Rename.RenameRefactoring.Refactor(Declaration target) in C:\projects\rubberduck\Rubberduck.Refactorings\Rename\RenameRefactoring.cs:line 112
   at Rubberduck.UI.Command.Refactorings.ProjectExplorerRefactorRenameCommand.OnExecute(Object parameter) in C:\projects\rubberduck\Rubberduck.Core\UI\Command\Refactorings\ProjectExplorerRefactorRenameCommand.cs:line 42
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in C:\projects\rubberduck\Rubberduck.Core\UI\Command\CommandBase.cs:line 47
```
