### ISSUE TITLE
Refactor|Rename dialog box will not display

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4824]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's Log or the About box:

Version 2.4.0.4565
OS: Microsoft Windows NT 10.0.15063.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.4711.1000
Host Executable: MSACCESS.EXE

**Description**
Attempting `Refactor | Rename` on a cleanly compiled, freshly parsed project will not pop the dialogue box. However `Refactor | Remove Parameter` works just fine.

**To Reproduce**
1. Open project
2. Compile/Parse
3. Wait for the `Ready` to be displayed in the RD tool bar.
4. Click on variable (notes that it's correctly identified in the tool bar
4. `Refactor | Rename`
4. See nothing...

**Expected behavior**
The rename dialog box should pop

**Screen Shot**
![capture](https://user-images.githubusercontent.com/11889733/53343896-68e1c600-38df-11e9-8408-ee3ebb515bd0.PNG)

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/2900924/RubberduckLog.txt)

**Additional context**
I am currently WFH using RDC to my machine at work. Not sure if that's got anything to do with it, but I could _not_ get the log file or the screen shot to DnD into this issue, so there may be other factors at play that are preventing this from working correctly for me in this particular instance.

**Comment by bclothier** [comment]
Relevant error:
```
2019-02-25 09:14:09.6715;DEBUG-2.4.0.4565;Rubberduck.UI.Command.MenuItems.ParentMenus.ParentMenuItemBase;(60473108) Executing click handler for menu item '&Rename', hash code 55421393;
2019-02-25 09:14:09.6871;ERROR-2.4.0.4565;Rubberduck.UI.Command.Refactorings.CodePaneRefactorRenameCommand;System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Rubberduck.Refactorings.Rename.RenameRefactoring.NeverRenameList() in C:\projects\rubberduck\Rubberduck.Refactorings\Rename\RenameRefactoring.cs:line 581
   at Rubberduck.Refactorings.Rename.RenameRefactoring..ctor(IRefactoringPresenterFactory factory, IMessageBox messageBox, IDeclarationFinderProvider declarationFinderProvider, IProjectsProvider projectsProvider, IRewritingManager rewritingManager, ISelectionService selectionService) in C:\projects\rubberduck\Rubberduck.Refactorings\Rename\RenameRefactoring.cs:line 59
   at Rubberduck.UI.Command.Refactorings.CodePaneRefactorRenameCommand.OnExecute(Object parameter) in C:\projects\rubberduck\Rubberduck.Core\UI\Command\Refactorings\CodePaneRefactorRenameCommand.cs:line 62
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in C:\projects\rubberduck\Rubberduck.Core\UI\Command\CommandBase.cs:line 47;System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Rubberduck.Refactorings.Rename.RenameRefactoring.NeverRenameList() in C:\projects\rubberduck\Rubberduck.Refactorings\Rename\RenameRefactoring.cs:line 581
   at Rubberduck.Refactorings.Rename.RenameRefactoring..ctor(IRefactoringPresenterFactory factory, IMessageBox messageBox, IDeclarationFinderProvider declarationFinderProvider, IProjectsProvider projectsProvider, IRewritingManager rewritingManager, ISelectionService selectionService) in C:\projects\rubberduck\Rubberduck.Refactorings\Rename\RenameRefactoring.cs:line 59
   at Rubberduck.UI.Command.Refactorings.CodePaneRefactorRenameCommand.OnExecute(Object parameter) in C:\projects\rubberduck\Rubberduck.Core\UI\Command\Refactorings\CodePaneRefactorRenameCommand.cs:line 62
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in C:\projects\rubberduck\Rubberduck.Core\UI\Command\CommandBase.cs:line 47
```

**Comment by comintern** [comment]
Linking [chat](https://chat.stackexchange.com/transcript/message/49198849#49198849).
