### ISSUE TITLE
Add/Remove References Dialog won't open.

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4911]
Version 2.4.1.4661
OS: Microsoft Windows NT 10.0.15063.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.4822.1000
Host Executable: EXCEL.EXE

**Issue:**
`Add/Remove References` dialog box won't open.

**Reproduce:**
1) Open an Excel project
2) Launch VBE
3) Wait for `Add/Remove References...` to be enabled
3) Click on `A/RR`
3) Nothing...

**Log:**
> 2019-04-12 09:55:33.3078;WARN-2.4.1.4661;Rubberduck.UI.AddRemoveReferences.AddRemoveReferencesPresenterFactory;Unexpected exception attempting to create AddRemoveReferencesModel.;System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Rubberduck.UI.AddRemoveReferences.AddRemoveReferencesPresenterFactory.Create(ProjectDeclaration project) in C:\projects\rubberduck\Rubberduck.Core\UI\AddRemoveReferences\AddRemoveReferencesPresenterFactory.cs:line 108
 
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/3073575/RubberduckLog.txt)

**Additional Info:**
It might be because I pasted some code that needed a reference. The compile failed due to the missing reference. Then again, it might not...

**Comment by Inarion** [comment]
Is this issue persisting for you @daFreeMan ? As I've noticed my reference dialog tends to open _behind_ other windows. I usually see it on top for a split-second and then it hides behind other windows. (I've got my VBE opened on the 2nd monitor and the dialog will always open on the 1st.)

To remedy this I need to maximize/bring to top another window and minimize it again, then the dialog will be visible.  
But I assume your issue was different as you didn't mention it and  for me it's impossible to overlook as the reference dialog is modal, so the VBE won't respond until I close it again.

**Comment by daFreeMan** [comment]
@Inarion You are correct, I am _not_ getting the dialogue opening behind other windows. (Just ran into this again today and thought to search for the issue instead of blindly opening a new one.)

Additionally, I'm actually getting an error in the log in reference to the 'AddRemoveReferencesPresenter', so it seems that it's an actual issue, more than an annoyance (which opening behind everything else certainly is).

**Comment by Vogel612** [comment]
@daFreeMan that error is unfortunately not available in the log that you already attached... Do you have a copy of that error for us? Thanks!

**Comment by daFreeMan** [comment]
@Vogel612 I may have mistyped somewhat - the error is referencing `AddRemoveReferencesPresenterFactory` and it's mentioned on line 3508 of the log attached to the original bug report. This is part of the multi-line error report I quoted (starting on line 3505 of said log file) in the OP.

However, this morning, after a fresh restart of Excel with RD .4782, the Add/Remove References dialogue does indeed pop-up when requested. I will note that I installed .4782 earlier this week and I was running this build yesterday when I commented that I'm still having the issue.

I would, though, like to leave this open for a bit, because I'm 100% certain that it did _not_ do so yesterday. It's possible that the error creeps in when I've left Excel sitting open (as I tend to do) for the whole week, since I'm usually in the middle of something at the end of the day and I want to easily pick up where I left off but the VBE doesn't remember any state from its last instantiation, so I'm left with leaving it open.

I do notice that in the original log where I was having the error, the click-handler is logged like this:
```
2019-04-12 09:55:33.1203;DEBUG-2.4.1.4661;Rubberduck.UI.Command.MenuItems.ParentMenus.ParentMenuItemBase;(56686067) Executing click handler for menu item 'Add/Remove References...', hash code 33962021;
```
and in the new log (created this morning) with a successful launch of the dialogue box, it's logged like this:
```
2019-07-11 07:51:34.0628;DEBUG-2.4.1.4782;Rubberduck.UI.Command.MenuItems.ParentMenus.ParentMenuItemBase;(45015971) Executing click handler for menu item 'Add/Remove References...', hash code 32376435;
```
There is a difference in the hash codes. I don't know if this is to be expected, or if something changed between the two releases.

Yesterday's attempts to get the `Add/Remove References` dialogue up were prompted by the appearance of 2 copies of the `Rubberduck TLB` showing up under `Library References` in the Code Explorer. This issue seems to be noted by this error in the log:

```
2019-07-10 14:40:27.2153;WARN-2.4.1.4782;Rubberduck.Parsing.VBA.ComReferenceLoading.COMReferenceSynchronizerBase;Types were not loaded from referenced type library 'Rubberduck'.;
2019-07-10 14:40:27.2513;ERROR-2.4.1.4782;Rubberduck.Parsing.VBA.ComReferenceLoading.COMReferenceSynchronizerBase;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.Parsing.ComReflection.ComCoClass.get_DefaultMember() in C:\projects\rubberduck\Rubberduck.Parsing\ComReflection\ComCoClass.cs:line 44
   at Rubberduck.Parsing.ComReflection.DeclarationsFromComProjectLoader.GetDeclarationsForModule(IComType module, QualifiedModuleName moduleName, ProjectDeclaration project) in C:\projects\rubberduck\Rubberduck.Parsing\ComReflection\DeclarationsFromComProjectLoader.cs:line 56
   at Rubberduck.Parsing.ComReflection.DeclarationsFromComProjectLoader.LoadDeclarations(ComProject type, String projectId) in C:\projects\rubberduck\Rubberduck.Parsing\ComReflection\DeclarationsFromComProjectLoader.cs:line 33
   at Rubberduck.Parsing.ComReflection.LibraryReferencedDeclarationsCollector.LoadDeclarationsFromLibrary(ReferenceInfo reference) in C:\projects\rubberduck\Rubberduck.Parsing\ComReflection\LibraryReferencedDeclarationsCollector.cs:line 33
   at Rubberduck.Parsing.ComReflection.LibraryReferencedDeclarationsCollector.CollectedDeclarations(ReferenceInfo reference) in C:\projects\rubberduck\Rubberduck.Parsing\ComReflection\LibraryReferencedDeclarationsCollector.cs:line 20
   at Rubberduck.Parsing.VBA.ComReferenceLoading.COMReferenceSynchronizerBase.LoadReference(ReferenceInfo reference, ConcurrentBag`1 unmapped) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\ComReferenceLoading\COMReferenceSynchronizerBase.cs:line 342;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.Parsing.ComReflection.ComCoClass.get_DefaultMember() in C:\projects\rubberduck\Rubberduck.Parsing\ComReflection\ComCoClass.cs:line 44
   at Rubberduck.Parsing.ComReflection.DeclarationsFromComProjectLoader.GetDeclarationsForModule(IComType module, QualifiedModuleName moduleName, ProjectDeclaration project) in C:\projects\rubberduck\Rubberduck.Parsing\ComReflection\DeclarationsFromComProjectLoader.cs:line 56
   at Rubberduck.Parsing.ComReflection.DeclarationsFromComProjectLoader.LoadDeclarations(ComProject type, String projectId) in C:\projects\rubberduck\Rubberduck.Parsing\ComReflection\DeclarationsFromComProjectLoader.cs:line 33
   at Rubberduck.Parsing.ComReflection.LibraryReferencedDeclarationsCollector.LoadDeclarationsFromLibrary(ReferenceInfo reference) in C:\projects\rubberduck\Rubberduck.Parsing\ComReflection\LibraryReferencedDeclarationsCollector.cs:line 33
   at Rubberduck.Parsing.ComReflection.LibraryReferencedDeclarationsCollector.CollectedDeclarations(ReferenceInfo reference) in C:\projects\rubberduck\Rubberduck.Parsing\ComReflection\LibraryReferencedDeclarationsCollector.cs:line 20
   at Rubberduck.Parsing.VBA.ComReferenceLoading.COMReferenceSynchronizerBase.LoadReference(ReferenceInfo reference, ConcurrentBag`1 unmapped) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\ComReferenceLoading\COMReferenceSynchronizerBase.cs:line 342
```
_Complete log:_ [RubberduckLog.160.txt](https://github.com/rubberduck-vba/Rubberduck/files/3381902/RubberduckLog.160.txt)

It was at this point that I could not get the A/RR dialogue to appear, though the above is the only occurence of `ERROR-` in the file.

**Comment by Vogel612** [comment]
The changed hash codes are to be expected, since the menu items are recreated on every startup (because the VBE doesn't like us putting menus in places).

**Comment by retailcoder** [comment]
Is this still occurrring? No repro here with .4942

**Comment by daFreeMan** [comment]
No repo in .4950 either.
