### ISSUE TITLE
What does Unable to cast object of type 'WhitespaceIndexExprContext' to type 'IndexExprContext' mean?

### ISSUE THREAD

**Issue by coverney** [rubberduck-vba/Rubberduck#5069]
Thanks in advance!

**Rubberduck version information**
    Rubberduck version [2.4.1.4627]
    Operating System: [Microsoft Windows NT 10.0.17763.0 x64]
    Host Product: [Microsoft Office x64]
    Host Version: [16.0.11328.20368]
    Host Executable: [EXCEL.EXE]

**Description**
I created a macro-enabled spreadsheet with simple buttons that run particular macros when clicked on. I am trying to add unit tests to these functions I wrote. To do so, I added one function at a time to a new spreadsheet and wrote tests for each function I added. However, when I added a particular function, `Function getDataFromFile(parFileName As String, parDelimiter As String, Optional parExcludeCharacter As String = "") As Variant` within the `AnalysisMethods` module, I got an `InvalidCastException`. Now I can't run any of my old tests anymore. Any help to debug this would be much appreciated! 

In other words, **what does Unable to cast object of type 'WhitespaceIndexExprContext' to type 'IndexExprContext' mean?**

**To Reproduce**
1. Open up the Test Explorer
2. Click the refresh button
3. Right-click on any test and select Run single test 
4. Open log and look for ERROR

**Expected behavior**
I was hoping that the old unit tests I wrote could execute.

**Logfile**
```
2019-07-24 20:41:45.6145;ERROR-2.4.1.4627;Rubberduck.Parsing.VBA.ReferenceManagement.ReferenceResolveRunnerBase;Exception thrown resolving 'VBAProject.AnalysisMethods' (thread 5).;System.InvalidCastException: Unable to cast object of type 'WhitespaceIndexExprContext' to type 'IndexExprContext'.
   at Rubberduck.Parsing.Symbols.IdentifierReferenceResolver.Resolve(RedimStmtContext context) in C:\projects\rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceResolver.cs:line 261
   at Rubberduck.Parsing.Grammar.VBAParser.RedimStmtContext.EnterRule(IParseTreeListener listener) in C:\projects\rubberduck\Rubberduck.Parsing\obj\Release\net46\VBAParser.cs:line 11082
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Rubberduck.Parsing.VBA.ReferenceManagement.ReferenceResolveRunnerBase.ResolveReferences(DeclarationFinder finder, QualifiedModuleName module, IParseTree tree, CancellationToken token) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\ReferenceManagement\ReferenceResolveRunnerBase.cs:line 251
```

**Additional context**
Here is the function that caused the problem. (I can't seem to attach the spreadsheet.)
```
'Helper function for copyDataFromCsvFileToSheet
Function getDataFromFile(parFileName As String, parDelimiter As String, Optional parExcludeCharacter As String = "") As Variant
'parFileName is the delimited file (csv, txt ...)
'parDelimiter is the separator, e.g. semicolon.
'The function returns an empty array, if the file
'is empty or cannot be opened.
'Number of columns is based on the line with most
'columns and not the first line.
'parExcludeCharacter: Some csv files have strings in
'quotations marks ("ABC"), and if parExcludeCharacter = """"
'quotation marks are removed.

Dim locLinesList() As Variant 'Array
Dim locData As Variant        'Array
Dim i As Long                 'Counter
Dim j As Long                 'Counter
Dim locNumRows As Long        'Nb of rows
Dim locNumCols As Long        'Nb of columns
Dim fso As Variant            'File system object
Dim ts As Variant             'File variable
Const REDIM_STEP = 10000      'Constant

'If this fails you need to reference Microsoft Scripting Runtime.
'You select this in "Tools" (VBA editor menu).
Set fso = CreateObject("Scripting.FileSystemObject")

On Error GoTo error_open_file
'Sets ts = the file
Set ts = fso.OpenTextFile(parFileName)
On Error GoTo unhandled_error

'Initialise the array
ReDim locLinesList(1 To 1) As Variant
i = 0
'Loops through the file, counts the number of lines (rows)
'and finds the highest number of columns.
Do While Not ts.AtEndOfStream
  'If the row number Mod 10000 = 0
  'we redimension the array.
  If i Mod REDIM_STEP = 0 Then
    ReDim Preserve locLinesList _
    (1 To UBound(locLinesList, 1) + REDIM_STEP) As Variant
  End If
  locLinesList(i + 1) = Split(ts.ReadLine, parDelimiter)
  j = UBound(locLinesList(i + 1), 1) 'Nb of columns in present row
  'If the number of columns is then highest so far.
  'the new number is saved.
  If locNumCols < j Then locNumCols = j
  i = i + 1
Loop

ts.Close 'Close file

locNumRows = i

'If number of rows is zero
If locNumRows = 0 Then Exit Function

ReDim locData(1 To locNumRows, 1 To locNumCols + 1) As Variant

'Copies the file values into an array.
'If parExcludeCharacter has a value,
'the characters are removed.
If parExcludeCharacter <> "" Then
  For i = 1 To locNumRows
    For j = 0 To UBound(locLinesList(i), 1)
      If Left(locLinesList(i)(j), 1) = parExcludeCharacter Then
        If Right(locLinesList(i)(j), 1) = parExcludeCharacter Then
          locLinesList(i)(j) = _
          Mid(locLinesList(i)(j), 2, Len(locLinesList(i)(j)) - 2)
        Else
          locLinesList(i)(j) = _
          Right(locLinesList(i)(j), Len(locLinesList(i)(j)) - 1)
        End If
      ElseIf Right(locLinesList(i)(j), 1) = parExcludeCharacter Then
        locLinesList(i)(j) = _
        Left(locLinesList(i)(j), Len(locLinesList(i)(j)) - 1)
      End If
      locData(i, j + 1) = locLinesList(i)(j)
    Next j
  Next i
Else
  For i = 1 To locNumRows
    For j = 0 To UBound(locLinesList(i), 1)
      locData(i, j + 1) = locLinesList(i)(j)
    Next j
  Next i
End If

getDataFromFile = locData

Exit Function

error_open_file:  'Returns empty Variant
unhandled_error:  'Returns empty Variant

End Function
```

**Comment by MDoerner** [comment]
Thanks for reporting this. 

This is definetly a bug on our side in the special handling of 'ReDim` statements.

The code seems to assume that it always finds an index expression after the `ReDim Preserve?`, i.e. an identifier immediately followed by something enclosed in parentheses. However, a whitespace index expression is valid as well, i.e. an identifier followed by a line continuation and whitespace followed by something in parentheses. These are a special case in which the VBE does not eliminate the whitespace in front of the parentheses leading to ambiguities with call statements followed by an argument in parentheses.

We will have to handle the whitespace index expression as well. 

If you want to work around this bug, remove the line continuation in the `ReDim Preserve  locLinesList`.

**Comment by coverney** [comment]
I will try that. Thank you very much!
