### ISSUE TITLE
Redim causing debug assertions in GetVariableStmtContext extension method

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#5177]
Credits goes to @IvenBach  for finding the bug initially.

**Rubberduck version information**
Version 2.4.1.13085
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2010 x86
Host Version: 14.0.7230.5000
Host Executable: MSACCESS.EXE

**Description**
Given a module with the code:

```
Public Sub x()
  Redim a(1 to 2)
End Sub
```

This will cause a debug assertion at this line 75:
https://github.com/rubberduck-vba/Rubberduck/blob/7a21154f73c2820aa3bdb0973f91182f32dace62/Rubberduck.Refactorings/Common/DeclarationExtensions.cs#L68-L83

The `target` is declared but is a `SimpleNameExprContext`, which fails the assertion.

**Expected behavior**
I don't think we should assert on the `Redim`, which won't be a `VariableSubStmt`. This probably should be amended to handle the `Redim`.

**Logfile**
(Note: this is from Iven's log, snipped to only the relevant error; my log is similar but too lazy to upload a file, so.... thanks, Iven!)
```
2019-10-03 11:30:22.3299;ERROR-2.4.1.20603;Rubberduck.UI.Command.Refactorings.RefactorIntroduceParameterCommand;System.MissingMemberException: Statement not found
   at Rubberduck.Common.DeclarationExtensions.GetVariableStmtContext(Declaration target) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Refactorings\Common\DeclarationExtensions.cs:line 79
   at Rubberduck.Common.DeclarationExtensions.GetVariableStmtContextSelection(Declaration target) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Refactorings\Common\DeclarationExtensions.cs:line 41
   at Rubberduck.Common.DeclarationExtensions.FindVariable(IEnumerable`1 declarations, QualifiedSelection selection) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Refactorings\Common\DeclarationExtensions.cs:line 474
   at Rubberduck.UI.Command.Refactorings.RefactorIntroduceParameterCommand.GetTarget() in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Core\UI\Command\Refactorings\RefactorIntroduceParameterCommand.cs:line 39
   at Rubberduck.UI.Command.Refactorings.RefactorIntroduceParameterCommand.SpecializedEvaluateCanExecute(Object parameter) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Core\UI\Command\Refactorings\RefactorIntroduceParameterCommand.cs:line 24
   at Rubberduck.UI.Command.CommandBase.<>c__DisplayClass14_0.<AddToCanExecuteEvaluation>b__0(Object parameter) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Core\UI\Command\CommandBase.cs:line 37
   at Rubberduck.UI.Command.CommandBase.CanExecute(Object parameter) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Core\UI\Command\CommandBase.cs:line 61;System.MissingMemberException: Statement not found
   at Rubberduck.Common.DeclarationExtensions.GetVariableStmtContext(Declaration target) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Refactorings\Common\DeclarationExtensions.cs:line 79
   at Rubberduck.Common.DeclarationExtensions.GetVariableStmtContextSelection(Declaration target) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Refactorings\Common\DeclarationExtensions.cs:line 41
   at Rubberduck.Common.DeclarationExtensions.FindVariable(IEnumerable`1 declarations, QualifiedSelection selection) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Refactorings\Common\DeclarationExtensions.cs:line 474
   at Rubberduck.UI.Command.Refactorings.RefactorIntroduceParameterCommand.GetTarget() in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Core\UI\Command\Refactorings\RefactorIntroduceParameterCommand.cs:line 39
   at Rubberduck.UI.Command.Refactorings.RefactorIntroduceParameterCommand.SpecializedEvaluateCanExecute(Object parameter) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Core\UI\Command\Refactorings\RefactorIntroduceParameterCommand.cs:line 24
   at Rubberduck.UI.Command.CommandBase.<>c__DisplayClass14_0.<AddToCanExecuteEvaluation>b__0(Object parameter) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Core\UI\Command\CommandBase.cs:line 37
   at Rubberduck.UI.Command.CommandBase.CanExecute(Object parameter) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Core\UI\Command\CommandBase.cs:line 61
2019-10-03 11:30:23.1659;ERROR-2.4.1.20603;Rubberduck.UI.Command.Refactorings.RefactorIntroduceFieldCommand;System.MissingMemberException: Statement not found
   at Rubberduck.Common.DeclarationExtensions.GetVariableStmtContext(Declaration target) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Refactorings\Common\DeclarationExtensions.cs:line 79
   at Rubberduck.Common.DeclarationExtensions.GetVariableStmtContextSelection(Declaration target) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Refactorings\Common\DeclarationExtensions.cs:line 41
   at Rubberduck.Common.DeclarationExtensions.FindVariable(IEnumerable`1 declarations, QualifiedSelection selection) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Refactorings\Common\DeclarationExtensions.cs:line 474
   at Rubberduck.UI.Command.Refactorings.RefactorIntroduceFieldCommand.GetTarget() in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Core\UI\Command\Refactorings\RefactorIntroduceFieldCommand.cs:line 39
   at Rubberduck.UI.Command.Refactorings.RefactorIntroduceFieldCommand.SpecializedEvaluateCanExecute(Object parameter) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Core\UI\Command\Refactorings\RefactorIntroduceFieldCommand.cs:line 24
   at Rubberduck.UI.Command.CommandBase.<>c__DisplayClass14_0.<AddToCanExecuteEvaluation>b__0(Object parameter) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Core\UI\Command\CommandBase.cs:line 37
   at Rubberduck.UI.Command.CommandBase.CanExecute(Object parameter) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Core\UI\Command\CommandBase.cs:line 61;System.MissingMemberException: Statement not found
   at Rubberduck.Common.DeclarationExtensions.GetVariableStmtContext(Declaration target) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Refactorings\Common\DeclarationExtensions.cs:line 79
   at Rubberduck.Common.DeclarationExtensions.GetVariableStmtContextSelection(Declaration target) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Refactorings\Common\DeclarationExtensions.cs:line 41
   at Rubberduck.Common.DeclarationExtensions.FindVariable(IEnumerable`1 declarations, QualifiedSelection selection) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Refactorings\Common\DeclarationExtensions.cs:line 474
   at Rubberduck.UI.Command.Refactorings.RefactorIntroduceFieldCommand.GetTarget() in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Core\UI\Command\Refactorings\RefactorIntroduceFieldCommand.cs:line 39
   at Rubberduck.UI.Command.Refactorings.RefactorIntroduceFieldCommand.SpecializedEvaluateCanExecute(Object parameter) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Core\UI\Command\Refactorings\RefactorIntroduceFieldCommand.cs:line 24
   at Rubberduck.UI.Command.CommandBase.<>c__DisplayClass14_0.<AddToCanExecuteEvaluation>b__0(Object parameter) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Core\UI\Command\CommandBase.cs:line 37
   at Rubberduck.UI.Command.CommandBase.CanExecute(Object parameter) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Core\UI\Command\CommandBase.cs:line 61
2019-10-03 11:30:23.8999;ERROR-2.4.1.20603;Rubberduck.UI.Command.Refactorings.RefactorIntroduceParameterCommand;System.MissingMemberException: Statement not found
   at Rubberduck.Common.DeclarationExtensions.GetVariableStmtContext(Declaration target) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Refactorings\Common\DeclarationExtensions.cs:line 79
   at Rubberduck.Common.DeclarationExtensions.GetVariableStmtContextSelection(Declaration target) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Refactorings\Common\DeclarationExtensions.cs:line 41
   at Rubberduck.Common.DeclarationExtensions.FindVariable(IEnumerable`1 declarations, QualifiedSelection selection) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Refactorings\Common\DeclarationExtensions.cs:line 474
   at Rubberduck.UI.Command.Refactorings.RefactorIntroduceParameterCommand.GetTarget() in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Core\UI\Command\Refactorings\RefactorIntroduceParameterCommand.cs:line 39
   at Rubberduck.UI.Command.Refactorings.RefactorIntroduceParameterCommand.SpecializedEvaluateCanExecute(Object parameter) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Core\UI\Command\Refactorings\RefactorIntroduceParameterCommand.cs:line 24
   at Rubberduck.UI.Command.CommandBase.<>c__DisplayClass14_0.<AddToCanExecuteEvaluation>b__0(Object parameter) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Core\UI\Command\CommandBase.cs:line 37
   at Rubberduck.UI.Command.CommandBase.CanExecute(Object parameter) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Core\UI\Command\CommandBase.cs:line 61;System.MissingMemberException: Statement not found
   at Rubberduck.Common.DeclarationExtensions.GetVariableStmtContext(Declaration target) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Refactorings\Common\DeclarationExtensions.cs:line 79
   at Rubberduck.Common.DeclarationExtensions.GetVariableStmtContextSelection(Declaration target) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Refactorings\Common\DeclarationExtensions.cs:line 41
   at Rubberduck.Common.DeclarationExtensions.FindVariable(IEnumerable`1 declarations, QualifiedSelection selection) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Refactorings\Common\DeclarationExtensions.cs:line 474
   at Rubberduck.UI.Command.Refactorings.RefactorIntroduceParameterCommand.GetTarget() in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Core\UI\Command\Refactorings\RefactorIntroduceParameterCommand.cs:line 39
   at Rubberduck.UI.Command.Refactorings.RefactorIntroduceParameterCommand.SpecializedEvaluateCanExecute(Object parameter) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Core\UI\Command\Refactorings\RefactorIntroduceParameterCommand.cs:line 24
   at Rubberduck.UI.Command.CommandBase.<>c__DisplayClass14_0.<AddToCanExecuteEvaluation>b__0(Object parameter) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Core\UI\Command\CommandBase.cs:line 37
   at Rubberduck.UI.Command.CommandBase.CanExecute(Object parameter) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Core\UI\Command\CommandBase.cs:line 61
2019-10-03 11:30:24.5859;ERROR-2.4.1.20603;Rubberduck.UI.Command.Refactorings.RefactorIntroduceFieldCommand;System.MissingMemberException: Statement not found
   at Rubberduck.Common.DeclarationExtensions.GetVariableStmtContext(Declaration target) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Refactorings\Common\DeclarationExtensions.cs:line 79
   at Rubberduck.Common.DeclarationExtensions.GetVariableStmtContextSelection(Declaration target) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Refactorings\Common\DeclarationExtensions.cs:line 41
   at Rubberduck.Common.DeclarationExtensions.FindVariable(IEnumerable`1 declarations, QualifiedSelection selection) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Refactorings\Common\DeclarationExtensions.cs:line 474
   at Rubberduck.UI.Command.Refactorings.RefactorIntroduceFieldCommand.GetTarget() in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Core\UI\Command\Refactorings\RefactorIntroduceFieldCommand.cs:line 39
   at Rubberduck.UI.Command.Refactorings.RefactorIntroduceFieldCommand.SpecializedEvaluateCanExecute(Object parameter) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Core\UI\Command\Refactorings\RefactorIntroduceFieldCommand.cs:line 24
   at Rubberduck.UI.Command.CommandBase.<>c__DisplayClass14_0.<AddToCanExecuteEvaluation>b__0(Object parameter) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Core\UI\Command\CommandBase.cs:line 37
   at Rubberduck.UI.Command.CommandBase.CanExecute(Object parameter) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Core\UI\Command\CommandBase.cs:line 61;System.MissingMemberException: Statement not found
   at Rubberduck.Common.DeclarationExtensions.GetVariableStmtContext(Declaration target) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Refactorings\Common\DeclarationExtensions.cs:line 79
   at Rubberduck.Common.DeclarationExtensions.GetVariableStmtContextSelection(Declaration target) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Refactorings\Common\DeclarationExtensions.cs:line 41
   at Rubberduck.Common.DeclarationExtensions.FindVariable(IEnumerable`1 declarations, QualifiedSelection selection) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Refactorings\Common\DeclarationExtensions.cs:line 474
   at Rubberduck.UI.Command.Refactorings.RefactorIntroduceFieldCommand.GetTarget() in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Core\UI\Command\Refactorings\RefactorIntroduceFieldCommand.cs:line 39
   at Rubberduck.UI.Command.Refactorings.RefactorIntroduceFieldCommand.SpecializedEvaluateCanExecute(Object parameter)
```

**Comment by bclothier** [comment]
Addendum: as per chat, it's probably best that the introduce refactorings don't deal with undeclared `Redim`s at all. That needs its own inspection/quickfix, after which can be then introduced.

**Comment by IvenBach** [comment]
Confirming that `ReDim Dependents(1 To dependentCount)` which includes the implicit `Dim` is the bad code causing ducky to barf. Adding `Dim Depenendents()` lets ducky consume the code without causing intestinal distress. Blame lies solely with Past-Iven.
