### ISSUE TITLE
Array & undeclared `Redim`'d variables' refcounts and renaming are incorrect

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#5277]
**Rubberduck version information**

Version 2.4.1.40892
OS: Microsoft Windows NT 10.0.17763.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.12130.20272
Host Executable: EXCEL.EXE

**Description**

Rubberduck is now handling the undeclared `Redim` well, thanks to new PRs merged in last few months that enhances the resolver's capabilities for handling this.

However, there seems to be some rough edges around how it is resolved and that also seems to affects the rename refactoring. In tests, it seem that creating a `Dim` statement will fix the problems whereas absent such statement, we see the anomalous reference counts and an exception thrown in rename refactoring).

**To Reproduce**
Create the following code:
```
Public Sub z()
    Dim y
    Debug.Print y
End Sub

Public Sub x()
    ReDim y(1)
    
    Debug.Print y(0)
    Debug.Print y(1)
    
    ReDim y(0)
    
    Debug.Print y(0)
End Sub
```

Note: the `z` procedure exists primarily to prove that reference isn't picking up the wrong declaration.

2. Parse the code and select the `y` in the `x` procedure. There should be 8 references shown:

![image](https://user-images.githubusercontent.com/2367644/68605084-6e813b00-0471-11ea-9b2d-126dfae9d383.png)

3. Try to rename the `y` variable. Nothing will apparently happen but an exception will be logged. See below.

4. Add a variable declaration, then reparse. The count should drop to 5:

![image](https://user-images.githubusercontent.com/2367644/68608502-b22b7300-0478-11ea-9107-4f264810e73d.png)

5. Rename refactoring will now succeed. 

6. Restore code, then add `Dim y() As Variant`, Reparse. We still get 8 references:
![image](https://user-images.githubusercontent.com/2367644/68609530-1c451780-047b-11ea-85de-3ff67b740e39.png)

7. The rename refactoring still fails.

**Logfile**
Relevant exception:
```
2019-11-11 12:04:33.6387;ERROR-2.4.1.40892;Rubberduck.UI.Command.Refactorings.CodePaneRefactorRenameCommand;System.ArgumentException: replace op boundaries of <ReplaceOp@[@73,144:144='y',<237>,12:16]..[@73,144:144='y',<237>,12:16]:"ZZZ"> overlap with previous <ReplaceOp@[@73,144:144='y',<237>,12:16]..[@76,147:147=')',<221>,12:19]:"ZZZ">
   at Antlr4.Runtime.TokenStreamRewriter.ReduceToSingleOperationPerIndex(IList`1 rewrites)
   at Antlr4.Runtime.TokenStreamRewriter.GetText(String programName, Interval interval)
   at Rubberduck.Parsing.Rewriter.ModuleRewriter.get_IsDirty() in C:\GitHub\Rubberduck\Rubberduck.Parsing\Rewriter\ModuleRewriter.cs:line 27
   at Rubberduck.Parsing.Rewriter.ModuleRewriter.Rewrite() in C:\GitHub\Rubberduck\Rubberduck.Parsing\Rewriter\ModuleRewriter.cs:line 31
   at Rubberduck.Parsing.Rewriter.CodePaneRewriteSession.TryRewriteInternal() in C:\GitHub\Rubberduck\Rubberduck.Parsing\Rewriter\CodePaneRewriteSession.cs:line 30
   at Rubberduck.Parsing.Rewriter.RewriteSessionBase.TryRewrite() in C:\GitHub\Rubberduck\Rubberduck.Parsing\Rewriter\RewriteSessionBase.cs:line 99
   at Rubberduck.Refactorings.Rename.RenameRefactoring.RenameRefactor(RenameModel model) in C:\GitHub\Rubberduck\Rubberduck.Refactorings\Rename\RenameRefactoring.cs:line 105
   at Rubberduck.Refactorings.Rename.RenameRefactoring.RefactorImpl(RenameModel model) in C:\GitHub\Rubberduck\Rubberduck.Refactorings\Rename\RenameRefactoring.cs:line 88
   at Rubberduck.Refactorings.InteractiveRefactoringBase`2.Refactor(TModel initialModel) in C:\GitHub\Rubberduck\Rubberduck.Refactorings\InteractiveRefactoringBase.cs:line 51
   at Rubberduck.Refactorings.InteractiveRefactoringBase`2.Refactor(Declaration target) in C:\GitHub\Rubberduck\Rubberduck.Refactorings\InteractiveRefactoringBase.cs:line 26
   at Rubberduck.Refactorings.RefactoringBase.Refactor(QualifiedSelection targetSelection) in C:\GitHub\Rubberduck\Rubberduck.Refactorings\RefactoringBase.cs:line 40
   at Rubberduck.UI.Command.Refactorings.RefactorCodePaneCommandBase.OnExecute(Object parameter) in C:\GitHub\Rubberduck\Rubberduck.Core\UI\Command\Refactorings\RefactorCodePaneCommandBase.cs:line 40
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in C:\GitHub\Rubberduck\Rubberduck.Core\UI\Command\CommandBase.cs:line 85;System.ArgumentException: replace op boundaries of <ReplaceOp@[@73,144:144='y',<237>,12:16]..[@73,144:144='y',<237>,12:16]:"ZZZ"> overlap with previous <ReplaceOp@[@73,144:144='y',<237>,12:16]..[@76,147:147=')',<221>,12:19]:"ZZZ">
   at Antlr4.Runtime.TokenStreamRewriter.ReduceToSingleOperationPerIndex(IList`1 rewrites)
   at Antlr4.Runtime.TokenStreamRewriter.GetText(String programName, Interval interval)
   at Rubberduck.Parsing.Rewriter.ModuleRewriter.get_IsDirty() in C:\GitHub\Rubberduck\Rubberduck.Parsing\Rewriter\ModuleRewriter.cs:line 27
   at Rubberduck.Parsing.Rewriter.ModuleRewriter.Rewrite() in C:\GitHub\Rubberduck\Rubberduck.Parsing\Rewriter\ModuleRewriter.cs:line 31
   at Rubberduck.Parsing.Rewriter.CodePaneRewriteSession.TryRewriteInternal() in C:\GitHub\Rubberduck\Rubberduck.Parsing\Rewriter\CodePaneRewriteSession.cs:line 30
   at Rubberduck.Parsing.Rewriter.RewriteSessionBase.TryRewrite() in C:\GitHub\Rubberduck\Rubberduck.Parsing\Rewriter\RewriteSessionBase.cs:line 99
   at Rubberduck.Refactorings.Rename.RenameRefactoring.RenameRefactor(RenameModel model) in C:\GitHub\Rubberduck\Rubberduck.Refactorings\Rename\RenameRefactoring.cs:line 105
   at Rubberduck.Refactorings.Rename.RenameRefactoring.RefactorImpl(RenameModel model) in C:\GitHub\Rubberduck\Rubberduck.Refactorings\Rename\RenameRefactoring.cs:line 88
   at Rubberduck.Refactorings.InteractiveRefactoringBase`2.Refactor(TModel initialModel) in C:\GitHub\Rubberduck\Rubberduck.Refactorings\InteractiveRefactoringBase.cs:line 51
   at Rubberduck.Refactorings.InteractiveRefactoringBase`2.Refactor(Declaration target) in C:\GitHub\Rubberduck\Rubberduck.Refactorings\InteractiveRefactoringBase.cs:line 26
   at Rubberduck.Refactorings.RefactoringBase.Refactor(QualifiedSelection targetSelection) in C:\GitHub\Rubberduck\Rubberduck.Refactorings\RefactoringBase.cs:line 40
   at Rubberduck.UI.Command.Refactorings.RefactorCodePaneCommandBase.OnExecute(Object parameter) in C:\GitHub\Rubberduck\Rubberduck.Core\UI\Command\Refactorings\RefactorCodePaneCommandBase.cs:line 40
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in C:\GitHub\Rubberduck\Rubberduck.Core\UI\Command\CommandBase.cs:line 85
```

**Comment by MDoerner** [comment]
I think both problems are on me. The root cause seems to be the existence of array access references, which also point to the array declaration.

I think I can fix that quickly by ignoring references with the `IsArrayAccess` property set to `true`.

Are there more places where we do something to all references to an array?
