### ISSUE TITLE
Unhandled Exception: Height most be non-negative

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#5512]
**Rubberduck version information**
Version 2.5.0.20863
OS: Microsoft Windows NT 10.0.18362.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.4978.1000
Host Executable: EXCEL.EXE

**Description**
Root cause is unknown. Intermittent as to when it shows. Started getting this unhandled exception after adding a lot of properties to a worksheet and unit tests.

**To Reproduce**
---Steps to reproduce the behavior:--- Will document if problem perists and can determine cause.

**Expected behavior**
Error gracefully handled internally.

**Logfile**
Rubberduck generates extensive logging in TRACE-Level. If no log was created at `%APPDATA%\Rubberduck\Logs`, check your settings. Include this log for bug reports about the behavior of Rubberduck.

**Call stack**
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

```
************** Exception Text **************
System.ArgumentException: Height must be non-negative.
   at System.Windows.Rect.set_Height(Double value)
   at System.Windows.Controls.VirtualizingStackPanel.ExtendViewport(IHierarchicalVirtualizationAndScrollInfo virtualizationInfoProvider, Boolean isHorizontal, Rect viewport, VirtualizationCacheLength cacheLength, VirtualizationCacheLengthUnit cacheUnit, Size stackPixelSizeInCacheBeforeViewport, Size stackLogicalSizeInCacheBeforeViewport, Size stackPixelSizeInCacheAfterViewport, Size stackLogicalSizeInCacheAfterViewport, Size stackPixelSize, Size stackLogicalSize, Int32& itemsInExtendedViewportCount)
   at System.Windows.Controls.VirtualizingStackPanel.IsExtendedViewportFull()
   at System.Windows.Controls.VirtualizingStackPanel.ShouldItemsChangeAffectLayoutCore(Boolean areItemChangesLocal, ItemsChangedEventArgs args)
   at System.Windows.Controls.VirtualizingPanel.OnItemsChangedInternal(Object sender, ItemsChangedEventArgs args)
   at System.Windows.Controls.Panel.OnItemsChanged(Object sender, ItemsChangedEventArgs args)
   at System.Windows.Controls.ItemContainerGenerator.OnItemAdded(Object item, Int32 index)
   at System.Windows.Controls.ItemContainerGenerator.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)
   at System.Collections.ObjectModel.ReadOnlyObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at MS.Internal.Data.CollectionViewGroupInternal.Insert(Object item, Object seed, IComparer comparer)
   at MS.Internal.Data.CollectionViewGroupRoot.AddToSubgroup(Object item, LiveShapingItem lsi, CollectionViewGroupInternal group, Int32 level, Object name, Boolean loading)
   at MS.Internal.Data.CollectionViewGroupRoot.AddToSubgroups(Object item, LiveShapingItem lsi, CollectionViewGroupInternal group, Int32 level, Boolean loading)
   at System.Windows.Data.ListCollectionView.AddItemToGroups(Object item, LiveShapingItem lsi)
   at System.Windows.Data.ListCollectionView.ProcessCollectionChangedWithAdjustedIndex(NotifyCollectionChangedEventArgs args, Int32 adjustedOldIndex, Int32 adjustedNewIndex)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at Rubberduck.UI.UnitTesting.TestExplorerModel.HandleTestsRefreshed(Object sender, EventArgs args) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Core\UI\UnitTesting\TestExplorerModel.cs:line 230
   at Rubberduck.UnitTesting.TestEngine.<StateChangedHandler>b__22_1() in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.UnitTesting\UnitTesting\TestEngine.cs:line 110
   at Rubberduck.Parsing.UIContext.UiDispatcher.<>c__DisplayClass2_0.<InvokeAsync>b__0(Object x) in C:\Users\ivenbach\source\repos\Rubberduck\Rubberduck.Parsing\UIContext\UiDispatcher.cs:line 26
```

**Comment by Vogel612** [comment]
The root cause of this issue seems to be the virtualization applied to the TestGrid having a bug in the height-calculation.

As it is currently, our code is only adding a new item to a collection [here](https://github.com/rubberduck-vba/Rubberduck/blob/37bd1bb1276854b0757e6a300e5845fc8d941ff2/Rubberduck.Core/UI/UnitTesting/TestExplorerModel.cs#L230). This triggers the insertion of a new row into the GroupingGrid's underlying ListView, where the VirtualizingStackPanel seems to break upon recalculation of the height.

For a repro you could try different "viewport sizes" for the TestExplorer. The issue should appear when the tests are refreshed after a parse completed.
