### ISSUE TITLE
Click "Pending", get "Parse error" followed by "Unexpected error"

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#5658]
Trying out the latest version

**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:
Version 2.5.1.5676
OS: Microsoft Windows NT 10.0.18363.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.13530.20316
Host Executable: EXCEL.EXE

**Description**
Click "Pending", get "Parse error" followed by "Unexpected error"

**Logfile**
Attached
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/5803868/RubberduckLog.txt)

**Comment by retailcoder** [comment]
```
2021-01-12 17:44:18.1564;ERROR-2.5.1.5676;Rubberduck.Parsing.VBA.Parsing.ModuleParser;COM Exception thrown in thread 7 while parsing module Sheet4, ParseTaskID 4c966dbc-e072-4a53-8fb5-ac13a8ad0cc9.;System.Runtime.InteropServices.COMException (0x800AC373): Exception from HRESULT: 0x800AC373
   at Microsoft.Vbe.Interop._VBComponent.Export(String FileName)
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBComponent.ExportAsSourceFile(String folder, Boolean isTempFile, Boolean specialCaseDocumentModules) in C:\projects\rubberduck\Rubberduck.VBEditor.VBA\SafeComWrappers\VB\VBComponent.cs:line 129
   at Rubberduck.VBEditor.VBA.TempSourceFileHandler.Export(IVBComponent component) in C:\projects\rubberduck\Rubberduck.VBEditor.VBA\TempSourceFileHandler.cs:line 20
   at Rubberduck.VBEditor.VBA.TempSourceFileHandler.Read(IVBComponent component) in C:\projects\rubberduck\Rubberduck.VBEditor.VBA\TempSourceFileHandler.cs:line 55
   at Rubberduck.VBEditor.SourceCodeHandling.SourceFileHandlerComponentSourceCodeHandlerAdapter.SourceCode(IVBComponent module) in C:\projects\rubberduck\Rubberduck.VBEEditor\SourceCodeHandling\SourceFileHandlerComponentSourceCodeHandlerAdapter.cs:line 23
   at Rubberduck.VBEditor.SourceCodeHandling.ComponentSourceCodeHandlerSourceCodeHandlerAdapter.SourceCode(QualifiedModuleName module) in C:\projects\rubberduck\Rubberduck.VBEEditor\SourceCodeHandling\ComponentSourceCodeHandlerSourceCodeHandlerAdapter.cs:line 24
   at Rubberduck.Parsing.VBA.Parsing.ModuleParser.AttributesPassResults(QualifiedModuleName module, CancellationToken token) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\Parsing\ModuleParser.cs:line 156
   at Rubberduck.Parsing.VBA.Parsing.ModuleParser.ParseInternal(QualifiedModuleName module, CancellationToken cancellationToken, TokenStreamRewriter rewriter, Guid taskId) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\Parsing\ModuleParser.cs:line 98
   at Rubberduck.Parsing.VBA.Parsing.ModuleParser.Parse(QualifiedModuleName module, CancellationToken cancellationToken, TokenStreamRewriter rewriter) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\Parsing\ModuleParser.cs:line 42
2021-01-12 17:44:18.2154;INFO-2.5.1.5676;Rubberduck.Parsing.VBA.RubberduckParserState;RubberduckParserState (4) is invoking StateChanged (Error);
```

Need more details about the project/environment, `VBComponent.Export` is failing. Is it trying to export to a UNC path? Is the host document saved? Locally? Please confirm whether the latest pre-release still does this.

**Comment by SystemsModelling** [comment]
Version 2.5.1.5758
OS: Microsoft Windows NT 10.0.18363.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.13801.20360
Host Executable: EXCEL.EXE

Start Excel, get default Book1, Alt+F11, RD shows "Parsing" then "Unexpected error" right away
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/6242600/RubberduckLog.txt)

**Comment by SystemsModelling** [comment]
Ahhh..
Excel File > Options > Save shows me
Default local file location C:\Users\Patrick\AppData\Roaming\Microsoft\Windows\Recent
I had that in order to be easily able to open recent files. But RD (and MZTools I now guess) must be trying to create a file there. I changed to a normal folder like F:\Docs and there is no error.
