### ISSUE TITLE
Rubberduck Version 2.5.2.5906 Error on exit from Excel.

### ISSUE THREAD

**Issue by DavidJLambert** [rubberduck-vba/Rubberduck#5764]
**Rubberduck version information**

```
Rubberduck Version 2.5.2.5906
OS: Microsoft Windows NT 10.0.19042.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.13929.20296
Host Executable: EXCEL.EXE
```

**Description**

Since upgrading Rubberduck from 2.5.1.5557 to 2.5.2.5906, when closing Excel, get dialog box with title "Microsoft .NET Framework" and this message:
"Unhandled exception has occurred in a component in your application.  If you click continue, the application will ignore this error and attempt to continue.

COM object that has been separated from its underlying RCW cannot be used."

Excel has not exited and will still be running as a zombie process, and it will not be possible to start up Excel again until the zombie process has been killed.

When I press the "Details button", I see this long long message:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.InteropServices.InvalidComObjectException: COM object that has been separated from its underlying RCW cannot be used.
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Office.Core.CommandBarControl.set_Enabled(Boolean pvarfEnabled)
   at Rubberduck.VBEditor.SafeComWrappers.Office12.CommandBarButton.set_IsEnabled(Boolean value) in C:\projects\rubberduck\Rubberduck.VBEditor.VBA\SafeComWrappers\Office\CommandBarButton.cs:line 192
   at Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase.<>c__DisplayClass11_1.<EvaluateCanExecuteAsync>b__1() in C:\projects\rubberduck\Rubberduck.Core\UI\Command\MenuItems\CommandBars\AppCommandBarBase.cs:line 174
```

**To Reproduce**

1. Open Excel.
2. Click "Developer" tab.
3. Click "Visual Basic" button.
4. Optionally Close "Visual Basic for Applications" window.
5. Exit Excel.

**Comment by Andre-ADPC** [comment]
I confirm that the same issue #5764 exists on my system as well.
The same process as was reported by @DavidJLambert above.

To Reproduce
Steps to reproduce the behavior:
1.	Open Excel.
2.	Click "Developer" tab.
3.	Click "Visual Basic" button. (Rubberduck Splash-screen appears)
4.	Optionally Save/Close "Visual Basic for Applications" window.
5.	Exit Excel. >> .NET Framework throws an error
Simply opening, editing in, and closing Excel does not reproduce the error though.
My System info:
2021-08-23 13:22:40.7561;DEBUG-2.5.2.5906;Rubberduck.Common.LogLevelHelper;
	Rubberduck version 2.5.2.5906 loading:
	Operating System: Microsoft Windows NT 10.0.19043.0 x64
	Host Product: Microsoft Office x64
	Host Version: 16.0.14228.20250
	Host Executable: EXCEL.EXE;
	.NET Framework: Please refer to “Win 10 .NET Update History Summary-2021-08-23_15-47-15.pdf”

Config file was edited and Min Log level was set to 1.
``<UserEditedLogLevel>true</UserEditedLogLevel>
``<MinimumLogLevel>1</MinimumLogLevel>

Based on .NET error message recommendation JIT was enabled in config file under Windows Group config (not sure if this is the correct/best place for the entry though).

``<WindowSettings>
``  <system.windows.forms jitDebugging="true" />
``  <CodeExplorerVisibleOnStartup>false</CodeExplorerVisibleOnStartup>
``    <  [Abreviated]>
``  <CodeExplorer_GroupByType>false</CodeExplorer_GroupByType>
``</WindowSettings>

Note: Full Log File is included with upload for reference.
[Win 10 .NET Update History Summary-2021-08-23_15-47-15.pdf](https://github.com/rubberduck-vba/Rubberduck/files/7030557/Win.10.NET.Update.History.Summary-2021-08-23_15-47-15.pdf)
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/7030558/RubberduckLog.txt)

**Comment by WoHuy** [comment]
I would just like to add I am experiencing this same issue _sometimes_ in Word 2016:
```
Version 2.5.2.5906
OS: Microsoft Windows NT 10.0.17763.0, x64
Host Product: Microsoft Office 2016 x86
Host Version: 16.0.5227.1000
Host Executable: WINWORD.EXE
```

**Comment by daFreeMan** [comment]
I'm not having this issue at all with the latest prerelease build https://github.com/rubberduck-vba/Rubberduck/releases/tag/Prerelease-v2.5.2.6037 and haven't noticed it with any of the pre-release builds since v2.5.2 was released.

**Comment by WoHuy** [comment]
I have installed the latest prerelease build https://github.com/rubberduck-vba/Rubberduck/releases/tag/Prerelease-v2.5.2.6037 and haven't experienced this specific issue anymore.

**Comment by OliverSCE** [comment]
I am experiencing this bug in both release 2.5.2.1 and pre-release 2.5.2.6045 on my office computer (Rubberduck is installed for local user). I have tried 2.5.2.6045 on another machine (installed for all users), and it does not show this bug.

Oliver

**Comment by ijourneaux** [comment]
First time posting here but i have been struggling with this issue on my system as well. Running 2.5.2.6059. In my case, when this occurs, I end up with ghost Excel worksheets that I can not delete. The only solution is to save workbook as a xlsx file and manually re add in the modules and work sheet code.  Real pain.  
Obviously not sure if it is related but if I see the extra sheets and exit Excel I get this error. If I don't I can save and exit Excel without any issues.

**Comment by michaelmagistro** [comment]
> 

Running into this same issue as well on Win 10

**Comment by tolga-balci** [comment]
Same here. Windows 11, Rubberduck 2.5.9, Microsoft Excel for Microsoft 365 MSO (Version 2307) 64-bit

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Threading.Tasks.TaskCanceledException: A task was canceled.


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Rubberduck
    Assembly Version: 2.5.9.6291
    Win32 Version: 2.5.9.6291
    CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.dll
----------------------------------------
Microsoft.VisualStudio.Interop
    Assembly Version: 17.0.0.0
    Win32 Version: 17.0.31723.112
    CodeBase: file:///C:/ProgramData/Rubberduck/Microsoft.VisualStudio.Interop.DLL
----------------------------------------
NLog
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.10.8381
    CodeBase: file:///C:/ProgramData/Rubberduck/NLog.DLL
----------------------------------------
CrowdStrike.Sensor.ScriptControl
    Assembly Version: 7.1.17312.0
    Win32 Version: 7.01.17312.0
    CodeBase: file:///C:/WINDOWS/System32/CrowdStrike.Sensor.ScriptControl17312.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9172.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
Rubberduck.VBEditor
    Assembly Version: 2.5.9.6291
    Win32 Version: 2.5.9.6291
    CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.VBEditor.DLL
----------------------------------------
Rubberduck.Core
    Assembly Version: 2.5.9.6291
    Win32 Version: 2.5.9.6291
    CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.Core.DLL
----------------------------------------
System.IO.Abstractions
    Assembly Version: 12.0.0.0
    Win32 Version: 12.2.1.44447
    CodeBase: file:///C:/ProgramData/Rubberduck/System.IO.Abstractions.DLL
----------------------------------------
Rubberduck.VBEditor.VB6
    Assembly Version: 2.5.9.6291
    Win32 Version: 2.5.9.6291
    CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.VBEditor.VB6.DLL
----------------------------------------
Rubberduck.VBEditor.VBA
    Assembly Version: 2.5.9.6291
    Win32 Version: 2.5.9.6291
    CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.VBEditor.VBA.DLL
----------------------------------------
Rubberduck.InternalApi
    Assembly Version: 2.5.9.6291
    Win32 Version: 2.5.9.6291
    CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.InternalApi.DLL
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
EasyHook
    Assembly Version: 2.7.6684.0
    Win32 Version: 2.7.6684.0
    CodeBase: file:///C:/ProgramData/Rubberduck/EasyHook.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Rubberduck.SettingsProvider
    Assembly Version: 2.5.9.6291
    Win32 Version: 2.5.9.6291
    CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.SettingsProvider.DLL
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
Rubberduck.Resources
    Assembly Version: 2.5.9.6291
    Win32 Version: 2.5.9.6291
    CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.Resources.DLL
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Rubberduck.Resources.resources
    Assembly Version: 2.5.9.6291
    Win32 Version: 2.5.9.6291
    CodeBase: file:///C:/ProgramData/Rubberduck/cs/Rubberduck.Resources.resources.DLL
----------------------------------------
Rubberduck.Resources.resources
    Assembly Version: 2.5.9.6291
    Win32 Version: 2.5.9.6291
    CodeBase: file:///C:/ProgramData/Rubberduck/de/Rubberduck.Resources.resources.DLL
----------------------------------------
Rubberduck.Resources.resources
    Assembly Version: 2.5.9.6291
    Win32 Version: 2.5.9.6291
    CodeBase: file:///C:/ProgramData/Rubberduck/es/Rubberduck.Resources.resources.DLL
----------------------------------------
Rubberduck.Resources.resources
    Assembly Version: 2.5.9.6291
    Win32 Version: 2.5.9.6291
    CodeBase: file:///C:/ProgramData/Rubberduck/fr/Rubberduck.Resources.resources.DLL
----------------------------------------
Rubberduck.Resources.resources
    Assembly Version: 2.5.9.6291
    Win32 Version: 2.5.9.6291
    CodeBase: file:///C:/ProgramData/Rubberduck/it/Rubberduck.Resources.resources.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Castle.Windsor
    Assembly Version: 4.0.0.0
    Win32 Version: 4.1.0
    CodeBase: file:///C:/ProgramData/Rubberduck/Castle.Windsor.DLL
----------------------------------------
Castle.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.2.1
    CodeBase: file:///C:/ProgramData/Rubberduck/Castle.Core.DLL
----------------------------------------
Rubberduck.Parsing
    Assembly Version: 2.5.9.6291
    Win32 Version: 2.5.9.6291
    CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.Parsing.DLL
----------------------------------------
Rubberduck.UnitTesting
    Assembly Version: 2.5.9.6291
    Win32 Version: 2.5.9.6291
    CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.UnitTesting.DLL
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
office
    Assembly Version: 15.0.0.0
    Win32 Version: 15.0.4613.1000
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/office/15.0.0.0__71e9bce111e9429c/office.dll
----------------------------------------
Rubberduck.Interaction
    Assembly Version: 2.5.9.6291
    Win32 Version: 2.5.9.6291
    CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.Interaction.DLL
----------------------------------------
Rubberduck.SmartIndenter
    Assembly Version: 2.5.9.6291
    Win32 Version: 2.5.9.6291
    CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.SmartIndenter.DLL
----------------------------------------
Antlr4.Runtime
    Assembly Version: 4.6.0.0
    Win32 Version: 4.6.4.0
    CodeBase: file:///C:/ProgramData/Rubberduck/Antlr4.Runtime.DLL
----------------------------------------
Rubberduck.CodeAnalysis
    Assembly Version: 2.5.9.6291
    Win32 Version: 2.5.9.6291
    CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.CodeAnalysis.DLL
----------------------------------------
Rubberduck.Refactorings
    Assembly Version: 2.5.9.6291
    Win32 Version: 2.5.9.6291
    CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.Refactorings.dll
----------------------------------------
Rubberduck.RegexAssistant
    Assembly Version: 2.5.9.6291
    Win32 Version: 2.5.9.6291
    CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.RegexAssistant.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
System.Windows.Interactivity
    Assembly Version: 4.0.0.0
    Win32 Version: 2.0.20525.0
    CodeBase: file:///C:/ProgramData/Rubberduck/System.Windows.Interactivity.DLL
----------------------------------------
ICSharpCode.AvalonEdit
    Assembly Version: 5.0.3.0
    Win32 Version: 5.0.3.0
    CodeBase: file:///C:/ProgramData/Rubberduck/ICSharpCode.AvalonEdit.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 1.2.3.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///C:/ProgramData/Rubberduck/System.Collections.Immutable.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
DynamicProxyGenAssembly2
    Assembly Version: 0.0.0.0
    Win32 Version: 4.2.1
    CodeBase: file:///C:/ProgramData/Rubberduck/Castle.Core.dll
----------------------------------------
DynamicProxyGenAssembly2
    Assembly Version: 0.0.0.0
    Win32 Version: 4.2.1
    CodeBase: file:///C:/ProgramData/Rubberduck/Castle.Core.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
WindowsFormsIntegration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9139.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsFormsIntegration/v4.0_4.0.0.0__31bf3856ad364e35/WindowsFormsIntegration.dll
----------------------------------------
Infralution.Localization.Wpf
    Assembly Version: 3.3.0.0
    Win32 Version: 3.3.0.0
    CodeBase: file:///C:/ProgramData/Rubberduck/Infralution.Localization.Wpf.dll
----------------------------------------
System.Windows.Controls.Ribbon
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Controls.Ribbon/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Controls.Ribbon.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
PresentationFramework.Aero
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero.dll
----------------------------------------
PresentationFramework.Aero2
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero2/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero2.dll
----------------------------------------
PresentationFramework-SystemData
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemData/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemData.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
PresentationFramework-SystemXmlLinq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXmlLinq/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXmlLinq.dll
----------------------------------------
PresentationFramework-SystemXml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXml/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXml.dll
----------------------------------------
PresentationFramework-SystemCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemCore/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemCore.dll
----------------------------------------
GongSolutions.WPF.DragDrop
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/ProgramData/Rubberduck/GongSolutions.WPF.DragDrop.DLL
----------------------------------------
UIAutomationProvider
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationProvider/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationProvider.dll
----------------------------------------
CustomMarshalers
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/CustomMarshalers/v4.0_4.0.0.0__b03f5f7f11d50a3a/CustomMarshalers.dll
----------------------------------------
stdole
    Assembly Version: 7.0.3300.0
    Win32 Version: 7.00.9466
    CodeBase: file:///C:/WINDOWS/assembly/GAC/stdole/7.0.3300.0__b03f5f7f11d50a3a/stdole.dll
----------------------------------------
System.Dynamic.DynamicAssembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.1.25517
    CodeBase: file:///C:/ProgramData/Rubberduck/Newtonsoft.Json.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```
