### ISSUE TITLE
Library not registered. -- HRESULT: 0x8002801D

### ISSUE THREAD

**Issue by AndreasMatthias** [rubberduck-vba/Rubberduck#5943]
The following issue happens by just opening VB-Editor without any direct interaction with Rubberduck.

This is what I did:

* Start Excel
* Create a new file
* Press ALT+F11

And this is the log file after these 3 steps:

```
2022-02-05 21:01:39.9453;DEBUG-2.5.2.6051;Rubberduck.Common.LogLevelHelper;
	Rubberduck version 2.5.2.6051 loading:
	Operating System: Microsoft Windows NT 10.0.19044.0 x64
	Host Product: Microsoft Office 2013 x86
	Host Version: 15.0.5415.1000
	Host Executable: EXCEL.EXE;
2022-02-05 21:01:40.2115;INFO-2.5.2.6051;Rubberduck.UI.Command.VersionCheckCommand;Executing version check...;
2022-02-05 21:01:40.3045;DEBUG-2.5.2.6051;Rubberduck.Parsing.VBA.RubberduckParserState;Project '133316613' was added.;
2022-02-05 21:01:40.3354;DEBUG-2.5.2.6051;Rubberduck.Parsing.VBA.ParseCoordinator;Parsing run started. (thread 5).;
2022-02-05 21:01:40.3354;INFO-2.5.2.6051;Rubberduck.Parsing.VBA.RubberduckParserState;RubberduckParserState (1) is invoking StateChanged (Started);
2022-02-05 21:01:40.8163;DEBUG-2.5.2.6051;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisWorkbook' state is changing to 'Started' (thread 5);
2022-02-05 21:01:40.8496;DEBUG-2.5.2.6051;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Sheet1' state is changing to 'Started' (thread 5);
2022-02-05 21:01:40.8496;INFO-2.5.2.6051;Rubberduck.Parsing.VBA.RubberduckParserState;RubberduckParserState (2) is invoking StateChanged (LoadingReference);
2022-02-05 21:01:40.8649;INFO-2.5.2.6051;Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase;System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rubberduck.UI.Command.MenuItems.CommandBars.RubberduckCommandBar.<OnParserStateChanged>d__11.MoveNext();System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rubberduck.UI.Command.MenuItems.CommandBars.RubberduckCommandBar.<OnParserStateChanged>d__11.MoveNext()
2022-02-05 21:01:41.2792;ERROR-2.5.2.6051;Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase;ReparseCommandMenuItem.EvaluateCanExecute(RubberduckParserState) threw an exception.;System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase.<EvaluateCanExecuteAsync>d__11.MoveNext()
2022-02-05 21:01:41.3374;ERROR-2.5.2.6051;Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase;Invalid cast exception while finding child with tag 'Rubberduck.UI.Command.MenuItems.CommandBars.ReparseCommandMenuItem' in the command bar.;System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Office.Core.CommandBarControl'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{000C0308-0000-0000-C000-000000000046}' failed due to the following error: Library not registered. (Exception from HRESULT: 0x8002801D (TYPE_E_LIBNOTREGISTERED)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Office.Core.CommandBarControl.get_Tag()
   at Rubberduck.VBEditor.SafeComWrappers.Office12.CommandBarButton.get_Tag()
   at Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase.<>c__DisplayClass6_0.<FindChildByTag>b__0(KeyValuePair`2 kvp)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase.FindChildByTag(String tag)
2022-02-05 21:01:41.3515;INFO-2.5.2.6051;Rubberduck.Parsing.Common.ParsingStageTimer;Loaded ComProjects for user projects in 445ms.;
2022-02-05 21:01:41.3852;INFO-2.5.2.6051;Rubberduck.Parsing.Common.ParsingStageTimer;Loaded declarations from ComProjects for user projects in 23ms.;
2022-02-05 21:01:43.1035;INFO-2.5.2.6051;Rubberduck.Parsing.Common.ParsingStageTimer;Loaded and unloaded referenced libraries in 1707ms.;
2022-02-05 21:01:43.6961;DEBUG-2.5.2.6051;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisWorkbook' state is changing to 'Parsing' (thread 5);
2022-02-05 21:01:43.7068;DEBUG-2.5.2.6051;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Sheet1' state is changing to 'Parsing' (thread 6);
2022-02-05 21:01:43.7068;INFO-2.5.2.6051;Rubberduck.Parsing.VBA.RubberduckParserState;RubberduckParserState (3) is invoking StateChanged (Parsing);
2022-02-05 21:01:43.8357;ERROR-2.5.2.6051;Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase;Invalid cast exception while finding child with tag 'Rubberduck.UI.Command.MenuItems.CommandBars.ReparseCommandMenuItem' in the command bar.;System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Office.Core.CommandBarControl'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{000C0308-0000-0000-C000-000000000046}' failed due to the following error: Library not registered. (Exception from HRESULT: 0x8002801D (TYPE_E_LIBNOTREGISTERED)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Office.Core.CommandBarControl.get_Tag()
   at Rubberduck.VBEditor.SafeComWrappers.Office12.CommandBarButton.get_Tag()
   at Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase.<>c__DisplayClass6_0.<FindChildByTag>b__0(KeyValuePair`2 kvp)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase.FindChildByTag(String tag)
2022-02-05 21:01:44.0427;DEBUG-2.5.2.6051;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisWorkbook' state is changing to 'Parsed' (thread 5);
2022-02-05 21:01:44.0496;DEBUG-2.5.2.6051;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Sheet1' state is changing to 'Parsed' (thread 5);
2022-02-05 21:01:44.0687;INFO-2.5.2.6051;Rubberduck.Parsing.Common.ParsingStageTimer;Parsed user modules in 350ms.;
2022-02-05 21:01:44.0687;INFO-2.5.2.6051;Rubberduck.Parsing.VBA.RubberduckParserState;RubberduckParserState (4) is invoking StateChanged (Parsed);
2022-02-05 21:01:44.0936;DEBUG-2.5.2.6051;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisWorkbook' state is changing to 'ResolvingDeclarations' (thread 5);
2022-02-05 21:01:44.0936;ERROR-2.5.2.6051;Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase;Invalid cast exception while finding child with tag 'Rubberduck.UI.Command.MenuItems.CommandBars.ReparseCommandMenuItem' in the command bar.;System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Office.Core.CommandBarControl'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{000C0308-0000-0000-C000-000000000046}' failed due to the following error: Library not registered. (Exception from HRESULT: 0x8002801D (TYPE_E_LIBNOTREGISTERED)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Office.Core.CommandBarControl.get_Tag()
   at Rubberduck.VBEditor.SafeComWrappers.Office12.CommandBarButton.get_Tag()
   at Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase.<>c__DisplayClass6_0.<FindChildByTag>b__0(KeyValuePair`2 kvp)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase.FindChildByTag(String tag)
2022-02-05 21:01:44.0936;DEBUG-2.5.2.6051;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Sheet1' state is changing to 'ResolvingDeclarations' (thread 12);
2022-02-05 21:01:44.1345;INFO-2.5.2.6051;Rubberduck.Parsing.VBA.RubberduckParserState;RubberduckParserState (5) is invoking StateChanged (ResolvingDeclarations);
2022-02-05 21:01:44.1345;DEBUG-2.5.2.6051;Rubberduck.Parsing.VBA.DeclarationResolving.DeclarationResolveRunnerBase;Creating declarations for module VBAProject.ThisWorkbook.;
2022-02-05 21:01:44.1571;DEBUG-2.5.2.6051;Rubberduck.Parsing.VBA.DeclarationResolving.DeclarationResolveRunnerBase;18ms to resolve declarations for component VBAProject.ThisWorkbook;
2022-02-05 21:01:44.1571;DEBUG-2.5.2.6051;Rubberduck.Parsing.VBA.DeclarationResolving.DeclarationResolveRunnerBase;Creating declarations for module VBAProject.Sheet1.;
2022-02-05 21:01:44.1571;DEBUG-2.5.2.6051;Rubberduck.Parsing.VBA.DeclarationResolving.DeclarationResolveRunnerBase;9ms to resolve declarations for component VBAProject.Sheet1;
2022-02-05 21:01:44.1571;INFO-2.5.2.6051;Rubberduck.Parsing.Common.ParsingStageTimer;Resolved user declaration in 31ms.;
2022-02-05 21:01:44.3384;INFO-2.5.2.6051;Rubberduck.Parsing.VBA.RubberduckParserState;RubberduckParserState (6) is invoking StateChanged (ResolvedDeclarations);
2022-02-05 21:01:44.3384;INFO-2.5.2.6051;Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase;System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rubberduck.UI.Command.MenuItems.CommandBars.RubberduckCommandBar.<OnParserStateChanged>d__11.MoveNext();System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rubberduck.UI.Command.MenuItems.CommandBars.RubberduckCommandBar.<OnParserStateChanged>d__11.MoveNext()
2022-02-05 21:01:44.4134;ERROR-2.5.2.6051;Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase;Invalid cast exception while finding child with tag 'Rubberduck.UI.Command.MenuItems.CommandBars.ReparseCommandMenuItem' in the command bar.;System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Office.Core.CommandBarControl'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{000C0308-0000-0000-C000-000000000046}' failed due to the following error: Library not registered. (Exception from HRESULT: 0x8002801D (TYPE_E_LIBNOTREGISTERED)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Office.Core.CommandBarControl.get_Tag()
   at Rubberduck.VBEditor.SafeComWrappers.Office12.CommandBarButton.get_Tag()
   at Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase.<>c__DisplayClass6_0.<FindChildByTag>b__0(KeyValuePair`2 kvp)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase.FindChildByTag(String tag)
2022-02-05 21:01:44.6892;DEBUG-2.5.2.6051;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisWorkbook' state is changing to 'ResolvingReferences' (thread 5);
2022-02-05 21:01:44.6892;DEBUG-2.5.2.6051;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Sheet1' state is changing to 'ResolvingReferences' (thread 6);
2022-02-05 21:01:44.7867;INFO-2.5.2.6051;Rubberduck.Parsing.VBA.RubberduckParserState;RubberduckParserState (7) is invoking StateChanged (ResolvingReferences);
2022-02-05 21:01:44.8077;INFO-2.5.2.6051;Rubberduck.Parsing.Common.ParsingStageTimer;Added supertypes for document modules in 4ms.;
2022-02-05 21:01:44.8199;ERROR-2.5.2.6051;Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase;Invalid cast exception while finding child with tag 'Rubberduck.UI.Command.MenuItems.CommandBars.ReparseCommandMenuItem' in the command bar.;System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Office.Core.CommandBarControl'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{000C0308-0000-0000-C000-000000000046}' failed due to the following error: Library not registered. (Exception from HRESULT: 0x8002801D (TYPE_E_LIBNOTREGISTERED)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Office.Core.CommandBarControl.get_Tag()
   at Rubberduck.VBEditor.SafeComWrappers.Office12.CommandBarButton.get_Tag()
   at Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase.<>c__DisplayClass6_0.<FindChildByTag>b__0(KeyValuePair`2 kvp)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase.FindChildByTag(String tag)
2022-02-05 21:01:44.9181;WARN-2.5.2.6051;Rubberduck.Parsing.VBA.ReferenceManagement.CompilationPasses.TypeAnnotationPass;Failed to resolve type VBE;
2022-02-05 21:01:44.9498;WARN-2.5.2.6051;Rubberduck.Parsing.VBA.ReferenceManagement.CompilationPasses.TypeAnnotationPass;Failed to resolve type VBE;
2022-02-05 21:01:44.9958;WARN-2.5.2.6051;Rubberduck.Parsing.VBA.ReferenceManagement.CompilationPasses.TypeAnnotationPass;Failed to resolve type HELPINFO;
2022-02-05 21:01:45.0027;WARN-2.5.2.6051;Rubberduck.Parsing.VBA.ReferenceManagement.CompilationPasses.TypeAnnotationPass;Failed to resolve type MSGBOXPARAMS;
2022-02-05 21:01:45.1086;WARN-2.5.2.6051;Rubberduck.Parsing.VBA.ReferenceManagement.CompilationPasses.TypeAnnotationPass;Failed to resolve type VBProject;
2022-02-05 21:01:45.1637;WARN-2.5.2.6051;Rubberduck.Parsing.VBA.ReferenceManagement.CompilationPasses.TypeAnnotationPass;Failed to resolve type UserForm;
2022-02-05 21:01:45.1920;WARN-2.5.2.6051;Rubberduck.Parsing.VBA.ReferenceManagement.CompilationPasses.TypeAnnotationPass;Failed to resolve type VBProject;
2022-02-05 21:01:45.3755;INFO-2.5.2.6051;Rubberduck.Parsing.Common.ParsingStageTimer;Executed compilation passes in 4ms.;
2022-02-05 21:01:45.3921;DEBUG-2.5.2.6051;Rubberduck.Parsing.VBA.ReferenceManagement.ReferenceResolveRunnerBase;Resolving identifier references in 'VBAProject.Sheet1'... (thread 5);
2022-02-05 21:01:45.3921;DEBUG-2.5.2.6051;Rubberduck.Parsing.VBA.ReferenceManagement.ReferenceResolveRunnerBase;Binding resolution done for component 'VBAProject.Sheet1' in 0ms (thread 5);
2022-02-05 21:01:45.4097;DEBUG-2.5.2.6051;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Sheet1' state is changing to 'Ready' (thread 5);
2022-02-05 21:01:45.4097;DEBUG-2.5.2.6051;Rubberduck.Parsing.VBA.ReferenceManagement.ReferenceResolveRunnerBase;Resolving identifier references in 'VBAProject.ThisWorkbook'... (thread 5);
2022-02-05 21:01:45.4361;DEBUG-2.5.2.6051;Rubberduck.Parsing.VBA.ReferenceManagement.ReferenceResolveRunnerBase;Binding resolution done for component 'VBAProject.ThisWorkbook' in 0ms (thread 5);
2022-02-05 21:01:45.4439;DEBUG-2.5.2.6051;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisWorkbook' state is changing to 'Ready' (thread 5);
2022-02-05 21:01:45.4538;INFO-2.5.2.6051;Rubberduck.Parsing.Common.ParsingStageTimer;Resolved references in 66ms.;
2022-02-05 21:01:45.5025;INFO-2.5.2.6051;Rubberduck.Parsing.Common.ParsingStageTimer;Determined module to module references in 34ms.;
2022-02-05 21:01:45.7149;INFO-2.5.2.6051;Rubberduck.Parsing.VBA.RubberduckParserState;RubberduckParserState (8) is invoking StateChanged (Ready);
2022-02-05 21:01:45.7364;ERROR-2.5.2.6051;Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase;Invalid cast exception while finding child with tag 'Rubberduck.UI.Command.MenuItems.CommandBars.ReparseCommandMenuItem' in the command bar.;System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Office.Core.CommandBarControl'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{000C0308-0000-0000-C000-000000000046}' failed due to the following error: Library not registered. (Exception from HRESULT: 0x8002801D (TYPE_E_LIBNOTREGISTERED)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Office.Core.CommandBarControl.get_Tag()
   at Rubberduck.VBEditor.SafeComWrappers.Office12.CommandBarButton.get_Tag()
   at Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase.<>c__DisplayClass6_0.<FindChildByTag>b__0(KeyValuePair`2 kvp)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase.FindChildByTag(String tag)
2022-02-05 21:01:45.7624;ERROR-2.5.2.6051;Rubberduck.Parsing.VBA.RubberduckParserState;An exception occurred when notifying consumers of updated parser state.;System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Vbe.Interop.VBE'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{0002E166-0000-0000-C000-000000000046}' failed due to the following error: Error loading type library/DLL. (Exception from HRESULT: 0x80029C4A (TYPE_E_CANTLOADLIBRARY)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Vbe.Interop.VBE.get_VBProjects()
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBE.get_VBProjects()
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBE.get_IsInDesignMode()
   at Rubberduck.VBEditor.ComManagement.NonDisposalDecorators.VbeNonDisposalDecorator`1.get_IsInDesignMode()
   at Rubberduck.UnitTesting.TestEngine.get_CanRun()
   at Rubberduck.UnitTesting.TestEngine.StateChangedHandler(Object sender, ParserStateEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Rubberduck.Parsing.VBA.RubberduckParserState.OnStateChanged(Object requestor, CancellationToken token, ParserState state, ParserState oldStatus)
2022-02-05 21:01:45.7869;INFO-2.5.2.6051;Rubberduck.Parsing.VBA.ParseCoordinator;Parsing run finished after 5.4475459s. (thread 5).;
2022-02-05 21:01:45.7869;ERROR-2.5.2.6051;Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase;Invalid cast exception while finding child with tag 'Rubberduck.UI.Command.MenuItems.CommandBars.ReparseCommandMenuItem' in the command bar.;System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Office.Core.CommandBarControl'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{000C0308-0000-0000-C000-000000000046}' failed due to the following error: Library not registered. (Exception from HRESULT: 0x8002801D (TYPE_E_LIBNOTREGISTERED)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Office.Core.CommandBarControl.get_Tag()
   at Rubberduck.VBEditor.SafeComWrappers.Office12.CommandBarButton.get_Tag()
   at Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase.<>c__DisplayClass6_0.<FindChildByTag>b__0(KeyValuePair`2 kvp)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase.FindChildByTag(String tag)
2022-02-05 21:01:45.9889;ERROR-2.5.2.6051;Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase;Invalid cast exception while finding child with tag 'Rubberduck.UI.Command.MenuItems.CommandBars.ReparseCommandMenuItem' in the command bar.;System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Office.Core.CommandBarControl'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{000C0308-0000-0000-C000-000000000046}' failed due to the following error: Library not registered. (Exception from HRESULT: 0x8002801D (TYPE_E_LIBNOTREGISTERED)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Office.Core.CommandBarControl.get_Tag()
   at Rubberduck.VBEditor.SafeComWrappers.Office12.CommandBarButton.get_Tag()
   at Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase.<>c__DisplayClass6_0.<FindChildByTag>b__0(KeyValuePair`2 kvp)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase.FindChildByTag(String tag)

```

**Comment by retailcoder** [comment]
The COM registration for the MSO CommandBars appears to be broken. This could be due to a faulty installation of Office, for example if multiple versions of different Office components were installed but not in chronological release order (e.g. installing Visio or Access 2010 *after* installing Office 2013). Can you confirm a clean Office install and no other VBIDE add-ins loaded?

**Comment by AndreasMatthias** [comment]
Yes. Office 2013 is the only Office version ever running on this operating system. No other add-ins are installed.

**Comment by AndreasMatthias** [comment]
Is there anything I can do to track down this issue? An Office repair did not help either.

**Comment by retailcoder** [comment]
Awesome! Thanks for posting the troubleshooting details! Makes me wonder if it could be turned into a script or a tool to detect such registration issues and clean up registry keys in the installer...
