### ISSUE TITLE
Error on close.

### ISSUE THREAD

**Issue by ateric** [rubberduck-vba/Rubberduck#6020]
Version 2.5.2.6106
OS: Microsoft Windows NT 10.0.22000.0, x64
Host Product: Microsoft Office 2013 x64
Host Version: 15.0.5485.1000
Host Executable: EXCEL.EXE

1. open Excel
2. open VBA
3. close Excel

```
System.Runtime.InteropServices.InvalidComObjectException: COM object that has been separated from its underlying RCW cannot be used.
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Office.Core.CommandBarControl.set_Enabled(Boolean pvarfEnabled)
   at Rubberduck.VBEditor.SafeComWrappers.Office12.CommandBarButton.set_IsEnabled(Boolean value)
   at Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase.<>c__DisplayClass11_1.<EvaluateCanExecuteAsync>b__1()
```

~ Not expected behavior.

**Comment by retailcoder** [comment]
Indeed, not expected. Crashing on exit has been afflicting Rubberduck for a long time, it's a known and disclosed issue. One solution would be to isolate RD by implementing a COM shim that loads RD into its own appdomain, but that would further complicate an already-complex build process. So what we're looking at is to remove all but one toolwindow, and move the entire RD UI there (including a custom editor pane) - work has begun on that front, but that's Rubberduck 3.x stuff involving a complete overhaul of the entire solution.

**Comment by ateric** [comment]
Thanks for the reply, sorry for the late response.

That's ok, not much harm done.

Is there a way to close RD properly so Excel doesn't leave any services behind when exiting?

**Comment by retailcoder** [comment]
It's kind of random - I personally haven't experienced a crash on shut down with an Excel host for a long time, but you can try to manually unload the add-in (via the VBE's "add-ins" menu) before closing Excel: the issue primary arises when the host decides to kill certain COM objects before Rubberduck had a chance to let them go, so a manual unload should systematically result in a clean process exit.

**Comment by ateric** [comment]
As I recall, I didn't experience this issue in the first version of RD that I tried. Then on the second or third version, the issue arose to disappear on the following version and then came back on the latest version again. It happens every time I exit.

I will try your suggestion although it may be simpler to kill Excel when I'm done... 😉

Thanks again and good luck with the next version.

**Comment by daFreeMan** [comment]
I used to have the ghost Excel and Access processes left behind _all_ the time and started Task Manager on boot as the workaround. I haven't had this happen in builds for well over a year now, probably more like 2 - 2.5 years.
