### ISSUE TITLE
When I recently open the code ( via any macro) , I get an OLE error, and wait for at least a minute , until it gives me a popup of OLE Problem

### ISSUE THREAD

**Issue by shaishalom** [rubberduck-vba/Rubberduck#6097]
When I recently open the code (via any macro)  I see the rubberdock image for a long time, then after a minute I get an OLE error with 3 options : OK ,wait and cancel  
only cancel gave me the VBA Editor
 
```
Rubberduck Version 2.5.2.5906
OS: Microsoft Windows NT 10.0.22621.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.15601.20538
Host Executable: EXCEL.EXE
```

**Description**
When I open the VB Editor and get the rubberduck image, it freeze for long time

**To Reproduce**

1. Go to excel
2. open the macro using assign macro
3. the icon of rubberduck is stuck for long time, until the OLE problem popup is appear with the options what to do

**Logfile** (taken from the file)

```
2023-03-11 08:50:09.6960;ERROR-;Rubberduck.VBEditor.SafeComWrappers.SafeComWrapper`1;Unexpected COM exception while acquiring the host application object for application Excel via COM reflection.;System.Runtime.InteropServices.COMException (0x80010002): Call was canceled by the message filter. (Exception from HRESULT: 0x80010002 (RPC_E_CALL_CANCELED))
   at System.Runtime.InteropServices.Marshal.GetActiveObject(Guid& rclsid, IntPtr reserved, Object& ppunk)
   at System.Runtime.InteropServices.Marshal.GetActiveObject(String progID)
   at Rubberduck.VBEditor.SafeComWrappers.Abstract.HostApplicationBase`1.ApplicationFromComReflection(String applicationName) in C:\projects\rubberduck\Rubberduck.VBEEditor\SafeComWrappers\Abstract\HostApplicationBase.cs:line 27
```

**Comment by daFreeMan** [comment]
Please post a complete log file.

**Comment by retailcoder** [comment]
Is the VBIDE loading any other add-ins?
