### ISSUE TITLE
Test Explorer crashes if a break point is set in test module. RD 1.4.3

### ISSUE THREAD

**Issue by AndrewM-** [rubberduck-vba/Rubberduck#833]
I have a test that is passing even when the function return value is wrong.  This means my test expression is wrong so I put a break point in the test module so I could examine the test.  Below is the result.  The workaround for me is to try the test expression in the immediate window instead.

```text
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.InteropServices.COMException (0x800ADF09): Can't execute code in break mode
   at Microsoft.Vbe.Interop.ReferencesClass.Remove(Reference Reference)
   at Rubberduck.UnitTesting.ProjectTestExtensions.EnsureReferenceToAddInLibrary(VBProject project) in c:\Users\Mathieu\Source\Repos\Rubberduck\RetailCoder.VBE\UnitTesting\ProjectTestExtensions.cs:line 105
   at Rubberduck.UI.UnitTesting.TestExplorerDockablePresenter.RunTests(IEnumerable`1 tests) in c:\Users\Mathieu\Source\Repos\Rubberduck\RetailCoder.VBE\UI\UnitTesting\TestExplorerDockablePresenter.cs:line 119
   at Rubberduck.UI.UnitTesting.TestExplorerDockablePresenter.OnExplorerRunSelectedTestButtonClick(Object sender, SelectedTestEventArgs e) in c:\Users\Mathieu\Source\Repos\Rubberduck\RetailCoder.VBE\UI\UnitTesting\TestExplorerDockablePresenter.cs:line 162
   at Rubberduck.UI.UnitTesting.TestExplorerWindow.RunSelectedTestMenuItemClicked(Object sender, EventArgs e) in c:\Users\Mathieu\Source\Repos\Rubberduck\RetailCoder.VBE\UI\UnitTesting\TestExplorerWindow.cs:line 134
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.96.0 built by: NETFXREL2STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Rubberduck
    Assembly Version: 1.4.3.2343
    Win32 Version: 1.4.3.0
    CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.DLL
----------------------------------------
Microsoft.Vbe.Interop
    Assembly Version: 15.0.0.0
    Win32 Version: 15.0.4749.1000
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.Vbe.Interop/15.0.0.0__71e9bce111e9429c/Microsoft.Vbe.Interop.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.93.0 built by: NETFXREL2STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
Rubberduck.VBEditor
    Assembly Version: 1.0.5667.2338
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.VBEditor.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Rubberduck.Parsing
    Assembly Version: 1.0.5667.2339
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.Parsing.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
Rubberduck.SourceControl
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.SourceControl.DLL
----------------------------------------
Ninject
    Assembly Version: 3.2.0.0
    Win32 Version: 3.2.2.0
    CodeBase: file:///C:/ProgramData/Rubberduck/Ninject.DLL
----------------------------------------
NLog
    Assembly Version: 3.2.1.0
    Win32 Version: 3.2.1.0
    CodeBase: file:///C:/ProgramData/Rubberduck/NLog.DLL
----------------------------------------
office
    Assembly Version: 15.0.0.0
    Win32 Version: 15.0.4753.1003
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/office/15.0.0.0__71e9bce111e9429c/office.dll
----------------------------------------
CustomMarshalers
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/CustomMarshalers/v4.0_4.0.0.0__b03f5f7f11d50a3a/CustomMarshalers.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

```

**Comment by retailcoder** [comment]
That's rather interesting... first time I see a breakpoint blow things up - I've seen "can't execute in break mode" fired by the VBE when you try to break when executing a method that was generated on the fly (don't try this at home!)... looking at the stack trace though, it looks like RD was attempting to ensure the project was referencing the `rubberduck.tlb` type library... we must be missing a `try/catch` there, but I'm curious about the repro steps. Please confirm:

 1. Place breakpoint in failing test
 1. Test Explorer / Run all tests
 1. Hit breakpoint
 1. Tweak code in break mode
 1. Run all tests again -> boom

I think 5 should have been F5-resume, to let the current "session" come to an end.

**Comment by AndrewM-** [comment]
I can't repeat it either.  They say that problems that go away by themselves can come back by themselves so I will wait till then.  It is all working like a charm now.

**Comment by AndrewM-** [comment]
Just a comment, I have MZ tools (free) installed and also have the FMS ($1000) add-ins installed.  These are the two toolkits that most access developers might have.  So effectively I am testing for compatibility with other tools.  So far their have been no conflicts.

**Comment by retailcoder** [comment]
@AndrewM-  there's a known issue with one [rather obscure] MZ-Tools functionality: if you toggle line numbers on, you will break the parser. We have yet to figure out how to make numbered lines play well with our VBA grammar. (see #417)

**Comment by retailcoder** [comment]
Confirming repro steps above: trying to run unit tests while in break mode will throw that exception. Simply dismiss the dialog and press F5 to resume execution (expect thrown-off test duration).

So the thing to fix here, is to handle that exception and display a friendly message. Or better, disable the test explorer and the unit testing menu commands altogether while tests are running.

**Comment by AndrewM-** [comment]
@retailcoder I have not been able to figure out the repro steps.  As I tend to cycle from a running form to the code and back again many times, I tend to create conditions that are hard to reproduce, even if I do exactly what I just did.  If I see it again, I will document how to cause it.  I had to decompile and repair and compact the database and restart ms-access to get my code working again.  This may be an ms-access issue.

**Comment by Vogel612** [comment]
@AndrewM- let me chime in here. There seems to be a minor misunderstanding. What @retailcoder  wants, is that you confirm the repro steps outlined in [this earlier comment](https://github.com/rubberduck-vba/Rubberduck/issues/833#issuecomment-147890250):

> 1. Place breakpoint in failing test
2. Test Explorer / Run all tests
3. Hit breakpoint
4. Tweak code in break mode
5. Run all tests again -> boom

These steps are what he's currently working with. Please confirm that these steps produce your problem. Thanks :smile:

**Comment by retailcoder** [comment]
Allright, I'm about to make a PR that solves this issue like this:

![image](https://cloud.githubusercontent.com/assets/5751684/10556910/7cdf20c0-7462-11e5-93e0-91ab6b82b370.png)

While the test engine is busy, the test explorer will be disabled. I have yet to figure out a way to disable menu commands, but one couldn't quite run into this exception *by accident* now.
