### ISSUE TITLE
Unhadled exception while trying to add a Test Module for the second time

### ISSUE THREAD

**Issue by michalkrzych** [rubberduck-vba/Rubberduck#87]
Open the Test Explorer window and add Test Module - it works for the first time, however it's throwing an error if you try to re-add it. 

![untitled](https://cloud.githubusercontent.com/assets/6545828/5186108/1aef0408-74bc-11e4-9487-9de317f7c255.png)

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.InteropServices.COMException (0x800A802D): Name conflicts with existing module, project, or object library
   at Microsoft.Vbe.Interop._References.AddFromFile(String FileName)
   at Rubberduck.Reflection.ProjectExtensions.EnsureReferenceToAddInLibrary(VBProject project) in c:\Users\Christopher\Source\Repos\RetailCoderVBE\RetailCoder.VBE\Reflection\Project.cs:line 28
   at Rubberduck.UnitTesting.NewUnitTestModuleCommand.NewUnitTestModule(VBE vbe) in c:\Users\Christopher\Source\Repos\RetailCoderVBE\RetailCoder.VBE\UnitTesting\NewUnitTestModuleCommand.cs:line 19
   at Rubberduck.UnitTesting.TestEngine.OnExplorerAddTestModuleButtonClick(Object sender, EventArgs e) in c:\Users\Christopher\Source\Repos\RetailCoderVBE\RetailCoder.VBE\UnitTesting\TestEngine.cs:line 197
   at Rubberduck.UI.TestExplorerWindow.OnButtonClick(EventHandler clickEvent) in c:\Users\Christopher\Source\Repos\RetailCoderVBE\RetailCoder.VBE\UI\UnitTesting\TestExplorerWindow.cs:line 68
   at Rubberduck.UI.TestExplorerWindow.AddTestModuleButtonClicked(Object sender, EventArgs e) in c:\Users\Christopher\Source\Repos\RetailCoderVBE\RetailCoder.VBE\UI\UnitTesting\TestExplorerWindow.cs:line 134
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18444 built by: FX451RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Microsoft.VisualStudio.Tools.Office.Runtime
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.50903.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualStudio.Tools.Office.Runtime/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Tools.Office.Runtime.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34238 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Microsoft.VisualStudio.Tools.Applications.Hosting
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.50903.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualStudio.Tools.Applications.Hosting/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Tools.Applications.Hosting.dll
----------------------------------------
Microsoft.VisualStudio.Tools.Applications.ServerDocument
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.50903.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualStudio.Tools.Applications.ServerDocument/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Tools.Applications.ServerDocument.dll
----------------------------------------
Microsoft.VisualStudio.Tools.Applications.Runtime
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.50903.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualStudio.Tools.Applications.Runtime/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Tools.Applications.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Deployment
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34244 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Deployment/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Deployment.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Microsoft.Office.Tools
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.50903.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Office.Tools/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.Office.Tools.dll
----------------------------------------
Rubberduck
    Assembly Version: 1.0.5440.40154
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Rubberduck/Rubberduck/Rubberduck.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
CustomMarshalers
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/CustomMarshalers/v4.0_4.0.0.0__b03f5f7f11d50a3a/CustomMarshalers.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by AndrewM-** [comment]
I don't know what version number the above issue relates to.  I am seeing this issue in version 1.4.3.  The error message is different though.  This time is says "Microsoft Access cannot find the procedure 'PhotoHarvester_NewTest.ModuleInitialize.'".  Deleting the second new and empty test module makes the unit test work again.  I noticed that the module name is not being used as a 'namespace'.  I use module names as namespaces in my VBA code.  
![testmoduleinitialize](https://cloud.githubusercontent.com/assets/5060805/10441447/249f5d72-718c-11e5-8534-6a5bea841990.png)

**Comment by ckuhn203** [comment]
@AndrewM that's an unrelated (and known) issue specific to Access. Due to the signature of Access's `Application.Run()` method, every test method name must be unique. 

This is because Access does not qualify the module name when calling `Run` for some god awful reason. 

Make sure all your method names are unique and the issue should go away.

**Comment by AndrewM-** [comment]
If the above is the case, can you change RD to make all of the method names in the test module boilerplate unique.  So testmodule1 gets fitted with ModuleInitialise1 etc.  Would it be simple to check for existing methods of the same name and assign new names on the fly?  The other thing would be to place a comment under each customised method name to say that the name must be unique within the project context.

**Comment by retailcoder** [comment]
@AndrewM-  we need to make the test module / test method stubs more dynamic, indeed. Right now they're basically a hard-coded string in the code base. With the improved parsing and annotations, the `Declarations` API is now equipped to find test methods and test modules - we can have code that checks when annotated methods in test modules aren't unique and display a nice, friendly message instead of letting everything blow up :wink:

**Comment by AndrewM-** [comment]
I am junior in this game and I know I am saying the obvious most of the time.  I work remote office where too many projects crash and burn do to poor communication with head office so I tend to and try to make sure that things don't go bad from lack of saying stuff that everyone thinks is obvious.  I hope no one is offended.  One day I will pay a visit to the source and enlighten myself.

**Comment by ckuhn203** [comment]
@AndrewM no worries mate. The issue is detailed in #570. @Retailcoder, you mentioned opening an issue for parameterizing the unit test names, but I couldn't find it. Does that need done yet?

**Comment by AndrewM-** [comment]
My temporary workaround it to prefix the contentious procedure with the module name of the test module and an underscore eg. TestModule1_ModuleInitialize.  This solution gets past the test that broke things before.

**Comment by ckuhn203** [comment]
That's likely very close to what we'll do to fix it too.
